### ISSUE TITLE
Prepare the Game presentation

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#10]
We need to announce the game in a super flashy way.

Also please note this presentation will be given by 2 different people, so the creator needs to brief the other venue.

A few similar presentations to look at:
- [SourceBots 2018](https://sourcebots.github.io/sb2018-game-presentation/)
- [SR2017 southampton](https://docs.google.com/presentation/d/1eZveEF-YzN1nAycJsirAKppqrJwpzfpSigcTnt0R_TM/edit#slide=id.g17a8ba71bc_1_182)  (scroll to game section)

depends on https://github.com/srobo/core-team-minutes/issues/14

copied from https://github.com/srobo/core-team-minutes/issues/44

**Comment by Adimote** [comment]
> Depends on https://github.com/srobo/core-team-minutes/issues/14

from @RealOrangeOne

**Comment by RealOrangeOne** [comment]
The intro and game presentations will be given in 1 presentation, and in the same presentation file as #13.

**Comment by RealOrangeOne** [comment]
This presentation was shipped successfully, with the information which was available at the time
