### ISSUE TITLE
Acquire Computers and screens For Venue

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#100]
- [x] Reception 2×computers, 2×monitors
- [ ] COMP screens
  - [x] Arena screens 
    - [x] 4×pis
    - [x] 4×monitors
  - [ ] Team score displays 
    - [x] 5×pis
    - [x] 2×SUSU TVs 
    - [ ] 1×monitor
    - [x] 2×fixed displays
  - [x] Cube score display 
    - [x] 1×pi
    - [x] 1×SUSU TVs
  - [ ] volunteer area
    - [x] 1×pi
    - [ ] 1×screen (could also use projector in the room)
  - [ ] tech desk preview
    - [x] 1×pi
    - [ ] 1×screen
  - [x] shepherding
    - [x] 2×pi
    - [x] 2×monitors
- [x] comp server 1×pi
- [x] Score entry
  - [x] 1×pc
  - [x] 1×screen
- [ ] livestream control computer
  - [x] 1×pc
  - [ ] 2x screen
- [x] nonsync sound 1×pc 1×screen (@RealOrangeOne will provide a laptop)
- [ ] Tech desk admin
  - [ ] 1/2×pc
  - [ ] 1/2×screen
- [ ] SR mixtape machine 1×PC
- [ ] Status dashboard (could use 2×pis if we can't get a dual output machine)
  - [ ] 1×PC 
  - [ ] 2×screen
- [x] Helpdesk laptop (@sedders123 will provide laptop)

**Comment by Tyler-Ward** [comment]
@mildlyincompetent @trickeydan can we use the SRO laptops for reception and score entry?

**Comment by Tyler-Ward** [comment]
SRO laptops can be used for reception and score entry.

**Comment by Tyler-Ward** [comment]
Since #70 we no longer need the router in this list

**Comment by Tyler-Ward** [comment]
18pis have been separated out for the arena displays there are some additional pi2s available if more compute power is needed for any screen. The SR screens have also been allocated for the arena and shepherding screens to complete these lines The pi2s in clear cases should be used for the staging screen and the 4 corners as these will gain VESA mounts shortly.

**Comment by Tyler-Ward** [comment]
@prophile are you intending to provide the mixtape machine?

**Comment by RealOrangeOne** [comment]
> @prophile are you intending to provide the mixtape machine?

If this isn't possible, I may be able to borrow an apple machine from work

**Comment by Tyler-Ward** [comment]
@jcwilliamson if you can try and borrow some monitors from ECS that would be great.

**Comment by TomWheal** [comment]
I have a couple 19” 4:3 monitors that could be borrowed for the weekend if needed

**Comment by kierdavis** [comment]
I'm also happy to loan a monitor ([BenQ GL2450)(https://www.benq.eu/en-uk/monitor/home-office/gl2450.html)) for the duration of the competition, if needed.

**Comment by PeterJCLaw** [comment]
We're getting as many of these as we're going to get.
