### ISSUE TITLE
Organise computer hardware for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1000]
We will need a large number of computers for the competition. This
ticket serves as a central place which records everything other than
volunteers individual laptops.

In addition to the hardware for the individual dependencies noted
below, we also need:
* machines to run the network (if not provided by the venue)
* machines for helpdesk (though this may be volunteers' laptops)

### Original

[comp/computer-hardware](https://github.com/srobo/recurring-tasks/blob/master/comp/computer-hardware.yaml)

### Dependencies

 * #994 Organise computering kit for the competition reception desk
 * #996 Organise drivers for the arena screens
 * #997 Organise machine to run score entry
 * #999 Organise the non-arena ("outside") display screens

**Comment by WillB97** [comment]
We need:
- 5 pis for the arena screens
- A pi for the compbox
- A pi for mixtape
- A score entry laptop
- 2-4 pis for external screens
- Power supplies for all the above

**Comment by trickeydan** [comment]
> machines for helpdesk (though this may be volunteers' laptops)

I have arranged for two laptops to be borrowed to sit permanently at helpdesk.

Additionally, we may have a status screen and Pi at helpdesk too, but I have not yet arranged for that yet.

**Comment by RealOrangeOne** [comment]
> A pi for mixtape

We could run this on the same machine as #1082, which I'll be providing.

**Comment by PeterJCLaw** [comment]
> A pi for mixtape

Is this even supported? My understanding is that mixtape needs macOS for the music alignment component.

**Comment by RealOrangeOne** [comment]
> My understanding is that mixtape needs macOS for the music alignment component.

It used to be, but I resolved that a while ago: https://github.com/srobo/srcomp-mixtape/pull/2

**Comment by WillB97** [comment]
We're 4 pi 4's and 4 pi's from the srcomp box to do the displays and WIll's macbook for mixtape

**Comment by PeterJCLaw** [comment]
I assume you mean Pi 3's if you're referring to the box of Pis we usually use for SRComp stuff?
