### ISSUE TITLE
Produce competition booklets for the SR2023 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1005]
The primary target of these booklets are invited guests (both of SR and of the teams), who may not know very much about either Student Robotics or the game the robots are competing in.
These flyers should include:
 - descriptions of both SR and the game
 - a summary of the teams competing (a list of TLAs and names is fine)
 - the overall schedule of the competition weekend
 - sponsors
 - map of the venue

Note: much of the content of these booklets does not need to actually be new -- the website already contains plenty of summaries of SR and the game, which can be copied liberally, as well as the day schedule.

### Original

[comp/flyers](https://github.com/srobo/recurring-tasks/blob/master/comp/flyers.yaml)

### Dependencies

 * #1004 Work out the day schedules for the competition

**Comment by sedders123** [comment]
This is in the drive https://drive.google.com/file/d/1MQJbO06LkMEaam5tl_SgsAvHYj4gGkuu/view?usp=share_link
