### ISSUE TITLE
Print the competition booklets for the SR2023 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1006]
Arrange printing of the competition booklets for handing out at the competition.

### Original

[comp/print-flyers](https://github.com/srobo/recurring-tasks/blob/master/comp/print-flyers.yaml)

### Dependencies

 * #1005 Produce handout flyers for the SR2023 Competition

**Comment by sedders123** [comment]
These have been ordered and I've update the freight list
