### ISSUE TITLE
Update MCF and link for SR2023

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1007]
The media consent form needs publishing for SR2023.

### Original

[comp/media-consent/form-update](https://github.com/srobo/recurring-tasks/blob/master/comp/media-consent/form-update.yaml)

**Comment by sedders123** [comment]
After discussion within the Marketing team and with the Trustees we will not be having a media consent form going forward. Instead we're opting for clear signage that photos and videos are being taken and having an opt out mechanism available via wearing of a red lanyard that can be requested at reception.
