### ISSUE TITLE
Produce Flyers for guests

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#101]
For competitors and spectators; note that competitors have a separate booklet (#87).

This should include:
- a summary of what Student Robotics is
- an outline of the game (maybe copy the text from the announcement post and an arena diagram from the rules)
- the list of teams
- a minimal schedule (maybe just highlight when the knockouts & finals are?)
- (optional) a list of the prizes
- (optional) a map of the venue

**Comment by Tyler-Ward** [comment]
see #87 for some usefull deisgn documents for this

**Comment by RealOrangeOne** [comment]
This almost certainly won't need designing. We can just print the rules document itself and use that

**Comment by Tyler-Ward** [comment]
we wont want to give out multi-page A4 documents to people on they day, this would be an A5 flyer as in previous years

**Comment by PeterJCLaw** [comment]
Yeah, this sounds very much like it's a part of #87 and we should just close this ticket.

We already have arena diagrams (from the rules) and short explanations of the game (from the announcement posts), so I'm not sure what's left to do for this ticket unless we're planning to have two separate flyers? (which seems overkill to me)

**Comment by Tyler-Ward** [comment]
If I am remembering the discussion correctly the event booklet is planned to also contain the other info required for competitors e.g. team pit map, event rules, food info, whereas the rules flyer for spectators wont have the competitor info and will just have the info required to understand matches.

**Comment by PeterJCLaw** [comment]
Ah, right. I've misunderstood what the booklet was about.

**Comment by PeterJCLaw** [comment]
@richardbarlow notes (https://github.com/srobo/tasks/issues/87#issuecomment-464048756):
> The design for the SR2016 leaflet can be found in arena.git (not sure why I put it in there): https://git.studentrobotics.org/cgit/arena.git/tree/comp16
> 
> I think that @jimmythompson designed the SR2017 leaflet and got them printed.
> 
> The README in the comp16 directory includes information relevant to getting them printed.

**Comment by PeterJCLaw** [comment]
@TomWheal just wondering if there's any update on this? I don't know what the lead time for printing these will be, though I imagine we're getting close. If you're not going to have time to look at this, that's fine -- better to let us know so we can reassign if needed :)

**Comment by TomWheal** [comment]
The lead time on this is short, my plan is to make them this afternoon when I finish off the booklet

**Comment by TomWheal** [comment]
@PeterJCLaw 
[flyer.pdf](https://github.com/srobo/tasks/files/3017824/flyer.pdf)

**Comment by Tyler-Ward** [comment]
The flyer designs look good to me.

**Comment by TomWheal** [comment]
Closing as its complete. Printing will start tomorrow.

**Comment by PeterJCLaw** [comment]
Nice!

Shame there wasn't space to include a description of the robot-positions bonuses feature of the rules.

**Comment by PeterJCLaw** [comment]
@TomWheal please could you contribute the source of this to a suitable repo? https://github.com/srobo/promotional-material perhaps? (maybe in a `sr2019` folder?)
