### ISSUE TITLE
[Meta] Organise media consent for SR2023

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1011]
We need media consent from everyone at the competition.

### Original

[comp/media-consent/main](https://github.com/srobo/recurring-tasks/blob/master/comp/media-consent/main.yaml)

### Dependencies

 * #1007 Update MCF and link for SR2023
 * #1008 Email teams about media consent
 * #1009 Print spare MCFs for visitors
 * #1010 Organise tickets for SR2023
 * #1139

**Comment by antoinepetty** [comment]
Closing as done as per https://github.com/srobo/tasks/issues/1007#issuecomment-1426232010

**Comment by antoinepetty** [comment]
D'oh actually no the dependencies are actionable so will reopen this. The organisation is done, it's just publicising the plan that still needs doing
