### ISSUE TITLE
Order wristbands for SR2023

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1013]
We need to order wristbands. The order should include the hire of a crimping tool if that applies to the kind of wristbands being ordered.

### Original

[comp/wristbands/order](https://github.com/srobo/recurring-tasks/blob/master/comp/wristbands/order.yaml)

### Dependencies

 * #1012 Design wristbands for SR2023

**Comment by sedders123** [comment]
We no longer need wristbands for media consent
