### ISSUE TITLE
Organise markers for the arena

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1016]
The arena (and, possibly, things inside it) is marked with AprilTag markers, which need printing off in advance.

### Original

[comp/game/markers](https://github.com/srobo/recurring-tasks/blob/master/comp/game/markers.yaml)

**Comment by WillB97** [comment]
Check if the comp markers exist in #995

**Comment by RealOrangeOne** [comment]
If they exist, it's likely we only have 1 full set. I suspect for safety it's more about how many sets we want to get printed rather than if we need to print any.

**Comment by WillB97** [comment]
2 sets is a good number, 1 for the test arena and 1 spare. Included in #1026.
