### ISSUE TITLE
Specify structure of knockout rounds.

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#102]

**Comment by PeterJCLaw** [comment]
The boring answer here is that `srcomp` has a built-in functionality to do this. However 36 teams doesn't go particularly nicely into a knockout (it's just above a power of two), so the layout it chooses may not be quite what we want. It's viable as a fallback though.

Once we've created the compstate (#119) we can have a look at what it would do.

**Comment by PeterJCLaw** [comment]
I've just done the import. For the current number of teams we get a first round of knockouts which is pretty pointless -- almost everyone gets a match with two robots in, meaning that they're effectively byes (except that the system doesn't know to automatically do that).
I _don't_ know the seeds interact with whether you get a two-robot or three-robot match, however I suspect that (unless we drop to 32 or fewer teams) it's going to be worth manually scheduling it.

The automatic schedule also takes longer (with gaps) than we have allocated (#73) for the knockouts. Without gaps it would _just_ fit.

**Comment by prophile** [comment]
Right:

I propose that for 32 teams we run with the straight round of 32 as generated by the automatic srcomp scheduler.

For the 36 team case I propose the following, 21-match structure:

* Round 1: the Elimination round. Involves the bottom 24 seeds from the league. 6 matches of 4 robots each, of which the top 2 advance. This eliminates 12 and carries forward 12.
* Round 2: the Heats. Involves the top 12 seeds from league, and the 12 robots taken forward from Elimination. 8 matches of 3 robots each, of which the top 2 advance. This eliminates 8 and carries forward 16.
* Round 3: the Quarter Finals. Involves the top 16 from the Heats. 4 matches of 4 robots each, of which the top 2 advance. This eliminates 8 and carries forward 8.
* Round 4: the Semi Finals. Involves the top 8 from the Quarter Finals. 2 matches of 4 robots each, of which the top 2 advance. This eliminates 4 and carries forward 4. Additional 5m spacing between these two matches.
* Round 5: the Final. Involves the top 4 from the Semi Finals. 1 match, 4 robots, deciding the prizes.

**Comment by PeterJCLaw** [comment]
Hrm, there's quite a big difference in difficulty in these matches between a team placing 12th in the league and 13th in the league. Can we do anything about that?

For example, could we have fewer teams take part in the elimination round but carry more through? I've not thought through what other weirdness that introduces though.

Otherwise seems ok I think.

If you have notes on the other approaches considered and why this one is what's being proposed, it might be useful to share those.

**Comment by PeterJCLaw** [comment]
> * Round 4: the Semi Finals. ... Additional 5m spacing between these two matches.

Regarding timings here -- do you mean extra between the semis themselves, or between them and the final?

Currently SRComp supports adding a consistent between the rounds of the knockout, with the ability to add an extra gap before the final.
(The tiebreaker is scheduled as an absolute time)

**Comment by Tyler-Ward** [comment]
@prophile now we are at 31 teams is this sorted@?

**Comment by PeterJCLaw** [comment]
Yes, now that we're ~at or~ below 32, this is trivial. (I happened to discuss this with @prophile in person the other day)
