### ISSUE TITLE
Print helpdesk documents

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1021]
Helpdesk will need a number of documents

 - [x] Rulebook
 - [ ] Helpdesk instructions
 - [x] Kit swap form
 - [x] Venue map

This list may need adding to.

### Original

[comp/pits/helpdesk/print-documents](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/helpdesk/print-documents.yaml)

**Comment by sedders123** [comment]
@srobo/kit-team We're planning on submitting a bulk order to [print all the things](https://github.com/srobo/tasks/issues/1026) on the 18th. We can include help desk documents on this if we know what they are, if not they'll need to be printed separately

**Comment by raccube** [comment]
I will print the helpdesk instructions myself as they weren't completely finished when the print order went through.

**Comment by raccube** [comment]
We're keeping the helpdesk procedures document as a live document. A sheet with a QR code of the link to it is up at helpdesk.
