### ISSUE TITLE
Plan overnight kit & battery loans at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1022]
Many teams will want to take their kits home with them overnight at the competition, in order to work on them. We usually require these teams to fill in some paperwork to record this, in order to ensure we know which team have done this and which parts they have taken with them. The latter is important as they will likely not be taking with them the same batteries as they had for the rest of the year and so the inventory will not track this loan.
See https://srobo.github.io/runbook/competition/teams/process-docs/overnight-battery-loan/ for details.

### Original

[comp/pits/overnight-loans](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/overnight-loans.yaml)

**Comment by Tyler-Ward** [comment]
This task also needs to cover if and howe we recover and store batteries overnight

**Comment by raccube** [comment]
Teams will need to request this. We can hand them a battery or two and a charger. Will need to have a form for this.

(Form should be prepared by Friday if to be included in print order)

**Comment by raccube** [comment]
This is part of the Helpdesk Procedures document.

**Comment by raccube** [comment]
Done as part of #1021
