### ISSUE TITLE
Print all the things for SR2023

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1026]
We need various stuff printing before we get to the venue.

Docs to Print (check indicates document in the [print folder](https://drive.google.com/drive/folders/1Uw4yON6d7mzNoLTvv8chM6tGNZ-Ik7pl?usp=share_link) ready for bulk print order):
- [x] Media Consent Posters x 10
- [x] Signage
- [x] High-viz jacket labels (A5 + A6) x 1 per team
- [x] [Safety Regs](https://studentrobotics.org/docs/kit/safety-regulations) x 4
- [ ] Safety notes sheets x 2
- [x] [80mm markers (for Gold Tokens)](https://drive.google.com/file/d/127BfyV0OzOeChfGRghewsZlUeokqEofF/view?usp=share_link) x 48
- [x] TLA labels (for pits) A4 x 1 per team
- [x] [Rules](https://studentrobotics.org/docs/resources/2023/rulebook.html) x 2
- [x] [Charging Instructions](https://studentrobotics.org/runbook/competition/team-support/battery-charging/) x 2
- [x] [Kit Contents Checklist](https://docs.google.com/document/d/1YsIddeSC6w8e_KRGGTpjbCYrCV0ujlGAfj7lq7IE7Mc/edit?usp=sharing) x 31
- [x] [Kit Return Forms](https://docs.google.com/document/d/1eegZOBdhhDcwjxq9rwLbtxBbY3gxckNpkNXDLWMA8Yo/edit) x 31
- [x] [Missing Return Forms](https://docs.google.com/document/d/1G9Rv0hWHamecVhk1saslqfMxlYuAg5miJwzOg4GCpVo/edit) x 31
- [x] [Kit Swap Forms](https://docs.google.com/document/d/1X4ewwhkTFKfCzQjlIUS-90ZhcFHzashRhz_kXnUlxjE/edit) x 3
- [x] Volunteer Sign in Form x 4
- [x] [Reception Documentation](https://github.com/srobo/runbook/pull/180) x 4
- [x] [Comp Arena Markers](https://drive.google.com/file/d/1ahFQAOxYHc1t60Wrw8pTj1-aOLYfqV5v/view?usp=sharing) (2 sets of 28) x 56
- [x] [Safeguarding Policy](https://opsmanual.studentrobotics.org/about-the-charity/safeguarding) x 3
- [ ] [Incident Response Policy](https://studentrobotics.org/runbook/competition/event/incident-management/) x 10
- [ ] Car Permit for Sunday x 50
- [x] [Radio Signout Sheets](https://docs.google.com/document/d/1_hydeF6ely-4NloKKoznRg0WMF3UYs2XxRLhxJlEdIw/edit) x 2
- [x] Tinker Time Coordination x 2
- [ ] ~~Test Arena Tinker Time Coordination x 4~~
- [x] Score sheet x 250
- [x] WiFi guest account signature sheet x 1
- [x] WiFi account passwords & Instructions x 1
- [x] Risk Assessments (setup & competition) x 1
- [ ] Helpdesk documentation x 2

### Original

[comp/printing](https://github.com/srobo/recurring-tasks/blob/master/comp/printing.yaml)

### Dependencies

 * #1006
 * #1009
 * #1015
 * #1016
 * #1018
 * #1020
 * #1021
 * #1022
 * #1023
 * #1024
 * #1097
 * #1025 Have name badges for volunteers at the competition

**Comment by RealOrangeOne** [comment]
Given the amount of printing we have to do, we may benefit from using https://www.doxdirect.com/ (the company who did the markers last year).

It means we can print well in advanced, not have to wait for our inkjet printer (#983), and it'll likely be cheaper than university printing / printing ourselves (at least when considering volunteer time).

**Comment by PeterJCLaw** [comment]
I'm not sure where the idea that the on-site printer (#983) is expected to print anything on this ticket. It is explicitly _not_ for printing anything on this list. This list is for things which can (and should) be printed well ahead of time.

That printer is for printing incidental things which come up on the day and could not have been pre-printed. Examples of this are the shepherding sheets, as they depend on the progression of the matches (assuming that shepherding still use those, they haven't in recent years), or the list of winners/runners up (which also depend on the matches).

**Comment by samjmartin04** [comment]
Please can we increase score entry sheets to 250 @WillB97, so that we have enough for some practice runs using actual score sheets on the Friday afternoon

**Comment by raccube** [comment]
From a kit perspective, this all looks fine to me.

Is the team arrivals list part of Reception Documents?

**Comment by raccube** [comment]
There's a [helpdesk procedures document](https://docs.google.com/document/d/1iINdqbfxwwHj6GZyQNeBNpE7bnSwZ9N1HyBmEVSsKUs/edit#) that we'd like to get printed but needs to be reviewed.

**Comment by WillB97** [comment]
The bulk order has benn submitted and is being delivered to James.
