### ISSUE TITLE
Plan for handling of sad batteries

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1028]
We should have a plan for how to handle lipos which are deemed to be unusable. This is to cover the handling of the lipos at the event, not the disposal afterwards.
See the runbook for the current safety protocol: https://studentrobotics.org/runbook/competition/team-support/battery-charging/#safety

### Original

[comp/safety/sad-battery-management](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/sad-battery-management.yaml)

**Comment by sedders123** [comment]
We have a bucket for very sad batteries (on fire). Think the plan for puffy/dodgy batteries may be under remit of kit team

**Comment by raccube** [comment]
We can follow the same procedures as last year and store failed batteries in a separate box (in fire safe bags, with the leads covered). 

https://github.com/srobo/tasks/issues/767#issuecomment-1079900142
