### ISSUE TITLE
Determine League Schedule

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#103]

**Comment by PeterJCLaw** [comment]
relates to #119

**Comment by PeterJCLaw** [comment]
We have pre-existing schedules for competitions at 48, 52 and 56 teams, thought unfortunately none for 36.

@RealOrangeOne could you confirm the total number of teams we're currently expecting (i.e: actual teams who have kits)? (Note that if it's 36 or less I'd be in favour of keeping it at 36 or less -- scheduling for 37 is much more challenging than for 36)

**Comment by prophile** [comment]
I'm self-assigning since I believe this to fall under the scope of the head judge. This can be left for a couple of weeks, since it may need reworking in the presence of dropouts.

**Comment by PeterJCLaw** [comment]
For info: I've been poking the ancient https://github.com/PeterJCLaw/blueflame in the hopes that it might be useful here. At the moment it suffers massively from pitting the same teams against each other too much.

I've also been wondering about how best to update the check scripts we have (https://www.studentrobotics.org/cgit/comp/match-scheduler2.git/tree/checks) so they're a bit more accessible, but hadn't got anywhere with that yet.

**Comment by PeterJCLaw** [comment]
I've ended up improving those checks a bit today (and thought of a new check we needed, so have added that).

I've put the best schedule I've generated so far into [a gist](https://gist.github.com/PeterJCLaw/b243e8e24383a4e4cc29600e7fcdf1c3) along with the summary of its checks; unfortunately I'm not even sure exactly what the code was which generated it and I can't reproduce it. That'll teach me to refactor without commiting first.

Feel free to use that if it's useful, or ignore completely if you prefer.

**Comment by PeterJCLaw** [comment]
Hrm, since we're down to 32 teams the schedule I linked above isn't useful (having four empty slots isn't good - we should reschedule for 32).

**Comment by PeterJCLaw** [comment]
@prophile how goes this?

(for info: we're down to 30 teams)

**Comment by sedders123** [comment]
Now we're down to 30 teams is it possible to increase the time in-between matches to say 2:30 minutes instead of 2 minutes? I'm a bit worried about getting scoring + robots in and out of the arena in time.

**Comment by PeterJCLaw** [comment]
As the matches are only 2:30 long, I believe we already are expecting to run at 2:30 between matches.

**Comment by PeterJCLaw** [comment]
@prophile sorted this, we've imported and deployed the schedule.
