### ISSUE TITLE
Update and publish risk assessments for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1031]
The risk assessment for the competition needs updating for SR2023 and publishing to schools.

### Original

[comp/safety/risk-assessments](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/risk-assessments.yaml)

**Comment by Scarzy** [comment]
The RA is updated, needs publishing

**Comment by sedders123** [comment]
This is on the website now
