### ISSUE TITLE
Prepare an incident response plan

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1032]
We should ensure that our incident response plans are current & applicable to the selected venue; we should update them as needed.

### Original

[comp/safety/incident-plan](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/incident-plan.yaml)

### Dependencies

 * #974
 * #1030 Have a means to record an incident
 * #1031 Update and publish risk assessments for the competition

**Comment by WillB97** [comment]
https://github.com/srobo/runbook/pull/182

**Comment by Adimote** [comment]
Status: needs some tweaks but is mostly completed

We may need clarification on who the tech lead is

**Comment by Scarzy** [comment]
srobo/runbook#186
srobo/runbook#187
