### ISSUE TITLE
Ensure that we have fire managing equipment at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1033]
We need to have available whatever equipment we believe will be needed to safely handle fires. Exactly what this entails will depend on the nature of our plans for handling any fires.
The runbook has details of what the current protocol is, for example: https://studentrobotics.org/runbook/competition/team-support/battery-charging/#safety
See also the notes at https://github.com/srobo/tasks/issues/822#issuecomment-1090656629 and onwards.

### Original

[comp/safety/fire-management-equipment](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/fire-management-equipment.yaml)

**Comment by Scarzy** [comment]
A metal bucket is available for issues at battery charging. This covers all existing protocols
