### ISSUE TITLE
Organise tinker time

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1036]
On the morning of the first day, teams are given a chance to tinker with their robots in the arenas. We're going to use a whiteboard to schedule this. Someone will be near the arena and will write teams into 15 minute time slots. Requires 1 Blueshirt to manage scheduling and changover.
Also requires that there is some kind of PA system that is audible in the Arena.

### Original

[comp/tinker-time](https://github.com/srobo/recurring-tasks/blob/master/comp/tinker-time.yaml)

### Dependencies

 * #981
 * #1035 Arrange a whiteboard at the competition

**Comment by RealOrangeOne** [comment]
Blocked on a final day schedule: https://github.com/srobo/tasks/issues/1004

I've duplicated the document from last year though, which can act as the template: https://docs.google.com/document/d/1ZwaOhCJkEYIuQVLMaTwCSiGn3zYSqDJk0ZpoB5m3HD0/edit?usp=sharing

**Comment by RealOrangeOne** [comment]
I've populated the tinker time sheet based on the current draft day schedule. It's enough for everyone to have a slot in the morning, and half the teams to have a slot in the afternoon. I'll mention this in #1138

**Comment by WillB97** [comment]
I've reduced the slot time to 10 minutes to give everyone two slots.
