### ISSUE TITLE
Print Arena markers

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#104]

**Comment by RealOrangeOne** [comment]
We may already have these markers in the container. We should check the state of these before we print markers unnecessarily

**Comment by Tyler-Ward** [comment]
I think they are in southampton in a box of mystery parts which came from rich

**Comment by PeterJCLaw** [comment]
ping container check task: #183

**Comment by RealOrangeOne** [comment]
The existing tokens are in `1MN2T`, in the boomcupboard, along with a set of spares for each arena. This should be more than enough.
