### ISSUE TITLE
Prepare the in-venue Compbox

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1042]
We have a Raspberry Pi 3 (part code `srL1CX`) which is typically used as the compbox.
This task is to prepare the micro SD card and validate that the Pi itself functions, so that deployment in the venue is as simple as plugging the Pi into the competition network.
The steps here are usually:
1. Flash the SD card with the latest Raspbian stable
2. Clone https://github.com/PeterJCLaw/srcomp-puppet onto the Pi
3. Run `srcomp-puppet/scripts/install` on the Pi
4. Use the `scripts/check-pages.py` to validate from outside the Pi that the expected pages can be reached

### Original

[comp/ops/prepare-compbox](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/prepare-compbox.yaml)

### Dependencies

 * [x] #995

**Comment by PeterJCLaw** [comment]
I've checked that the puppet setup applies cleanly using my own Pi 3 and Raspberry Pi OS 2022-09-22 Bullseye Lite 64-bit.

**Comment by PeterJCLaw** [comment]
I've checked that the puppet setup (also) applies cleanly using my own Pi 3 and Raspberry Pi OS 2023-02-21 Bullseye Lite 64-bit.
