### ISSUE TITLE
Work out layout of teams at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1043]
The layout of team pits in the venue needs to be worked out. There are constraints such as keeping teams under the same teacher close together, and keeping overseas teams near each other.
This task covers both the placement of the pits within the venue and the allocation of specific teams to pits.
Ideally the pits should be internally numbered and kept with an ordered list of teams which fit to those locations. This helps ensure that the compstate can easily be kept in step with the physical locations of each team.

### Original

[comp/pits/layout](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/layout.yaml)

### Dependencies

 * #986

**Comment by sedders123** [comment]
We have assigned teams to pits in this spreadsheet (https://docs.google.com/spreadsheets/d/1ADDD-7LmkiChD4_lqH-k6sRnLCwpC8_rydY6PY8qQQo/edit). We'll keep an eye on the teams competition details responses to tweak if any accessibility requirements are needed

**Comment by PeterJCLaw** [comment]
@sedders123 is there a reason we have a team in pit 31 but not pit 30?

**Comment by sedders123** [comment]
We wanted to leave some space for larger teams in that area

**Comment by PeterJCLaw** [comment]
I've added a sheet to that doc which computes the inverse mapping and updated the compstate based on it.
