### ISSUE TITLE
Plan video feeds

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1048]
The livestream will need to have a few different camera feeds to show different parts of the venue
- Arena (likely multiple) - Hosts (who may be different to commentators) - Stage (only needed for prize giving)

### Original

[comp/livestream/plan-video-feeds](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/plan-video-feeds.yaml)

**Comment by antonnikitin97** [comment]
@WillB97 has put me in contact with Jamie to discuss multi-cam setups for the physical competition.

**Comment by antonnikitin97** [comment]
-I had a productive discord chat with Jamie on Monday where he outlined what sort of equipment he could lend us, this consists of professional/PTZ (pan-tilt-zoom cameras).

Action points:

* Jamie would like to know if we have capture cards.
* Plan what scenes we would like (a), (b)
* For any NDI sources - find out the nature of the comp network for access points.

(a): For the main area, (top down camera, on-stage side on cam, robot zoom cam (PTZ), between rounds "holding cam" (wide angle view of the arena))
(b): Test arena cam

**Comment by Tyler-Ward** [comment]
The test areana cam will be in a public area which will confilct with the media consent system.

**Comment by antonnikitin97** [comment]
Makes sense :)
