### ISSUE TITLE
Identify Prop Construction

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#105]
Work out how we make the props in the arena.

- [x] https://github.com/srobo/tasks/issues/167 Caldera
- [x] Tokens
- [x] https://github.com/srobo/tasks/issues/106 Robot flags

**Comment by RealOrangeOne** [comment]
Upgrading status, as there's a lead time in ordering parts and assembling them.

**Comment by RealOrangeOne** [comment]
Token boxes need ordering. Everything else has been identified and obtained.

**Comment by joe9599** [comment]
I'm looking into finding tokens

**Comment by joe9599** [comment]
Is there a rough budget, or certain suppliers that should be used, as this size cubes are available in packs of 25 from amazon
https://www.amazon.co.uk/d/Home-Office-Containers/Single-Wall-Cardboard-Boxes-130x130x130mm/B006C0RJC4

**Comment by RealOrangeOne** [comment]
Wow, that's convenient! Amazon certainly names delivery quite a bit simpler! I suspect we have the budget to purchase 3 sets of those (totaling 75), but deferring to @Tyler-Ward to confirm.

**Comment by RealOrangeOne** [comment]
@joe9599 yes, these will do nicely! Just awaiting budget sign off before we can order them. But because it's Amazon, there's not a massive lead time, which is great!

**Comment by Tyler-Ward** [comment]
I think we have historically got them from cardboardboxes.co.uk but amazon also sounds good. The cost looks fine, still pending on some budget sorting before we can order stuff but if you are happy to arrange ordering these I will let you know when you are good to order.

**Comment by PeterJCLaw** [comment]
@joe9599 thanks for investigating. £17 per pack of 25 sounds quite expensive to me though, particularly when we need at least 60 of them (40 in the arena at any one time, plus a good number of spares).

As a general comment: we should always consider at least two possible suppliers when looking at this sort of thing -- we're much more likely to find a good price that way.

For reference, a quick search yields:
- https://www.boxed-up.co.uk/single-wall-cardboard-box-5x5x5 (£11.80 per pack of 50, plus delivery)
- https://www.ukpackaging.com/catalog/product/view/id/10054/s/single-wall-brown-cardboard-box-127x127x127mm/category/8/ (£6.36 per pack of 20, plus delivery)
 - https://www.cardboardboxes.co.uk/product/5-inch-cubed-single-wall-brown-cardboard-box-x-25-2/ (£7.99 per pack of 25, plus delivery)

I've not looked at delivery costs from either of those two suppliers, however the reduction in the cost of the packs suggests that we can do better than amazon here.

@joe9599 would you be able to work out the overall costs of the various options (note that many of these sites list both inc. VAT and ex. VAT prices, we'll be paying inc. VAT) for 60 boxes including delivery and make a recommendation?

**Comment by PeterJCLaw** [comment]
P.S: apologies for the lack of clarity here -- we really should have done a better job of specifying what was involved here before you started @joe9599.

**Comment by joe9599** [comment]
Just noticed that the links above are 127*127*127, is that Ok, or are they required to be 130*130*130?

**Comment by RealOrangeOne** [comment]
The rules state: 
> 3.5.1  Tokens are cubic cardboard boxes with a side length of 130±10mm.

So `127mm` is still fine.

**Comment by PeterJCLaw** [comment]
There's a tolerance on the size of the cubes for this purpose, though also because cardboard boxes are usually specified via the _internal_ dimensions:

> Tokens are cubic cardboard boxes with a side length of 130±10mm

I _strongly_ suspect that any boxes we get will actually be 5" sized, meaning 127mm (internal) walls, with the overall outer being about 130mm.

**Comment by joe9599** [comment]
![image](https://user-images.githubusercontent.com/15144435/53913039-40ca3380-4052-11e9-87be-481695133fe3.png)
Here is a table of possible suppliers, It looks like Kite Packaging are the cheapest, however Boxed up is free next day delivery and would give us a lot of spares

[cardboard box suppliers.xlsx](https://github.com/srobo/tasks/files/2938259/cardboard.box.suppliers.xlsx)

**Comment by PeterJCLaw** [comment]
@joe9599 awesome :). Do you have a link to the actual product on Kite Packaging? (the one in the spreadsheet seems to go to the checkout page)

**Comment by joe9599** [comment]
sorry, here is the correct link https://www.kitepackaging.co.uk/scp/boxes/standard-cardboard-boxes/?sfpartno=CSW050505&gclid=CjwKCAiA_P3jBRAqEiwAZyWWaJXsvPBAYzUGkmwbNVgtkjiLwQSZmLzaENOQjEcRQfJ_Uv_bBzapmBoCzcoQAvD_BwE

**Comment by TomWheal** [comment]
Might be useful to have these for the tech day on Saturday if possible.


________________________________

**Comment by Tyler-Ward** [comment]
Budget signoff for the tokens has been granted in #203

**Comment by RealOrangeOne** [comment]
We've now identified the contruction items for all the items on this ticket

- Caldera is made of wood (and already assembled)
- Tokens will be cardboard boxes (see https://github.com/srobo/tasks/issues/105#issuecomment-470274310)
- Robot flags will be PVC pipe with coloured tape on, hardened with card (likely taken from spare cardboard boxes)

We can therefore consider this ticket closed.

**Comment by PeterJCLaw** [comment]
What are the markers on the side of the tokens being made from?

**Comment by RealOrangeOne** [comment]
ah, good catch. I believe in the past it's been printed on card, which we'll need to source and print.

**Comment by RealOrangeOne** [comment]
This has been extracted as #221
