### ISSUE TITLE
Arrange a live stream from the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1051]
We should have a live stream of the competition.
We'll need to work out:
 - what hardware & sofware will be used to drive the stream (both cameras and
 mixing desk/driver computer)
 - where the cameras for the stream should go

### Original

[comp/livestream/main](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/main.yaml)

### Dependencies

 * #984
 * #1047 Have livestream training sessions
 * #1049 Organise hardware to run livestream
 * #1050 Organise livestream scenes

**Comment by Tyler-Ward** [comment]
@sedders123 with the plan to remove media consent how will we be handling opt out users and the live stream should they walk in front of a camera?

**Comment by sedders123** [comment]
Clear signage and telling competitors the livestream is happening in the cube when giving them a lanyard.

**Comment by antoinepetty** [comment]
Perhaps you'd like to take this one on @antonnikitin97 ?
