### ISSUE TITLE
Put stream on website

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1052]
The live stream needs to be linked or embedded from the website.

- [x] Virtual Competition
- [x] In-person Saturday
- [ ] In-person Sunday

### Original

[comp/website/livestream](https://github.com/srobo/recurring-tasks/blob/master/comp/website/livestream.yaml)

### Dependencies

 * #1051 Arrange a live stream from the competition

**Comment by sedders123** [comment]
Saturday done in https://github.com/srobo/competition-website/pull/44. Sunday to do
