### ISSUE TITLE
Publish SR2023 layout maps

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1055]
We should have maps of the layout for reference. This should include maps with team locations.
This should be put on the website. If we are publishing a competition booklet or flyer then it should be considered for inclusion there too.

### Original

[comp/venue/layout-map](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/layout-map.yaml)

### Dependencies

 * #986
 * #1043 Work out layout of teams at the competition

**Comment by WillB97** [comment]
Blocked on #986

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/comp-floorplans/pull/21 should also help with this.
