### ISSUE TITLE
Order blueshirts for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1059]
We may need more.

### Original

[comp/volunteers/blue-shirts](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/blue-shirts.yaml)

**Comment by antoinepetty** [comment]
We should change the description and title because we reprint all tshirts for each year anyway because of sponsor logos

**Comment by sedders123** [comment]
These have been ordered
