### ISSUE TITLE
Build robot flags

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#106]
Depends on #93.

At least two of each corner colour, plus a spare in another colour (likely white) which is marked for return to Helpdesk (for use in testing mount points).

**Comment by RealOrangeOne** [comment]
The rules contain a specification for the flags, and there are some assembled ones in the cupboard. 

The assembled ones are functional, but could do with a rebuild if we have time.

**Comment by Adimote** [comment]
Can we also get an extra flag marked with "RETURN TO HELPDESK", so teams can test-fit their flags?

**Comment by RealOrangeOne** [comment]
That's a good idea! We can use some white gaff for the flag and write on it.

(Also, having a robot holding a surrender flag will be funny!)

**Comment by BitBait** [comment]
Added cardboard to previous flags to sturdy them as well as adding new tape, they're pretty much refurbished!
(http://imgur.com/a/Y7db04b)

**Comment by RealOrangeOne** [comment]
The dummy flag should be the same size as the regular flag, but be made using white tape. We'll need to cut some more pipe for this.

**Comment by Tyler-Ward** [comment]
I believe the dummy flag ash now been built
