### ISSUE TITLE
Organise hotels and travel for volunteers

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1062]
It's important that volunteers are able to get to the competition, therefore hotels and other travel arrangements need to be organised.
This should also include travel between the venue and the hotels on each of the competition days.

### Original

[comp/volunteers/hotels-and-travel](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/hotels-and-travel.yaml)

### Dependencies

 * #1061 Recruit volunteers for the competition

**Comment by PeterJCLaw** [comment]
@Adimote is there anything outstanding on this? I think you were going to send another email with the details of that self-organisation sheet, was that it?

**Comment by sedders123** [comment]
Sheet was shared with all that requested accommodation
