### ISSUE TITLE
Prepare and send out volunteer information pack

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1064]
We should email all the volunteers with information about where to go on the day, parking, who to contact, and any other info we need to tell them.
We should aim to send this out at least a few weeks before the competition.

### Original

[comp/volunteers/information](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/information.yaml)

### Dependencies

 * #1062 Organise hotels and travel for volunteers
 * #1063 Schedule volunteer roles

**Comment by Tyler-Ward** [comment]
Some info to potentialy include

- [ ] Information on rail strikes (Thursday + Friday) + rail works
- [ ] Information on marathon
- [ ] Information on provided lunches
- [ ] Information on arrival times
- [ ] Reminder about the safeguarding policy 
- [ ] Info on the volunteer meal
- [ ] Parking locations
- [ ] what to do when you arrive
- [ ] accomodation reimbursement
- [ ] Roles information

**Comment by PeterJCLaw** [comment]
I've updated the recurring task with those suggestions, thanks @Tyler-Ward.

**Comment by sedders123** [comment]
@Adimote Is this done now? Think I saw an email go out
