### ISSUE TITLE
Acquire carpet for the SR2023 arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1066]
We currently use carpet as the flooring of the arenas. Usually the venue doesn't have an equivalent flooring underneath the arena area so we need to get some ourselves.
We need enough for all the arenas plus some spare for a testing area.

### Original

[comp/arena/carpet](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/carpet.yaml)

**Comment by WillB97** [comment]
This is included in the venue #974
