### ISSUE TITLE
Acquire tape for the SR2023 arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1067]
For the competition we will need vast quantities of tape: - white - black - neon yellow, blue, green, pink - hazard - double-sided for laying the carpet with
We should check what stocks we have and order more if needed.

### Original

[comp/arena/tape](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/tape.yaml)

### Dependencies

 * #995

**Comment by WillB97** [comment]
We need a roll of yellow, green, orange and some rolls of white and the yellow roll for the tokens

**Comment by sedders123** [comment]
Necessary tape has been ordered
