### ISSUE TITLE
Construct arena props

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#107]
Following from #105 we need to build the various arena props.

- [x] Volcano (design: #167)
- [x] Tokens (purchasing: #203, markers: #221)
- [x] Robot flags (#106)

**Comment by Adimote** [comment]
We need budget approval for the tokens

**Comment by Tyler-Ward** [comment]
budget was approved in #203

**Comment by PeterJCLaw** [comment]
Construction of the tokens can probably happen at the venue during the setup days. We'll have lots of volunteers around, meaning that we should have good parallelism to deploy.

@sedders123 are you around on the setup days? If so, as you're doing a bunch of staging/arena things, would you be able to coordinate this and work with @Tyler-Ward to find a slot in the setup schedule (#220)?

**Comment by sedders123** [comment]
I shall be around on the setup days and am happy to coordinate this.

**Comment by PeterJCLaw** [comment]
This is underway
