### ISSUE TITLE
Put up screens around the arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1071]
We have screens around the arena to display live information, these need putting up.

### Original

[comp/arena/screens](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/screens.yaml)

### Dependencies

 * #996
 * #998
 * #1068 Provide network to the arena
 * #1069 Provide power to the arenas
 * #1070 Organise stands for the arena screens

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
