### ISSUE TITLE
Build the arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1073]
Build some arenas for the games.
This covers the physical construction of the arenas, including props needed for the game and markings for the start-position of any which are moveable. The arenas should also be marked so it's clear which is which.

### Original

[comp/arena/build](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/build.yaml)

### Dependencies

 * #1015
 * #1066 Acquire carpet for the SR2023 arenas
 * #1067 Acquire tape for the SR2023 arenas
 * #1068 Provide network to the arena
 * #1069 Provide power to the arenas
 * #1071 Put up screens around the arenas
 * #1072 Organise tools for arena construction

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
