### ISSUE TITLE
Put crowd barriers around the arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1074]
Since SR2015 we have used short wood-only walls for the actual arenas and had separate crowd barriers around the arena area (including the staging area).
We need to ensure that these barriers are procured in advance and then put into place before the first matches. They also need a mechanism to prevent them from moving (tape on the feet has been used in the past).

### Original

[comp/arena/barriers](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/barriers.yaml)

### Dependencies

 * #1073 Build the arenas

**Comment by WillB97** [comment]
This will be rope barriers.

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
