### ISSUE TITLE
Prepare robot flags for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1076]
During matches robots are given coloured flags so that the audience know which robot is from which scoring zone.
At least two complete sets of each badge are needed: one for the robots currently playing and another for the robots currently staging.

### Original

[comp/game/robot-flags](https://github.com/srobo/recurring-tasks/blob/master/comp/game/robot-flags.yaml)

### Dependencies

 * #995
 * #1075 Purchase spare robot flag mounting hardware

**Comment by sedders123** [comment]
Blocked on knowing whether we already have these made, needs a container trip

**Comment by WillB97** [comment]
These are in the container
