### ISSUE TITLE
Prepare generic music playlist for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1082]
During matches we want music to be played into the arena.
We typically have 2 playlists: one for during matches, and one for during breaks. Generally the former is more "intense" than the latter.
Note that there is a separate task for the time-synchronised music played during the finals.

### Original

[comp/arena/music](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/music.yaml)

### Dependencies

 * #981

**Comment by sedders123** [comment]
We have enough to run on, we may continue to tweak this
