### ISSUE TITLE
Design Scoring Sheets

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#109]

**Comment by PeterJCLaw** [comment]
This is highly coupled to the score-input software. See https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#create-a-score-sheet for guidance.

**Comment by PeterJCLaw** [comment]
Historically this has been stored in https://studentrobotics.org/cgit/arena.git, though more recently (because of how coupled it ends up being to the scoring logic (#111) and the score-input UI (#175).

**Comment by PeterJCLaw** [comment]
Our usual design would be to have an arena-like layout, with score entry boxes for each zone, however in this year's competition, that's 25 entry boxes, which is quite a lot.
I think that using the form would be ok, it's just going to be ugly.
Has anyone had any other ideas?

**Comment by PeterJCLaw** [comment]
Hurr. So this is _further complicated by needing to record where each robot ends up as well. Our usual approach is to have letters for each of the colours of token (per robot) and record/parse a string of those.

However, those are now ambiguous because the robots are also (somewhat by definition) the same colours.

An obviously (but utterly unworkable) approach would be to use upper case for one and lower case for the other.

Zone numbers might be possible, but then there's the question of match officials needing to remember that numbers are robots and letters are tokens (or vice-versa).

We probably _can't_ use the idea of writing TLAs where the robots end up either, as I strongly suspect that the TLAs overlap with our colour names too (though it would be totally awesome if they somehow didn't).

**Comment by PeterJCLaw** [comment]
Here's a first pass at this [score-sheet-2019.pdf](https://github.com/srobo/tasks/files/2898437/score-sheet-2019.pdf)

Concerns I have:
* Is it clear enough that you need to fill in stuff outside the main arena box?
* Is it clear enough what to do using the boxes inside the arena? I think the tokens are probably fine, it's the robot notations I'm concerned about.
* Is there enough space to write stuff in?

**Comment by RealOrangeOne** [comment]
We ran a test with a given mock arena, and 4 people scoring it, and everyone made mistakes. The fastest someone scored it was 1:45, most were just over 2 minutes. These were done with little training on how the sheet works.

### Mistakes:
- People putting the second line of tokens on the robot line
- Duplicating tokens outside the arena
- Tokens elsewhere expects a list, not a number.

### Potential improvement
- Increase contrast between grid lines and underlines for tokens / robot inputs. The grid lines should
- Making tokens elsewhere a number of those elsewhere (maybe)
- Lots of training!!!!
- A lot of padding between matches

The main slowness was enumerating each section of the caldera. I don't know how this can be improved.

**Comment by PeterJCLaw** [comment]
Ok, here's a second approach. This:
 - introduces a highlight underneath the volcano squares
 - greatly simplifies the sheet visually (I've actually made the boundary lines _thinner_ as I suspect that the overall visual clarity will win out over thicker lines, but happy to also try approach if this version doesn't improve things)
 - clarifies the instruction around the "robots" slots

[score-sheet-2019.pdf](https://github.com/srobo/tasks/files/2922464/score-sheet-2019.pdf)
![score-sheet-2019](https://user-images.githubusercontent.com/336212/53686998-a488ef80-3d26-11e9-873c-a6411dd70186.png)

**Comment by RealOrangeOne** [comment]
This looks like it should improve things greatly. Removing the 'tokens elsewhere' section does reduce error correction, but I suspect that's fine.

I'll ensure some testing is done on this iteration next weekend.

**Comment by PeterJCLaw** [comment]
[score-sheet-2019.pdf](https://github.com/srobo/tasks/files/2948643/score-sheet-2019.pdf)

**Comment by PeterJCLaw** [comment]
I'm happy with that last sheet, so I'm calling this done.

**Comment by PeterJCLaw** [comment]
Now with `s/Purple/Pink/`

[score-sheet-2019.pdf](https://github.com/srobo/tasks/files/3026864/score-sheet-2019.pdf)
![score-sheet-2019](https://user-images.githubusercontent.com/336212/55291885-f4b5a900-53db-11e9-978e-ef6bc0e686b2.png)
