### ISSUE TITLE
Plan helpdesk at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1095]
Helpdesk is the single-point-of-contact for teams to get help with their robots. We need to plan who will run this on the day as well as the various things it needs to be able to help the teams.

### Original

[comp/pits/helpdesk/main](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/helpdesk/main.yaml)

### Dependencies

 * #1022
 * #1028 Plan for handling of sad batteries
 * #1079 Provide power to all team pits
 * #1080 Prepare battery charging station
 * #1089 Create a list of available subject matter experts
 * #1093 Have spare kit available at the competition
 * #1094 Create domain expert list

**Comment by trickeydan** [comment]
The Kit Team are organising Helpdesk this year.
