### ISSUE TITLE
Set up a power tools area

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1096]
Rather than letting teams use power tools in their team pits, we ask them to go to a separate area.

### Original

[comp/pits/power-tools](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/power-tools.yaml)

### Dependencies

 * #986
 * #1079 Provide power to all team pits

**Comment by Scarzy** [comment]
This doesn't feel like a Health and Safety task?

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
