### ISSUE TITLE
Organise internet access for the team pits

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1097]
Teams need access to the internet to access Discord and the documentation. We therefore need network access in all the team pits.
Past experience with WiFi-only network provision has been mixed, so hard-wire network provision should be considered unless the venue has well proven capacity.
Some venues' internet provision requires the use of guest accounts. If these are needed, We should ensure (as part of this task or by adding a sub-task) that suitable accounts are obtained, ideally at least per-team as well as for volunteers.

### Original

[comp/pits/network](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/network.yaml)

**Comment by WillB97** [comment]
This will be Eduroam accounts.

**Comment by trickeydan** [comment]
We'll need to document the helpdesk process for handing out eduroam accounts in line with university IT policy

**Comment by Adimote** [comment]
I've sent an email to joyce asking for a set of 50 eduroam accounts.

That's for 36 teams + comp systems + some volunteers.

**Comment by Adimote** [comment]
I emailed son at 10pm last night, and got eduroam accounts at 9am this morning :)

Have added them to the print drive folder in #1026 so I'm marking this done
