### ISSUE TITLE
Print the scoring sheets

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#110]
Depends on #109

- [ ] 250 x https://github.com/srobo/tasks/files/3026864/score-sheet-2019.pdf (from https://github.com/srobo/tasks/issues/109#issuecomment-478375018)

**Comment by antonnikitin97** [comment]
I will do this.

**Comment by Tyler-Ward** [comment]
These will need to be printed with punch holes to aid binding.

**Comment by Tyler-Ward** [comment]
@PeterJCLaw how many do we need to print

**Comment by RealOrangeOne** [comment]
2 per match, plus ~20 for spares.

The spares number is quite low, because the lead time for additional spares is quite low.

**Comment by trickeydan** [comment]
>  because the lead time for additional spares is quite low.

I would class about an hour as medium lead time during the competition.

**Comment by Tyler-Ward** [comment]
How many matches will that be for?
Also we should have some for training marshals.

Given how few volunteers will have access to printing and the fact that they might be busy the lead time will be quite high so. However we can do a print run at lunchtime on the sunday if we are running low on spares.

**Comment by RealOrangeOne** [comment]
We have a printer we can have pre-prepared and setup in the cube, therefore the lead time is "low".

src: https://github.com/srobo/tasks/issues/183#issuecomment-471165419

**Comment by trickeydan** [comment]
> We have a printer

It is untested. Given that it is an inkjet, it is probably blocked up by now.

Additionally, it has run out of ink https://github.com/srobo/tasks/issues/183#issuecomment-471165736, a replacement costs [£23.84](https://www.amazon.co.uk/HP-Tri-color-Original-Cartridges-X4D37AE/dp/B01LXLFF6H). If we were to purchase another one, it would degrade in the container and would have to be replaced next year anyway.

Even if we pay full price for uni printing(we don't intend to), it would cost £20 for 500 sheets (500 * [£0.04](https://www.southampton.ac.uk/isolutions/students/printing-for-students.page)), which is obviously cheaper, higher quality and is guaranteed to work. Also we can print in advance if we use the university printers.

**Comment by PeterJCLaw** [comment]
We shouldn't rely on the printer for printing large volumes of things. It's fine for spare maps & schedules for the shepherds, but as it's a standard home-office printer it'll take far too long to print score-sheets on.

Assuming that we have about 100 matches (which is about right) and allowing for some spares, I'd suggest that we get 250 copies of the score-sheets.

As a side-point: note that we _do_ want to have in-venue printing capabilities, so the comparison against the replacement ink cartridge is somewhat moot as we pretty much need the replacement anyway.

**Comment by PeterJCLaw** [comment]
I've just spotted that the score-sheets still label Zone 2 as "purple" when it's more nearly a "pink". We should fix that before printing.

**Comment by PeterJCLaw** [comment]
Colour fix in @jsedens https://github.com/srobo/arena/pull/1 for you

**Comment by PeterJCLaw** [comment]
Colour fixed.

**Comment by RealOrangeOne** [comment]
We need around 100 more of these.

**Comment by TomWheal** [comment]
@RealOrangeOne so 350?

**Comment by RealOrangeOne** [comment]
Sorry no, bad wording. We need 100 more to be printed, I believe we already have 150 printed.

**Comment by TomWheal** [comment]
Done
