### ISSUE TITLE
Prepare team pits at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1101]
Teams need team pits to work in, and these need setting up.

### Original

[comp/pits/main](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/main.yaml)

### Dependencies

 * #1043 Work out layout of teams at the competition
 * #1079 Provide power to all team pits
 * #1092 Organise tables and chairs for team pits
 * #1095 Plan helpdesk at the competition
 * #1096 Set up a power tools area
 * #1097 Organise internet access for the team pits
 * #1098 Determine and publish rules for the pits
 * #1099 Roll out at team pits at the competition
 * #1100 Furnish each pit with a clearly visible label

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
