### ISSUE TITLE
Prepare game equipment for the arena

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1102]
We need to prepare the things that will go in the arena. See this year's [rulebook](https://studentrobotics.org/docs/resources/2023/rulebook.html) for details.
Sub tasks should be added to this task for each of the various props which are needed.

### Original

[comp/game/props](https://github.com/srobo/recurring-tasks/blob/master/comp/game/props.yaml)

### Dependencies

 * #1016
 * #1076 Prepare robot flags for the competition

**Comment by WillB97** [comment]
This year this includes tokens and a plinth.

**Comment by WillB97** [comment]
The tokens have been assembled.

**Comment by WillB97** [comment]
The plinth constuction has been organised.
