### ISSUE TITLE
Deploy the Compbox

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1110]
The compbox VM will need deploying onto the host machine and ensuring that it works.
This should also include confirming that it's got a static name/address and that the relevant pages can be seen from other machines.

### Original

[comp/ops/deploy-compbox](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/deploy-compbox.yaml)

### Dependencies

 * #1042 Prepare the Compbox
 * #1068 Provide network to the arena
 * #1069 Provide power to the arenas

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
