### ISSUE TITLE
Deploy Ops for the SR2023 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1112]
Ops needs a table and network connection to work from. It should be located somewhere protected from the competitors, but vaguely near the arena so the people manning it can see what's going on and easily communicate with the Master(s) of Ceremonies.

### Original

[comp/ops/deploy](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/deploy.yaml)

### Dependencies

 * #1045 Prepare the SR2023 Compstate
 * #1110 Deploy the Compbox
 * #1111 Deploy the score entry system

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
