### ISSUE TITLE
Import the (final) teams data into the compstate

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1113]
We need to run the teams import into the compstate as part of the setup so that it's got the latest team images.
This import may also need re-running during the competition.

### Original

[comp/ops/teams-import](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/teams-import.yaml)

### Dependencies

 * #1045 Prepare the SR2023 Compstate

**Comment by PeterJCLaw** [comment]
We don't do team images any more. There might be dropouts between now and the competition, but I don't think that this task will be useful in ensuring that we remember to remove them.
