### ISSUE TITLE
Plan the Tech Desk

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1114]
Ensure we have enough table top space, power and networking for all necessary equipment at the tech desk.
Things that have previously been on tech desk include:
 - Event scoring control + printing
 - Livestream (handled separately https://github.com/srobo/tasks/issues/1158)
 - Networking
 - Judging
 - Radio charging
 - Lighting desk
 - Sound desk
 - Score-entry (typically now its own desk near the arena; ref https://github.com/srobo/tasks/issues/1111 and https://github.com/srobo/tasks/issues/1106)
 - A corner for various servers for:
   - Non-sync audio (background music not running through mixtape)
   - sync audio (currently [mixtape](https://github.com/srobo/srcomp-mixtape))
   - compbox

### Original

[comp/ops/plan-tech-desk](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/plan-tech-desk.yaml)

**Comment by sedders123** [comment]
@RealOrangeOne I think we've used your laptop for background music in the past, are we ok to use it again?

**Comment by RealOrangeOne** [comment]
Yep that's fine :+1: I'll make sure it's setup and ready for that. We can reuse it for mixtape if needed.

**Comment by antonnikitin97** [comment]
Request, can the desk for the livestream be such that you can attach monitor clamps to it? :)

**Comment by PeterJCLaw** [comment]
I suggest that we have a separate task for planning the livestream desk? While it may be located near the Tech Desk, I think it's probably got enough other considerations that having its own issue would be useful (for tracking, discussion, etc.). What do you think @antonnikitin97?

**Comment by antonnikitin97** [comment]
I agree :) I've raised #1158 to track it.

**Comment by WillB97** [comment]
This year the balcony will be reserved for the livestream. Lighting and sound desks will be in the booth along with networking, radio charging and my mac + interface to run mixtape and non-sync audio. Score entry will be on the stage, next to staging.
