### ISSUE TITLE
Acquire trophies for SR2023

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1116]
Some awards involve trophies being given to the winning teams. The trophies need purchasing.

### Original

[comp/prizes/trophies](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/trophies.yaml)

**Comment by Adimote** [comment]
Had a look at a couple suppliers, 'TrophyStore.co.uk' is now slightly cheaper than our usual supplier, 'Trophies2u.co.uk'. So will order from them. I think we've ordered from both before.

Feels like a bit of a shame to make the robot and team image edible, last year it was an actual trophy

**Comment by Adimote** [comment]
Size | Code | Engraving Text | Price
-- | -- | :--: | --
24cm | GL3100C | 2023<br/>Greed<br/><br/>1st Place | £35.49
22cm |  GL3100B | 2023<br/>Greed<br/><br/>2nd Place | £32.75
20.5cm | GL3100A | 2023<br/>Greed<br/><br/>3rd Place | £30.49
20.5cm |  GL3100A | 2023<br/>Greed<br/><br/>Committee Award | £30.49
20.5cm |  GL3100A | 2023<br/>Greed<br/><br/>Rookie Award | £30.49

Which Totals £159.71 with free delivery. 

See [Spreadsheet](https://docs.google.com/spreadsheets/d/1T2RorLqhv1F5-ql0x-FqD_zxU2Rw_GsrkEXfvEwB73M/edit?usp=sharing)

**Comment by Adimote** [comment]
In addition to the table above, I sent this information to their enquiries@ email:

I've just made the attached order for trophies for our robotics competition. We selected 'send artwork later', so here is the artwork. I've attached mocks for the 3 sizes of trophy we ordered (they're all basically the same design).

Please note the font is '[Open Sans](https://fonts.google.com/share?selection.family=Open%20Sans:ital,wght@0,700;1,700)' Bold 700. Something similar would also be acceptable.
The logo image includes the 'STUDENT ROBOTICS' text, so no need to match fonts for that.

[22cm-gl3100b.pdf](https://github.com/srobo/tasks/files/10948834/22cm-gl3100b.pdf)
[20cm-gl3100a.pdf](https://github.com/srobo/tasks/files/10948835/20cm-gl3100a.pdf)
[24cm-gl3100c.pdf](https://github.com/srobo/tasks/files/10948836/24cm-gl3100c.pdf)
![logo-text-black-vertical](https://user-images.githubusercontent.com/2551763/224493808-39767f55-0d0e-48c1-9171-b3e3e1edbc88.svg)
![logo-text-black-vertical](https://user-images.githubusercontent.com/2551763/224493809-607bd204-76b1-4e03-a0d3-fbc5741e4326.png)

**Comment by PeterJCLaw** [comment]
Yeah, I'm not sure what's happened to the award allocations -- it looks like historically it was the online presence & first movement awards which were edible, but the robot & team image wasn't (at least not stated so in the rulebooks).

**Comment by PeterJCLaw** [comment]
Have created https://github.com/srobo/tasks/issues/1166 for next year.

**Comment by Adimote** [comment]
Annoyingly trophystore.co.uk hit me with a £12 set-up fee, I didn't spot the "NB: art set-up fees may apply" on their website.

This pushes them to be more expensive than trophies2u, but might still be cheaper next year and I'm too lazy to organise a refund so we're just going to pay it

**Comment by WillB97** [comment]
These have arrive and are tracked in the freight list.
