### ISSUE TITLE
Distribute certificates

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1119]
Certificates need distribution to members of the winning teams.

### Original

[comp/prizes/certificates](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/certificates.yaml)

### Dependencies

 * #1118 Design certificates

**Comment by antoinepetty** [comment]
Not doing certificates this year https://github.com/srobo/tasks/issues/1118#issuecomment-1426425471
