### ISSUE TITLE
Organise the SR2023 post-finals sequence

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1126]
At the end of the competition we want to give out some prizes. We need to plan how we will transition from the finals, through any speeches and run the actual prize-giving ceremony.
We should ensure that anyone who is speaking (whether a volunteer or a guest speaker) knows how long they have, what we're expecting them to talk about and is well rehearsed.
We should include (somewhere) thanks to various people: teams, volunteers, sponsors, etc.

### Original

[comp/prizes/ceremony](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/ceremony.yaml)

### Dependencies

 * #1023
 * #1120 Arrange a speaker for the prize ceremony
 * #1121 Take a vote on the online presence award
 * #1122 Establish the winner of the first movement award
 * #1123 Establish the final results for the main prizes and the rookie award
 * #1124 Decide on the recipient of the committee award
 * #1125 Decide on the winner of the team image award

**Comment by RealOrangeOne** [comment]
Current plan: https://docs.google.com/document/d/19DAhOTKNY9wXCOS4bCrX0O2ZR01iJe1k5utSJsr3XDg/edit?usp=sharing

**Comment by PeterJCLaw** [comment]
@RealOrangeOne just checking your aware that the current day schedules (https://github.com/srobo/tasks/issues/1004) have the group photo between the final and the prize-giving? That will likely impact how this flows.
