### ISSUE TITLE
Purchase Scoring Stationery

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#113]

**Comment by PeterJCLaw** [comment]
Historically this has consisted of:
* pens (for the match officials to use)
* the printed score-sheets (#110)
* a box file or lever-arch folder for the used score-sheets
* a hole-punch

Having a box of pens at the venue is useful anyway (reception & helpdesk are other places which would benefit, I'm not aware that anywhere needs a whole box on its own though).

I think we might have a hole-punch in storage from previous years, but we should check that.

**Comment by prophile** [comment]
We need a box file but nothing else.

**Comment by Adimote** [comment]
Maybe available in Zepler reception

**Comment by jcwilliamson** [comment]
I've had a dig around my room at home, and I've found a large lever arch/ringbinder folder. Unless people definitely want a box file, it should be fine.

**Comment by RealOrangeOne** [comment]
The issue with a ringbinder is that it also required a holepunch, which isn't ideal, although it does maintain order nicer. If we can also get a holepunch, it's _probably_ fine.

**Comment by Tyler-Ward** [comment]
we could prepunch the scoring sheets when we print them

**Comment by TomWheal** [comment]
You can do this on the uni printers.

**Comment by PeterJCLaw** [comment]
We also _have_ a hole-punch (in storage).

**Comment by Tyler-Ward** [comment]
Do we need to purchase anything for this if so can someone create a shopping list that I can approve.

**Comment by RealOrangeOne** [comment]
If @jcwilliamson is happy _donating_ his ringbinder, and we remember to print the score sheets holepunched (#110), then we can close this issue entirely

**Comment by trickeydan** [comment]
@jcwilliamson has confirmed to me in person and will put it in the Mountbatten cupboards on Monday.
