### ISSUE TITLE
Show the live stream within the venue

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1134]
We should ensure the live stream of the competition is viewable within the venue. This enables everyone to see matches without actually being arena-side.
In the past the display has included a split-screen view of all the arenas which most people liked. It would be good to do this again.

### Original

[comp/livestream/local](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/local.yaml)

### Dependencies

 * #1051 Arrange a live stream from the competition

**Comment by WillB97** [comment]
The displays in the venue support being given a youtube livestream to display.

**Comment by WillB97** [comment]
This will be shown on the patio screen, concourse screen and one of the cafe screens.
