### ISSUE TITLE
Prepare signage for the SR2023 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1139]
We'll want to put up various signage of our own, even if the venue cover the basics. For example, we have our own giant banner which should go somewhere and we'll want directions to Helpdesk and the Areans.

### Original

[comp/venue/signage](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/signage.yaml)

### Dependencies

 * #986

**Comment by sedders123** [comment]
With our new media consent strategy we need to make sure we have signs stating photos and videos are being taken and that people can opt out by requesting a red lanyard at helpdesk.

**Comment by sedders123** [comment]
We should also have a separate sign for the cube indicating that a livestream is in progress and we can't guarantee that they won't be visible on camera

**Comment by sedders123** [comment]
Also:
 - No Entry
 - Arrows pointing in different directions with label of Arena
 - Toilets with arrows

**Comment by antoinepetty** [comment]
We have a file for signage from last year in the Competition drive https://docs.google.com/presentation/d/12wD2JXHxDHOTe5ymerCehyfl5H_GK0lfUasdEOIRIQQ/edit?usp=sharing

**Comment by Tyler-Ward** [comment]
Elevator direction signage was requested in the retro review from last year

**Comment by sedders123** [comment]
This was sent to print https://docs.google.com/presentation/d/12wD2JXHxDHOTe5ymerCehyfl5H_GK0lfUasdEOIRIQQ/edit?usp=sharing
