### ISSUE TITLE
Plan setup schedule and organisation

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1140]
We need to plan tasks for the setup days

### Original

[comp/setup-plan](https://github.com/srobo/recurring-tasks/blob/master/comp/setup-plan.yaml)

### Dependencies

 * #986

**Comment by WillB97** [comment]
https://docs.google.com/spreadsheets/d/1TNd25IXQd1r1vh6heelIT62Py7OtYkqEQDnQmxEPrR4/edit?usp=sharing
