### ISSUE TITLE
Trim the live stream VOD (Video on Demand)

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1146]
The live stream VOD should be trimmed to remove the start and end of the competition.

### Original

[comp/livestream/crop-vod](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/crop-vod.yaml)

### Dependencies

 * #1051 Arrange a live stream from the competition

**Comment by PeterJCLaw** [comment]
https://srcomp-cli.readthedocs.io/en/latest/commands/youtube-chapters.html is likely useful once the trimming is done.

**Comment by sedders123** [comment]
We have trimmed Day 1, day 2 is too long to trim. Chapters have been added
