### ISSUE TITLE
Gather feedback from teams

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1147]
Send to everyone who was signed up for SR2023.
Usual things:
  - Demographics
  - Prior experience
  - Did they get the support they needed
  - Are Tech Days useful to them?
  - Do they feel that they have the resources in school now?
    If not, why aren't they coming/what can we do to make them more useful?
    Is more real-competition testing the key factor here?

Example from SR2020: https://docs.google.com/forms/d/1HE8b1oRF6dHc3wbBUICJV5CsXHv3qR7egcMtud6pfd4/edit?usp=sharing

### Original

[comp/feedback/gather-team-feedback](https://github.com/srobo/recurring-tasks/blob/master/comp/feedback/gather-team-feedback.yaml)

**Comment by WillB97** [comment]
Some of this data we can gather before the competition so it's probably worth spliting the questions across 2 feedback forms.

**Comment by RealOrangeOne** [comment]
A draft of these questions has been sent to the trustees for review.

I agree with separating these into 2 forms, as most of the questions aren't dependent on the final competition (eg demographics).

**Comment by PeterJCLaw** [comment]
@RealOrangeOne where did we get to on this? Have we sent out a wrap-up email to teams yet?

**Comment by RealOrangeOne** [comment]
The form was publicized (throughout the event and in the prize-giving), and we have some responses.

Given the number we have, I think we can consider this resolved as #1150 goes out.

**Comment by Adimote** [comment]
Feedback from the end of 2023: we should capture the team's TLA when capturing information
