### ISSUE TITLE
Create post competiton reports

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1149]
We should give a report on the SR2023 competition cycle and details of the event to the trustees once everything from the event has been sorted out. This will also include a spending report for the year.

### Original

[comp/feedback/post-competition-reports](https://github.com/srobo/recurring-tasks/blob/master/comp/feedback/post-competition-reports.yaml)

### Dependencies

 * #1147 Gather feedback from teams
 * #1148 Gather feedback from volunteers

**Comment by prophile** [comment]
https://docs.google.com/document/d/1gYniRn6yVnNonWEHcBXnIC_tWRieaFlZ-5B6nbRIfw0/edit?usp=sharing
