### ISSUE TITLE
Establish the winner of the challenges award

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1157]
The challenge submissions need to be searched and the first team to complete all 3 challenges recorded.

**Comment by RealOrangeOne** [comment]
I've created a document to track the winners of the various prizes: https://docs.google.com/spreadsheets/d/1X4oIw7JndpZ18oaaCcz-4LD8utWVfar2QMB0nfEIaHw/edit?usp=sharing

**Comment by PeterJCLaw** [comment]
Have updated the sheet.
