### ISSUE TITLE
Plan the music for the livestream

### ISSUE THREAD

**Issue by antonnikitin97** [srobo/tasks#1161]
It would be nice to have music during the livestream to make it more engaging.

**Comment by ZachWilliamsSR** [comment]
[Spreadsheet for music ideas](https://docs.google.com/spreadsheets/d/1_A26pGus0drJshlkoUZRMzekP1ScVglM/edit?usp=sharing&ouid=105303143956001283534&rtpof=true&sd=true&authuser=1)

**Comment by sedders123** [comment]
Woops this looks like its for the in person competition not the virtual one
