### ISSUE TITLE
Plan handling of batteries overnight

### ISSUE THREAD

**Issue by raccube** [srobo/tasks#1165]

**Comment by RealOrangeOne** [comment]
Suggestion: Request teams hand all batteries in to helpdesk. Have roving helpers look in pits for any batteries left behind.

**Comment by raccube** [comment]
What I have so far:

>All teams hand batteries in to helpdesk by the end of the day. Roving helpers to go through pits for any leftover batteries. Batteries are to be put LiPo-safe bags. These batteries are to be locked overnight in The Cube.

**Comment by raccube** [comment]
This is now in the Helpdesk Procedures document.
