### ISSUE TITLE
Plan post-competition news announcements

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#117]

**Comment by RealOrangeOne** [comment]
We missed this for SR2017, and it looked bad, i'd suggest upgrading this to 'must have'.

**Comment by PeterJCLaw** [comment]
The competition _can_ happen without this, so I've downgraded. I agree this is very important though.

**Comment by PeterJCLaw** [comment]
Perhaps we need a second milestone of Competition Planning, which this would fit under? That is: a list of tasks which should be done well ahead of time, rather than in the immediate run-up or setup days for the competition?

**Comment by antoinepetty** [comment]
Draft available here based on previous years:
https://docs.google.com/document/d/1bHZp2GgbSrQPB5Iyh1-VQoLIjZp61iQF2nmh_k6-Rpw/edit?usp=sharing
Can't add much more detail until the competition has concluded.

**Comment by Tyler-Ward** [comment]
I have added some comments and ideas to the doc

**Comment by antoinepetty** [comment]
Template created - closing for now. Will revisit very soon after competition (ie competition evening or next morning)
