### ISSUE TITLE
Organise provisions for coping with the marathon

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1170]
Southampton has a marathon on the Sunday of the event. We need to organise how we deal with parking and access to Burgess Road.

**Comment by Scarzy** [comment]
Same story as last year, we can access between Burgess Road (westbound) down to Salisbury Road. Permission to cross route slip in the shared drive.. We should allocate some of our volunteers to direct vehicles down Salisbury road.

First Aid will be directed to the carpark closest to the rear of SUSU.
