### ISSUE TITLE
Plan the competitor Photo

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1171]
## Dry Weather
1. Ensure side-gate is unlocked
2. Banner removed
3. League matches end
4. Shepherds used to direct teams to the normal hill, told to bring robots
5. Banner taken to hill
6. When all at hill, robots placed on floor in front of banner with competitors holding banner
7. Photographer takes photo
8. All return to pits/lunch
9. Banner taken to cube and put up on bottom of stage (ready for prizegiving)

## Wet Weather

1. Banner removed
2. League matches end.
3. Arena cleared of tokens
4. Shepherds used to direct teams to the cube, told to bring robots
5. Competitors directed to stand in and arena with robots held by team members on stage
6. Photographer takes photo
7. All return to pits/lunch
8. Banner taken to cube and put up on bottom of stage (ready for prizegiving)

**Comment by WillB97** [comment]
Those are the instructions for the competitor photo, not the volunteer photo

**Comment by Adimote** [comment]
oops.
