### ISSUE TITLE
Design shift changes when making the day schedule

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1172]
Change the recurring task around day schedule design to take shift changes into consideration.

Ensure we don't have:
- Odd shift lengths.
- Long shifts.
- People not getting a full lunch break.

**Comment by sedders123** [comment]
We're changing scheduling for SR2025 to allow areas more flexibility in the timing of their shifts. This should help, say, match ops to ensure that shift changes happen outside of matches and at times optimal to them
