### ISSUE TITLE
Ops training – make sure we have ‘drill’/’training’ in messages

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1178]
We caused a scare in SR2023 by doing a drill first-aid incident during training. Any time we do training we need to include the words 'drill' and 'training'

**Comment by samjmartin04** [comment]
To add to this, one of SUSU crew said that we should let them know beforehand that we are doing a training exercise. Wouldn't have prevented the problem that happened this year, but letting some people know beforehand would be helpful.

**Comment by trickeydan** [comment]
> To add to this, one of SUSU crew said that we should let them know beforehand that we are doing a training exercise. 

Nobody told us on helpdesk either. The first message was quite alarming.

**Comment by samjmartin04** [comment]
This has been included as part of the training process requirements of match ops training https://github.com/srobo/tasks/issues/1437.
