### ISSUE TITLE
Rename Event Coordinator  to 'volunteer coordinator' + clarify responsibilities

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1179]
We should update our documentation/recurring tasks to refer to the 'Volunteer Coordinator'. Also should clarify the responsibilities between them and the Event Director.

**Comment by PeterJCLaw** [comment]
These feel like two separate roles to me, even if we have the same person doing them at the moment. It's not clear to me that renaming this role is a good move. What's the motivation for this?

**Comment by PeterJCLaw** [comment]
Maybe I'm missing something. "Event Coordinator" is a role which appears in the runbook and appears to be used in place of what you're maybe calling "Event Director" (which does not appear at all). "Volunteer Coordinator" has precisely one mention in the runbook.

Neither seems to have an outline of what the role is, so expanding on that sounds good either way.

None of these terms are mentioned in the recurring tasks.

Perhaps it would be useful to clarify on this ticket what is actually going to get changed here?

**Comment by sedders123** [comment]
This has changed. For SR2025 we have an event coordinator and volunteer coordinator as named roles + area owners
