### ISSUE TITLE
Tape for specific roles should be kept separate

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1186]
Earmarked tape needs to be kept separate, to avoid using it for other tasks.

**Comment by PeterJCLaw** [comment]
FWIW: at this year's event I reorganised the boxes of tape into "interesting" (18l RUB) and "boring" (35l RUB) tape. The latter is things like white/black gaffer tape and carpet tape, the other is all forms of coloured gaffer tape, electrical tape etc.

**Comment by sedders123** [comment]
Sorting into interesting and boring worked well for SR2024. We should ensure we have a surplus of boring tape to make sure that both the arena and other areas/tasks can work in parallel. Think this should already be tracked by https://github.com/srobo/tasks/issues/1418
