### ISSUE TITLE
Create pre-training checklist

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1192]
Make sure we have:
- Radios ready
- Clipboards and docs ready
- Awareness of what channels we’re using for training
- Awareness of training-specific procedures
- srcomp running fake matches
- Make sure an example handover brief is done

**Comment by prophile** [comment]
I think we're going with ops now rather than match ops but yes

**Comment by RealOrangeOne** [comment]
It's not so much a checklist that we want, but some documentation that covers what it is we want to train people on (match process, scoring, competitor management etc). A part of that naturally will be a requirements checklist.

**Comment by samjmartin04** [comment]
A list of what is required for training has been added to training match ops https://github.com/srobo/tasks/issues/1437.
