### ISSUE TITLE
Shepherd procedures during teardown should rely on radios only and stop using phones

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1196]
Shepherd procedures during teardown should rely on radios only and stop using phones, as the phones will be torn down during teardown

**Comment by samjmartin04** [comment]
Was this a problem in the past? The shepherding team disbands as soon as all competitors have left the building, so the potential time when phones may have been torn down and shepherding team still exists seems small/non existent to me.

Either way, a note about this has been added to the Head Shepherd checklist.
