### ISSUE TITLE
Have a 5th person on shepherding shift

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1197]
This is to allow for an additional marshal and a shepherd at the test arena.

**Comment by PeterJCLaw** [comment]
Is the number 5 important here? Or is the point that this is N_AREAS + 1?

**Comment by prophile** [comment]
min(5*arenas, n_areas+1)

**Comment by samjmartin04** [comment]
Number of people required per match ops team has been included as part of organising match ops https://github.com/srobo/tasks/issues/1435.
