### ISSUE TITLE
Pick & Announce Tech Day dates

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#12]
We should find some good Saturdays for tech days, aim for 1 per month, so 4 in total.

Space them out nicely, bearing in mind that teams don't do much at the start of the competition, and that teams are less likely to turn up in the middle of school breaks.

**Comment by Adimote** [comment]
I've done some research and made some proposed dates at:
https://docs.google.com/spreadsheets/d/1B2NNTxMt8lTa8quxXa_FuxiU4z6-yI4GcRjK4wX18yQ/edit?usp=sharing

**Comment by Adimote** [comment]
Will close this once we've confirmed them on Tuesday

**Comment by Adimote** [comment]
Dates are confirmed, will announce soon

**Comment by PeterJCLaw** [comment]
@Adimote can we close this then?

**Comment by Adimote** [comment]
I'll wait until they're announced before I close this

**Comment by PeterJCLaw** [comment]
Dates are live on the website.
