### ISSUE TITLE
Plan group photo

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#120]
We should have a photo with everyone at the competition (competitors, team-leaders and volunteers).
We should also have a photo with just the volunteers, probably in the same slot since we'll already all be in the right place.

Note: if you're looking for the team photos, see #198.

**Comment by RealOrangeOne** [comment]
We've now allocated a time slot in the schedule for this (https://studentrobotics.org/events/sr2019/competition/). 

We now need to arrange who will take the picture, and where to take it. I suspect the hill next to SUSU will be ideal, if we can get the camera high enough and far enough away.

**Comment by Tyler-Ward** [comment]
Plan for locations.
With rain: Bar 2 or Arena
Without rain: Redbrick/Grass south of SUSU.

**Comment by PeterJCLaw** [comment]
Do we know who will be taking this photograph and that they have sufficient experience and quality camera to do it well?

**Comment by RealOrangeOne** [comment]
@Tyler-Ward has volunteered, and i've checked he has a camera of decent quality, and a tripod.

**Comment by PeterJCLaw** [comment]
Would that still allow him to be _in_ the photo? It would be a shame if not all the Core Team were able to be in the photo.

**Comment by Tyler-Ward** [comment]
I can either use the timer and then move in or setup the shot and have someone else just press the button.
