### ISSUE TITLE
Use 'tickets' for test area

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1200]
In SR2023, the tickets in tinker time worked well. The test arena on second hand was very chaotic. We should use the same system for both.

**Comment by RealOrangeOne** [comment]
We intentionally didn't use the same more stringent tinker-time process for the test arena, to make life easier. A table form gets quite large when it needs to span 2 days.

The reason for the "tickets" was to allow booking and validating in different locations. Given the schedule of the test arena, that's probably not useful, and booking at the arena itself is probably ok.

I'd be interested in speaking to people who ran the test arena as to how we can optimise the booking process. The forms they ended up making ad-hoc might be enough (TLA, corner, time in, time out).

**Comment by prophile** [comment]
I think it makes sense to have the same process across anywhere you can book tinker time.

**Comment by trickeydan** [comment]
> In SR2023, the tickets in tinker time worked well.

This was incredibly chaotic at helpdesk. If we're going to expand the scope of bookings via helpdesk, we should revise the process on the helpdesk end.

**Comment by sedders123** [comment]
For SR2024 we borrowed a whiteboard and this seemed to work? Let's do this again.
