### ISSUE TITLE
Confirm number of chairs on Friday

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1204]
we ran out of chairs in SR2023 and had to use venue chairs, we should confirm the number we had.

**Comment by RealOrangeOne** [comment]
I think the main feature is intentionally over-ordering chairs so we have spares, and also ensuring we have a few allocated for the staging area.

**Comment by prophile** [comment]
It wasn't a question of ordering this year. On Friday we were asked whether we had all the chairs we wanted, we didn't check, and by the time it came to Saturday estates weren't around to give us more.

**Comment by sedders123** [comment]
We had spare chairs on hand for SR2024. We will do so again and make sure Help Desks now where they are.
