### ISSUE TITLE
Tinker time coordinator role – should be more junior now we have tickets

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1205]
In SR2023 the tinker time co-ordinator was absent a few times sort important issues. We should have someone less-needed on the role next time.

**Comment by RealOrangeOne** [comment]
I think the title of this ticket is slightly misleading to what the actual improvement is.

Even before, there was nothing that stopped a "junior" volunteer from taking it on (we all start somewhere, even I started doing it as a "junior"). Tinker time has been documented for a while: https://studentrobotics.org/runbook/competition/team-support/tinker-time/

"Document new ticket-based tinker time process" might be a better title, as that's the real outcome for this.

**Comment by prophile** [comment]
I think we kind of assumed implicitly it had to be you :)

s/should/can/

**Comment by sedders123** [comment]
For SR2025 the current plan is to move tinker time bookings into the Helpdesk system
