### ISSUE TITLE
Scoresheet design: orientate the scoresheet for where people will actually be standing

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1215]
We should orientate the scoresheet to be probably from the stage POV or staging POV, so they don't need to mentally rotate the arena.

**Comment by samjmartin04** [comment]
I have thought that this would be useful in the past, but the orientation is something that you adapt to fairly quickly after a few practice runs and having this orientation match the rules with corner 0 in the top left does make sense. Orienting the arena for this to be the orientation for staging seems reasonable though.

**Comment by PeterJCLaw** [comment]
We are doing this for SR2024 (see https://github.com/srobo/arena/pull/5) -- per Sam's suggestion (though separately thought of) we've opted to change the orientation of the arena in the Cube rather than changing the score-sheet.
