### ISSUE TITLE
Plan helpdesk procedure

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#122]
See also https://bitbucket.org/richardbarlow/sr-comp-team-support-coord/wiki/Helpdesk

**Comment by RealOrangeOne** [comment]
In my experience, one of the most useful things for this is some kind of escalation tree, which takes into account those peoples kit experience, and likeliness to be busy during the event

**Comment by Adimote** [comment]
https://hackmd.io/2FKmAGKzSKm2OuTWh3M9UA has some info on how helpdesk people should handle battery charging, sadly @trickeydan is too busy to finish this.
