### ISSUE TITLE
Game Themes should be much stronger

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1223]
Think hard about the theme of the game in the dev process; allocate budget for it.

We received feedback from teams that having a theme really motivates some students, so lets try hard at theming the game!

**Comment by PeterJCLaw** [comment]
I think this has happened this year? Do we want to keep this open to turn it into a checklist/runbook entry perhaps?

**Comment by samjmartin04** [comment]
To ensure this does not get missed, I've mentioned this as part of creating the SR2025 game https://github.com/srobo/tasks/issues/1363, but this may fit better as its own task in future.
