### ISSUE TITLE
Organise SR2024 Tech Days

### ISSUE THREAD

**Issue by sedders123** [srobo/tasks#1229]
We should reach out and book venues for tech days throughout the SR2024 competition year. If we can announce dates + locations at Kickstarts makes everyone's life easier from a planning perspective.

**Comment by sedders123** [comment]
4th Nov - Tech Day
9th Dec - Challenge Deadline + Tech Day
20th Jan - Challenge Deadline + Tech Day
10th Feb - Virtual Competition
2nd March - Tech Day

**Comment by PeterJCLaw** [comment]
This has happened; the details are on the website and teams have been signing up. The virtual competition is still in flux, but that's separate.
