### ISSUE TITLE
Plan SR2024 livestream music

### ISSUE THREAD

**Issue by antonnikitin97** [srobo/tasks#1232]
**As an:** SR Livestream Area Owner
**I want to:** Create playlists of music for the various livestreams that will occur for SR2024.
**So that:** We can have appropriate music for all the livestreams to increase production value and maintain engagement.

**Acceptance criteria:**

- Existing SR 2023 livestream playlists reviewed and updated for SR2024.
- Epidemic licenses are obtained for when we need them (see additional info below).
- New playlist created for Kickstart 2024.

**Additional information:**
We need to create playlists for the various livestreams for SR2024.

We already have music playlists for SR2023 Day 1/Day 2 so we can use/adapt those.

Epidemic Sound licenses
We use epidemic sound in our livestreams, we need to buy monthly subscriptions to allow us to use the music for the kickstart, virtual, and in-person comps.
- [x] Obtain monthly Epidemic Sound license for Kickstart.
- [ ] Obtain monthly Epidemic Sound license for Virtual Competition
- [ ] Obtain monthly Epidemic Sound license for SR2024 in-person competition.

**Comment by antonnikitin97** [comment]
I purchased an Epidemic sound license last week to cover us for the kickstart.

**Comment by PeterJCLaw** [comment]
Kickstart happened :)
