### ISSUE TITLE
Request access to info@ from the trustees

### ISSUE THREAD

**Issue by sedders123** [srobo/tasks#1236]
Since we're occasionally using info@ to send emails (e.g: volunteering enticement emails) which encourage replies, it would be great if we had access to that inbox.

From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-24.md#specific

**Comment by RealOrangeOne** [comment]
I've just checked Google Workspace. `info@` is configured as an alias for `trustees@`

**Comment by PeterJCLaw** [comment]
I think that's probably ok? We probably need to work out what the intended use-case for `info@` is anyway and let that decide what address we use for each outgoing case.

**Comment by PeterJCLaw** [comment]
I've asked all the committees to contribute to a spreadsheet with what our various email addresses are used for. Hopefully that'll help with next steps here.

**Comment by PeterJCLaw** [comment]
@srobo/marketing-committee @srobo/trustees what are your thoughts on moving `info@` to being a group which forwards to both of your addresses, rather than just being `trustees@`?

**Comment by PeterJCLaw** [comment]
> @srobo/marketing-committee @srobo/trustees what are your thoughts on moving `info@` to being a group which forwards to both of your addresses, rather than just being `trustees@`?

Have added this to the agenda for the next all-committees meeting.

**Comment by samjmartin04** [comment]
@PeterJCLaw did this ever get discussed at an all-committees meeting?

**Comment by PeterJCLaw** [comment]
I think it might have done, but I can't remember the outcome.

**Comment by Scarzy** [comment]
It did.

Whilst there isn't a particular problem adding others to the list, 99.9% of
what comes in to it is just spam, we probably get fewer than 10 genuine
e-mails into it each year, and those tend to be forwarded to the relevant
team fairly quickly. If others want to be added to all the spam then that's
not a problem, but I'm not sure I see a benefit.
