### ISSUE TITLE
Plan power tool area

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#124]
We do not want competitors to drill each other.

**Comment by WillB97** [comment]
This should be in an outdoor/well ventilated area and must not be done on SUSU furniture.

**Comment by RealOrangeOne** [comment]
The area to the right of the cube might work nicely for this, as we can open the doors to ventilate it. 

If we can't work on SUSU furniture (which makes sense), we should ensure it's documented in https://github.com/srobo/tasks/issues/125

**Comment by Tyler-Ward** [comment]
We can no longer open the fire doors at the end of bar 2 as they are now locked.

@Scarzy this might be good one for you to look at

**Comment by trickeydan** [comment]
> We can no longer open the fire doors at the end of bar 2 as they are now locked.

Clarification, there are emergency exit buttons and magnetics locks. These will open in the event of a fire alarm.

**Comment by PeterJCLaw** [comment]
There's a location for this in the floorplans (by the doors on L2 if memory serves), can we call this complete or is there more to do here?

**Comment by TomWheal** [comment]
Do we have a table for this as we probably can’t use one we hired

**Comment by WillB97** [comment]
We have 2 workmates which can be used for sawing or drilling. Anything that only needs a table I would have thought they could do in their pits.

**Comment by RealOrangeOne** [comment]
We specifically want teams to be using things like drills / saws in the power tools area rather than their pits, so we can keep an eye on them, and only have 1 place to clean up!

Assuming we have enough table space for that on 2 workmates, which I doubt. I suspect we're going to want another table or something for some extra room. Or we just ensure we move teams along as quickly as possible.

**Comment by TomWheal** [comment]
As it's likely to be ruined, you can get a cheap(ish) table on Amazon for ~£35. It would be useful to have a table that it doesn't matter if it's ruined for tech-days as well. 
https://www.amazon.co.uk/6ft-Folding-Table-Rectangular-Handle/dp/B008YFCAFQ/ref=lp_2850898031_1_2/260-2565748-8722021?s=kitchen&ie=UTF8&qid=1553681130&sr=1-2

**Comment by PeterJCLaw** [comment]
That's a neat idea, not sure we have the spare budget though.
If we have workmates (where from?) I suspect they're probably more useful than a table.

**Comment by Adimote** [comment]
SRO has the aforementioned workmates, I've asked if we can use them

**Comment by Tyler-Ward** [comment]
Getting a foldable table sounds like a sensible idea as i can see teams damaging the power tool area tables and wouldn't want to have to pay the hire company to replace (do we know how we have prevented this in previous years? Amazon has one slightly cheaper one which looks the same at https://www.amazon.co.uk/Crystals-Premium-Quality-Folding-Catering/dp/B0797YCJ9F/

**Comment by PeterJCLaw** [comment]
I'm not aware that we've done anything in particular to prevent it in the past.

**Comment by sedders123** [comment]
We should get 2 sacrificial tables + 3 g-clamps

**Comment by sedders123** [comment]
[3 x G Clamps different sizes](https://www.amazon.co.uk/Rolson-14189-G-Clamp-Set-Pieces/dp/B004LGUV62/) - £5.49

**Comment by Tyler-Ward** [comment]
Approved for two tables and one of each clamps

**Comment by sedders123** [comment]
Tracking added to #200
