### ISSUE TITLE
Prepare a livestream for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1247]
To allow teams to watch the competition matches remotely, such as from their pits, we should to livestream the event.

To do this we need a machine to run the livestream, and a plan for how the livestream will be run. This will also need to include where cameras are placed around the arena.

In previous years, we have borrowed or hired equipment to run the livestream, the general requirements are:
 - Video mixer PC (With dedicated GPU, capable of running OBS)
 - 2× HDMI capture card
 - 2× preview monitors
 - 2× cameras (depending on feed plan)
 - Audio mixers

Ideas for the camera feeds:
 - Arena (likely multiple)
   - Top down view showing whole arena
   - Side view showing one side of the arena
   - A PTZ camera to follow the action
 - Hosts (who may be different to commentators)
 - Stage (only needed for prize giving)

Scenes will also need to be created in OBS in advance of the competition. See https://studentrobotics.org/runbook/competition/livestream/scenes/.

Required actions:
 - [ ] Decide who will run the livestream
 - [ ] Create the required scenes in OBS
 - [ ] Generate a livestream link to be shared with teams
 - [ ] Train volunteers to run the livestream
 - [ ] Test using the cameras when setup in the venue
 - [ ] Practice running the livestream

### Original

[comp/livestream/comp-livestream](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/comp-livestream.yaml)
```[tasklist]
### Dependencies
 - [ ] #1246
```

**Comment by PeterJCLaw** [comment]
The livestream happened.
