### ISSUE TITLE
Trim the live stream VOD (Video on Demand) for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1248]
The live stream VOD should be trimmed to remove the start and end of the competition.

### Original

[comp/livestream/crop-vod](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/crop-vod.yaml)
```[tasklist]
### Dependencies
 - [ ] #1247
```

**Comment by PeterJCLaw** [comment]
@antonnikitin97 we should work out the chapters for the livestreams too I think.

**Comment by PeterJCLaw** [comment]
The trimming happened as much as possible. It turns out that longer streams (>6 hours) cannot be trimmed :(
