### ISSUE TITLE
Ensure the key events of the SR2024 competition occur

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1249]
We need to ensure that the key events of the competition occur.

This includes matches, the prize-giving ceremony, and photos.

Required actions:
 - [x] Have the league matches
 - [x] Have the knockout matches
 - [x] Take photos of individual teams with their robots
 - [x] Take a group photo of the Blueshirts
 - [x] Take a group photo of all teams with their robots
 - [x] Have the prize-giving ceremony

### Original

[comp/key-events](https://github.com/srobo/recurring-tasks/blob/master/comp/key-events.yaml)

**Comment by PeterJCLaw** [comment]
Is this about preparing the day schedule? Or something more than that?

**Comment by PeterJCLaw** [comment]
This happened.
