### ISSUE TITLE
Create event rules

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#125]
Not competition rules, rules such as no running, etc.
This will be the responsibility of #137.

**Comment by Adimote** [comment]
Scarzy is doing this, please assign him once he's accepted the invite!

**Comment by RealOrangeOne** [comment]
https://srobo.github.io/runbook/competition/teams/process-docs/sr2017-orientation-and-pit-rules/ may be of use

**Comment by Scarzy** [comment]
FYI, these are done, I just need time to remind myself how to git to get them into the runbook

**Comment by TomWheal** [comment]
@Scarzy Can you dump these somewhere so I can add them to the competitor booklet

**Comment by Scarzy** [comment]
@TomWheal A pull request should now exist to put these in the runbook

**Comment by Tyler-Ward** [comment]
https://github.com/srobo/runbook/pull/22

**Comment by Scarzy** [comment]
As the PR has been merged, I'm closing this
