### ISSUE TITLE
Publish an article following the SR2024 Competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1252]
After the competition we want to have a news article which describes how the event went, which teams won, etc.

The post-competition news article can take some time to write. We should write a skeleton one as soon as possible, and the details can be filled in after the competition.

Once published we should link various people to the article, including:
 - Our social media accounts
 - Various tech/STEM blogs and other media outlets (we should email them)

Required actions:
 - [x] Write a skeleton news article
 - [x] Fill in the details of the news article
 - [x] Publish the news article
 - [ ] Link to the news article from social media
 - [ ] Email the news article to various tech/STEM blogs and other media outlets

### Original

[comp/publish-news-article](https://github.com/srobo/recurring-tasks/blob/master/comp/publish-news-article.yaml)
```[tasklist]
### Dependencies
 - [ ] #1250
 - [ ] #1251
```

**Comment by PeterJCLaw** [comment]
This is now published, though hasn't been publicised.

**Comment by PeterJCLaw** [comment]
Not sure if this got publicised, it's probably a bit late now. Either way this ticket isn't really helpful any more.
