### ISSUE TITLE
Gather feedback from volunteers

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1254]
To be able to make guided improvements to the volunteer experience

We should send this to everyone who was signed up for SR2024.

We could include questions about:
 - workload
 - training
 - atmosphere
 - open questions about any improvements or key positives

SR2020 Feedback form: https://docs.google.com/forms/d/1nIG36tZNykCxgilKXOT6TJiY2je3iHR2YNMtoXeLeJw/edit?usp=sharing

Required actions:
 - [ ] Create a feedback form
 - [ ] Post form in Slack
 - [ ] Email form to volunteers

### Original

[comp/feedback/gather-volunteer-feedback](https://github.com/srobo/recurring-tasks/blob/master/comp/feedback/gather-volunteer-feedback.yaml)

**Comment by PeterJCLaw** [comment]
This happened, reviews & retros happened also.
