### ISSUE TITLE
Appoint safeguarding officers for the virtual competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1258]
Safeguarding officers need to be appointed, by the Safeguarding Lead, as per the safeguarding policy.

Email the Safeguarding Lead to coordinate this.

Required actions:
 - [ ] Safeguarding officers are appointed

### Original

[comp/appoint-virtual-comp-safeguarding-officers](https://github.com/srobo/recurring-tasks/blob/master/comp/appoint-virtual-comp-safeguarding-officers.yaml)

**Comment by antonnikitin97** [comment]
Sent an email to @Scarzy :)

**Comment by PeterJCLaw** [comment]
The event happened, I believe James was appointed.
