### ISSUE TITLE
Plan simulating the SR2024 virtual competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1259]
For the virtual competition, all the matches need to be simulated in advance. Running the simulation at reasonable speed requires a reasonably powerful computer with a discrete GPU.

Once the simulation is complete, the videos need to be sent to the livestream producer so that they can be played during the livestream.

Required actions:
 - [x] Decide who will run the simulation
 - [x] Decide when the simulations will be run
 - [x] Plan for generating a schedule for the simulated matches

### Original

[comp/virtual-comp/plan](https://github.com/srobo/recurring-tasks/blob/master/comp/virtual-comp/plan.yaml)

**Comment by PeterJCLaw** [comment]
Decisions were made [in the kick-off](https://docs.google.com/document/d/1A8_AemUXVI92WVwm_KQie6tR_xqzHgm_pUzguziXYtw/edit).

**Comment by PeterJCLaw** [comment]
This essentially is now fully planned. What's left is to execute the plan.

**Comment by prophile** [comment]
We planned, we ran, we broadcasted.
