### ISSUE TITLE
Invite Press

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#126]
We need to invite press humans.

**Comment by antoinepetty** [comment]
Have contacted a few local news organisations. Not expecting too much based on the lack of publicity on our previous competition cycles. 
Closing this issue but will update in Slack if we get any responses.

**Comment by PeterJCLaw** [comment]
@antoinepetty is there any reason not to post updates here rather than in Slack? (here is considerably more open than Slack and would mean that context around this is all in one place)

**Comment by trickeydan** [comment]
We are going to go all out on press coverage.

**Comment by trickeydan** [comment]
Places we are inviting:

- [ ] BBC
- [ ] IET
- [ ] The Daily Echo
- [ ] TechCrunch
- [ ] The Wessex Scene
- [ ] IEEE
- [ ] ECS Press
- [ ] Central Uni Press
- [ ] Times Higher Education
- [ ] The Guardian
- [ ] The Independent
- [ ] Radio Solent
- [ ] Jack FM / The Breeze
- [ ] BBC Radio 2 / 4
- [ ] Wired
- [ ] The Verge
- [ ] IMechE

**Comment by RealOrangeOne** [comment]
It's worth liaising with @antoinepetty to work out if any of the above list have already been invited.

**Comment by antoinepetty** [comment]
Damn I like that list. I invited The Daily Echo and BBC South Today but that's it from that list.
I wasn't sure how to pitch such a visual event to radio.

Is the rest being managed by Southampton volunteers now?

**Comment by trickeydan** [comment]
> I wasn't sure how to pitch such a visual event to radio.

Phone interviews with volunteers and competitors.

> Is the rest being managed by Southampton volunteers now?

Anton and Jack are working on it currently. They are very excitable currently.

**Comment by PeterJCLaw** [comment]
"The pictures are always better on radio".

**Comment by PeterJCLaw** [comment]
@trickeydan do we know how many/which of the the above list that Jack & Anton were able to reach out to?

@antoinepetty would you be able to pick this up?

**Comment by antoinepetty** [comment]
Getting a bit short notice for this sort of thing now but I can give it a go. 
Shall I just try all of them? I'm not sure who's been contacted by @antonnikitin97 and @jcwilliamson as of now

**Comment by Tyler-Ward** [comment]
I have informed the ECS media person about the event so hopeful they will pass it on to the rest of the uni media team.

**Comment by trickeydan** [comment]
It is probably too late now, so what we have done will have to do.

\- @mildlyincompetent
