### ISSUE TITLE
Setup code submitter for SR2024 virtual competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1260]
In order for teams to submit their code for the virtual competition, we need to setup the code submitter. This will be a web application that allows teams to submit their code and will be hosted on the SR's infrastructure.

Required actions:
 - [x] Setup the code submitter on the SR's infrastructure
 - [x] Populate the code submitter with the teams' passwords
 - [x] Advertise the code submitter to the teams

### Original

[comp/virtual-comp/code-submitter](https://github.com/srobo/recurring-tasks/blob/master/comp/virtual-comp/code-submitter.yaml)

**Comment by PeterJCLaw** [comment]
This happened, was used for the friendlies/run-through.
