### ISSUE TITLE
Prepare a livestream for the SR2024 virtual competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1261]
As the virtual competition is presented as a livestream, we need to prepare how it will be run. This is likely to be similar to the livestream for Kickstart, but with some differences.

To do this we need a machine to run the livestream, and a plan for how the livestream will be run. Additionally, we need to decide who will present the livestream.

In the past, this livestream has had both presenters and producers in a single location, and used the producer's machine to run the livestream. However, this can be done remotely, so we may want to consider this.

In terms of scenes and feeds, the livestream generally consists of:
 - An introduction, to explain the game and the competition
 - An in match view, where the match recording is played
 - A post match view, normally with the presenters' camera feeds
 - A view of the league table
 - A view of the schedule
 - Optionally, some playbacks of interesting moments from the matches

See also: https://studentrobotics.org/runbook/competition/livestream/scenes/.

Required actions:
 - [x] Decide who will run the livestream
 - [x] Create the required scenes in OBS
 - [x] Generate a livestream link to be shared with teams
 - [x] Decide who will present the livestream
 - [x] Practice running the livestream

### Original

[comp/livestream/virtual-comp-livestream](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/virtual-comp-livestream.yaml)

**Comment by prophile** [comment]
I think we can close this
