### ISSUE TITLE
Trim the live stream VOD (Video on Demand) for the SR2024 virtual competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1262]
The live stream VOD should be trimmed to remove the start and end of the virtual competition.

### Original

[comp/livestream/crop-virtual-comp-vod](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/crop-virtual-comp-vod.yaml)
```[tasklist]
### Dependencies
 - [ ] #1261
```

**Comment by PeterJCLaw** [comment]
Chapters added.
