### ISSUE TITLE
Work out the day schedules for the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1263]
We need a list of what is happening at what times on both days of the competition (tinker time, lunch, league etc).

This should include:
 - An intro talk on Saturday
 - Tinker time
 - League matches
 - Knockout matches
 - Prize giving
 - Lunch
 - Finish times for the days

Required actions:
 - [x] Generate day schedule
 - [ ] Circulate to other areas for comment

### Original

[comp/day-schedule](https://github.com/srobo/recurring-tasks/blob/master/comp/day-schedule.yaml)

**Comment by PeterJCLaw** [comment]
Solved, see https://studentrobotics.slack.com/archives/CBP7UL6RG/p1710367845608849?thread_ts=1710366640.966689&cid=CBP7UL6RG
