### ISSUE TITLE
Schedule the matches for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1264]
In order to run matches a schedule for the league matches needs to be generated. The final version of this may need generating close to the day, once we have a firmer number for attending teams.

Then we need to decide on the structure of the knockouts. Generally this has been a single elimination tournament. With the top of the leaderboard starting at later rounds when the number of teams is not a power of 2.

Required actions:
 - [x] Generate an initial match schedule
 - [x] Decide on the knockout shape
 - [x] Generate the final match schedule

### Original

[comp/game/match-schedule](https://github.com/srobo/recurring-tasks/blob/master/comp/game/match-schedule.yaml)
```[tasklist]
### Dependencies
 - [ ] #1263
```

**Comment by prophile** [comment]
Draft schedule in Slack, will materialise this today/tomorrow
