### ISSUE TITLE
[Meta] Have the SR2024 virtual competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1268]
Root ticket for the virtual competition.

### Original

[comp/virtual-comp/main](https://github.com/srobo/recurring-tasks/blob/master/comp/virtual-comp/main.yaml)
```[tasklist]
### Dependencies
 - [ ] #1258
 - [ ] #1259
 - [ ] #1260
 - [ ] #1262
 - [ ] #1267
```

**Comment by PeterJCLaw** [comment]
We had the virtual competition.
