### ISSUE TITLE
Invite Sponsors

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#127]
We need to invite our sponsors.

**Comment by antoinepetty** [comment]
Waiting for info from Trustees regarding sponsor contact details

**Comment by antoinepetty** [comment]
Have contacted Motorola & Joyce inviting them to the competition.

**Comment by Tyler-Ward** [comment]
Are we inviting them to present any prizes/do anything at the end.

**Comment by antoinepetty** [comment]
Ah I hadn't even considered that. At the moment, I have just invited them to attend. When they respond I'll propose that idea in Slack and reply accordingly.

**Comment by PeterJCLaw** [comment]
@antoinepetty did we get any responses to this?

**Comment by antoinepetty** [comment]
> @antoinepetty did we get any responses to this?

Nothing yet
