### ISSUE TITLE
Organise the helpdesk for the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1271]
Helpdesk is the single-point-of-contact for teams to get help with their robots. We need to plan who will run this on the day as well as the various things it needs to be able to help the teams.

If kit breaks at the competition for teams, we should be prepared to replace it quickly. For that we will need spares readily available. This should be coordinated with the Kit team.

If there is a problem at helpdesk, that those on helpdesk cannot solve, they need to know who to escalate to. There will be different experts depending on the domain of the problem.

An example set of domains are:
 - Rules
 - Event
 - Kit
   - Python API
   - Hardware
   - Competition operations

Note that this list of people should also take into account who is likely to be available.

Required actions:
 - [x] Decide who will run helpdesk
 - [x] Create a list of available subject matter experts
 - [x] Have spare kit available at the competition
 - [x] Train volunteers to run helpdesk

### Original

[comp/helpdesk](https://github.com/srobo/recurring-tasks/blob/master/comp/helpdesk.yaml)

**Comment by RealOrangeOne** [comment]
Subject-matter experts list: https://docs.google.com/document/d/1Vl0pUaXtGpSDp148iqFZT7SczPUFu-0THWx7BrLicmU/edit?usp=sharing
