### ISSUE TITLE
Recruit volunteers for the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1276]
We need to publicise the date and location of the competition to all volunteers and solicit their help, both in preparing for the competition and at the competition itself.

We should prepare a signup form which captures information about the volunteer so that we can schedule them at the competition as well as provide them with travel and accommodation.

We should also reach out to the volunteers who have helped in the past, as well as those who have expressed an interest in helping in the future.

Required actions:
 - [x] Create a sign-up form
 - [x] Send an email to all volunteers encouraging them to signup

### Original

[comp/volunteers/recruit](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/recruit.yaml)

**Comment by sedders123** [comment]
We have volunteers 🎉
