### ISSUE TITLE
Arrange first aid presence at the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1278]
We need to provide first aid coverage at the competition for both main days.

Required actions:
 - [x] Get quotes for first aid cover for the competition
 - [x] Book first aid cover for the competition

### Original

[comp/safety/first-aid](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/first-aid.yaml)
```[tasklist]
### Dependencies
 - [ ] #1245
```

**Comment by sedders123** [comment]
First aider has been booked and paid
