### ISSUE TITLE
Organise photos/videos to be taken at the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1279]
We want to have a good set of photos from the competition to use in news articles, social media, etc. We should plan what photos we want to take and who will take them.

This task is about planning the photos to be taken. We should include:
 - A photo of each team with and without their robot (ideally with their TLA visible) 
    this is a good opportunity for them to show off their team image and for us to associate the robot with the team
 - A photo with all the teams and their robots
   this is generally useful for publicity and for looking back on previous years to see which robots competed
 - A photo of all the Blueshirts
   this is useful for promoting volunteering at the competition
 - Photos of the competition in progress
 - Photos of the prizegiving
 - Photos of the winning teams
 - Photos of the robots
 - Photos of the robots in the arena

Required actions:
 - [ ] Decide what photos we want to take
 - [ ] Decide who will take each photo

### Original

[comp/plan-photos](https://github.com/srobo/recurring-tasks/blob/master/comp/plan-photos.yaml)
```[tasklist]
### Dependencies
 - [ ] #1246
```

**Comment by PeterJCLaw** [comment]
Many photos & videos were taken.
