### ISSUE TITLE
Plan post-finals sequence

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#128]

**Comment by RealOrangeOne** [comment]
Related to https://github.com/srobo/tasks/issues/133.

I'm more than happy to give the ceremony

**Comment by RealOrangeOne** [comment]
A suggested plan:

- Speaker says some things (https://github.com/srobo/tasks/issues/133)

- Present first movement award
- Present rookie award
- Present online presence
- Present committee award
- Present team image
- Present 3rd place
- Present 2nd place
- Present 1st place

- Thank teams
- How to return kit

Assuming the speaker has time, it would be nice for them to present the awards, and me to just read out the winning teams.

The prizes are in an arbitrary order. Although I do think the first movement should be the first award, and the main competition ones should be the last.

**Comment by trickeydan** [comment]
> The prizes are in an arbitrary order. Although I do think the first movement should be the first award, and the main competition ones should be the last.

I think committee award should be the last of the non-main prizes. In the past it has been like that I think

**Comment by RealOrangeOne** [comment]
> I think committee award should be the last of the non-main prizes. In the past it has been like that I think

I agree, updated comment.

**Comment by trickeydan** [comment]
Can we write this into a PR for the runbook? It will be useful to keep this for the future and a PR allows better review.

**Comment by RealOrangeOne** [comment]
We _can_, but i've intentionally not. https://github.com/srobo/runbook/pull/8 somewhat blocks putting things in the runbook for now. I've got a note for myself to move anything i've worked on into the runbook to the relevant page for after the competition. 

For now, just put feedback in here, quote replying where possible. We shouldn't be blocking review on it.

**Comment by trickeydan** [comment]
> We _can_, but i've intentionally not. [srobo/runbook#8](https://github.com/srobo/runbook/pull/8) somewhat blocks putting things in the runbook for now. I've got a note for myself to move anything i've worked on into the runbook to the relevant page for after the competition.

I suggest making a task to track this post-competition.

**Comment by Tyler-Ward** [comment]
This plan really needs to be almost a stageplay style plan in order that we can plan around it and avoid the mess ups we have made the last few events.

Things we need to know
* Relative timings. we should probably start this from the end of the final.
* How people are moving around and who is where (both blue-shirts,competitors and external speakers).
* What kit e.g. prizes and mics need to be where when.
* What lighting and sound triggers are required.
* rough backup plans if things aren't in the right place.

**Comment by PeterJCLaw** [comment]
> > We _can_, but i've intentionally not. [srobo/runbook#8](https://github.com/srobo/runbook/pull/8) somewhat blocks putting things in the runbook for now. I've got a note for myself to move anything i've worked on into the runbook to the relevant page for after the competition.
> 
> I suggest making a task to track this post-competition.

An alternative is to base a branch on https://github.com/srobo/runbook/pull/8 and open a PR which targets that PR. This ends up a bit odd in terms of what gets merged when, but you get the right history and nice diffs on GitHub.

**Comment by PeterJCLaw** [comment]
> This plan really needs to be almost a stageplay style plan in order that we can plan around it and avoid the mess ups we have made the last few events.
> 
> Things we need to know
> 
>     * Relative timings. we should probably start this from the end of the final.

Bear in mind that we might have a tiebreaker to run. We cannot start the ceremony until the final has been scored.

>     * What kit e.g. prizes and mics need to be where when.

All the prizes should be on the table from the start.
The MC needs a mic, as does the speaker. The speaker _doesn't_ need their mic once they're done talking, even if they're handing out prizes. Maybe therefore only have a single mic?

>     * What lighting and sound triggers are required.

IMO: None whatsoever. We should run with boring static lights and no additional sound effects. Statically setting these long before we start the ceremony is ideal.

Other things to consider:
- where will the photographers be? (both ours and the team-leaders/parents of each winning team)
- will we prescribe the route in & out of the arena?
- how will the MC know which teams won what? (historically this has been solved by me writing down what SRComp says)

**Comment by Tyler-Ward** [comment]
see hack MD here https://hackmd.io/07dzrtQaRSe22IqXucqHwg

**Comment by Tyler-Ward** [comment]
# Post finals plans

Pre finals tasks
* Awards decided and writted down for non placed awards
* Prizes + shiny tablecloth placed in boxes by scoreing ready to move to the stage

### Finals start

### Finals end

Marshals perform scoring and report scores.
Marshals Clear arena of robots.
Score entry enter scores but do not push live
In event of tiebreak score entry should signal this and arena will be cleaned and reset goto "Finals start".

*Out of match mode lighting faded to general wash stage wash repointed*

Staging area dismantled and competetors and spactators alowed in to it and arena
Stage is of spectators cleared
Scoring staff write and prepare awards cards for ranked roles
Trophies and awards cards moved to stage
Speaker and presenter are miced up and mics tested.

*room lights faded down*
*finals playlist faded down*

### Start of Prizegiving ceremony

*stage wash faded up*
*Primary speaker enters stage left*

Initial speach and intro to the prizegiving

*Guest speaker enters stage left*

Guest speaker gives a speech ~10 minuites

#### Awards (in order!)

- Online Presence
- First movement
- Rookie award
- Team Image
- Committee award
- 3rd place
- 2nd place
- 1st place

##### Awards loop (for prize in prizes):
1. awards card given to guest speaker
2. Award description and notes read out by presenter
3. speaker opens awards card
4. Speaker reads out the winning team
5. *Team gathers stage left*
6. Filler talk
7. *Team enters stage left*
8. Team given award (and prizes) by guest and congratulated
9. *Team exits stage right*
10. Goto loop
    
*External speaker exits stage left*

Thanking people:
* Trustees
* Volunteers
* Sponsors
* Delta-V
* FutureWorlds
* Special thanks:
    * Joyce

Finals closing remarks from prize giving
Next steps anouncments.
    Kit return
    

*Speaker exits stage left*

### End of prize-giving ceremony

*stage lights fade to black*
*nonsync fades up exit playlist*
*room wash fades up*

*voluntters to clear cube*
*cube packdown begins*

@Adimote can you add the following roles to the volunteer sheets
Stage left guard to buffer teams and manage stage access
Stage right guard to ensure teams leave stage and that they have room to do so.

**Comment by Adimote** [comment]
I've now added the roles to the schedule

**Comment by Tyler-Ward** [comment]
The this is done

**Comment by PeterJCLaw** [comment]
Did we want the pre-finals tasks to be a role?
I think we thought the card preparation might be a good fit for @antoinepetty if he's free then, as he likely needs the same information for social media/the news blog post?

**Comment by antoinepetty** [comment]
I'm not sure exactly what you mean, but I should be free to do that just after the finals.

**Comment by PeterJCLaw** [comment]
Sorry, I wasn't at all clear!

We'd like to have envelopes with the names of the winner of each award on them for the presenter to open. While a little odd for the place prizes, it brings a air of award ceremony to the others. Practically this means that the speaker has some notes to work from, ensuring that the award goes to the right people without needing to rely on memory. The cards could even have some prompts for what to say about the award and the team.

The plan is that someone write up the cards and put them in the envelopes on the Sunday afternoon. Most can be done well ahead of time, though obviously the place prizes will need writing up after the finals.

Where we have time, having the details on the card printed is definitely an option.

We're deliberately getting spare token-marker card (#221) so we can use the spare for these cards too.
