### ISSUE TITLE
Organise equipment transport

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1283]
A large quantity of equipment needs to be transported to and from the competition venue. For the setup includes things like the arena, and spare kit, and for the teardown this will also include all the teams kits.

Generally, it is most cost effective to hire one van to transport transport items from storage to the competition venue on the Thursday and then hire a second van to return items to storage on the Monday.

For both vans, we will need someone with a full UK driving license of suitable age, who is available, to drive the van.

Required actions:
 - [x] Decide on the size of the van required
 - [x] Decide when the equipment will be transported to the venue
 - [x] Organise a driver for the van for the Thursday/Wednesday
 - [x] Organise a driver for the van for the Monday
 - [x] Book the vans

### Original

[comp/venue/transport](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport.yaml)
```[tasklist]
### Dependencies
 - [ ] #1282
```

**Comment by WillB97** [comment]
Scarzy has said he may be available to drive a van Wednesday evening and Monday morning.

**Comment by Scarzy** [comment]
I can pick this https://www.kendallcars.com/vehicles/transit-van/ up from near my work, and have it from 8am Wednesday morning through to 8am Tuesday morning inclusive for £224.52 GBP. Fuel would be on top of this. This would then be available to load up from the container on Wednesday and throughout the event.
I have used this hirer several times before.

Do let me know if I should go ahead with booking this

**Comment by Adimote** [comment]
I approve this budget item @Scarzy

**Comment by Scarzy** [comment]
Van has been booked, collection Wednesday.

We can load it from the container on Wednesday, but I'll need someone to bring a key and help load

**Comment by sedders123** [comment]
Wednesday plan:
- (Alistair collect key from Peter on 9th)
- Alistair to drive to Scarzy's
- Scarzy and Alistair to van to container
- Load van and return to Scazry's

**Comment by PeterJCLaw** [comment]
Things were moved.
