### ISSUE TITLE
Prepare game equipment/props for the arena

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1284]
We need to prepare the things that will go in the arena, including the wall markers, the robot flags, any tokens and other props. See this year's [rulebook](https://studentrobotics.org/docs/resources/2024/rulebook.pdf) for details.

During matches robots are given coloured flags so that the audience know which robot is from which scoring zone. At least two complete sets of each badge are needed: one for the robots currently playing and another for the robots currently staging.

The markers should be printed as part of the main printing run.

We may also need tools for the arena construction. Generally we'll need some drills, screwdrivers and a tape measure. We may also need a knife to cut the carpet.

Required actions:
 - [x] Prepare the wall markers
 - [ ] Prepare the robot flags
 - [ ] Prepare the tokens
 - [ ] Prepare the spaceships
 - [ ] Prepare the nest
 - [ ] Organise tools needed for assembly

### Original

[comp/game/props](https://github.com/srobo/recurring-tasks/blob/master/comp/game/props.yaml)
```[tasklist]
### Dependencies
 - [ ] #1282
```

**Comment by PeterJCLaw** [comment]
Parts for the spaceships are in 1MM2J, which was also the one we used for testing against and thus has holes in.

**Comment by PeterJCLaw** [comment]
@gitLRD is taking the PVC pipe for the spaceship flags and mounts.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne please could you post on here the image of the whiteboard notes we took on Saturday regarding building the Spaceships?

**Comment by PeterJCLaw** [comment]
Props were prepared.
