### ISSUE TITLE
Print event booklets and flyers

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#129]
Depends #87 and #101.

**Comment by Tyler-Ward** [comment]
These will take time to make

**Comment by Tyler-Ward** [comment]
A potential supplier for this is https://www.digitalprinting.co.uk/products/saddle-stitched

**Comment by TomWheal** [comment]
https://www.instantprint.co.uk/
Flyers and Booklets £138

**Comment by Tyler-Ward** [comment]
Per in person discussion Budget is approved for this.

**Comment by TomWheal** [comment]
[Booklet-Final.pdf](https://github.com/srobo/tasks/files/3018136/Booklet-Final.pdf)
[flyer-Final.pdf](https://github.com/srobo/tasks/files/3018137/flyer-Final.pdf)
Have been sent off to print with: https://www.instantprint.co.uk/ 

Printing starts tomorrow so any changes can be made today

**Comment by Tyler-Ward** [comment]
I have added these to #200 so i think this can be closed, I assume they are being delivered to you?

**Comment by TomWheal** [comment]
I’ll leave open until I get print confirmation

**Comment by TomWheal** [comment]
Managed to Make the Changes and printing has started, ETA is Tueday next week
