### ISSUE TITLE
Organise prizes for the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1292]
The prizes for the competition are a combination of trophies and edible prizes, these will need purchasing in advance.

Generally we have three sizes of trophies, one for each of 1st, 2nd and 3rd place. The remaining trophies are a mixture of the medium and small sizes.

Note: Gold sponsors can sponsor a prize, their logo then appears on the trophy

Required actions:
 - [x] Decide on trophy sizes and design
 - [x] #1348
 - [ ] Order edible prizes

### Original

[comp/prizes/acquire-prizes](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/acquire-prizes.yaml)
```[tasklist]
### Dependencies
 - [ ] #1291
```

**Comment by sedders123** [comment]
Decision made not to engrave sponsors on trophies, instead using the approach for SR2023 of printing their logos on the award card we present alongside the trophy

**Comment by RealOrangeOne** [comment]
I'll purchase the edible prizes on the setup days

**Comment by RealOrangeOne** [comment]
Edible prizes have now been purchased
