### ISSUE TITLE
Organise swag for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1294]
We want to have a good set of swag to give out at the competition. We should plan what swag we want to give out and who will be responsible for getting it.

This task is about planning the swag to be given out. We should include:
 - For each participant:
   - A set of stickers
   - A branded pencil
   - A bag to contain the above and the competition booklet

Required actions:
 - [x] Select what types of swag we want for competitors
 - [x] Create swag designs
 - [x] Get quotes for swag
 - [x] Order selected swags

### Original

[comp/swag](https://github.com/srobo/recurring-tasks/blob/master/comp/swag.yaml)
```[tasklist]
### Dependencies
 - [ ] #1291
```

**Comment by sedders123** [comment]
We've also invited Gold Sponsors to contribute marketing materials to the goody bags
