### ISSUE TITLE
Invite key people to the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1295]
We should invite some press to the competition. This should be done as early as possible, and we should follow up with them closer to the time.

Additionally we should send out invitations to various people from both our current and any prospective sponsoring organisations to come along to the competition.

Required actions:
 - [x] Invite press to the competition
 - [x] Invite additional sponsors to the competition

### Original

[comp/invite-key-people](https://github.com/srobo/recurring-tasks/blob/master/comp/invite-key-people.yaml)
```[tasklist]
### Dependencies
 - [ ] #1291
```

**Comment by gitLRD** [comment]
I've got a few possible emails for this:

```Hi,

I'm writing to you from Student Robotics, where our teams of 16-19 year olds are building their own fully autonomous robots, which will compete in complex league matches to choose a final winner. 

This is a display of creativity and engineering expertise from some very bright young people, which gives the competitors key experience of working in teams and to a deadline. We'd like to get as much publicity as we can for the event, so would like to invite you to attend.

On Saturday 13th April, teams will be making the finishing touches to their robots before competing in league matches which define their place on our leaderboard. The knockouts will be held the next day, with the lucky few making their way to our finals.

You can find out more about the competition from our website, or by looking at our social media to see how the teams are getting on. 

If you have any questions at all, please don't hesitate to ask. We hope to see you there!

Kind regards,

James
```

**Comment by antoinepetty** [comment]
Thanks I really like the first and third options. Maybe we should always repeat the key date and location in the style of the third at the end
