### ISSUE TITLE
Schedule volunteer roles

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1296]
We need to work out how many people we need doing each role and then come up with a timetable which shows who is doing which role when.

A noted job that should be remembered is delivering refreshments to volunteers that have long shifts and cannot leave their posts for long periods of time.

Required actions:
 - [x] Capture volunteer job preferences
 - [x] Schedule roles

### Original

[comp/volunteers/schedule](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/schedule.yaml)
```[tasklist]
### Dependencies
 - [ ] #1276
 - [ ] https://github.com/srobo/tasks/issues/1355
```

**Comment by PeterJCLaw** [comment]
This happened.
