### ISSUE TITLE
Inform volunteers for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1297]
We should email all the volunteers with information about where to go on the day, parking, who to contact, and any other info we need to tell them.

We should aim to send this out at least a few weeks before the competition.

Some info to potentially include:
  - [ ] Information on third party activities which might complicate travel
        or venue access (e.g: other events, rail works, etc.)
  - [ ] Reminder about the safeguarding policy
  - [ ] Parking locations
  - [ ] Information on arrival times
  - [ ] What to do when you arrive
  - [ ] Roles information
  - [ ] Information on provided lunches (if any)
  - [ ] Information on the volunteer meal
  - [ ] Accommodation reimbursement
  - [ ] When the volunteer photo is

### Original

[comp/volunteers/inform-volunteers](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/inform-volunteers.yaml)
```[tasklist]
### Dependencies
 - [ ] #1245
 - [ ] #1296
```

**Comment by PeterJCLaw** [comment]
This happened.
