### ISSUE TITLE
Brief volunteers at the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1298]
We'll need to brief volunteers at the event.

The brefing should cover at a minimum:
  - Key Roles & Point of Contacts
  - Health and Safety
    - COVID-19 Requirements
  - Safeguarding
  - Venue layout
  - Schedule of Event
  - Communication
     - Mechanisms we're using
     - Who to contact in various scenarios

If we're using radios, then volunteers at stations with radios need to be briefed on basic radio protocol, so that they are confident in using it.

The radio briefing should include:
 - How to start a call (e.g. "Helpdesk, for reception.")
 - The difference between "Over" and "Out"

### Original

[comp/volunteers/brief-volunteers](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/brief-volunteers.yaml)
```[tasklist]
### Dependencies
 - [ ] #1245
 - [ ] #1296
```

**Comment by PeterJCLaw** [comment]
This happened.
