### ISSUE TITLE
Organise match ops for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1299]
In order to make sure match ops runs smoothly the processes for marshals and shepherds needs to be thought out in advance.

For marshalling, this will include a checklist of what marshals need to do from the end of one match to the start of the next. This will include:
 - Scoring
 - Resetting tokens
 - Placing in the next robots

This should be as comprehensive as possible in order to simplify the training that these volunteers need. And should probbaly go in the arena repo as it will change considerably between years and will be specific to the details of the arena.

See https://github.com/srobo/arena/blob/master/comp19/reset-checklist.md for an example.

Required actions:
 - [ ] Generate the arena reset checklist
 - [ ] Plan how shepherding will work

### Original

[comp/game/match-ops](https://github.com/srobo/recurring-tasks/blob/master/comp/game/match-ops.yaml)

**Comment by PeterJCLaw** [comment]
Matches & ops happened.
