### ISSUE TITLE
Obtain edible prizes

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#130]
For the online presence and first robot movement awards.

**Comment by RealOrangeOne** [comment]
Depends on https://github.com/srobo/tasks/issues/194

**Comment by PeterJCLaw** [comment]
We promise these prizes in the rules, which makes them a must-have.

**Comment by RealOrangeOne** [comment]
The plan is to purchase these the week of the competition when we know the numbers.

https://github.com/srobo/tasks/issues/194#issuecomment-468918286

**Comment by RealOrangeOne** [comment]
Budget has been approved for 2 teams worth of prizes, at a total of £40.

We shall purchase 2 prizes for this, and extend on the setup days if for whatever reason we find a need to.

**Comment by RealOrangeOne** [comment]
These have now been purchased, exactly at budget. Unfortunately, as it's easter, there were no tubs / tins of things in Tesco, only easter eggs, which don't share well. I instead purchased a large assortment of items, which is more than enough treats for any sized team.
