### ISSUE TITLE
Train marshals for the SR2024 game

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1301]
The marshals should have a chance to run through the process of running a competition match sequence.

The marshals need to know:
 - what the rules are
 - who the experts on them are
 - who the judge is
 - how to use the score entry forms
 - the circumstances under which they should turn a robot off

Required actions:
 - [ ] Plan training
 - [ ] Organise a time to run training
 - [ ] Run training

### Original

[comp/volunteers/marshals-training](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/marshals-training.yaml)
```[tasklist]
### Dependencies
 - [ ] #1296
 - [ ] #1299
 - [ ] #1300
```

**Comment by PeterJCLaw** [comment]
Matches & marshalling happened.
