### ISSUE TITLE
Design the physical scoring form for the SR2024 game

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1303]
The forms for marshals to fill in after each match needs to be designed.

To make score entries job easier, this should have a similar format to the score entry UI.

There is guidance for how to do this for SRComp at https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#create-a-score-sheet

Required actions:
 - [x] Create a scoring sheet
 - [x] Compare the sheet to the scoring UI
 - [x] Add the scoring sheets to the print order

### Original

[comp/ops/scoring-form](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/scoring-form.yaml)

**Comment by PeterJCLaw** [comment]
Fixed by https://github.com/srobo/arena/pull/5
