### ISSUE TITLE
Order volunteer shirts for the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1307]
Every volunteer at gets a blue t-shirt at the competition so they can be easily identified. They contain the year-specific sponsors so we need to order enough for all the volunteers at the competition.

We will want to design these with the year-specific sponsors and possibly some game-specific artwork.

Required actions:
 - [ ] Design the t-shirts
 - [ ] Order t-shirts

### Original

[comp/volunteers/blue-shirts](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/blue-shirts.yaml)
```[tasklist]
### Dependencies
 - [ ] #1276
 - [ ] #1294
```

**Comment by sedders123** [comment]
We used [Clothes2Order](https://www.clothes2order.com/), these have arrived
