### ISSUE TITLE
Plan volunteer meal for Saturday evening

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1308]
We typically go out on the Saturday evening as volunteers to relax and share a meal together. This is normally organised centrally, though volunteers pay for their meal themselves.

Required actions:
 - [x] Collect attendance numbers for the meal, along with dietary restrictions
 - [x] Decide on the location
 - [x] Book a table

### Original

[comp/volunteers/saturday-meal](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/saturday-meal.yaml)
```[tasklist]
### Dependencies
 - [ ] #1276
```

**Comment by sedders123** [comment]
Preorder link was sent and preorders are now closed.
