### ISSUE TITLE
Plan lunch & refreshments for volunteers

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1309]
Since volunteers often don't have time to leave the venue for lunch we should organise some food to be available for lunch during the competition.

In the past we have had food vendors available outside the venue. In other years we have had pizza/sandwiches bulk ordered for the volunteers.

We should have some refreshments for the volunteers at the competition. Generally this should include at least tea, coffee & water as well as some biscuits & fruit. At a minimum this will include water and cups being available at all times throughout the competition including the setup day.

Required actions:
 - [ ] Organise lunches
 - [ ] Organise refreshments

### Original

[comp/volunteers/refreshments](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/refreshments.yaml)
```[tasklist]
### Dependencies
 - [ ] #1276
```

**Comment by PeterJCLaw** [comment]
Foods happened.
