### ISSUE TITLE
Appoint safeguarding officers for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1310]
Safeguarding officers need to be appointed, by the Safeguarding Lead, as per the safeguarding policy.

Email the Safeguarding Lead to coordinate this.

Required actions:
 - [x] Safeguarding officers are appointed

### Original

[comp/appoint-comp-safeguarding-officers](https://github.com/srobo/recurring-tasks/blob/master/comp/appoint-comp-safeguarding-officers.yaml)
```[tasklist]
### Dependencies
 - [ ] #1276
```

**Comment by sedders123** [comment]
Scarzy (Lead) and James (officer)
