### ISSUE TITLE
Safety check the SR2024 robots

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1311]
We need to inspect all the robots to ensure they are safe.

The inspectors will want a list of the teams' first matches so they can visit them in order.

Required actions:
 - [x] Prepare the inspection checklist
 - [x] Inspect the robots
 - [x] Record the results of the inspection
 - [x] Re-inspect robots that failed

### Original

[comp/safety/check-robots](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/check-robots.yaml)
```[tasklist]
### Dependencies
 - [ ] #1244
```

**Comment by andybusse** [comment]
This happened. Points of feedback for next year will go into the retro.
