### ISSUE TITLE
Determine and publish rules for the pits

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1312]
We'll want a collection of rules for the competitors on the day. In the past this has included rules about where power tools and paint (etc.) can be used so we don't break the venue as well as reminders about staging and not going in the arena during matches. Also a map of the venue.

Ideally these should be displayed somewhere the competitors can read them, without being placed somewhere they'll end up hiding when they arrive and put their kit down.

They also need to be short enough that the competitors actually read through them.

Required actions:
 - [x] Generate a set of rules for the pits

### Original

[comp/pits/rules](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/rules.yaml)
```[tasklist]
### Dependencies
 - [ ] #1244
```

**Comment by PeterJCLaw** [comment]
Last year's ticket for this: https://github.com/srobo/tasks/issues/1098
