### ISSUE TITLE
Announce the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1313]
The competition needs fanfare so that people know when & where it will happen. Once we have confirmed a venue and date we need to inform teams and volunteers. We may also want to inform the press of our competition at this stage,

Required actions
 - [x] Add an event to the website
 - [x] Send an email to the team supervisors
 - [x] Send an email to volunteers
 - [x] Send an announcement on Discord
 - [ ] Optionally, announce on our social media, linking to the event page
 - [ ] ~~Optionally, publish a news article~~
 - [ ] Optionally, send an email to tech/STEM blogs and other external media outlets

### Original

[comp/announce](https://github.com/srobo/recurring-tasks/blob/master/comp/announce.yaml)
```[tasklist]
### Dependencies
 - [ ] #1245
```

**Comment by PeterJCLaw** [comment]
Why is this under Teams? This feels like a Media/Press task given that they'll have access to e.g: the Social Media accounts.
