### ISSUE TITLE
Organise how arena testing slots will be booked

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1315]
There is limited availablity for teams to test their robots in the arenas. We need to plan how we are going to ensure that this time is fairly distributed between teams.

Tinker time slots in the main arena need to be long enough for teams to properly run through their strategies in the actual arena. Conversely, test arena slots need to be regular enough that teams aren't waiting significant times to be able to test.

Required actions:
 - [x] Decide on the lengths of tinker time and test arena slots
 - [x] Decide how tinker time slots are booked
 - [x] Decide how test arena slots are booked
 - [x] Decide where teams book their slots

### Original

[comp/game/tinker-time](https://github.com/srobo/recurring-tasks/blob/master/comp/game/tinker-time.yaml)
```[tasklist]
### Dependencies
 - [ ] #1263
```

**Comment by RealOrangeOne** [comment]
Tinker time table: https://docs.google.com/document/d/1nj2opHm2OHlO7qcJYpvEb-yk_zWMimzjnbEM7xF1y6U/edit?usp=sharing

Pending day schedule.

**Comment by RealOrangeOne** [comment]
Tinker time table for SR2024: https://docs.google.com/document/d/1nj2opHm2OHlO7qcJYpvEb-yk_zWMimzjnbEM7xF1y6U/edit?usp=sharing

Conveniently, there are enough slots for everyone to have 1 slot in the morning and 1 in the afternoon. We can ask around the pits as teams arrived, based on their rookie status, to try and seed the slots well in advance.

**Comment by PeterJCLaw** [comment]
> Conveniently, there are enough slots for everyone to have 1 slot in the morning and 1 in the afternoon. We can ask around the pits as teams arrived, based on their rookie status, to try and seed the slots well in advance.

It's almost like it was planned that way...

**Comment by prophile** [comment]
Are we OK with having a printed table at the test arena which people can fill in? Blu-tac on the wall perhaps?
