### ISSUE TITLE
Setup machine to run score entry

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1316]
In order to enter the data from the scoring sheets into the competition software, we need a machine that can be left in score-entry for the duration of the competition.

This needs to be capable of running the score-entry software locally, so probably running a linux, and will need access to the competition network.

This machine needs setting up with the score-entry software and, once in the venue, we should confirm that it can access the relevant pages of the compbox.

### Original

[comp/ops/scoring-hardware](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/scoring-hardware.yaml)
```[tasklist]
### Dependencies
 - [ ] #1266
```

**Comment by RealOrangeOne** [comment]
@sedders123 _Jaaaaaaaames_? :grin:

**Comment by sedders123** [comment]
I'm the first to admit hardware is not my speciality, but I do believe it's conventional for the hinge of a laptop to remain inside the chassis.

![PXL_20240212_174308031.jpg](https://github.com/srobo/tasks/assets/1496834/fb74cc6b-a74a-47ff-ae23-8c2088b885f9)

Laptop does still work, so happy for use if we're careful with it, alternatively I can try and figure out how the hinge should fit back in.

**Comment by PeterJCLaw** [comment]
Alternatively, if we have screens and Pis to spare, would it make sense to move in the direction of using Pis as workstations?

**Comment by PeterJCLaw** [comment]
And/or, do we think it's worth SR renting/buying some cheap machines?

**Comment by RealOrangeOne** [comment]
Trying this year to see if we can do it with a Pi and monitor would be nice (although not sure SR own any input devices), and we can use James's laptop as a fallback? Given we have compute hardware, we might as well use it. I don't think buying / renting devices is worth it for us.

**Comment by PeterJCLaw** [comment]
This was set up. We probably need to expand this ticket in future to cover things like ensuring we have a mouse for the computer.
