### ISSUE TITLE
Design and order a banner for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1318]
For the SR2024 competition, we need to have a banner to display at the event. This should contain the logos of all the sponsors for the event.

Normally, the banner is 6x1m and is displayed at the entrance and prize-giving ceremony. It is also used in the group photo.

Required actions:
 - [x] Create a banner design
 - [ ] Order the banner

### Original

[comp/banner](https://github.com/srobo/recurring-tasks/blob/master/comp/banner.yaml)
```[tasklist]
### Dependencies
 - [ ] #1291
```

**Comment by RealOrangeOne** [comment]
Design: https://github.com/srobo/promotional-material/pull/22

**Comment by sedders123** [comment]
We have ordered the banner from BannerWorld.co.uk. An Event Banner, with Hem & Eyelets, 6m x 1m
