### ISSUE TITLE
Setup the in-venue compbox for the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1319]
The competition software is used to drive the live displays of scores, etc. We have two separate compboxes, one in the venue and on in the cloud. The displays connected to the comp network (those around the arena) will use the local compbox and those outside this network will use the remote compbox.

We have a Raspberry Pi 3 (part code `srL1CX`) which is going to be used as the in-venue compbox. We will need to prepare the micro SD card for the Pi on the setup days in the venue.

The steps here are:
 1. Flash the SD card with the latest Raspbian stable
 1. Clone https://github.com/PeterJCLaw/srcomp-puppet onto the Pi
 1. Checkout the [`raspbian-2024`](https://github.com/PeterJCLaw/srcomp-puppet/tree/raspbian-2024) branch
 1. Run `srcomp-puppet/scripts/install` on the Pi
 1. Use the `scripts/check-pages.py` to validate from outside the Pi that the expected pages can be reached

Required actions:
 - [x] Deploy the in-venue compbox

### Original

[comp/ops/compbox](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/compbox.yaml)
```[tasklist]
### Dependencies
 - [ ] #1265
 - [ ] #1266
```

**Comment by PeterJCLaw** [comment]
This is going to be our usual Pi 3. It'll need flashing the SD card on the day and then puppetting (as in the description).

**Comment by PeterJCLaw** [comment]
This happened.
