### ISSUE TITLE
Determine the winner of the first movement award.

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#132]

**Comment by RealOrangeOne** [comment]
This can be done by looking through the forums for the earliest post. 

> 4.5.3  This must be demonstrated by a video on the web (e.g.  on YouTube,  flickr,  etc.)  andlinking to this video from a post on the Student Robotics forum

**Comment by PeterJCLaw** [comment]
@antoinepetty would you be able to do this? I'm hoping that it's fairly easy to find the teams which have posted any movement.
There's a list of teams in a spreadsheet somewhere, or alternatively the compstate has a list of teams along with whether they're a rookie at https://github.com/srobo/sr2019-comp/blob/master/teams.yaml.

**Comment by antoinepetty** [comment]
I have not yet seen social media activity from any rookie team (Based on teams I have found via the forum, googling TLAs, and those using our hashtags or @).
So I guess it's still all to play for?

**Comment by RealOrangeOne** [comment]
The rules specify it has to come through the forum, so we need to look there primarily. 

I honestly don't know what happens if no rookie team posts... I guess we'll work that one out when it comes to it.

**Comment by PeterJCLaw** [comment]
If no rookie team posts on the forums I suggest we allow looking at other postings.

@antoinepetty perhaps we could craft a social media post which reminded teams to post their robot movements, without making it too obvious that no-one has yet won this?

**Comment by RealOrangeOne** [comment]
At time of writing, no rookie teams have posted on the forum in accordance with the rules.

**Comment by antoinepetty** [comment]
I think I'll need a hand with the wording on this one. Here's what I have so far: https://docs.google.com/document/d/1_We1AUOf6jGF5Nn6jqF9LhHSviEFyFo3w0YMCTCxqLc/edit

**Comment by RealOrangeOne** [comment]
I think that wording is fine. It looks like it's lifted straight from the rules, which is definitely a good thing!

**Comment by antoinepetty** [comment]
Post scheduled for tomorrow afternoon.

**Comment by prophile** [comment]
No winner.
