### ISSUE TITLE
Arrange a speaker for the prize-giving

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#133]
Maybe Paul Lewin?

**Comment by RealOrangeOne** [comment]
I'd quite like to do this again from our side.

(Although I realise chances are this issue is about organising a _guest_ presenter to award the prizes)

**Comment by RealOrangeOne** [comment]
I suspect we can borrow some names from #126 and #212

**Comment by jcwilliamson** [comment]
I wouldn't bank on Paul just yet, he's yet to accept the invitation.

**Comment by Adimote** [comment]
Based on Denis' speech from SB2018, he shouldn't be the finals speaker  :P. When was the email to Paul sent? Can we prod Paul?

**Comment by jcwilliamson** [comment]
I emailed Paul either yesterday or Tuesday, don't remember. Dorota also said she would ask on our behalf in her reply.

**Comment by PeterJCLaw** [comment]
We haven't always had someone in the past and the reality here is that we _can_ have a prize-giving without an external speaker. Downgrading to should-have (albeit an important one) accordingly.

**Comment by RealOrangeOne** [comment]
If we can't find anyone, and we still want someone to act as the guest, @prophile will step in as head judge.

**Comment by RealOrangeOne** [comment]
Current plan is to grab someone who happens to be around the venue

**Comment by sedders123** [comment]
Joyce did a great job
