### ISSUE TITLE
Update and publish risk assessments for the Kickstart

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1331]
The risk assessment for the Kickstart needs updating for SR2024 and publishing to schools.

We also need to make sure that there is a process for recording any incidents that occur during the Kickstart.

Required actions:
 - [ ] Update the risk assessment for the Kickstart
 - [ ] Publish the risk assessment to schools

### Original

[kickstart/risk-assessments](https://github.com/srobo/recurring-tasks/blob/master/kickstart/risk-assessments.yaml)

**Comment by PeterJCLaw** [comment]
Closing as this was part of the tasks import which happened after Kickstart.
