### ISSUE TITLE
[Meta] SR2024 Kickstart Event

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1337]
This is a barrier ticket for the SR2024 Kickstart event.

Tasks for the Kickstart event should be added as dependencies of this ticket.

### Original

[kickstart/event](https://github.com/srobo/recurring-tasks/blob/master/kickstart/event.yaml)
```[tasklist]
### Dependencies
 - [ ] #1324
 - [ ] #1325
 - [ ] #1327
 - [ ] #1328
 - [ ] #1329
 - [ ] #1330
 - [ ] #1331
 - [ ] #1332
 - [ ] #1333
 - [ ] #1334
 - [ ] #1335
 - [ ] #1336
```

**Comment by PeterJCLaw** [comment]
Closing as this was part of the tasks import which happened after Kickstart.
