### ISSUE TITLE
Trim the live stream VOD (Video on Demand)

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1339]
The live stream VOD should be trimmed to remove the start and end of Kickstart.

Required actions:
 - [x] The live stream VOD is trimmed

### Original

[kickstart/crop-vod](https://github.com/srobo/recurring-tasks/blob/master/kickstart/crop-vod.yaml)
```[tasklist]
### Dependencies
 - [ ] #1336
 - [ ] #1337
```

**Comment by PeterJCLaw** [comment]
This has been done.

**Comment by PeterJCLaw** [comment]
We haven't added chapters, but it's unclear how useful those are for the kickstart presentation.
