### ISSUE TITLE
Order trophies

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#134]
Depends on #88.

**Comment by Tyler-Ward** [comment]
@Adimote are you planning on taking this on?

**Comment by Adimote** [comment]
![trophy](https://user-images.githubusercontent.com/2551763/54567594-aa442d80-49d4-11e9-84b4-caae870e50e5.png)
..is an inkscape mock-up of my planned design, any feedback?

**Comment by Tyler-Ward** [comment]
i think the student robotics name looks a bit small the only fix i can think for this is to split onto two lines but i'm not sure if we want to do this.

**Comment by Adimote** [comment]
![trophy_vert](https://user-images.githubusercontent.com/2551763/54567811-6140a900-49d5-11e9-8c7c-cbc8f4391d3d.png)
Here's one with vertical text, I prefer the other one personally.

**Comment by PeterJCLaw** [comment]
Should this discussion be happening on #88 (which is for the design aspect)?

**Comment by Adimote** [comment]
Yes

**Comment by Adimote** [comment]
I've now ordered the trophies from https://www.trophymaster.co.uk/peak6-jade-glass-8mm-03-thick-203mm-8-525615-p.asp

Some notes for future orderers:

- Leave items in the checkout basket over night, they email you with a 10% discount in the morning (Sadly I saw the email after I had made the order this time)

- Their website has a slight bug where they show the billing address as the delivery address on the confirmation page.

**Comment by Adimote** [comment]
Total price was £147.94

**Comment by RealOrangeOne** [comment]
> Their website has a slight bug where they show the billing address as the delivery address on the confirmation page.

I hope this is a bug with their site rather than a bug with Andy! Getting them delivered to you will certainly be logistically _interesting_

**Comment by Tyler-Ward** [comment]
added to #200 for delivery tracking
