### ISSUE TITLE
Publish an article following the SR2024 Kickstart

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1340]
After the kickstart we want to have a news article which describes how the event went and continues to build up the excitement around the comptition. To ensure we have a news article ready to go we should write a skeleton article before the kickstart and then fill in the details as needed.

Things we should mention:
 - that we had N locations, the number of teams who attended, etc.
 - anything particularly interesting from the days (optional; if such things happen)
 - a link to the rulebook (it'll probably be in the usual place in the docs)
 - a summary of the game
 - a link to the kickstart microgames

Once published we should link various people to the article, including:
 - Our social media accounts
 - Various tech/STEM blogs and other media outlets (we should email them)

Required actions:
 - [ ] Write a skeleton article before the kickstart
 - [ ] Publish the article after the kickstart
 - [ ] Link to the article from our social media accounts
 - [ ] Email various tech/STEM blogs and other media outlets with a link to the article

### Original

[kickstart/publish-news-article](https://github.com/srobo/recurring-tasks/blob/master/kickstart/publish-news-article.yaml)
```[tasklist]
### Dependencies
 - [ ] #1337 <!-- [Meta] SR2024 Kickstart Event -->
 - [ ] #1338 <!-- Publish the rules for the SR2024 game -->
```

**Comment by sedders123** [comment]
This was done in https://github.com/srobo/website/pull/533
