### ISSUE TITLE
[Meta] Have the SR2024 Kickstart

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1341]
We need to have the SR2024 Kickstarts.

### Original

[kickstart/main](https://github.com/srobo/recurring-tasks/blob/master/kickstart/main.yaml)
```[tasklist]
### Dependencies
 - [ ] #1337
 - [ ] #1338
 - [ ] #1339
 - [ ] #1340
```

**Comment by PeterJCLaw** [comment]
It did indeed happen. Closing as this was part of the tasks import which happened after Kickstart.
