### ISSUE TITLE
Acquire guest accounts for the guest WiFi network

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1343]
So that all the competitors have internet access, we need to get guest accounts for the teams to access the venue's wifi network.

For this year those will be Eduroam accounts from iSolutions. We should get at least 50 accounts to allow one for each team and some for volunteers. 
We should get them from the Thursday to the Monday to allow for handling any issues as support is reduced at weekends.

**Comment by Alexbruvv** [comment]
We have 50 iSolutions conference accounts for 11th-15th April; the credentials and signature sheet are in the print order folder in Google Drive.

Each login that is used must be signed for and the signed sheet needs to be returned to iSolutions by 30th April 2024 to avoid charges.
