### ISSUE TITLE
Organise audio/visual equipment for SR2024 livestream

### ISSUE THREAD

**Issue by antonnikitin97** [srobo/tasks#1349]

**Comment by antonnikitin97** [comment]
> In previous years, we have borrowed or hired equipment to run the livestream, the general requirements are:
> 
> Video mixer PC (With dedicated GPU, capable of running OBS)
> 2× HDMI capture card
> 2× preview monitors
> 2× cameras (depending on feed plan)
> Audio mixers
> Ideas for the camera feeds:
> 
> Arena (likely multiple)
> Top down view showing whole arena
> Side view showing one side of the arena
> A PTZ camera to follow the action
> Hosts (who may be different to commentators)
> Stage (only needed for prize giving)

From 1247

**Comment by antonnikitin97** [comment]
In conversation with Jamie from Hexibox events regarding obtaining cameras.

**Comment by antonnikitin97** [comment]
From Jamie: 
"I have on my list:
1.Arena top-down camera (will be a PTZ but set and left)
2. "Sidelines" PTZ camera (... balcony)
3. Truss flown PTZ camera
4. Balcony "cube overview" camera (will be a PTZ but set and left)
5. Presenter camera"

Also borrowing a mic from @Adimote , and a streamdeck from @sedders123 .

I will provide the streaming PC and monitors.

**Comment by PeterJCLaw** [comment]
The livestream happened.
