### ISSUE TITLE
Organise music playlists for SR2024 livestream

### ISSUE THREAD

**Issue by antonnikitin97** [srobo/tasks#1350]
```[tasklist]
### Tasks
- [ ] Create a Spotify playlist for Day 1
- [ ] Create a Spotify playlist for Day 2
```
We need to have a good selection of music for the competition.

We'll have access to:
- Epidemic Sound
- Deep Rock Galactic Soundtrack

**Comment by PeterJCLaw** [comment]
The livestream happened.
