### ISSUE TITLE
Determine winner of web presence award

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#136]

**Comment by PeterJCLaw** [comment]
Assigning @prophile as Judge to own this.

**Comment by RealOrangeOne** [comment]
I suspect @antoinepetty will also be in a good place to input on this too, as he's handling social media for the year.

**Comment by antoinepetty** [comment]
Going to wait until closer to the competition date for this one as there is still time for teams to post things.

**Comment by RealOrangeOne** [comment]
I suspect the ideal time to decide this would be saturday night. On the off chance something spectacular happens on Sunday, we'll probably hear about it anyway.

**Comment by PeterJCLaw** [comment]
While I appreciate the sentiment here, I really don't think we should be deciding this that late. The decision here involves research into and then judging of potentially quite a lot of content which the winning team will have been putting out over the course of the year.

It strikes me as highly unlikely that we'll have the spare time or brain capacity to give this the attention it deserves at that point.

To be clear: if something particularly impressive does happen after we've made our initial pick, I'm not averse to changing our minds. However given that a part of this award is sustaining the presence over the course of the year, we should have already formed a strong opinion by then.

**Comment by antoinepetty** [comment]
https://docs.google.com/spreadsheets/d/1r-vGBxArp8UhbTQrJq9hMcIEZt9F1zChh4vXuDzM0UI/edit#gid=0
Record of all team posts online

**Comment by antoinepetty** [comment]
Have messaged Alistair on Slack with my nomination

**Comment by RealOrangeOne** [comment]
Does that mean this is done?

**Comment by antoinepetty** [comment]
> Does that mean this is done?

Waiting for final judgement by @prophile
