### ISSUE TITLE
Design tablecloths

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#138]
We need to design tableclothes for reception

**Comment by RealOrangeOne** [comment]
I suspect _"design"_ is a stretch. If we can find blue-ish cloths, that'll do fine.

That being said, if we have the budget, some SR-branded ones could look quite cook, although that's *very* low priority

**Comment by Tyler-Ward** [comment]
We have budget for branded ones hence needing designing

**Comment by Tyler-Ward** [comment]
With the designs do we want to get them customized for each location e.g. say reception on the reception ones ect or shall we just go with the logo.

**Comment by Tyler-Ward** [comment]
Suggestion from this evening is to have some generic and get labeled ones for fixed locations e.g. reception and helpdesk, can anyone think of any others that want a named tablecloth?

**Comment by Tyler-Ward** [comment]
Leadtime for production is 7 days

**Comment by Tyler-Ward** [comment]
Have thrown together some rough ideas, based on a 150 by 30 printing area for just the logo and 150 by 40 printing area for logo+location name, we might want to check with the suppleier that the names will be level if we go with this style of layout
![location](https://user-images.githubusercontent.com/3390465/53449329-78612c00-3a11-11e9-8a02-4b4e78f7d683.png)
![plain](https://user-images.githubusercontent.com/3390465/53449278-5d8eb780-3a11-11e9-8b78-95c8f2527e28.png)

**Comment by Tyler-Ward** [comment]
Based on some comments here is a version without the orange, what are peoples thoughts?
![location](https://user-images.githubusercontent.com/3390465/54045592-f1a70e80-41c9-11e9-85b0-3d076be43d31.png)

**Comment by Tyler-Ward** [comment]
see https://github.com/srobo/promotional-material/pull/9 for pull request

**Comment by Tyler-Ward** [comment]
designs are merged and ready for ordering
