### ISSUE TITLE
Create means to know whether a robot has been safety tested

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#139]

**Comment by pringon** [comment]
Should the label just be a sticker that goes on the robot to let people know whether it is working or faulty?

**Comment by PeterJCLaw** [comment]
Approximately. This will need space for the signature of the inspector and a way to know when it was granted. That might be the date, or we maybe should have different colours for each day.

We also need to agree a protocol for robots which pass and then change such that they fail (perhaps something happens during a match which changes the robot's structure). This could be that we remove the labels, or it might be that we strike them through with a bold pen. If the latter, this ticket should also include organising the pen too. (Other solutions are also fine)

**Comment by RealOrangeOne** [comment]
In the past, we've done this with hi-viz jackets, which were needed to enter the arena. Is there a reason to do anything different?

**Comment by PeterJCLaw** [comment]
I was just thinking the same actually. There's a bunch of them in storage, which we should check for #183.

**Comment by PeterJCLaw** [comment]
There are a _large_ number of high-vis jackets in the container.

**Comment by Adimote** [comment]
Scarzy is doing this, please assign him once he accepted the invite.

**Comment by Scarzy** [comment]
At this point I'm working on the assumption that "a _large_ number" of high-vis jackets is at least 36. So we'll use them as before. I'll get some labels designed for them.

One issue we had previously was that the labels with the TLA's crunched up and became hard to read. Will we be able to laminate the labels?
Can someone in Southampton count the number of high-vis jackets and confirm how many there are?

**Comment by PeterJCLaw** [comment]
The high-vis jackets are in storage, rather than Southampton. There was an 18l RUB which contained only jackets, which I estimated had about 30 in. There was another similar RUB which contained another 20 or so I think. There was also a blue bag which probably contained another 20 or so, though these were from the years when we let the teams decorate them with TLAs.

Laminating the labels sounds like a good idea.

I recall in the past there was a trade-off between having the labels on the back, where they fit more easily, and on the front, where they got more scrunched up but could more easily be seen by the staging guards (cc @sedders123 as head shepherd).
Should we have labels on both front and back? (Maybe smaller on the front to fit better?)

**Comment by RealOrangeOne** [comment]
If we have the resources, then doing on both would be nice. We've hopefully got enough volunteers that we can get through adding 2 labels should be quick enough.

**Comment by Tyler-Ward** [comment]
What is the benefit of using the high vis jackets over just labeling the robots, as we wont have competitors in the closed off area which was the reason for the initial use.

**Comment by Scarzy** [comment]
A competitor will be accompanying the robot into the staging area and placing it in the arena. Also, a high-vis is far easier to notice than having to look for a label on the robot, and also easier to remove from a team should the robot no longer meet the requirements.

I agree that 1 front and 1 back would be best. Large on the back, small on the front. (This is actually what we did in SR2017)

**Comment by PeterJCLaw** [comment]
IMO the high-vis jackets are also quite cool.

**Comment by sedders123** [comment]
I agree with @Scarzy and @PeterJCLaw . High-vis jackets seem like an easy win to help shepherds know who is allowed in the staging area at any given time. If possible having the TLA on both the front and back of the high-vis sounds ideal.

**Comment by Adimote** [comment]
One thing to note is high-vis jackets ruin any photos with flash
photography.

**Comment by Scarzy** [comment]
@Adimote Please inform the photographer to engage brain and turn off the flash before taking the picture.

It's far more important that we only allow safety checked robots into the arena than someone takes a less than perfect photo. Only 1 of them can result in a claim on our public liability insurance.

**Comment by RealOrangeOne** [comment]
Most of the competition is well lit, which means a flash won't be necessary. In the cube, a flash will either do nothing, or light up the foreground too much. As Scarzy says, a generous serving of common sense should solve this.

**Comment by PeterJCLaw** [comment]
> One thing to note is high-vis jackets ruin any photos with flash photography.

This sounds like a feature to me.

**Comment by PeterJCLaw** [comment]
I am confident that there are enough of these in storage. There was a RUB which I counted the contents of, plus another which I estimated at being well above the number we need.

**Comment by PeterJCLaw** [comment]
@Scarzy how goes the creation of the labels? (Do you want to keep this ticket open until they're done?)

**Comment by Scarzy** [comment]
> @Scarzy how goes the creation of the labels?

Time has not been my friend lately. I hope to find a bit of time this weekend. (Though if someone else finds they have time and could take it on that would be appreciated)

> (Do you want to keep this ticket open until they're done?)

I feel this ticket should be kept open, yes.

**Comment by Scarzy** [comment]
Ok, time has really not been my friend and I haven't had chance to create these labels. Can someone else pick them up?

Front should be badge sized.
Rear should be ~A5 sized.
It should contain our name/logo, SR2019, the competition name, and the relevant TLA (this latter bit being by far the largest)

**Comment by TomWheal** [comment]
I’m happy to pick this up. 

How were you planning on printing the stickers, do we have sheets of sticker paper in the cupboard?

**Comment by Scarzy** [comment]
Thanks Tom!

Print on standard paper, and then laminate them (stickers wouldn't survive)

**Comment by PeterJCLaw** [comment]
Hrm, do we have or have access to a laminator?

**Comment by TomWheal** [comment]
@Tyler-Ward Is there budget for a laminator?

**Comment by Scarzy** [comment]
Hmm... Good point. When it was mentioned earlier in the ticket I completely
forgot to check.

Unlaminated will work, there will just be more issues with the labels
becoming screwed up.

**Comment by RealOrangeOne** [comment]
In the past, I don't think we've laminated the sheets, and they've lasted fairly well, although I agree it would be better. I believe some of them have TLAs written on with sharpies already.

**Comment by PeterJCLaw** [comment]
I think we'd rather use the non-written-on ones as much as we can, it's a bit cleaner that way.

How about getting some heavy paper (even just more of the card we were going to use for the token markers #221) if we don't have access to a laminator? That should help the A5 sheets last longer.

My experience of cutting sheets after they've been laminated is very mixed; such sheets don't last as long as full sheets. Might be fine since it's just for a weekend though.

(I don't feel strongly about a solution; I think either card or lamination is going to be better enough than paper to make a difference)

**Comment by Tyler-Ward** [comment]
We have plenty left in the tools budget to cover the laminator if you think it will be useful. (there are probably some other handouts that could benefit from this as well). For durability we can either get some extra laminating pouches the right size or cue the paper pre laminating then cut the laminating pouches.

**Comment by Scarzy** [comment]
In the past we haven't laminated them, no. But we have ended up with them
completely scrunched by lunchtime the first day.

If we do laminate them, we would definitely want to cut them to size first.

**Comment by Tyler-Ward** [comment]
If the sheets we plan to print are A5 we can also get some A5 laminating pouches. I have approved budget for this @sedders123 are you happy to prime this. if we want A5 laminating pouches another £10 is approved for those.

**Comment by Scarzy** [comment]
Hmm... I just realised I never asked how many of the safety pins needed to
connect the labels to the hi-vis were still in the container. Anyone have
any idea?

**Comment by PeterJCLaw** [comment]
I don't recall seeing any safety pins.

**Comment by TomWheal** [comment]
[TeamSafteryChk.pdf](https://github.com/srobo/tasks/files/3047561/TeamSafteryChk.pdf)
I Plan to print these as both A5 and 'A6' one for front one for back

**Comment by TomWheal** [comment]
Will close this when theyve been printed

**Comment by Scarzy** [comment]
They look good to me!
