### ISSUE TITLE
Order the tablecloths 

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#141]
We should order the tablecloths #138

**Comment by Tyler-Ward** [comment]
what style(s) do we want to go for?
there are two styles we might want one is full length on all sides and the other is shorter at the back
For reception at the competition I would think the shorter back is more usefull but might want full length for other events.

https://www.tablecloths.co.uk/shop/printed-branded-exhibition-tablecloths/
https://www.tablecloths.co.uk/shop/printed-box-conference-tablecloths/

**Comment by Tyler-Ward** [comment]
Per discussion this evening It has been suggested to get half back for named locations and get several full length ones for other locations/holding awards at the end.

**Comment by Tyler-Ward** [comment]
These need to be for 6ft tables as these are more common.

**Comment by Tyler-Ward** [comment]
On the map we have 4 reception tables 2 helpdesk tables plus optionally the photo studio and score entry.

getting 6 would cost just over £400 which is affordable does this sound ok or do people think we should get ones for the other locations as well.

**Comment by Tyler-Ward** [comment]
Can someone get some prices from some other suppliers for these so we have at least three quotes before ordering.

My current thoughts on what to order is.
3* full with just logo
2* box style with Reception
1* box style with Helpdesk
Does this sound sensible to people or do people think we need more/less?

**Comment by trickeydan** [comment]
[Helloprint](https://www.helloprint.co.uk/tableclothregular-220x150-polyester190gsm-withouthem-6) - £268
[Vistaprint](https://www.vistaprint.co.uk/signs-posters/tablecloths) - £750 (Yes, really.)
[BannerWorld](https://www.bannerworld.co.uk/product/printed-tablecloths/) £253 + VAT
[TextileTown](https://www.textiletown.co.uk/buy/Branded-Tablecloths.html) - £324 + VAT
[Discount Displays](https://www.discountdisplays.co.uk/html/display-table.html) - £486

**Comment by Tyler-Ward** [comment]
I had a look at those suppliers and am getting a much higher prices than you found, which settings have you gone with?

![image](https://user-images.githubusercontent.com/3390465/54244149-34971800-4523-11e9-84ca-20df322b5bb4.png)
![image](https://user-images.githubusercontent.com/3390465/54244166-4b3d6f00-4523-11e9-9795-1b8fbfff27eb.png)

**Comment by trickeydan** [comment]
> which settings have you gone with?

6 foot long, 4 foot wide, or there abouts. I was estimating the length of a table

**Comment by trickeydan** [comment]
AH

>To work out the perfect size for your tablecloth use the following sum:
>
>Tablecloth length = table length + table height + table height
>Tablecloth width = table depth + table height + 300mm

**Comment by Tyler-Ward** [comment]
> Can someone get some prices from some other suppliers for these so we have at least three quotes before ordering.
> 
> My current thoughts on what to order is.
> 3* full with just logo
> 2* box style with Reception
> 1* box style with Helpdesk
> Does this sound sensible to people or do people think we need more/less?

I will order the above this evening unless there are any other comments before then

**Comment by Tyler-Ward** [comment]
These have now been ordered see #200 for delivery status
