### ISSUE TITLE
Arrange for transport of spare kit to Southampton

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#144]

**Comment by RealOrangeOne** [comment]
Currently AFAIK, there are 2 partial kits with @PeterJCLaw, and I've got a battery and motor board.

**Comment by Tyler-Ward** [comment]
see #183 for other kit which needs to come down

**Comment by Adimote** [comment]
Peter has returned team kits

**Comment by RealOrangeOne** [comment]
The battery and motor board in my possession are now in the cupboard. The inventory needs updating now t reflect this.

**Comment by PeterJCLaw** [comment]
For clarity: I still have some spare kit parts (boards, batteries and chargers) which I have in case we needed to send spares out (the remaining spares of each component being in storage).
I'll bring them with me to the competition.
