### ISSUE TITLE
Plan Tinker Time Organisation

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#145]

**Comment by RealOrangeOne** [comment]
I've got a sheet around somewhere we've used in previous events, we can use that to organise it. 

As there's only 4 zones, and 1 arena, we're going to have be stringent on only allowing teams 1 slot, until all teams have been given a chance

**Comment by PeterJCLaw** [comment]
I'm pretty sure there's a whiteboard in storage which has been used to organise this on the day in the past.

@mildlyincompetent what preparatory stuff did you have in mind here?

**Comment by RealOrangeOne** [comment]
There's also usually a whiteboard in the cube which could be used too. Depending on how many slots there are, and how many teams want them, i've often had to resort to a google sheet to ensure things don't get messy. If that does happen, it might be useful to put a (read-only, obviously) link on the competition page, so teams can see for themselves where their slots are.

**Comment by RealOrangeOne** [comment]
This is blocked on https://github.com/srobo/tasks/issues/73, to confirm how long tinker time will be, to decide how long slots will be to ensure each team gets a reasonable amount of time and chance to test

**Comment by RealOrangeOne** [comment]
According to the schedule in https://github.com/srobo/tasks/issues/73, There's a total of 3h20 to allocate to teams, spread over the 3 days. 

The current intention is to go with 10 minute slots, leaning towards having more, smaller slots, rather than fewer longer ones.

An exact plan with more notes is in progress.

**Comment by PeterJCLaw** [comment]
I suggest that the booking of the slots only be allowed for slots during the next tinker time window.

**Comment by Tyler-Ward** [comment]
booking only one slot in advance will likely end up with a queue of teams waiting to book slots. To avoid teams being able to monopolize it we can limit teams to one slot until a sufficient window has been give to together teams to register.

**Comment by RealOrangeOne** [comment]
@sedders123 and I discussed how to deal with duplicate bookings. The best idea we came to was to stagger releasing slots, and prevent booking too close together. 

I suspect common sense can be employed on the day to ensure slots aren't abused.

**Comment by RealOrangeOne** [comment]
I've created a google sheet which we can use to plan this. In my experience, whiteboards end up messy, and don't show a history of teams slots to prevent abuse. https://docs.google.com/spreadsheets/d/1voJr27a9vkpTzpZntFwjZwO_aher9BpJrra62T0Te4E/edit?usp=sharing (write available upon request)

There's 20 slots throughout the weekend, and 4 corners, so there's 80 possible tinker time slots. Given that we have ~32 teams, I suggest we prevent teams from booking more than 1 slot on in a given section, and remind them that chances are, they're only going to get 2 possible slots. I suspect common sense can also be employed on the day to prevent abuse, too.

**Comment by PeterJCLaw** [comment]
Whiteboards have the superb advantage of being easily readable by everyone, at a good distance, as well as not requiring an internet connection or power. I'm not aware we've had any issues with them becoming illegible or messy.

**Comment by sedders123** [comment]
PR to the runbook here https://github.com/srobo/runbook/pull/19

**Comment by RealOrangeOne** [comment]
Now that https://github.com/srobo/runbook/pull/19 has shipped, we can close this.
