### ISSUE TITLE
Validate the information provided by SR2025 signups

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#1464]
During SR2024 we had a couple of cases where the phone numbers provided for team supervisors were to their institution landline rather than being a direct way to contact the person at an event. We should at least do a basic check that the numbers look like mobile numbers.

We should also sanity check any other details we're asking for to ensure that they're useful to us.

Follows from https://github.com/srobo/runbook/issues/204

**Comment by samjmartin04** [comment]
Worth noting that some institutions that have signed up with their landline number may not know the mobile number that they will have during the competition weekend at this stage

**Comment by PeterJCLaw** [comment]
Thus far we have:
- four teams where the primary contact's phone number doesn't look like a mobile number
- one team where there is no secondary contact mobile number

**Comment by PeterJCLaw** [comment]
Have sent emails to the teams without a mobile number. Holding off on the missing secondary contact phone number until we've done #1467.

**Comment by PeterJCLaw** [comment]
All have been chased and provided alternatives or reasons why they can't.
