### ISSUE TITLE
Purchase Insurance

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#147]

**Comment by RealOrangeOne** [comment]
We need events and public liability. We should check if we're covered by the insurance of SUSU.

We should get a quote for both, just in case.

**Comment by TomWheal** [comment]
Has this been done? Seems like it’s kinda urgent?

**Comment by Tyler-Ward** [comment]
For budget info: A rough price from hiscox is £70 for just the event and £250 ish with cover for volunteers.

**Comment by Scarzy** [comment]
I'm going to regret saying this, but:
When we have this, can someone send me a copy of the T's&C's, so that I can make sure I know what our obligations are from a H&S standpoint.

**Comment by Adimote** [comment]
Alistair doesn't have a quote just yet, he said these should arrive tomorrow

**Comment by Tyler-Ward** [comment]
The quote has arrived for £210 if this covers what we need then it is budget approved.

**Comment by PeterJCLaw** [comment]
I've forwarded the quote document (which contained the T&Cs) to @Scarzy for info.

@prophile just to check - are you owning making a decision on whether this provides the cover we want and do you want any input or review from others?

**Comment by prophile** [comment]
I'll make this decision in consultation with Scarzy (subject, of course, to the veto of the core team).

**Comment by Scarzy** [comment]
Alistair and I agreed that we should take this insurance.

I've informed Hiscox that we wish to take it out.

**Comment by PeterJCLaw** [comment]
@Scarzy what's the status on this?

**Comment by sedders123** [comment]
Competition is over
