### ISSUE TITLE
Plan the SR2025 Horsham Tech Day in November

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#1478]
- [x] https://github.com/srobo/tasks/issues/1482
- [x] Re-advertise to teams
- [x] Appoint safeguarding officer: it's James
- [x] Sign up volunteers

**Comment by PeterJCLaw** [comment]
Risk assessment updated: https://docs.google.com/spreadsheets/d/1PpTx_isP_SPUFMVyY2JuRnudHawK0lRevSiz4ggo34c/edit?gid=0#gid=0

**Comment by sedders123** [comment]
The tech day happened
