### ISSUE TITLE
Create music playlists

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#148]

**Comment by RealOrangeOne** [comment]
Work has started on combing through the previous playlists. I'm going to open up the suggestions list soon.

@Tyler-Ward where's the list you've been putting together?

**Comment by PeterJCLaw** [comment]
Does this include the finals? (cc @prophile is pretty good at that)
If so, whoever does this should co-ordinate with #74.

**Comment by kierdavis** [comment]
Possibly of use: https://open.spotify.com/user/kierdavis/playlist/6aprxudtjc2WaWbRUqEc1P?si=Whl1G63yQkC_waPQkyB3vA

**Comment by RealOrangeOne** [comment]
I've been working on just the match playlist, and the _Chill_ playlist (to be played when there's not matches).

I suspect @prophile will do the finals tracks, but i'm happy to help where needed!

**Comment by prophile** [comment]
I would very much like to do the finals tracks again.

**Comment by RealOrangeOne** [comment]
The playlists are now in a state where they could function perfectly for the event. There are 2 playlists, 1 for during matches, and 1 for between matches.

Currently the match playlist is 148 tracks at 9h30. Currently the _chill_ playlist is 221 tracks at 14h16. These should both be more than enough, and cover the previous complaints at events of playlists looping too much, and hearing the same song too many times.

**Comment by Tyler-Ward** [comment]
Did you manage to fine the ones from my list or do you need me to find any, also did you create a chill instrumental only playlist.

**Comment by RealOrangeOne** [comment]
I've not split out the chill playlist. It'll take like 10 minutes so we can do that if we find an issue with it.

I need to go through the sheet you've been adding too again at some point to do a second pass.

**Comment by RealOrangeOne** [comment]
I've now gone through all the linked suggestions, as well as previous years, and things i've come across, and I think we're in a good position now to close this.

The durations haven't changed much since https://github.com/srobo/tasks/issues/148#issuecomment-471282263, which is fine.

If anyone wishes to submit more suggestions, then feel free to post them here or talk to me. But for now, we can consider this done.
