### ISSUE TITLE
Plan and Simulate the SR2025 virtual friendly competition

### ISSUE THREAD

**Issue by samjmartin04** [srobo/tasks#1487]
For the virtual friendly competition, all the matches need to be simulated in advance. Running the simulation at reasonable speed requires a reasonably powerful computer with a discrete GPU.

Once the simulation is complete, the videos need to be sent to the livestream producer so that they can be played during the livestream.

Required actions:

- [x] Decide who will run the simulation
- [x] Decide when the simulations will be run
- [x] Create a branch in the compstate for the friendlies
- [x] Generate a schedule for the simulated matches
- [x] Run the simulation
- [x] Send the videos to the livestream producer

**Comment by samjmartin04** [comment]
Andy BS has volunteered to simulate the friendlies.

**Comment by samjmartin04** [comment]
Simulations will be run on Thursday 12th December 2024 after the 6pm deadline for teams to submit their code by.

I can provide the schedule for the simulated matches at this point when we know how many teams have submitted code.

**Comment by PeterJCLaw** [comment]
This all happened.
