### ISSUE TITLE
Plan communications 

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#149]
Possibly solutions:
- [x] Radios
- [ ] VoIP

Related to #71

**Comment by trickeydan** [comment]
Given how we're short on time, we should plan for *just* radios.

**Comment by RealOrangeOne** [comment]
Individuals who need radios:
- Head judge
- Kit support
- _Showman_
- Technical Director
- Head shepherd

Locations which need radios:
- Reception
- Help Desk
- Battery charging / scoring
- 3x shepherds

Shepherds will use the SUSU existing radios. Head shepherd will have both networks. The others will be hired in.

**Comment by trickeydan** [comment]
- SUSU radios are for shepherds
- Malt Vinegar Radios are for control / locations.
