### ISSUE TITLE
Create expert list for helpdesk

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#150]
Work out who knows the kit

**Comment by RealOrangeOne** [comment]
The volunteer signup form had a question about this, so we can probably use that to gauge experience. Considering issues we've had in the past (namely around burnout), we should ensure we train up as many volunteers as possible, if not all of them.

**Comment by RealOrangeOne** [comment]
We just need to take a list of anyone who entered `3`/`4` on the _"I know the Student Robotics kits"_ question when signing up to the event, and substitute those in perma-assigned roles. Most of those who entered 5 are likely to be very busy during the event!

Scores:
1. 5 people
2. 7 people
3. 6 people
4. 10 people
5. 5 people

We should aim to do volunteer scheduling such that at least 1 person who voted `4` is on help desk at a given time, or in a role which isn't as time-consuming, to allow them to assist with debugging when possible. Assigning @Adimote in preparation for volunteer scheduling for opinions on this.

(I've intentionally not put the list of names here, we can print it off at the event when necessary)

**Comment by Adimote** [comment]
I've finished assigning the 'Head Helpdesker' role in the task schedule up to the end of the Finals (in the process of finishing #80, which will take some more time), so I'm going to declare this done.

**Comment by Adimote** [comment]
Well looks like I misunderstood this ticket, I'll make a list of people
