### ISSUE TITLE
Send hotel information to competitors

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#152]

**Comment by Tyler-Ward** [comment]
#53 will help this

**Comment by Tyler-Ward** [comment]
Given we announced the date a few weeks ago now do we still think this is worth doing?

**Comment by RealOrangeOne** [comment]
It's highly unlikely. If we assume we're just going to send volunteers to a hotel, which is close to the uni, we probably don't need to inform volunteers where until very shortly before the event itself.

**Comment by Tyler-Ward** [comment]
In which case i will close this then
