### ISSUE TITLE
Plan volunteer meal for Saturday

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#154]
PUB PUB PUB

**Comment by RealOrangeOne** [comment]
Cowherds? :trollface:

**Comment by sedders123** [comment]
Below is the current count of volunteers who have responded about attending the meal. At this point we are not expecting volunteer sign up numbers to change drastically.

Attending the meal | Number
-- | --
Yes | 22
No | 1
Maybe | 10

**Comment by PeterJCLaw** [comment]
@Adimote can you take this?

**Comment by Adimote** [comment]
I just sent an email trying to convert some of those Maybe's into Yes-es. I'll take up the task of actually booking the meal. 

With this number of people it's best to get people's menu choices before-hand. I think that's in scope if I sort it on Monday.

**Comment by Tyler-Ward** [comment]
@Adimote Any update on this.

**Comment by WillB97** [comment]
From discussion we are thinking:
- The Stable
- The buffet places in town (JRC or Cosmo)

If those aren't available tell us.

**Comment by Adimote** [comment]
Thanks, I'll make the calls today.

**Comment by Adimote** [comment]
I've booked the stable for 28 people at 19:30, they say it should be fine to bring more or less guests, and it's fine to come later if needed.

**Comment by RealOrangeOne** [comment]
Is there a plan for getting volunteers _to_ the stable, and back again? I suspect those with cars will not want to drive there, as parking isn't fun.
