### ISSUE TITLE
Create name badges

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#155]

**Comment by mildlyincompetent** [comment]
Needs #158

**Comment by Tyler-Ward** [comment]
Final printing is still blocked on knowing who we have at the competition. however this can progress for the current signup list

**Comment by Adimote** [comment]
We have badge holders in the container. (We need the card to print on it)

**Comment by PeterJCLaw** [comment]
There's a box of badge holders in the container. Not sure how many, but _many_.
Doesn't include the card to print on.

**Comment by Tyler-Ward** [comment]
@sedders123 can you get the file of these to @TomWheal. These will need to be printed on card.

**Comment by sedders123** [comment]
The file [can be found in slack](https://studentrobotics.slack.com/archives/CDCJ93YMC/p1554307578021100)

**Comment by TomWheal** [comment]
These have been printed

**Comment by TomWheal** [comment]
These have been made
