### ISSUE TITLE
Plan communications training

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#156]
We need to teach people how it works.

E.g phone numbers, radio protocols.

Depends on #149

**Comment by RealOrangeOne** [comment]
This is only necessary if we're using something other than radios. 
Although either way, we should probably work out a communications protocol for how to get someones attention, or get help with a specific issue (eg kit electronics)

**Comment by Tyler-Ward** [comment]
We will still need training with radios, most volunteers wont be familiar with how to use them.

**Comment by RealOrangeOne** [comment]
@prophile has a plan. We may want to be worried...
