### ISSUE TITLE
Order Refreshments for Volunteers

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#157]

**Comment by Tyler-Ward** [comment]
My current rough thoughts for this for people to provide opinions on.

In the volunteer area we provide:
* Soft drinks/fruit juice.
* Tea/coffee (with milk+shugar ect)
* light snacks e.g. biscuits, snack boxes, fruit ect.
* will also need cups and napkins.

based on this we also have budget to provide some food around lunch or some evening food (will need checking regards to budget). what are people thoughts when to do this? note that we have the volunteer meal on Saturday #154 so wouldn't want to do stuff then.

**Comment by mltnhm** [comment]
From having a run through of Sainsbury's website:

| **Product** | **Price** |
| --- | --- |
| [McVitie's Digestive Biscuits 400g](https://www.sainsburys.co.uk/shop/gb/groceries/mcvities-digestive-biscuits-500g) | £1.00 |
| [McVitie's Milk Chocolate Digestives Biscuits 266g](https://www.sainsburys.co.uk/shop/gb/groceries/mcvities-milk-chocolate-digestives-biscuits-332g) | £1.00 |
| [Walkers Classic Variety Crisps 6x25g](https://www.sainsburys.co.uk/shop/gb/groceries/walkers-variety-crisps-6x25g) | £1.25 |
| [Coca-Cola Original Taste 1L](https://www.sainsburys.co.uk/shop/ProductDisplay?storeId=10151&amp;productId=1192740&amp;urlRequestType=Base&amp;catalogId=10122&amp;langId=44) | £1.00 |
| [Coca-Cola Zero Sugar 2L](https://www.sainsburys.co.uk/shop/ProductDisplay?storeId=10151&amp;productId=1192734&amp;urlRequestType=Base&amp;catalogId=10122&amp;langId=44) | £1.95 |
| [Sainsbury&#39;s White Granulated Sugar 1kg](https://www.sainsburys.co.uk/shop/gb/groceries/sainsburys-british-white-granulated-sugar-1kg) | £0.75 |
| [Cravendale Purefilter Semi Skimmed Milk 2L](https://www.sainsburys.co.uk/shop/gb/groceries/cravendale-purefilter-semi-skimmed-milk-2l) | £1.50 |
| [Douwe Egberts Pure Indulgence Instant Coffee 190g](https://www.sainsburys.co.uk/shop/gb/groceries/douwe-egberts-dark-roast-coffee--pure-indulgence-190g) | £5.00 |
| [Tetley Everyday Tea Bags, Softpack x240](https://www.sainsburys.co.uk/shop/gb/groceries/tetley-everyday-tea-bags--softpack-x240) | £3.30 |
| [Sainsbury&#39;s Pure Orange Juice 4x1L](https://www.sainsburys.co.uk/shop/gb/groceries/sainsburys-pure-orange-juice-4x1l-6313748-p-44) | £2.95 |
| [Sainsbury&#39;s Pure Apple Juice 1L](https://www.sainsburys.co.uk/shop/gb/groceries/sainsburys-pure-apple-juice-1l) | £0.85 |


No idea about sandwiches as they're not on their website

**Comment by trickeydan** [comment]
> From having a run through of Sainsbury's website:

Given the volatility of the price of certain items in Sainsbury's, I would recommend that we buy whatever variety of item is on offer.

**Comment by kierdavis** [comment]
Have we surveyed the dietary requirements of our volunteers? Do we need to provide alternatives that are (for example) lactose-free, gluten-free, vegan and/or low calorie?

**Comment by mltnhm** [comment]
I did think about that as I'm lactose intolerant myself but I don't really know what to do about that.

**Comment by Tyler-Ward** [comment]
Based on some quick sums the suggestion is to have some refreshments in the volunteer area and to provide lunch for volunteers on both days if we can keep the cost to a reasonable level. Hoffers have been suggested as a suitable supplier. Is someone able to head there and enquire about prices.

Shopping list for volunteer area refreshments.
- [ ] Box of tea bags
- [ ] 2 Jars of instant coffee
- [ ] 30 cartons of fruit juice
- [ ] 20 packs of biscuits
- [ ] an amount of snack-able fruit
- [ ] 400 cups for hot liquid
- [ ] 2000 generic cups. (also for competitors) doing this also solves #159

**Comment by Tyler-Ward** [comment]
@WillB97 is going to acquire quotes for lunch options

**Comment by Tyler-Ward** [comment]
Some prices from Costco for reference
hot cups: £11.98/150
plastic cups: £3.22/100
Fruit juice: £9.22 orange/£7.18 apple for 12L
Edible prizes (Lindor) 4*200g = 13.18

**Comment by PeterJCLaw** [comment]
:+1: to plastic cups.
Could we also add a tray to transport refreshments to volunteers (#159)? I'm guessing that would cost about £5, but we should be able to re-use it in the future. (We've had one in the past, but I don't know where it came from).

**Comment by WillB97** [comment]
Hoffers is £1.50 per sandwich

**Comment by sedders123** [comment]
[Plastic Cups](https://www.amazon.co.uk/Plastic-Disposable-Clear-Drinking-Glasses/dp/B00BSD57GU/)
[Hot Cups](https://www.amazon.co.uk/Premium-Disposable-Perfect-Parties-Outdoors/dp/B01K86JGOQ/)
[Kettle](https://www.argos.co.uk/product/9016710)

**Comment by Tyler-Ward** [comment]
Shopping list: for general refreshments.
### Costco: (@Tyler-Ward  approved up to £20)
* Fruit Juice: 12*1L orange 12*1L apple
### Supermarket: (@RealOrangeOne approved up to £40)
* 2*jar coffee £10
* 1*box tea bags £3.30
* £15 worth of fruit.
* 4*1L milk carton £3.20
### SUSU: About £15 (not yet assigned to be purchased on setup days)
4* broken biscuit assortment
### Amazon: (@sedders123 approved £33)
* 2000 plastic cups £18
* 200 hot cups £14.98
### Argos: (@sedders123 approved £8)
* Kettle

Total approved for volunteer break room supplies: £116

**Comment by PeterJCLaw** [comment]
Can we get something more than just some boxes of broken biscuits? They're ok, but not the greatest especially considering the take-things-to-volunteers aspect.

Perhaps add the following (and maybe slightly reduce the number of packs of broken biscuits?):
- 5 packs of hobnobs (£1 each)
- 5 packs of chocolate digestives (£1 each)
- 3 packs of fig rolls (£0.36 each)

**Comment by Tyler-Ward** [comment]
Sounds good to me @RealOrangeOne are you happy to order if so ill bump your approval by another £10 to cover the above (£50 total) and ill drop down to 2* broken biscuits £7.50 approved.

**Comment by Tyler-Ward** [comment]
Drinks have been purchaced

**Comment by RealOrangeOne** [comment]
@Tyler-Ward Yes, this is fine with me. I suspect the execution will be a slightly more varied mix than 5 packets of each, but it depends what Tesco have in stock. I'll just cap it at £10 and see what we come out with.

**Comment by Tyler-Ward** [comment]
I have updated the approvals accordingly

**Comment by Tyler-Ward** [comment]
Based on the hoffers price and the fact that they can do both days I suggest we go for sandwiches on both days. The cost for this would be £1.50 per person per day.

We currently have 41 volunteers and i believe we have another few expected to sign up in the next couple of days from what people have said. In order to have some spare capacity and choice ordering 50 sandwiches per day sounds sensible which would cost £150. does this sound good to people?

@Adimote can you compile a list of dietary requirments we need to cater for.

**Comment by PeterJCLaw** [comment]
Just had a thought -- do we have binbags? Should we get some?

**Comment by Tyler-Ward** [comment]
Unless you think we have some in the container we should buy some. @RealOrangeOne are you happy to pick these up as well shouldn't come to more than a couple of pounds?

**Comment by PeterJCLaw** [comment]
I couldn't say for sure that we have some and given that they're a minimal cost I suggest just getting some.

**Comment by RealOrangeOne** [comment]
@Tyler-Ward yes, this is fine. On that note, Is it worth getting a roll of paper towels too?

**Comment by WillB97** [comment]
@Tyler-Ward @Adimote  If we want to be sure hoffers can make the combination we want, we need to get a list what sandwiches we want to them by this friday so they can order the fillings.

**Comment by Adimote** [comment]
Apologies for being so late on this, here are the details:
```
Lactose Intolerant x2
No seafood
Vegetarian x4
Nut allergy x2 (One of which is life threatening)
```

**Comment by Tyler-Ward** [comment]
@RealOrangeOne sounds good, ill increase the approval by £10 which should be plenty for the above. now £60
@WillB97 I think a general mix is probably a good idea. I don't think we will be able to take orders from people in advance so i suggest we just over order to give some choice (hence the 50 above). I we don't want to have too many options possibly go with ten of five different fillings.

**Comment by Adimote** [comment]
Deleted my previous comment because it had a bit too much PII to be search indexed. I'll PM the relevant people about the volunteer food requirements.

**Comment by Tyler-Ward** [comment]
@WillB97 has told me that the sandwiches have been ordered and will be delivered to gower carpark on the saturday.

**Comment by RealOrangeOne** [comment]
My part of this order has been purchased, almost. I elected _not_ to purchase fruit quite so early, i'll hopefully go and grab this on a setup day (task for this incomming).

These items came in slightly under budget also, which is good.

**Comment by RealOrangeOne** [comment]
@Tyler-Ward I believe everything listed in https://github.com/srobo/tasks/issues/157#issuecomment-475906928 has now either been ordered, or split up into its own ticket to be ordered on setup day.

Can we close this?

**Comment by Tyler-Ward** [comment]
I have added the sandwiches to #200 as they will be delivered. So this can be closed
