### ISSUE TITLE
Design Name Badges

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#158]

**Comment by Tyler-Ward** [comment]
Have created a quick design inspired by the business card design thoughts?
![badge](https://user-images.githubusercontent.com/3390465/53290577-f1584d80-379d-11e9-94ad-18338553dd4f.png)

**Comment by trickeydan** [comment]
Do we require a role name on the names? I feel like that introduces too much complexity as people move between roles. Also I dislike unnecessary bureaucracy.

**Comment by Tyler-Ward** [comment]
The role is optional, I suggest that gets left to #155 to decide but could also be volunteer for most people. we might want to to identify trustees and key static roles like head judge, however that has the catch of potentially feeling exclusive for those who don't have named roles .

**Comment by RealOrangeOne** [comment]
I agree with @trickeydan here, it's unnecessary to list roles on name badges, considering it's likely that only a handful of people will have fixed roles for the full duration of the event. If we're set on having roles on the name badges, then potentially stating "Core Team" would benefit, but I still go with that it's unnecessary.

**Comment by Tyler-Ward** [comment]
A pull request for the design can be found at https://github.com/srobo/promotional-material/pull/4

**Comment by Tyler-Ward** [comment]
This has now been merged
