### ISSUE TITLE
Plan volunteer refreshment/water distribution

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#159]
Our volunteers will be very busy during the competition and many will have roles that require them to be in a single place for the majority of the competition.

We need to distribute water (preferably not with an aquaduct) and other refreshments to these volunteers.

**Comment by RealOrangeOne** [comment]
As an aquaduct has been banned (:sob: ), we might be able to use the existing water machines, assuming we have enough cups around.

Is there a water machine on the concourse? That would make life a lot easier!

**Comment by WillB97** [comment]
There are water machines in Bar 2 & 3

**Comment by JennyLouise** [comment]
Could ask for southampton uni branded (or other?) water bottles and labels, and have volunteers collect, refill, and redistribute them?

**Comment by prophile** [comment]
Is the scope here just volunteers or all attendees?

**Comment by Tyler-Ward** [comment]
@prophile This would be mainly for volunteers, but if we can also provide facilities for competitors that is an added bonus.

**Comment by RealOrangeOne** [comment]
@JennyLouise could you ask around about this?

**Comment by RealOrangeOne** [comment]
If we can't do this, we can just get volunteers to service other volunteers

**Comment by PeterJCLaw** [comment]
In the past we've had a role for delivering refreshments to other volunteers. It's pretty important that we have that as there are some roles which don't allow you to away from your post at all.

**Comment by PeterJCLaw** [comment]
@Adimote as you're handling the volunteer schedule #80, could you handle this?
(I'm not actually sure why this is a separate ticket rather than just being one of the roles we're going to have)

**Comment by Tyler-Ward** [comment]
it is a separate ticket as we currently have no way to move the water around.

**Comment by PeterJCLaw** [comment]
Suggestions:
- bottles
- plastic cups
- a tray

We've used a tray in the past, but I don't recall seeing one anywhere in the inventory or storage, so it's possible we borrowed one from somewhere.

I have a tray not unlike this https://www.therange.co.uk/cooking-and-dining/tableware-and-dinnerware/serveware/serving-trays/simply-polka-dots-tea-tray/ which I could probably bring, though given how cheap they are it might be easier to include one in our refreshments order.

We should definitely add some plastic cups to #157 if we don't already have some there.

**Comment by trickeydan** [comment]
Might be able to get bottles from the uni - #202

**Comment by Adimote** [comment]
@PeterJCLaw RUB lids work really well as trays, I'll take this

**Comment by PeterJCLaw** [comment]
RUBs as trays is a pretty ugly solution though.

**Comment by Tyler-Ward** [comment]
I think we are done with this unless we want to order a tray or two. if so can someone find a link for me to approve purchase of if not sufficient cups have been ordered in #157 to cover the water needs.

**Comment by PeterJCLaw** [comment]
I think it's https://www.therange.co.uk/cooking-and-dining/tableware-and-dinnerware/serveware/serving-trays/simply-polka-dots-tea-tray/ that I have. I have a "The Range" around the corner and could happily grab one or two of these.

**Comment by PeterJCLaw** [comment]
(Turns out I actually have the grey one which is currently slightly cheaper: https://www.therange.co.uk/cooking-and-dining/tableware-and-dinnerware/serveware/serving-trays/simply-slate-grey-polka-dot-drinks-tray/)

**Comment by Tyler-Ward** [comment]
Sounds good, Approved for two grey trays £4.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward for clarity: I expect two of them will total £8, is that ok?

**Comment by PeterJCLaw** [comment]
Ah, hrm I appear to have linked the wrong thing when I linked the grey one. I think we want a full size tray (a little over double the size): https://www.therange.co.uk/cooking-and-dining/tableware-and-dinnerware/serveware/serving-trays/simply-slate-grey-polka-dot-tea-tray/, which is £3.49.

**Comment by Tyler-Ward** [comment]
That is fine now approved for £8

**Comment by Adimote** [comment]
I've written some documentation on how I think refreshments should work in https://github.com/srobo/runbook/pull/26, is it okay if I carry on with handling this task?

**Comment by PeterJCLaw** [comment]
@Adimote please do, I have acquired the trays.

**Comment by Adimote** [comment]
as https://github.com/srobo/runbook/pull/26 is merged, I can call this done!
