### ISSUE TITLE
Investigate other IDE software

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#16]
Our recent team-leader survey (https://github.com/srobo/core-team-minutes/issues/4) showed that being able to install software onto school computers is still an issue for many teams, so we still need to provide a way for competitors to develop their code.

While this _probably_ means a hosted IDE, it might not. One sort-of-hosted option would be to run an IDE on the robots.

If it does mean a hosted IDE, here are some requirements:

#### IDE stuff
- code editor
- Python syntax highlighting
- multiple files per project, directory structure available & browseable
- easy way to export code for putting on the robot (perhaps as a single archive)
- (nice to have): version control with history & diffs

#### Other stuff
- per-user accounts, ideally would integrate with our existing systems
- user groups (users can be in one or many groups), with projects private to each group
- no public projects (we don't want teams accidentally able to publish their code; while we obviously can't prevent them publishing it somewhere else, we should avoid handing them a loaded footgun)
- no personal projects (anyone in the team _must_ be able to access the code -- teams already suffer from their coder not turning up at the competition and struggling to edit the code, if they also couldn't _access_ that code they'd be totally hosed)
- ability to have user accounts which are limited to read-only access (for team-leaders) specified on a per-group basis (for mentors)
- ability to customise the export mechanism so that we can add to the emitted archive
- easy to set up (either by just being trivial to configure in the first place, or easy to configure through a configuration management system)
- low cost (the definition of "low" is vague, notably we don't need the solution to be free; especially if it means less maintenance for us)
- (should have) ability to brand it, both visually as well as urls (proxying is fine for the urls)
- (should be) Open Source
- (nice to have) ability to add links in the interface (so we can add links to the docs, forums & ticket signup)

**Comment by Adimote** [comment]
I've made an analysis of if we could use Cloud9 as an IDE at https://docs.google.com/document/d/1HlA_NxJ4_wJZyGA4DF1cJrOC_iHQiX3Q3pTJ0uvXilE/edit?usp=sharing

**Comment by PeterJCLaw** [comment]
Not really directly suitable as a replacement for our IDE, but something to consider as a set of features thought through for beginners: https://thonny.org/

**Comment by PeterJCLaw** [comment]
Note: while the following isn't entirely on-topic, it hopefully provide useful insight into the direction our requirements should head in future.

From some hands-on direct user testing I was able to do this morning (with some beginner programmer volunteers at work) it turns out that:
* downloading a zip file onto a USB stick to get it onto the robot is _really_ long winded and frustrating compared to the rest of our experiences with modern technology. In particular one person didn't initially understand why you needed to first "Save" then also "Export" ([if had been saved then] "where had it saved it to?"), which is a really interesting insight now that the world of cloud documents is something people take for granted
* syntax checking should happen _before_ file saving (ideally in the background, though maybe also on-click and blocking?
* people _do_ work out what the diff view in the current IDE does on their own (I'm not sure if they find it valuable, but it's gratifying that its purpose is sufficiently self evident as I've never been sure)
* waiting for the robot to reload the code takes _ages_ (even hot reloading)

**Comment by PeterJCLaw** [comment]
https://kevinhq.com/a=review-of-gitpod-is-it-worth-to-try.html suggests that https://www.gitpod.io/ could be worth investigating.

**Comment by mltnhm** [comment]
Might seem a bit overkill but could do with GitLab. The WebIDE is pretty good

**Comment by RealOrangeOne** [comment]
https://coder.com/ has just been made open source, which could be interesting. Server-side vscode. 

If we can get some decent project setup, it could work quite well.

**Comment by trickeydan** [comment]
Meta: If we do end up using `j5` and the associated OS, it will support both zipped and unzipped code.

**Comment by meysholdt** [comment]
I just found this issue while searching for mentions of 'gitpod' and thought you might find this article helpful: https://www.infoworld.com/article/3342624/cloud-ide-review-aws-cloud9-vs-eclipse-che-vs-eclipse-theia.html

**Comment by PeterJCLaw** [comment]
https://devblogs.microsoft.com/visualstudio/intelligent-productivity-and-collaboration-from-anywhere/ seems relevant on the VSCode-in-the-cloud side of things.

**Comment by trickeydan** [comment]
https://www.theia-ide.org implements vscode and has a nice plugin system.

**Comment by PeterJCLaw** [comment]
While not strictly related, we should probably consider whether we want the IDE to be real-time collaborative.

**Comment by trickeydan** [comment]
> While not strictly related, we should probably consider whether we want the IDE to be real-time collaborative.

I realise I have yet to write up the notes yet, but this was requested by competitors.

Also raised RE the IDE:

- It's critical to many teams that it's online.
- Currently too slow (Unsure if it's slow, but this was definitely mentioned)
- They don't want to be restricted to just our IDE, some copy-pasted code from other (offline) IDEs.
- Don't use git functionality. (mentioned as confusing and just click through it to make it go away)
- Would be good to delete projects
    - I'm aware of the reasons behind this restriction, I suggest either a "Hide Project" or "Recycle Bin" function.
- It's useful that they can program the robot whilst not necessarily being near it.

**Comment by PeterJCLaw** [comment]
Thanks for sharing the notes. I've various thoughts on how to improve the current IDE, but I've held back on those from this.

>* Currently too slow (Unsure if it's slow, but this was definitely mentioned)

This is fantastically vague. Do we have any hints as to what aspects are too slow? What would "fast enough" look like?
Is it the initial load? The time to save? The time to export? The edit/debug cycle as a whole?
If we don't already know, this will likely be something we need to carefully ask about in the future -- we're not going to be able to improve this by guessing.

>* They don't want to be restricted to just our IDE, some copy-pasted code from other (offline) IDEs.

Hrm, sounds like we need to do a better job of explaining how this is already not the case.

An idea I've been kicking around for a long while is to have a VSCode extension which either pings the IDE for the zip creation and/or the repos. _Maybe_ this could do the zip creation locally, though that gets messy from the perspective of ensuring they pick up updates in a timely manner (which is already an issue).

In either case, if we want to enable both in-IDE and extra-IDE development, having a good story for how to get the code between the two is important.

>* Don't use git functionality. (mentioned as confusing and just click through it to make it go away)

Do we know what's meant by "just click though"? Is this related to being asked for a commit message?
There _are_ teams who use this for development outside the IDE, so the git aspects are clearly valuable to some.

A substantial benefit to having everything in git is that it's relatively easy to find out what was running on the robot when as the robot prints the commit hash into the logs.

**Comment by trickeydan** [comment]
> This is fantastically vague. Do we have any hints as to what aspects are too slow? What would "fast enough" look like?
> Is it the initial load? The time to save? The time to export? The edit/debug cycle as a whole?
> If we don't already know, this will likely be something we need to carefully ask about in the future -- we're not going to be able to improve this by guessing.

I did attempt to press for details, didn't get much.

> > * They don't want to be restricted to just our IDE, some copy-pasted code from other (offline) IDEs.
> 
> Hrm, sounds like we need to do a better job of explaining how this is already not the case.
> 
> An idea I've been kicking around for a long while is to have a VSCode extension which either pings the IDE for the zip creation and/or the repos. _Maybe_ this could do the zip creation locally, though that gets messy from the perspective of ensuring they pick up updates in a timely manner (which is already an issue).

See https://github.com/systemetric/sr-zipper for the latter.

> Do we know what's meant by "just click though"? Is this related to being asked for a commit message?

Indeed.

> There _are_ teams who use this for development outside the IDE, so the git aspects are clearly valuable to some.

Interesting. 

> A substantial benefit to having everything in git is that it's relatively easy to find out what was running on the robot when as the robot prints the commit hash into the logs.

Perhaps we could add a mode where it 'auto-commits' regularly + when the code is exported? We should also leave a proper git mode though for teams that use it.

**Comment by PeterJCLaw** [comment]
> > A substantial benefit to having everything in git is that it's relatively easy to find out what was running on the robot when as the robot prints the commit hash into the logs.
> 
> Perhaps we could add a mode where it 'auto-commits' regularly + when the code is exported? We should also leave a proper git mode though for teams that use it.

Yeah. The idea I'd had a long time ago was that we'd have it commit either all the time or (more likely) when the user hits the "save" button, but then there'd be a way to annotate old revisions with things like whether the robot worked or not. I'd imagined the latter would work using annotated tags.
I'd probably keep the current mode available for those who want it, though perhaps not as the default.

**Comment by PeterJCLaw** [comment]
https://code.visualstudio.com/blogs/2019/05/02/remote-development is also interesting here.

**Comment by PeterJCLaw** [comment]
https://visualstudio.microsoft.com/services/visual-studio-online/ looks like it might be interesting here.

**Comment by trickeydan** [comment]
> [visualstudio.microsoft.com/services/visual-studio-online](https://visualstudio.microsoft.com/services/visual-studio-online/) looks like it might be interesting here.

This should definitely be considered when we get around to investigating this issue.

I particularly like how we can "register" self-hosted instances with their service at apparently [no cost](https://azure.microsoft.com/en-us/pricing/details/visual-studio-online/).

**Comment by PeterJCLaw** [comment]
So https://repl.it/ appears to have changed quite a bit since we last looked. It's now turning into an online collaborative IDE, rather than just REPLs in your browser.
Try out https://repl.it/repls/DeepMediumbluePhp#main.py

It also looks like it has version control, package installs, stepping debugger and databases. I've not poked very much so far, but it looks fairly awesome.
It's remarkably along the lines of what I think we'd hoped the "happiness" frontend for the SR "cyanide" backend might become, only, you know, actually complete and pretty good.

Shame it doesn't appear to be something we can self-host, which pretty much rules out putting it on the robots, meaning that it'd be online-only and likely wouldn't have as good integration with the robots as we'd like.

**Comment by PeterJCLaw** [comment]
https://github.com/ekzhang/rustpad looks potentially interesting.

**Comment by PeterJCLaw** [comment]
We have opted to not ship the IDE for the past couple of competition cycles (and once again aren't for SR2024) and teams seem to be ok with that. Given that that is where we're now at the question here would be not so much "alternative" as "offering as an additional". Much of the content here is likely still useful, however as there is no immediate impetus to add this offering I'm going to close this until such time as that changes.

The "other" solution we have thus chosen is "competitors run their own, on their own machines".
