### ISSUE TITLE
Update Website with event info

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#160]

**Comment by RealOrangeOne** [comment]
.. with what?

**Comment by Tyler-Ward** [comment]
Requires #79 and #193

**Comment by antoinepetty** [comment]
To complete at least a core version of this, I need info on:

- Food outlets (or any food-related arrangements)
- Parking information on site
- (Schedule if that is being planned on the hack day)

And any info you believe is missing from https://github.com/srobo/website/blob/competition-2019-details/_events/sr2019/competition.md

**Comment by RealOrangeOne** [comment]
- We'll most likely provide this on the day, just a brief guidelines
- In progress. Ship without it? (#193)
- TBC (https://github.com/srobo/tasks/issues/73)

**Comment by antoinepetty** [comment]
https://github.com/srobo/website/pull/132

**Comment by antoinepetty** [comment]
Closing this. Further updates will be related to #94
