### ISSUE TITLE
Plan Welcome Talk

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#163]

**Comment by RealOrangeOne** [comment]
I've got the notes and videos from previous years, so can use those to get something concise. 

Last years ran a little long, so I'll need to cut that down a little

**Comment by RealOrangeOne** [comment]
This is now in progress https://docs.google.com/document/d/1AGI5pcDmrkBAjjoFuOSj4PGZyipmhmTJEliEie9wnwU/edit#

**Comment by RealOrangeOne** [comment]
#73 accounts for 10 minutes for this talk, which will almost certainly run over. Some practice will be needed, and likely some cutting down.

**Comment by PeterJCLaw** [comment]
Nice, I've left some comments in the doc.

**Comment by Tyler-Ward** [comment]
This looks good to me
