### ISSUE TITLE
Purchase Wristbands

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#164]
depends on #91 

We need 500 wristbands, There's no standard supplier for this, but they need to be cheap and able to order custom embroidered cloth wristbands

**Comment by Tyler-Ward** [comment]
How many crimp tools will we need, they are £30 each. i believe @prophile said he already has one.

**Comment by trickeydan** [comment]
> How many crimp tools will we need, they are £30 each. i believe @prophile said he already has one.

@prophile did say that he had one. I suggest we order one more as well.

**Comment by mltnhm** [comment]
This has been done by @nathanp99

**Comment by Tyler-Ward** [comment]
We order the wrong amount as the ticket description was updated with the wrong number, this needs to be fixed with the supplier.

**Comment by Tyler-Ward** [comment]
@nathanp99 have you managed to contact the supplier?

**Comment by nathanp99** [comment]
I was able to amend the order to 500 for an extra £42. I will send the new invoice to Tyler's email I sent the other ones to.

**Comment by Tyler-Ward** [comment]
Thanks, much appreciated.
