### ISSUE TITLE
Arrange For Wristband Crimping Tool

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#165]
Assuming we are using wristbands, and assuming said wristbands require crimping, and assuming the world does not come to an end prior to the competition.

**Comment by prophile** [comment]
Usually the crimping tools come with the wristbands, but there is no need: I can provide one.

**Comment by Tyler-Ward** [comment]
just noticed that there is a separate ticket for this in #164 we have been working out how many crimp tools we need, given there are two receptions then getting 2 seems sensible. 
https://www.idcband.com/crimper/

**Comment by Tyler-Ward** [comment]
Ordered with the wristbands
