### ISSUE TITLE
Re-Evaluate Recurring Tasks

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#166]

**Comment by PeterJCLaw** [comment]
This is happening as part of https://github.com/srobo/competition-team-minutes/issues/107. I intend for us to use the https://github.com/srobo/recurring-tasks for SR2020 planning.

**Comment by PeterJCLaw** [comment]
This is now an ongoing task as part of setting up the tasks for each stage of the competition year. I don't think this is useful as a specific task.
