### ISSUE TITLE
Recruit volunteers for the competition

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#168]
Recruit volunteers and find out information to allow scheduling and hotel booking

**Comment by RealOrangeOne** [comment]
An email has gone out to the existing mailing list with a signup link.

**Comment by Adimote** [comment]
Yes the email has been sent, more effort can be put in here if needed, but for now we have enough people to run a competition, so this can be marked as done.

**Comment by trickeydan** [comment]
Isn't a final number of volunteers blocking on things like #151 and #80? @Adimote

**Comment by Adimote** [comment]
I don't think it's likely, we've never rejected volunteers because we have too many

**Comment by RealOrangeOne** [comment]
We don't reject volunteers, although we should ensure that the signup form is explicit that we can't offer accommodation
