### ISSUE TITLE
Create social media displays

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#170]
Create a social media display feed to show during the event, similar to ones used in tech days in the past.

**Comment by RealOrangeOne** [comment]
We've used https://github.com/realorangeone/srobo-techday at tech days in the past, although it could do with an update / re-skin

**Comment by mltnhm** [comment]
Do we want to show images?

**Comment by RealOrangeOne** [comment]
This is unlikely to happen this year, however if someone wants to pick this up, that's also fine :+1: Moving out of milestone

**Comment by mltnhm** [comment]
I spoke to someone while at [Evoke](https://evoke.eu) and they said they can send me their social media display. They did say it's hooked in heavily to something else but shouldn't be too much of a pain to rip apart or bring our own backend.

**Comment by mltnhm** [comment]
Currently in the process of emailing them about it.

**Comment by raccube** [comment]
I've changed my stance on this and don't really think this is worth the effort as it [would require moderation during the competition](https://www.youtube.com/watch?v=ROaj3bCpZEM).
