### ISSUE TITLE
Create live stream graphics

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#172]
Graphics will need to be designed for the live stream

**Comment by RealOrangeOne** [comment]
Can we reuse (and rebrand) the one used for Smallpeice 2018?

Also, that is this blocked on?

**Comment by Tyler-Ward** [comment]
we can mostly reuse the live stream overlay (https://github.com/sourcebots/livestream-overlay) but it will need re-branding and updating for more teams and we also need to create the other graphics e.g. overlay logos, and other material, it is blocked on knowing SUSUTV's requirements

**Comment by Tyler-Ward** [comment]
For info the licence for the livestream overlay has been sorted and is now in MIT.

**Comment by mltnhm** [comment]
Working on this in [mltnhm/livestream-overlay](/mltnhm/livestream-overlay)

Here is what that looks like at the moment:
![image](https://user-images.githubusercontent.com/6197148/55279244-42fc7680-530e-11e9-85f5-e16bda72470b.png)

**Comment by mltnhm** [comment]
Full overlay including scores:
![image](https://user-images.githubusercontent.com/6197148/55281211-0be78e80-5329-11e9-93a5-3c53b1e90ee9.png)

**Comment by PeterJCLaw** [comment]
@mltnhm nice :) Do you have an example of what it looks like with a real image behind it?
