### ISSUE TITLE
Find out what happened to the RCDs with UKpostbox

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#174]
we should find out the status of these, last commit on the inventory https://github.com/srobo/inventory/commit/8c1a7c2130a05af13036369052e023bd8dd01ccf has them as being marked for sale
```
Move last few bits to ukpostbox

The photo of the asset tag provided by ukpostbox was illegible. Now that
I've moved the rest of the boxes to my house it's clearly this one.

We also sent the RCDs to ukpostbox packaged up ready for selling.
```

**Comment by Tyler-Ward** [comment]
@richardbarlow might have some idea of what their status is

**Comment by richardbarlow** [comment]
They're still in UKPostBox. They can be shipped wherever necessary if you
give me an address and contact (email me directly with the details)

**Comment by PeterJCLaw** [comment]
We know what happened to them - https://github.com/srobo/tasks/issues/174#issuecomment-466645014.
