### ISSUE TITLE
Inform volunteers of these tasks and encourage them to take some of them on

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#176]
We need more volunteers to help with these tasks, we should tell them that they are here and help is needed with them.

**Comment by trickeydan** [comment]
I have informed some volunteers at the SRO meeting

**Comment by Adimote** [comment]
This was partially done by #180 but I won't mark this as done until I go through people's slack/emails and start a conversation about helping out.

**Comment by RealOrangeOne** [comment]
Volunteers have been informed about the tasks, that's the primary acceptance criteria of this issue, right? To me it seems we've completed this
