### ISSUE TITLE
Tag GitHub repos

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#178]
We should label the github repos to make searching them easier

**Comment by RealOrangeOne** [comment]
What do repository topics actually achieve for searching? They improve SEO slightly, but generally when you're looking for something, searching by the repo name is probably better. I _think_ the repo search also uses the descriptions, which would probably be a better use of time

**Comment by PeterJCLaw** [comment]
Thanks for raising! Since this was raised many of our repos have become tagged. I'm not sure it's worth exhaustively trying to tag them all as a single task -- rather allowing the tags to be added as we spot them is fine. Closing as this otherwise doesn't have a clear definition of completion.
