### ISSUE TITLE
Inform Volunteers of Hack Day

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#180]
We are going to have a Hack Day on the 2nd March. We need to tell volunteers.

**Comment by Tyler-Ward** [comment]
See https://github.com/srobo/volunteer-emails/pull/8 for email draft

**Comment by Adimote** [comment]
Email scheduled for 2019-02-24 10:00 GMT:
https://mailchi.mp/eb78175db43b/competition-preparation
