### ISSUE TITLE
Book Mountbatten Level 4 for Hack Day and Tech Day

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#181]
We should book 53/4025 for 2nd March and 9th March.

**Comment by trickeydan** [comment]
@Tyler-Ward Do you know the appropriate person to email for this?

**Comment by Tyler-Ward** [comment]
I believe you can book it at zepler reception.

**Comment by RealOrangeOne** [comment]
I doubt4025 will be used much, as we'll want to be in the same location teams are to assist them. That being said, we'll probably still need access to the room at some point during the day.

**Comment by trickeydan** [comment]
> I doubt4025 will be used much, as we'll want to be in the same location teams are to assist them. That being said, we'll probably still need access to the room at some point during the day.

**Hack Day** and Tech Day.

We will need cupboard access too.

**Comment by RealOrangeOne** [comment]
Sorry yes, my comment was primarily aimed towards the tech day portion. Should probably have made that clearer.

**Comment by trickeydan** [comment]
Both days have been booked.
