### ISSUE TITLE
Book van for transport

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#182]
A van needs to be booked to move kit from and to newbury.
Kit should be delivered to southampton on Wednesday/Thursday and taken back Sunday or Monday
see #78 for main logistics task

We probably have 2 car loads worth of things. We definitely need a van for the return trip though

Returning van needs to fir the remainder of the carpet roll, (4m long)

**Comment by prophile** [comment]
As an alternative, we could do this via pallet shipping rather than a van.

**Comment by RealOrangeOne** [comment]
We also need to account for someone to drive said van.

**Comment by Adimote** [comment]
We probably have 2 car loads worth of things. We definitely need a van for the return trip though

**Comment by PeterJCLaw** [comment]
Who is it planned would be driving this van?

**Comment by RealOrangeOne** [comment]
Currently unknown, although I suspect @prophile.

For bringing kit _to_ Southampton, I believe the rough plan is for me and @prophile to go to the container and fill our cars. 

For bringing kit _from_ the container, we'll need a van for this, and specifically someone with a license to drive one. I suspect that can be arranged closer to the time, i'm happy to do if possible.

**Comment by WillB97** [comment]
Blocked on finding a driver

**Comment by TomWheal** [comment]
I’m happy to drive if there’s budget for a driver under 24

**Comment by PeterJCLaw** [comment]
> Returning van needs to fir the remainder of the carpet roll, (4m long)

I'm not sure that this is viable -- I don't think that a 4m roll of carpet will fit in the container. We only have a half container, so it's about 2m × 2m × 2m. While we might be able to mostly fit it across the full diagonal, that would likely mean that we couldn't get anything else in.

We probably need to find another alternative for the carpet.

**Comment by RealOrangeOne** [comment]
I'll investigate our options for a van this evening

**Comment by RealOrangeOne** [comment]
Looking around, it looks as though Thrifty are the only place which will do van hire to <23 year olds, which is the majority of our volunteer base. I'm more than happy driving the van (actually, i'd quite like to!).

Unfortunately, there's quite a price delta between someone 22, and say 28.

Assuming a booking on the 8th for between 11:30 and 17:30, for a 22 year old is £59, vs someone 28 is £24. Being 28 also enables you to hire larger vehicles, 22 year olds are restricted to short wheel base vans or smaller. 

I recall some discussions about the fact the carpet may not even fit in the container, meaning the larger van may not be a requirement. Although that's probably a discussion for a different ticket.

I defer the final decision to @Tyler-Ward on the worth of this, but to me, ~£30 is basically nothing for something like this.

**Comment by RealOrangeOne** [comment]
I will drive this. Will book over the weekend.

**Comment by sedders123** [comment]
This is done
