### ISSUE TITLE
Check the container for things

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#183]
This ticket exists as a target for other tickets where we think that the items needed may be in storage. Just mention this ticket's ID in the other ticket and we'll use the list of referencing tickets when the container storage is actually visited.

This could well happen as part of moving the kit to Southampton (#78 / #182), though ideally would happen in advance of that to allow for time to purchase things which turn out not to be present.

"must have" because of the things which depend on this, rather than directly itself.

List of things based on the tickets referencing this issue:
- [ ] competition mode USB sticks
- [x] (tinker time) whiteboard
- [x] scoring stationery (clipboards, box files, pens)
- [x] display monitors
- [x] high vis jackets

**Comment by Tyler-Ward** [comment]
Is anyone planning on going via storage on the way to the hackday/next techday, not sure if anyone is passing closeish by.

**Comment by RealOrangeOne** [comment]
No, but we definitely need a trip up there in the not-too-distant future. There's a lot of tickets blocked on the state of whatever's in the container.

Do we know how to get access to the container? @prophile if I recall you got access in the past? 

@Tyler-Ward do we have the capacity to bring the contents to Southampton and keep it there? It seems unnecessary to get everything to Southampton just to send it back

**Comment by Tyler-Ward** [comment]
@RealOrangeOne we dont have room for everything we will need for the competition but we have room for some stuff e.g. stuff requiring testing/dev

**Comment by PeterJCLaw** [comment]
> Do we know how to get access to the container?

Yes. (I'm deliberately not putting much in the way of detail on a public forum, feel free to message me directly if you get to the point of planning a trip though).

**Comment by RealOrangeOne** [comment]
@prophile will arrange getting access to the container on the 9th March, and potentially bring things to Southampton to test if required.

**Comment by prophile** [comment]
There’s printing paper here

**Comment by prophile** [comment]
There are two hole punches and a printer power supply, and a tape measure, and pens in the FQ34

**Comment by prophile** [comment]
“That is a LOT of cable ties.” -Peter Law, 2019, on 1QJ2Q

**Comment by prophile** [comment]
Competition mode sticks MIA

**Comment by prophile** [comment]
Printer is in its box with a power supply.

**Comment by prophile** [comment]
Need to source a box file.

**Comment by Tyler-Ward** [comment]
> Printer is in its box with a power supply.

We have a printer, Is this SR's or one we borrowed and forgot to return? Also can we get the make/model and ink status of it.

**Comment by prophile** [comment]
It will need more ink. It’s an HP DeskJet 2130. It takes HP Original Ink
302 in standard CMYK
