### ISSUE TITLE
Plan finals tracks

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#184]
We generally use a bespoke cut of various songs for the finals tracks, to build tension, ensure the music is dramatic enough, and is timed perfectly, with starting of matches and timing.

Breaking this ticket out of https://github.com/srobo/tasks/issues/148.

Previous years playlists:
- Smallpeice 2018: https://open.spotify.com/user/theorangeone97/playlist/5VvONyDmSpdErqseA75Vad?si=U1adYZc-QryZErjZFaAxrg
- SourceBots 2018: https://open.spotify.com/user/theorangeone97/playlist/2mowt6maj0vhLUdrnCKtnw?si=AGzULOo7SFSn7o_eL6rY7g
- Smallpeice 2017: https://open.spotify.com/user/theorangeone97/playlist/4ZaS9NTwF1erqqpE1IxHlP?si=DKExkDEUR9KF__ZswCdicg

(This years playlist is still private, but available upon request)

**Comment by Tyler-Ward** [comment]
We should plan for this playlist to run to the start of the awards #128

**Comment by RealOrangeOne** [comment]
I'm not sure how useful that willl be. Unless we can get the time after competition down to the second, there may be music stopping and starting when we don't want it to. I suggest we just swap over to the dramatic playlist from #148 for the interim, perhaps dropping to a specially-defined song when we're ready to start it to create a short buildup

**Comment by Tyler-Ward** [comment]
We can still fade out of the sync music when we want to start the awards. the other option is the music just cutting off after the final. this just gives us a bit more music time after the final and we can select appropriate tracks for this point in time rather than it being random.

**Comment by prophile** [comment]
Planned and programmed although untested.

**Comment by sedders123** [comment]
This was done
