### ISSUE TITLE
Book Mountbatten L4 on Wednesday evening, Thursday and Monday morning for kit movement.

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#185]
required for #78

**Comment by trickeydan** [comment]
Booked: 5pm - 9pm Wednesday 3rd April

Unable to book at all on Thursday 4th April: Another event taking place 8am - 8pm
Booked 5pm - 8pm on Friday 5th April: Another event taking place 9am - 5pm

Booked All Day on 6th and 7th.
Monday: Seminar starting at 9am. Booked 8am - 9am.

**Comment by trickeydan** [comment]
Update: we have contacted Joyce Lewis as we believe that she is one of the bookings and we should be able to negotiate with her to move to a different location.

I'm also going to pin this task as it does currently require attention.

**Comment by trickeydan** [comment]
I have obtained a booking for Thursday 4th from 6pm onwards via Joyce.

**Comment by RealOrangeOne** [comment]
Is there an intermediary location we can move things on Wednesday evening? The only reason we need `53/4025` is because of the cupboard. If we can move things out of it before it's booked, then we remove the reliance on it.

Is there anywhere in SUSU we can move the stuff overnight. This would be a massive amount of work, but would solve our issue somewhat.

**Comment by trickeydan** [comment]
Update: Joyce has attempted to get the other meetings on Thursday moved, and has been unable to.

`59 / 1257 has been reserved for you, from 16:00 to 18:00 on Wed 03 Apr 2019.`

`59 / 1257 has been reserved for you, from 9:00 to 18:00 on Thu 04 Apr 2019.`

**Comment by trickeydan** [comment]
`59 / 1257 has been reserved for you, from 9:00 to 18:00 on Mon 08 Apr 2019.`

**Comment by RealOrangeOne** [comment]
There's a slight risk that we may have a new cupboard to return things to. It's unlikely, just something to bear in mind.
