### ISSUE TITLE
Update Media Consent forms

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#187]
The media consent form, found at https://git.studentrobotics.org/cgit/media-consent.git, still contains the old "Student Robot" branding (no, that's not a typo). This will need to be updated.

As this is a legal document, I shall pass a current iteration over to trustees to review the wording of, to ensure we're properly covered.

As the repo is currently on CGit, step 1 should definitely be moving it to GitHub.

**Comment by PeterJCLaw** [comment]
> Student Robot
:disappointed:

**Comment by PeterJCLaw** [comment]
The form builds on the logo in the `marketing` repo, so we'll need to migrate that repo too.

**Comment by RealOrangeOne** [comment]
agreed. I'll migrate those over today. Although both repos are currently unlicensed, which might have some ramifications. @PeterJCLaw as you've done a lot of license stuff recently, and idea what the process is here?

**Comment by RealOrangeOne** [comment]
I've now had the first round of feedback from trustees on this, and will make the amendments and updates over the weekend.

**Comment by PeterJCLaw** [comment]
I'm in the process of sorting the license for the `marketing` repo (i.e: I've emailed the contributors, not had replies from all yet).

The "process" I've been following is to:
 1. pick a suitable license
 2. email the contributors (`git shortlog --summary --email` is useful for this), asking if they'd be happy with that license
 3. if needed, attempt to resolve any discrepancies in their responses by asking nicely and/or suggesting alternative licenses they might be happier with (repeat until everyone agrees)
 4. add the license, being sure to mention in the commit message that I've had agreement from each of the contributors (see https://github.com/srobo/kit-maintenance-docs/pull/7/commits/a8e784c5ca302791b22f51c3c7808ecd84b2f7ae for an example)

I have generally also asked whether the contributors would be happy with the given license for their contributions over a wide range of repos in one go, typically also asking if I can use the same license for other SR repos. Generally the responses to this are favourable.
I have now had responses from a bunch of people about licensing things, so if you let me know which repos you're interested in I may be in a position to just add a license based on the responses I've already had. (I've been meaning to do this anyway, but not yet had time)

**Comment by RealOrangeOne** [comment]
I've looked at the existing repo, and there's 6 contributors, 1 of which is you, @PeterJCLaw. I've DMd you on Slack in an attempt to resolve a license. 

Once the license is resolved, i'll migrate the repository to GitHub, and start working on updating the document.

**Comment by RealOrangeOne** [comment]
I've now sent an email to the existing contributors, and am awaiting a response. 

In the mean time, I've opened a PR with the required changes at https://github.com/srobo/media-consent/pull/1

**Comment by RealOrangeOne** [comment]
The forms have now been sent to the trustees for approval. As it's a legal document, we shouldn't ship it until they're happy with it.

**Comment by RealOrangeOne** [comment]
The trustees have approved the changes, with the amendment that the age be lowered to 16, which matches research.

This also reduces the chance of needing to handle someone who hasn't given media consent, which is great!

**Comment by PeterJCLaw** [comment]
Remaining tasks:
- [ ] put the details of how to do this on the website
- [ ] put a copy of of the form on the website
- [ ] email the teams about the process

**Comment by RealOrangeOne** [comment]
This has now shipped.
