### ISSUE TITLE
Arrange for overhead arena view camera

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#188]
we typical have a gopro rigged above the arena it would be nice if we can do this again.

**Comment by PeterJCLaw** [comment]
Do we have a general ticket or docs for assembling the truss? If so, this probably makes sense as part of that rather than a specific task (I doubt we're going to be ticking off tasks as we go on the setup day). If not, would it make sense to create that?

**Comment by Tyler-Ward** [comment]
This ticket is for acquiring the camera and mounting hardware for the camera rather than the mounting of it itself

**Comment by mltnhm** [comment]
I have a GoPro I could use

**Comment by mltnhm** [comment]
Complete with mounting hardware!
![img_20190303_140136](https://user-images.githubusercontent.com/6197148/53696291-6b4f8e80-3dbd-11e9-98f4-2fe1d73d69cb.jpg)
![img_20190303_140156](https://user-images.githubusercontent.com/6197148/53696293-6d195200-3dbd-11e9-9f8f-083ee5d92dd0.jpg)

**Comment by Tyler-Ward** [comment]
We will need to mount this to a 50mm horizontal curricular pole with the camera pointing down so not sure how well that mount will work for that. might need some sort of intermediate adapter. I expect that susu will have the bar clamps if we need them and can get a mount with an M10 bolt hole, (@WillB97 does that size sound right to you?)
 
Also just to check does that version of the gopro have HDMI out?

**Comment by mltnhm** [comment]
It's USB-C so it might carry video

**Comment by WillB97** [comment]
The easiest way is to have a small tri/monopod attached to the go-pro which can then be taped to the truss.
It'll also need the cables to adapt it to HDMI for us to get the video off the truss.

**Comment by RealOrangeOne** [comment]
I have a camera we can certainly try for this. It supports video output over micro-HDMI, and charging over mini USB. I suspect a mixture of the provided mounting and duct tape can affix to the truss. 

I recall something about it not running quite properly recording whilst charging. I will test this and report back.

Meta: Looks like the company which sold it originally has stopped trading, which sucks http://www.replayxd.com/

**Comment by RealOrangeOne** [comment]
I've now tested this camera, and after finding the "remember power state after power cycle" option, it's working just as we need it. It comes on and outputs over the builtin HDMI port (1080p60) once powered, and shuts down shortly after power is lost (once the builtin battery is drained).

We can also use the mobile app from my phone to configure things if necessary.

Things we need which I don't have access to:

- HDMI capture interface of some sorts
- A way of getting a USB cable onto the truss (I've got a mini USB cable, but it's only ~1ft)
- Some way of getting the micro HDMI signal to said capture interface (I've got a 2m micro HDMI cable which can be used)

@Tyler-Ward What have we used in the past for this, and can we get access to it again? Do SUSU / SUSUtv have kit we can use?

**Comment by Tyler-Ward** [comment]
In the past we charge the camera from the truss there is plenty of power up there.
For hdmi capture we plugged the output into the ATEM mixer directly.
For getting the video from the truss we used SUSU's SDI converters and preview monitors.

**Comment by RealOrangeOne** [comment]
In that case, I believe this ticket is resolved. If we have access to the above kit (which it sounds like we do), then we're done!

**Comment by Tyler-Ward** [comment]
we still need to acquire the truss mounting hardware unless you already have that.

**Comment by RealOrangeOne** [comment]
The only mounting the camera comes with is to a flat surface, and it doesn't support the go-pro adapters. I suspect a generous application of duct tape will handle this nicely, mounting it to a vertical bar in the truss, especially considering the camera is cylindrical.

**Comment by WillB97** [comment]
For later reference:
There are currently 4 13A sockets in the center of the truss so a mains USB adapter will be needed.

> For getting the video from the truss we used SUSU's SDI converters and preview monitors.

Last year the video was run off the truss on HDMI so the SDI converters are only needed if we need to transport the signal beyond the balcony.

> For hdmi capture we plugged the output into the ATEM mixer directly.

There was an issue last year as the ATEMs are clocked for SUSUtv's 1080i50 feeds so a computer with the blackmagic USB capture card is needed to reclock the camera feed.

**Comment by RealOrangeOne** [comment]
I believe I can get the camera to output `1080i60` if that's of more help (I doubt it), if not we can mess around with it on the day

**Comment by PeterJCLaw** [comment]
> There are currently 4 13A sockets in the center of the truss so a mains USB adapter will be needed.

I have several mains USB adapters; I'm sure one can be used for this.

**Comment by RealOrangeOne** [comment]
I believe this is now sorted. Assuming we have access to the cabling and SUSU equipment.
