### ISSUE TITLE
Book university estates to move kit

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#189]
Book estates to move kit to cube, required as part of #78

**Comment by RealOrangeOne** [comment]
The times required for this may have changed, see https://github.com/srobo/tasks/issues/185

**Comment by Tyler-Ward** [comment]
This needs to be booked soon otherwise we wont get it.

**Comment by RealOrangeOne** [comment]
Jack Williamson will handle this

**Comment by jcwilliamson** [comment]
What days and times should I ask for, both for the move there from mountbatten, and the move back?

**Comment by RealOrangeOne** [comment]
I _believe_ we need it Friday morning from L1 Zepler to SUSU. I know we'll need it Sunday / Monday at some point, but not sure that's been worked out yet. 

(I wouldn't book based on this comment, it's possible I've missed a bit of information)

**Comment by Tyler-Ward** [comment]
Estates need to move kit on Thursday morning from the zepler CLS room to the cube and then back on the Monday morning to a location(not sure where this is @trickeydan will know).

Estates will need to move.
Lengths of wood probably around 50 or so.
hardboard sheets probably around 20-30
Boxes of kit probably around 40 or so.

**Comment by trickeydan** [comment]
>  back on the Monday morning to a location(not sure where this is @trickeydan will know).

Zepler Level 1 Seminar Room

**Comment by jcwilliamson** [comment]
Joyce is now on the case, she's sending me an email to confirm when she's done it

**Comment by trickeydan** [comment]
Apparently there have been issues with this. Undergrads are not allowed to book estates as expected.

Joyce is fighting this for us. I am unsure how successful she'll be.

Alternatives:

- [Office Removal Company](http://mastermoversremovals.co.uk/man-and-van-southampton/)
- ~Burn out volunteers~
- Move things in cars

**Comment by RealOrangeOne** [comment]
> - ~Burn out volunteers~
> - Move things in cars

I don't think suggesting volunteers do this by hand is useful, nor burnout. If we're using volunteers, we'll be using cars, trolleys, and anything else we can get our hands on, which may also include a van from #182, depending on when that happens.

If we can't get university estates, it might also be useful to look into how possible it would be to move things directly from `53/4025` to SUSU on Wednesday evening, as that will reduce the number of things we need to do  / move on Thursday, hopefully lightening the load on volunteers. 

Another alternative, which will take some creativity, but is quite possible, is taxis. Most taxis charge for distance, which for us is incredibly low, so getting an 8-person minibus type vehicle, packing it up with _luggage_ would get us things moved quite quickly. Although obviously that requires budget, and should really be a last resort.

**Comment by Tyler-Ward** [comment]
We don't have access to SUSU before Thursday morning.

**Comment by TomWheal** [comment]
Hiring a university mini bus is an option as well, I should be allowed to hire one by the competition

**Comment by Tyler-Ward** [comment]
@jcwilliamson I believe this has been sorted now can you confirm.

**Comment by jcwilliamson** [comment]
Joyce has now booked this for us, I forwarded her reply to the coreteam

**Comment by RealOrangeOne** [comment]
Copying in booking reference for, well, reference: 

REFERENCE: | 956575.01
-- | --
DESCRIPTION: | 4/4/19 & 8/4/19
GROUP/TRADE: | DLO-F.02 Portering
PRIORITY | Routine - 1 week
RELATED BUILDING: | 0059 New Zepler
RELATED SPACE: | 1257 Seminar Room 1
LOCATION TEXT: | seminar space in use as storage facility
REQUEST DATE: | 19/03/2019 17:06


I think we can consider this complete!
