### ISSUE TITLE
Upgrade the SR kit software stack to Python 3

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#19]
We need to do this before SR2020 in order that competitors aren't faced with using a version of Python which isn't supported at all. This task replaces https://github.com/srobo/core-team-minutes/issues/34.

We need to explore how we should do this. The following are some possible ways forwards (there may be others):
* Just update the existing stack
* Write a new stack
* Adapt a different stack (for example SourceBots' [robot-api](https://github.com/sourcebots/robot-api))

Known issues:
* Upgrading [likoki](https://www.studentrobotics.org/cgit/libkoki.git) integration (specifically [pykoki](https://www.studentrobotics.org/cgit/pykoki.git)) to Python 3 may involve changing versions of OpenCV (from 2 to 3), yet OpenCV 3 doesn't yet have good Python bindings (see https://github.com/srobo/core-team-minutes/issues/34#issuecomment-425716080 and later comments there)

**Comment by trickeydan** [comment]
-> [`j5`](https://github.com/j5api/j5)

**Comment by trickeydan** [comment]
> This is likely infeasible to do before Kickstart for SR2020, especially since the timescale for kit testing and packing is already quite tight.

[Source](https://github.com/srobo/kit-team-minutes/blob/master/2019/meeting-2019-09-03.md)

**Comment by RealOrangeOne** [comment]
For the sake of compatibility, I really think we shouldn't ship this part way through the year.

Opt-in _might_ work, although we'd need to make sure it's a plain python upgrade rather than providing any other benefits.

**Comment by trickeydan** [comment]
> For the sake of compatibility, I really think we shouldn't ship this part way through the year.
> 
> Opt-in _might_ work, although we'd need to make sure it's a plain python upgrade rather than providing any other benefits.

The plan was opt in to an otherwise identical (from a student perspective) stack. Alternatively we could wait until next year. The exact software that we use has yet to be determined, and the kit team will likely run an investigation into possible stacks after we've properly formed.
