### ISSUE TITLE
Check Odroids 1HH7W and 1ML7J have their proper cases

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#190]
According to https://bitbucket.org/richardbarlow/sr-hw-prod-coord/wiki/SR2018_Kit_Collation_Plan they had their cases swapped.

I recall spotting that previously, but I can't remember whether we fixed it at the kit collation/packing events this year.

According to the inventory, [1HH7W](https://github.com/srobo/inventory/blob/ce7a68e3827434057342743314dda87a0bf010c1/southampton/broomcupboard/broken/box-18l-rub-srFK39/odroid-u3-sr1HH7W) is in the broomcupboard. Checking whether it has the proper case on it would be mildly useful.

**Comment by RealOrangeOne** [comment]
We've found `1ML7J`, which has the correct case with it. `1HH7W` doesn't seem to be in the cupboard.

**Comment by PeterJCLaw** [comment]
That's odd. 1ML7J should be in storage!

**Comment by PeterJCLaw** [comment]
Whichever way around. If you've found one of them with the correct case on it, then I suspect we did indeed fix the case issue already. All other issues can be handled separately.

**Comment by PeterJCLaw** [comment]
Thanks for looking at this @RealOrangeOne

**Comment by RealOrangeOne** [comment]
`1HH7W` is also in the broomcupboard, in the RUB it was expected to be in.
