### ISSUE TITLE
Identify car parking locations and produce maps/details

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#193]
we need information for competitors on where to park

**Comment by RealOrangeOne** [comment]
This information should also be distributed to volunteers

**Comment by sedders123** [comment]
Chatted with @Tyler-Ward to produce:
 - A map displaying car parks, entrances to car park, entrance to the cube
 - Written instructions for the 'last mile' of the journey (from Junctions on motorway and from train station)

**Comment by sedders123** [comment]
I'm not a designer but I think this conveys the information.
![highfield_campus_parking](https://user-images.githubusercontent.com/1496834/53685331-0179ab00-3d11-11e9-98f3-1b2b691191bd.png)

**Comment by PeterJCLaw** [comment]
@sedders123 nice :) Maybe use something more positive for the parking entrances? (The cross implies that they're somehow not allowed, which clearly isn't what you're trying to convey)

**Comment by sedders123** [comment]
:+1: Yeah I can see that issue. I was thinking 'x marks the spot'. Any suggestions for alternative symbols? Can't think of anything immediately, so might just go with a green circle.

**Comment by PeterJCLaw** [comment]
I'd been wondering about using a symbol of a car somewhere, but I'm not sure that would be easily legible or particularly clear. Green circles sound good to me.

**Comment by sedders123** [comment]
Have made the change and will upload this evening (its on my home PC). Just had a thought, will we need to acquire permits for parking, or is it free during holidays?

**Comment by RealOrangeOne** [comment]
Parking in these car parks should be free from the requirement of both permits and money.

**Comment by TomWheal** [comment]
Can confirm that at weekends all parking on campus is free.

**Comment by sedders123** [comment]
Map with updated parking entrance icons
![highfield_campus_parking](https://user-images.githubusercontent.com/1496834/53769380-a17f3200-3ed3-11e9-8bcc-1c0a39c13b13.png)

**Comment by PeterJCLaw** [comment]
Nice one. I'm closing this as that map is great and we're about to ship it on the website.
