### ISSUE TITLE
Plan edible prizes

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#194]
For the online presence and first robot movement awards.

**Comment by PeterJCLaw** [comment]
We promise these prizes in the rules, which makes them a must-have.

**Comment by trickeydan** [comment]
We shipped [these](https://www.amazon.co.uk/-/dp/B00JWNOR0K/) for SourceBots I believe.

**Comment by RealOrangeOne** [comment]
The plan is to purchase the prizes the week before the competition, when we will know exactly how many we need.

**Comment by Tyler-Ward** [comment]
needs bugget approval first

**Comment by Tyler-Ward** [comment]
Now i can start approving budget this is mostly just needs for us to work out which prizes come with edible components and how many to provide, then we can price up some mixed chocolate boxes from the supermarket

**Comment by Tyler-Ward** [comment]
We have 8 prizes each will want two tall chocolate containers. these come to around £3 each this comes at £50 ish.

**Comment by PeterJCLaw** [comment]
We have _two_ awards which are specified as being edible, not eight; we've not historically done edible prizes for the awards which have an actual prize and I'm not sure what doing so adds?

**Comment by Tyler-Ward** [comment]
Useful to know that that is in the rules. we can ditch them per the rules however as mentioned on slack if we just give the glass trophy to the top prizes then the students themselves wont have anything. While not amazing for this giving edible prizes to all teams means there is at least something there. opinions on what we should do about this?

**Comment by RealOrangeOne** [comment]
We can get 1 tub of assorted chocolates for ~£3 (src: Amazon, Sainsbury's), which have enough for ~2 people. The average team size is 8 people, therefore it's roughly £20 per team we want to get prizes for.

2 prizes: ~£40
8 prizes: ~£160

If we have the budget, I think it would be _nice_ to give a prize like this, although it's a sizable amount of money. 

If we can get approval on one of the above budget lines, we can close this and move the relevant details to #130.

**Comment by RealOrangeOne** [comment]
As discussed in person, we shall purchase 2 prizes for this, and extend on the setup days if for whatever reason we find a need to.

Just awaiting budget approval from @Tyler-Ward

**Comment by RealOrangeOne** [comment]
Nice, i'll purchase prizes later this week.

**Comment by RealOrangeOne** [comment]
We have https://github.com/srobo/tasks/issues/130 to track the purchase of these. Therefore, as we have a plan, this ticket can be closed.
