### ISSUE TITLE
Obtain radios

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#196]
From #149 

- [ ] HIre SUSU radios
- [ ] Hire additional radios externally

Current estimates are around £7 per radio when hiring externally.

Radios needed: https://github.com/srobo/tasks/issues/149#issuecomment-468937167

**Comment by trickeydan** [comment]
Quote requested from Delta V.

**Comment by trickeydan** [comment]
These will cost us nothing.

Obtained:
```
    12 x Baofeng BF888S - Pre-programmed for UK General Business usage
    12 x Baofeng BF888S Charger
    Use of our UK General Business Licence
```

>For hygiene reasons, we do not offer earpeices with the radios.  We understand this may come as a disappointment, however, such items are cheaply, and readily available online.
> While we would expect the BF888S to be compatible with the SUSU tech team radios, we cannot guarantee this at this point in time, not knowing the model or channels of their kit.

Added to #200 to tick off on comp day.

**Comment by RealOrangeOne** [comment]
This ticket is to obtain the radios, so technically it's not complete. Although it is an outlier in our patterns, so It's definitely better to rename the issue "Order radios", and leave it closed.

**Comment by PeterJCLaw** [comment]
Can we do something ahead of time to ensure that the radios we're getting from Delta V are compatible with those we're getting from SUSU? If not, what's our fallback for the scenario where they're not compatible?

**Comment by trickeydan** [comment]
Also obtained SUSU radios to be clear.

> Can we do something ahead of time to ensure that the radios we're getting from Delta V are compatible with those we're getting from SUSU? If not, what's our fallback for the scenario where they're not compatible?

Not really. However it doesn't matter as we plan to use the SUSU radios for the Shepherd net, and the head shepherd will have a radio for both nets so can relay messages between if necessary.

**Comment by PeterJCLaw** [comment]
Aha, that's fine. Just to check then: do we have enough radios to allow the head shepherd to have one of each?

**Comment by trickeydan** [comment]
> do we have enough radios to allow the head shepherd to have one of each?

Yeah, we have plenty.
