### ISSUE TITLE
Plan team photos

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#198]
It would be great to have photos of each of the teams as a memento for them to take home as well as for our own media.

It might be nice if we had custom photo-frames to put around these (#90).

SourceBots have a pair of studio flashes we can use but will need to find a camera and a backdrop.
we also need to plan how it will work during the weekend.

If you're looking for the whole-group photo, see #120.

**Comment by RealOrangeOne** [comment]
1 thing I think it would be worth doing is allowing teams to just turn up and use it as a backdrop for their own photos, without using our camera equipment.

**Comment by Tyler-Ward** [comment]
Drape for the backdrop has been added to the SUSU kit list

**Comment by PeterJCLaw** [comment]
This has been included in the volunteer schedules, we know roughly how and where it's going to happen and have a backdrop planned. What's more to do here, or is this done?

**Comment by Adimote** [comment]
I'll write some basic instructions on how to handle photography, then I'll call it done.
