### ISSUE TITLE
Await delivery of items

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#200]
This ticket is a list of things that are awaiting delivery to ensure we get what we ordered, This is separate from the budget tracking as this info wants to be more open than the budget.

### To SUSU
- [x] Buisness cards
- [x] Tokens
- [x] Tablecloths
- [x] Trophies
- [x] Barcode scanners
- [x] Chairs and tables (on setup day)
- [x] Radios (on setup day)
- [x] Paper Cups
- [x] Plastic Cups
- [x] Tape
- [x] Scaff (on setup day)
- [x] Folding Tables
- [x] G-Clamps
- [x] sandwiches (on setup day)
- [x] HDMI to VGA adapters
- [x] Stanley Knives

### To volunteers
- [x] Wristbands
- [x] Wristband crimper
- [x] Banner
- [x] Incident book
- [x] Box files and Document wallets (#232)
- [x] Flyers and Booklets

### Collection
- [x] Tshirts
- [x] Testing kit
- [x] Kettle

**Comment by kierdavis** [comment]
This issue feels like it will get out of date very easily. Is this not better tracked on the corresponding issues for ordering each item? Perhaps we could label the issues as "awaiting delivery" or tag this issue in a comment in order to collate them.

**Comment by Tyler-Ward** [comment]
Business cards have arrived

**Comment by TomWheal** [comment]
Shirts are in my possession

**Comment by trickeydan** [comment]
If we are going to track things on this ticket (which I personally dislike as it's fragmented), please could we link the appropriate issue numbers.

**Comment by sedders123** [comment]
According to carrier text messages both plastic and paper cups should now have been delivered to SUSU.

**Comment by Tyler-Ward** [comment]
They have (it turns out 2000 cups are quite large) also trophies are here, checked one and it looks good, probably worth checking the rest this weekend.

**Comment by TomWheal** [comment]
Banner is Here

**Comment by Tyler-Ward** [comment]
@nathanp99 have the wristbands arrived yet?

**Comment by Tyler-Ward** [comment]
I have been informed that the wristbands have arrived however the crimp tool is missing which will be chased up.

**Comment by Tyler-Ward** [comment]
An update, the missing crimper will be hopefully be delivered tomorrow.

**Comment by sedders123** [comment]
Got an email saying tape has been signed for

**Comment by nathanp99** [comment]
Got an email saying Crimper delivered and signed for

**Comment by Tyler-Ward** [comment]
Everything arrived
