### ISSUE TITLE
Get uni prospectuses/swag for giving out at the competition.

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#202]
we should get some ECS prospectuses for any interested competitors at the competition.

**Comment by antonnikitin97** [comment]
I can speak to Reena about this and obtaining taster sessions.

**Comment by PeterJCLaw** [comment]
@antonnikitin97 please could you clarify what you mean by "taster sessions"?

**Comment by trickeydan** [comment]
> @antonnikitin97 please could you clarify what you mean by "taster sessions"?

He means leaflets apparently :roll_eyes:

**Comment by antonnikitin97** [comment]
> > @antonnikitin97 please could you clarify what you mean by "taster sessions"?
> 
> He means leaflets apparently 🙄

My apologies, I will endeavour to be less ambiguous in the future :)

**Comment by prophile** [comment]
wontfix due to lack of time
