### ISSUE TITLE
Purchase tokens

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#203]
https://github.com/srobo/tasks/issues/105#issuecomment-470274310 notes suppliers.

**Comment by Tyler-Ward** [comment]
If someone is able to order these that would be good, The best deal looked to be from kite packaging and should be around £16 as long as it is close to this that is fine to order. Make sure to post here before ordering so we don't do it twice.

**Comment by Tyler-Ward** [comment]
I will order these

**Comment by Tyler-Ward** [comment]
These have been ordered see #200 for status

**Comment by PeterJCLaw** [comment]
For reference, how many tokens of each type did we get in the end?

**Comment by Tyler-Ward** [comment]
75 have been ordered
