### ISSUE TITLE
Hire chairs + tables

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#204]
SUSU dont have enougth #67 so we should order some more. SUSU recomend http://www.wessexcaterhire.co.uk/

**Comment by Tyler-Ward** [comment]
I have requested a quote for this.

**Comment by Adimote** [comment]
Thyler!

**Comment by Tyler-Ward** [comment]
I have a quote back at £519 inc vat and delivery/collection which is more than we budgeted but is still affordable.

**Comment by Tyler-Ward** [comment]
I got some other quotes for comparison: 
* alenshire.co.uk £575.40 without delivery
* eventhireuk £1406 inc vat and delivery
* furnaturehireuk £831.67 inc vat and delivery

**Comment by Tyler-Ward** [comment]
Given the suggested supplier by SUSU is cheaper than the alternatives I will pass the quote to the trustees to be paid.

**Comment by Tyler-Ward** [comment]
Deposit has been paid, will confirm remaining details with the supplier then this can be closed

**Comment by Tyler-Ward** [comment]
Supplier has confirmed remainder of the invoice needs to be paid prior to the event but otherwise we are done here, await deliver in #200
