### ISSUE TITLE
Create list of equipment to move from storage to Southampton

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#205]
Split off from #78 we need a list of items to move from the container to Southampton for the competition.
Also see #206 for movement on setup days

A list of inventory codes would be useful but not essential as this is an easy way to check that everything has been collected.

**Comment by Tyler-Ward** [comment]
Also see #182 for van hire for this trip if required

**Comment by PeterJCLaw** [comment]
(renaming from "kit" to "equipment" to disambiguate vs team kits)

**Comment by PeterJCLaw** [comment]
Here's the list:
- everything in the first two columns of RUBs on the right as you go into the container
- check the third column too, but I think that's history stuff
- check the column in the next bank, but I'm pretty sure that's history stuff too
- most of the stuff on the left on the floor of the container (various bags & boxes), notably:
  - the printer (though that might have already been moved before this trip happens)
  - the boxes of tape
- the whiteboard
- the board with screws in for use in the staging area (in the middle at the back, next to the arena pieces)
- the cubes of judgement (they're at the back on top of the arena pieces)
- the box of pipe-covering foam for covering the scaff (it's on top of the RUBs on the right)

Things we don't need:
- anything labelled v3 or history
- the wooden arena pieces
- the old banner (I assume)
- the networking kit

**Comment by Tyler-Ward** [comment]
That looks good to me, I have updated the freight list with the kit listed above that is not already there.
Probably worth checking the new kit boxes as there will be a couple of un useful boxes e.g. tablets and tablet chargers which i think were sent to the container.

**Comment by PeterJCLaw** [comment]
Good point on the tablets -- not much point having them. The tablet chargers could be useful as backup power supplies for the Pis though.

**Comment by WillB97** [comment]
This was sorted in https://docs.google.com/spreadsheets/d/13jDdRkZxgKdROVau9VaZiKZbiDV34_rlcZhWcpzQZO8/edit#gid=0
