### ISSUE TITLE
Move equipment from storage to southampton

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#206]
We need to move equipment from storage to Southampton. see https://github.com/srobo/tasks/issues/205#issuecomment-476893864 for the list to move.

**Comment by PeterJCLaw** [comment]
(renaming from "kit" to "equipment" to disambiguate vs team kits)

**Comment by RealOrangeOne** [comment]
I believe there was an early-stages plan for me and @prophile to drive to the container to do this first thing Thursday. I don't know whether that is still the plan, although i'm still happy to help.

**Comment by RealOrangeOne** [comment]
This has happened.
