### ISSUE TITLE
Create list of equipment to move from broomcupboard to competition

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#207]
Split off from #78 we need a list of items to move from the broomcupboard to the competition.
As per #185 we need to move this down to L1 on Wednesday evening and will be moved as a result of #189 

A list of inventory codes would be useful but not essential as this is an easy way to check that everything has been collected.

**Comment by WillB97** [comment]
This was sorted in https://docs.google.com/spreadsheets/d/13jDdRkZxgKdROVau9VaZiKZbiDV34_rlcZhWcpzQZO8/edit#gid=0
