### ISSUE TITLE
Create list of return destinations for kit.

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#208]
Split off from #78 we need a plan of where to return kit to after the competition. main destinations are the broom cupboard and storage however some items might be going elsewhere.

**Comment by RealOrangeOne** [comment]
We can base these lists off #207 and #205

**Comment by WillB97** [comment]
This was sorted in https://docs.google.com/spreadsheets/d/13jDdRkZxgKdROVau9VaZiKZbiDV34_rlcZhWcpzQZO8/edit#gid=0
