### ISSUE TITLE
Invite important people

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#212]
- Important Uni People
- Local MPs
etc

**Comment by TomWheal** [comment]
Unsure if UKESF is on this list but they would be worth inviting

**Comment by jcwilliamson** [comment]
A representative from power academy might be worth investigating also.

**Comment by RealOrangeOne** [comment]
This ticket is closely related to #126, I don't know if the distinction warrants a separate ticket?

**Comment by trickeydan** [comment]
> This ticket is closely related to #126, I don't know if the distinction warrants a separate ticket?

Press /= Important People within Uni, e.g Joyce, Bashir, Paul Lewin, Denis

**Comment by RealOrangeOne** [comment]
> Press /= Important People within Uni

I have no idea what this means?

**Comment by jcwilliamson** [comment]
I'd agree with Dan here, the process for getting external organizations to attend is likely to be significantly different to the one for getting (predominantly) internal individuals.

**Comment by RealOrangeOne** [comment]
I agree. If the differentiating factor is inviting internal vs external entities (people, companies, whatever), then that should be reflected in the ticket title, and the contents of the ticket aligned as such.

**Comment by Tyler-Ward** [comment]
I have created a list here (limited to core team as it is a list of names for people we should invite)
https://docs.google.com/spreadsheets/d/1faw3Y4TBb83AJrHGqhpXpTMVQ4dfjthAheO_G0lMLu8/edit#gid=0

**Comment by trickeydan** [comment]
It is too late to do anything about this now, so the people who have been invited will have to do.

- @mildlyincompetent

**Comment by jcwilliamson** [comment]
I invited everybody on the list that was given to me.
