### ISSUE TITLE
Plan how we will do overnight loans of batteries etc. at the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#213]
Some teams will want to have a battery or two, possibly plus a charger overnight at the competition.

We need to have a way to allow this while also keeping track of who has taken this up.
We probably _don't_ want this to be in the inventory as that could be overly complicated.

See also #121 (battery charging) #122 (helpdesk) #186 (extended kit loans).

**Comment by RealOrangeOne** [comment]
As #121 and #122 are being handled by @trickeydan, it makes sense to assign as such.

**Comment by trickeydan** [comment]
@Adimote

**Comment by RealOrangeOne** [comment]
> trickeydan removed their assignment
> @Adimote

Context?

**Comment by Adimote** [comment]
We decided last meeting to avoid assigning to people in Soton because they're very burnt out

**Comment by PeterJCLaw** [comment]
@RealOrangeOne perhaps you or @Scarzy could look at this (since you're handling semi-related things)?

**Comment by RealOrangeOne** [comment]
Yeah I can take this, and word it into https://github.com/srobo/runbook/pull/16

**Comment by RealOrangeOne** [comment]
https://github.com/srobo/kit-coordination-documents/pull/6 has now merged, so we can consider this solved
