### ISSUE TITLE
Arrange in-venue colour printing capability

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#214]
We're going to want to be able to print various things in the venue at very short notice. We almost certainly need direct access to a printer.

Examples:
* Assuming that the shepherding will work like it has in the past, we're going to want to be able to print updated shepherding sheets (these need to be colour printed)
* We often end up wanting to print more maps too

We do own a printer. I'm not sure if it's in the inventory, but it is [in the container](https://github.com/srobo/tasks/issues/183#issuecomment-471165736). It will almost certainly need fresh [ink cartridges](https://www.amazon.co.uk/HP-Tri-color-Original-Cartridges-X4D37AE/dp/B01LXLFF6H), not least because I expect that they will have perished as a result of spending a couple of years in storage.

If we do want to use our printer then it'll need brining to Southampton (#205, #206).

**Comment by RealOrangeOne** [comment]
Needs budget signoff for purchasing cartridges.

**Comment by trickeydan** [comment]
There is on-site printing at the university.

Using our printer is more expensive than this. See https://github.com/srobo/tasks/issues/110#issuecomment-473592515

It is significantly easier to send a volunteer to the printer in B40 (literally next door).

**Comment by PeterJCLaw** [comment]
For context: we need a sub-minute turnaround on the shepherding sheets as the time between the end of the previous knockout round and the start of the next one is very short.

What's the level of effort required to use the printer in B40, and how long will it take between rendering the pages to print and having the paper in your hands?

This task is about having _direct_ access to a colour printer. Finding someone with university print access, having them find their laptop, sending them the files, them going next door, interfacing with an authorisation mechanism on a printer and then coming back doesn't seem very direct to me.

A possible speed-up would be to have a uni-print-enabled person stationed at a laptop next to comp-ops permanently and having a third person who is already at the printer and able to bring the paperwork back. This doesn't feel very efficient to me in terms of our resources and seems likely to be a spectacularly dull role for those two volunteers to be stuck with.

I fully expect the printer to be in working condition, though as noted it's almost certainly going to need new ink cartridges.

Given the amounts we're looking at spending on lunch for volunteers (something we don't normally do at all), I'm pretty sure we can afford some ink cartridges.

**Comment by jcwilliamson** [comment]
There is also a university printer at the top of the stairs behind the desk, that might be an option if we ask susu.

**Comment by trickeydan** [comment]
University printers do colour printing...

**Comment by trickeydan** [comment]
Blocked on #216 if you wish to use that printer

**Comment by Tyler-Ward** [comment]
Ink for this has been purchased and can be returned if the printer is broken. cost £31.99

**Comment by trickeydan** [comment]
Moving this to be a setup day task, as this will involve getting and testing the printer.
