### ISSUE TITLE
Unite Peter with the Pis

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#215]
The Pis which we're going to use for the display screens (#76, #96) and compbox (#118) need to make their way to me so that I can configure them.

This task needs to be done by someone in Southampton and involves:
- going in the cupboard to extract the Pis
- either giving them to someone who can deliver them to be in person (perhaps @prophile) or sending them via post

**Comment by sedders123** [comment]
These have been separated and are ready to be transported to Peter. We were thinking @prophile may be able to take them?

**Comment by PeterJCLaw** [comment]
Unfortunately not, I don't think he's coming from Southampton to London any time soon.
I was wondering whether it would make sense for @RealOrangeOne to bring them back with him and then perhaps meet me somewhere?
Alternatively, postal services exist.

**Comment by PeterJCLaw** [comment]
Have been discussing with @RealOrangeOne in Slack, it doesn't look like that's viable either. I can probably pick them up next weekend in person though or do the flashing later that week in Southampton (I am free the whole week, but won't be in Southampton for all of it)

In order to enable that, please could you record here:
- what models of Pis are there, how many of each
- what SD/miniSD cards they are, how many and importantly *what their nominal capacities are*

This will allow me to create the images for them while being sure that I'm not creating images which won't fit on the cards (we've had that issue in the past).

**Comment by PeterJCLaw** [comment]
Of the SD cards, there are apparently: 11 4GB, 2 8GB, 6 16GB

**Comment by RealOrangeOne** [comment]
Considering the above, the solution instead is to ship Peter to the Pis (ie flash them in Southampton). @PeterJCLaw I believe we can close this ticket?

**Comment by PeterJCLaw** [comment]
Since there's still a pending issue that I'm not co-located with the Pis, I'm going to leave this open but I've self-assigned as I'll be doing this.

**Comment by Tyler-Ward** [comment]
Peter is now next to the pis.
