### ISSUE TITLE
Test Printer in Storage

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#216]
If we are to use this printer, we need to test it is working.

**Comment by PeterJCLaw** [comment]
#225

**Comment by PeterJCLaw** [comment]
My current thinking here is that this can wait until the print is in Southampton as part of the kit move (#206).
My reasoning is that the lead-time on new one is about an hour (it means a trip to Argos or PC world or the like) and getting new ink is about the same (Staples or another office supplier, or Amazon next-day), versus the two or so days we'll have before the competition.

I realise that that's tighter than is ideal, however the level of effort required to check it before then doesn't seem worth it (see my analysis in https://github.com/srobo/tasks/issues/225#issuecomment-475905556)
