### ISSUE TITLE
Prepare reception machines.

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#217]
Now that we've done https://github.com/srobo/tasks/issues/59, we need to install the software on the machines provided by #100. 

## Requirements
- Python 2
    - PyGTK
    - zbarpygtk
- https://git.studentrobotics.org/cgit/tickets.git/ cloned _somewhere_
- The private `ticket.key` file (currently possessed by @PeterJCLaw and @RealOrangeOne )
- FIlesystem encryption

I've tested this on [Antergos](https://antergos.com/), but the required packages exist in the Debian APT repositories, so we should use that, for stability reasons.

These machines should also have external webcams ideally, to prevent volunteers needing to take competitor devices.

**Comment by trickeydan** [comment]
> I've tested this on Antergos, so unless anyone has any strong objections

Can we please use a stable OS.

Debian 9 will do.

**Comment by RealOrangeOne** [comment]
It looks like the required packages are available in the Debian APT repos, so yes let's use that instead!

**Comment by Tyler-Ward** [comment]
Are we planning on installing this on live USB sticks or do we need to reformat the machines being used for reception? I believe currently they run windows for use with the minibots mindstorms kits.

**Comment by RealOrangeOne** [comment]
Reformat if possible, unless we can get access to some decent quality and capacity USB drives.

**Comment by Tyler-Ward** [comment]
If we need to reformat then we might need to find new machines for use on reception as we don't want to have to rebuild all the minibots outreach machines after the competition.

**Comment by RealOrangeOne** [comment]
The UI doesn't work on windows, so we'll need to source some USBs. IIRC there's some USBs with fedora installed on, so we can use those. Worst comes to worst we can just partition it

**Comment by trickeydan** [comment]
We aren't reformatting the SRO laptops.

**Comment by RealOrangeOne** [comment]
Then unless we can get some decent USB drives, we can just partition them, which is fine. And I suspect useful for SRO to have some additional machines which also run Linux

**Comment by PeterJCLaw** [comment]
We have a bunch of USB sticks which were spares for team kits. While they're not very large, I'm reasonably sure you can fit a Debian image onto them. We don't need them to have particularly stellar performance as the UI is pretty lightweight and will be all in memory by the time it matters.

The challenge there is wanting to encrypt the key somehow, though that's a challenge when running anything off a USB stick. Ideally the key would only exist on physical devices which are a bit harder to remove than a USB stick.

Maybe we do need to use a different key for signing than the internal authz.

**Comment by trickeydan** [comment]
Add a separate LUKS encrypted partition on the USBs that contains the keys. That way if the USB is removed the encryption key is lost and the key is still secure.

**Comment by trickeydan** [comment]
>  we can just partition them, which is fine. And I suspect useful for SRO to have some additional machines which also run Linux

No you cannot partition them, you will not modify the operating system or settings on the machines in any way. They are currently setup as we need and like them.

**Comment by RealOrangeOne** [comment]
> you will not modify the operating system or settings on the machines in any way

We don't need to. A partition doesn't modify the existing OS, and we can use the boot-time override to specify we want to boot to the additional partition. Then after the competition, we login to the original OS, and nuke the new partitions

**Comment by trickeydan** [comment]
https://sourcebots.slack.com/archives/C2XQGF8QP/p1553175662013300

**Comment by RealOrangeOne** [comment]
After the aforementioned discussions, the laptops may not be modified in any way by SR, this includes formatting or partitioning. The reception software doesn't run under windows (the only OS on the laptops currently).

We therefore have 2 options:

- SRO (the owners of the laptops) install Virtualbox on them for us, which we then use to run the reception software inside a VM, assuming we can correctly passthrough a webcam (which is a feature of virtualbox).
- Rearrange resources so that the SRO laptops are used in locations which only require a web browser  (eg scoring), and then move those machines (likely Pis) to reception. 
- Find the USB drives (as discussed in https://github.com/srobo/tasks/issues/217#issuecomment-473706280), and install Debian to those (boot partition and all). We can't live-boot as it means that we'd need to re-install the software whenever the devices reboot.

**Comment by PeterJCLaw** [comment]
Last time I tried, it was possible to live-boot a USB stick while also having a second partition on the USB stick which persists changes. If we can make that work I think it would be ideal.

Note separately that the score-entry machine is currently assumed to be a linux (or mac) box as I'm not aware that SRComp has ever been tested running on Windows, nor do we have a hosted version of the score-entry software. Either of these could change, but I'm highlighting that that's the current situation.

**Comment by RealOrangeOne** [comment]
The boot USB drives are now in my possession. The laptops weren't available to test today, so i'll aim to do some testing during the week, and if not, next weekend.

**Comment by Tyler-Ward** [comment]
This either happened or it didnt

**Comment by PeterJCLaw** [comment]
As I understand it, there were some issues here. Notably:
- we had prepared live USB sticks (as noted above), but the machines had some configuration which prevented that being used
- the prepared live USB sticks didn't actually have the requisite private key on them

We should improve this for next year.
