### ISSUE TITLE
Obtain webcams for Ticket Scanning

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#218]
Required for #217.

> These machines should also have external webcams ideally

**Comment by PeterJCLaw** [comment]
We have a bunch of spare kit webcams. They're what we've used in the past.

**Comment by trickeydan** [comment]
> We have a bunch of spare kit webcams

We need to ensure that these are taken to the venue and set aside then.

**Comment by PeterJCLaw** [comment]
The spare webcams are in storage. #206 covers moving things from there to the venue.

I suggest we want at least 5 cameras for this (I think we're doing 4 lanes of reception?) so this allows a spare. It'll almost certainly be easier to just bring the box.

**Comment by Tyler-Ward** [comment]
We have two lanes of reception on the current floor plans if we want to increase to four we will need more computers and possibly more wristband crimpers.

**Comment by PeterJCLaw** [comment]
More likely I misremembered.

**Comment by Tyler-Ward** [comment]
see #225

**Comment by PeterJCLaw** [comment]
There are 12 working ones in the container, which were placed there after the kit-collation events at the start of this competition-year. Even if one or two have failed over this winter, there's more than enough buffer there not to need to check these.

```
$ sr inv-query 'type is *webcam* and path:storage and cond:working'
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-srEX30
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-srER35
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-sr2WT25
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c500-sr2H8U
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-srEP37
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c500-sr1VJ2G
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-sr0MAP
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-srN1G4G
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-srN1R39
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-srN1H4F
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c500-sr2XK1C
.../inventory/storage/box-18l-rub-sr1TL2J/webcam-logitech-c270-srEY3Y
```

**Comment by RealOrangeOne** [comment]
Linking to https://github.com/srobo/tasks/issues/205 so we remember to bring these.

**Comment by PeterJCLaw** [comment]
I've also realised that I have to spare webcams in my collection of bits of kit I'd hung on to in case we needed to send spares out to teams. I'l test that these work for scanning tickets.

**Comment by PeterJCLaw** [comment]
I have confirmed that these cameras work. The Logitech seemed to be better, but both are fine.

They are parts srET34 and sr1GK27.
