### ISSUE TITLE
Organise token markers

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#221]
We have cardboard boxes for the tokens (#203, #105) and will likely be constructing them during the setup days (#107), though we need markers for the sides of them.

The spec of the markers are in the docs (https://studentrobotics.org/docs/programming/sr/vision/markers) and the game-markers repo contains the PDFs we need (https://github.com/srobo/game-markers/tree/master/SR2019/comp; scroll to the bottom for those labelled TOKEN).

We need these printing on a material which will stand up in the arena. The arena wall markers are printed on plastic, which might be an option, though might also be overkill. Unfortunately I can't recall what material the token markers have been in the past, though @richardbarlow might.

We should get 20 copies of each marker (10 in the arena at any one time, plus a full set of spares). If in doubt err on the side of a few more copies of each as the markers are more likely to get damaged than the tokens' structure. For reference we have [75 tokens ordered](https://github.com/srobo/tasks/issues/203#issuecomment-473698543).

**Comment by PeterJCLaw** [comment]
@TomWheal as you're handling a bunch of printing tasks, would you be able to look into this?

**Comment by Tyler-Ward** [comment]
The tokens have arrived

**Comment by TomWheal** [comment]
@PeterJCLaw I probably won't have time to organise this, If we can find what paper we need this could be done on the setup days.

**Comment by PeterJCLaw** [comment]
@antonnikitin97 would you be able to pick this up?

**Comment by PeterJCLaw** [comment]
I'm wondering whether 100gsm is going to be enough. If we think it is, we can get some at a supermarket for about £5: https://www.tesco.com/groceries/en-GB/products/265149015

**Comment by PeterJCLaw** [comment]
@TomWheal no worries, thanks for letting us know.

**Comment by RealOrangeOne** [comment]
As we're only printing 130mm markers, we don't need to worry about getting this printed on A3, which is significantly harder. I've got some old tokens from previous SR events at home, i'll attempt to use one of those to find a material which is close enough in strength and material to use.

Printing can be as simple as using the SR printer, or any other printer we can get our hands on.

**Comment by RealOrangeOne** [comment]
I've spoken to a photographer, and shown them an old token (SR2017), and they believe it's quite likely to be ~200gsm matte photo paper. This is ~£10 on amazon for 100 sheets (https://www.amazon.co.uk/Double-Inkjet-180gsm-Sheets-210x297mm/dp/B07JYT7BN8/). 

We can print 2 markers per sheet. With ~70 tokens with 6 faces, that's 210 sheets, meaning we'd need to get 3 packs, costing ~£23.

200gsm is thick paper, but can be printed on by most printers, assuming they take the paper flat, and don't try and push it around any rollers. 

Depending on if people agree with my thinking, @Tyler-Ward requesting budget signoff.

**Comment by richardbarlow** [comment]
All markers for the past two or three competitions have been printed on 270mic (I presume micron - 270mic is what the printers say) synthetic media (plastic) by stormpress (https://www.stormpress.co.uk). I can forward the request for quote from the last competition to somebody if that helps. The lead time has generally been around 5 days from requesting the quote to it being delivered. I'm sure that this can be sped up if you ask nicely.

**Comment by richardbarlow** [comment]
(the synthetic media itself is basically indestructible and the printing itself is similarly robust)

**Comment by RealOrangeOne** [comment]
@richardbarlow interesting! I should have thought of reaching out! If you could send the previous quote over to me it would be appreciated, so I can try and replicate the order for the new token sizes.

**Comment by PeterJCLaw** [comment]
@richardbarlow sure, please could you forward the previous quote to coreteam@?

I'm not sure we'll have time for it, but it's useful as a reference.

@RealOrangeOne nice find, that's well worth having as a fallback.

**Comment by PeterJCLaw** [comment]
Note: I'm not sure that the printer we have would do particularly well for this -- it's an inkjet so I suspect not especially high precision.

**Comment by richardbarlow** [comment]
I've forwarded the request for quote I sent for sr2017 to coreteam@

**Comment by RealOrangeOne** [comment]
I've sent off a request for a quote to stormpress with the following spec:

> printed single-sided on 270gsm synthetic media with each page cut to 122mm. The grey square should be exactly 115mm x 115mm and centered on the page.

Will update with status changes.

**Comment by RealOrangeOne** [comment]
I've received a quote for this. This comes to £367.10, and takes 4 working days, meaning we're going to want to order this tomorrow. There's a quicker order for £374.01 which takes 2 working days, which if we have the budget, I suggest we do.

Considering these prices are so much higher than those of 200gsm paper, i'm leaning towards not getting them. If we over-order the paper, we can always print more if they become damaged.

@Tyler-Ward thoughts?

**Comment by Tyler-Ward** [comment]
This is quite a bit over the budget for markers and a lot more than the paper we have used in the past. I might be able to find the budget if we want to go this route but would need to check when I get home.

**Comment by RealOrangeOne** [comment]
I personally don't think it's worth it. If we ensure we make a lot of spares, then we can replace them easily. It'll also be useful to know if we can use paper markers for future competitions.

**Comment by PeterJCLaw** [comment]
SR has used plastic for the past few years, though I'm not clear on how much difference it has made.
Paper is obviously cheaper financially, but at the cost of volunteer time in both setup (needing to print and cut the markers ourselves) and at the competition (needing to have someone checking the tokens constantly). As there are quite a few of them, I suspect this is a substantial amount of extra volunteer time.

How much scope do we have to test the paper approach? From the sounds of it, the two-day option is basically the same price (which I wouldn't have expected) and a viable alternative.

Would it be possible to get some heavy paper and beat it a bit this weekend? (What's the lead-time on getting some heavy paper?)

**Comment by PeterJCLaw** [comment]
Answering my own question#;
- the linked 230gsm could be shipped to arrive on Sunday
- the 180gsm and 140gsm "sizes" from on the same link could be shipped to arrive on Saturday (tomorrow) if we order by 9pm today (Friday)

I'm quite tempted to suggest we get some 180gsm to try and see how it fares.

Given the amount of extra volunteer time involved in the paper approach, I'm much more inclined to the plastic approach. If there is a printing company who can do the cutting for us that might help, though I wouldn't be surprised if that works out a similar cost to the plastic.

**Comment by RealOrangeOne** [comment]
We'd want to check tokens constantly anyway, but this can be done by the marshals when resetting the arena. 

We can cut the markers very quickly using a guillotine (which I have). Setting the markers to print whilst we're doing things allows us to do things concurrently. 

Saturday would be an ideal time to test this. I'm sure there's somewhere around we can purchase something like this. (I'll push the decision on to someone on the day with better _local knowledge_ than I).

My issue with the plastic is that it's a *lot* more expensive, and the markers are unlikely to be reused, unlike the arena markers. Also, it doesn't look like they offer delivery (@richardbarlow ?), which would mean we'd have to go pick them up, which is definitely less than ideal!

**Comment by PeterJCLaw** [comment]
> We'd want to check tokens constantly anyway, but this can be done by the marshals when resetting the arena.

I agree, however I think with plastic we can be much more relaxed about it.
 
> Saturday would be an ideal time to test this. I'm sure there's somewhere around we can purchase something like this. (I'll push the decision on to someone on the day with better _local knowledge_ than I).

Oh, I was thinking to just buy the one you linked from amazon, ideally if someone has a prime account.

> Also, it doesn't look like they offer delivery (@richardbarlow ?), which would mean we'd have to go pick them up, which is definitely less than ideal!

Clicking through to one of their product pages (e.g: https://www.stormpress.co.uk/products/a4-and-a3-posters/a3-posters/) there's a delivery option on the left.

**Comment by TomWheal** [comment]
(I have prime and am happy to purchase anything from Amazon for the event)

**Comment by RealOrangeOne** [comment]
After purshasing 210gsm card (budget approval given in person), we're happy that this card is fine, we just need to get more. 

The card is A4, meaning we can fit 2 markers per sheet. We have 60 tokens (the arena calls for 40), so we need 360 markers, and 180 sheets. We currently have 50 sheets, so we need an additional 150 more (3 packs)

Said card was ~£6 per pack. I can purchase the additional packs this week. Requesting budget signoff from @Tyler-Ward.

**Comment by Tyler-Ward** [comment]
As per in person discussion this has been approved for 4 packs to give some spares

**Comment by RealOrangeOne** [comment]
We've also tested that these can be printed using the university printers (namely those in L3 labs), and they do.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne am I right in thinking that the card ended up somewhere in the broomcupboard? (I'm hoping it was labelled?)

If so, I think all that's left here is for us to actually print the token markers. Do you agree?

**Comment by RealOrangeOne** [comment]
It's in the broomcupboard, yes. This card tracks both the fact we need to print it (or, that'll end up in a separate ticket), but also that I need to purchase additional card

**Comment by RealOrangeOne** [comment]
The office outlet near me has actually already shut, so i'll need to order it from an alternative location. Click and collect has it in store in Southampton, so i'll keep an eye on that and probably head over there Wednesday afternoon.

**Comment by PeterJCLaw** [comment]
Worth ordering there now for collection later in the week? (Do they support that?)

**Comment by RealOrangeOne** [comment]
> Worth ordering there now for collection later in the week? (Do they support that?)

It doesn't look like it, which is annoying. But keeping an eye on stock levels in the Chichester and Southampton branches is the best we can do.

**Comment by RealOrangeOne** [comment]
The card for this has now been purchased. We just need to print them!

I've extracted the printing into a separate issue (https://github.com/srobo/tasks/issues/271)

This is now done.

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/game-markers/pull/3 creates a PDF for print these two to an A4 page.
