### ISSUE TITLE
Purchace barcode scanners

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#222]
We should purchase a pair of bar-code scanners for inventory and other tasks at the competition and beyond.

Are people happy with the following.
https://www.amazon.co.uk/Bluetooth-Koolertron-Wireless-Maxicode-Automatically/dp/B0716PPS8S?th=1

**Comment by mltnhm** [comment]
[Do you guys not have phones?](https://www.youtube.com/watch?v=ly10r6m_-n8)

**Comment by trickeydan** [comment]
:shipit:

**Comment by PeterJCLaw** [comment]
Barcode scanners here are USB devices which hook into computers for direct use. While ~phones~ personal mobile ~tracking~ computing devices can read barcodes, they're not particularly convenience.

@Tyler-Ward I may know of an alternate source where we can get some barcode scanners from (or at least borrow for the competition if that's useful), let me ask.

**Comment by Tyler-Ward** [comment]
@PeterJCLaw is this get as in borrow or get as in can have? Being able to borrow more around the competition will be useful but we should probably own some for longer term use as well.

**Comment by trickeydan** [comment]
> we should probably own some for longer term use as well

This is essential imo.

**Comment by Tyler-Ward** [comment]
ordered see #200 for tracking

**Comment by PeterJCLaw** [comment]
I have some additional barcode scanners.
