### ISSUE TITLE
Create a means to record an incident

### ISSUE THREAD

**Issue by Scarzy** [srobo/tasks#223]
We need a means to record and store details of an incident or near-miss occurring.

At bare minimum this needs to store what happened and why, and what follow up occurred.

At this point I don't know if we need to be recording the personal details of who was involved, or if we can merely record e.g. which school they belonged to and who holds more specific details (i.e. the first aid provider).

**Comment by TomWheal** [comment]
A google form should be fine for this

**Comment by RealOrangeOne** [comment]
I suspect there may be issues around having this information available to all volunteers, due to the nature of the information and the fact we don't have a requirement for volunteers to be DBS checked. 

I suspect a simple paper form, stored securely, and operated by the H&S lead (@Scarzy) will probably cover this. I believe you can buy ready-made incident booklets, which might be something useful for SR to invest in

**Comment by Scarzy** [comment]
> A google form should be fine for this

Maybe.
I need to do some checking, but I recall being informed during some data protection training a while back that because of where google house some of their servers storing any personal data on them can violate data protection laws.

**Comment by Scarzy** [comment]
> I suspect there may be issues around having this information available to all volunteers

I suspect you're almost certainly right.

> I suspect a simple paper form, stored securely, and operated by the H&S lead (@Scarzy) will probably cover this. I believe you can buy ready-made incident booklets, which might be something useful for SR to invest in

Agreed. Simple, secure. We would just need to work out which fields we actually need to fill. I suspect that will be dictated largely by the insurance T's&C's. I'll try to find some options.

**Comment by Tyler-Ward** [comment]
> > A google form should be fine for this
> 
> Maybe.
> I need to do some checking, but I recall being informed during some data protection training a while back that because of where google house some of their servers storing any personal data on them can violate data protection laws.

I think we have a data sharing agreement with google as we have an organisation account which will cover us storing personal data there.

For the paper incident book we would need to consider where to store it, not sure what our obligations are in this regard.

**Comment by PeterJCLaw** [comment]
> For the paper incident book we would need to consider where to store it, not sure what our obligations are in this regard.

Indeed. The ones I've seen are typically these things are in a tear-off style, so that you can store the filled-in forms separately from the book itself. The first-aid variants I've seen come with carbon-paper sheets (or similar) allowing for you to give a copy to the person (or guardians thereof) who needed first-aid.

**Comment by Scarzy** [comment]
> Indeed. The ones I've seen are typically these things are in a tear-off style, so that you can store the filled-in forms separately from the book itself.

Turns out that this is actually a requirement under GDPR.

> The first-aid variants I've seen come with carbon-paper sheets (or similar) allowing for you to give a copy to the person (or guardians thereof) who needed first-aid.

This isn't something we need to worry about, the first aid provider will supply that to them, we just need to be able to record it for our own records.

The more I look into this the more gotcha's I'm coming across, as such to avoid falling foul of one I suggest we just go with the one produced by a related regulatory body (HSE): https://www.amazon.co.uk/Accident-Britain-Health-Safety-Executive/dp/071766693X

We also need something separate to keep the completed sheets in, so I'll find some form of wallet for them.

**Comment by Scarzy** [comment]
In the absence of any further comment, I've ordered one of those books. So I'll close this ticket

**Comment by Tyler-Ward** [comment]
Are you purchasing this for yourself or are you hoping to be reimbursed for this? I am happy to allocate budget for this if needed but we should allocate budget before making the purchases. is there going to be another order for the wallet to store them in or is that going to be found from ones lying arround?

**Comment by Scarzy** [comment]
The first time a paper form was mentioned the wording used was:
> useful for SR to invest in
I suggested an option. I waited 48 hours during which there was absolutely no comment. We are less than 2 weeks from the competition, on a ticket flagged as "Urgent".
Can someone please explain to me what the magic words are to get the required response in a reasonable time frame? Rather than only getting a response after I've dealt with it.


The booklet can be considered as SR's. Whilst I would prefer it if it was, I won't get upset if it's not reimbursed (frankly, it'll cost me more in petrol to get to the competition than the book is worth anyway).
Regarding the wallet; I'm hoping an existing one can be found. I'm fairly sure I've got one here that could be used if nothing else. I'll update further tomorrow.

**Comment by Tyler-Ward** [comment]
Adding something like "can I get budget approval for the following:" would be the best way to do it, also tagging me in the post and adding the needs budget approval tag. A lot of links to items get posted in tickets so it is easy to miss an un-labled purchase request when there are lots of items as pricing information appearing on tickets. I have now allocated the budget for this can you email me an invoice so i can start the reimbursement process. Also we have a budget for volunteer travel (information on this will be going out in an email in a couple of days)

**Comment by Tyler-Ward** [comment]
added to #200 for delivery tracking
