### ISSUE TITLE
Pay for SUSU venue hire

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#224]
We should pay for stuff from SUSU. we don't have a price yet, will follow this up.

**Comment by Tyler-Ward** [comment]
We now have the invoice for the tech. Which has been sent for payment. We are still waiting for the venue hire costs

**Comment by Tyler-Ward** [comment]
SUSU have been paid for the tech hire and carpet purchace

**Comment by Adimote** [comment]
Just to clarify, we're only waiting on venue hire cost now?

**Comment by Tyler-Ward** [comment]
That is correct

**Comment by Tyler-Ward** [comment]
This has been paid
