### ISSUE TITLE
Setup OBS for livestream

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#226]
as part of #77 

We should setup an OBS install and config for the livestream

**Comment by Tyler-Ward** [comment]
The OBS internal browser can render the overlay over any capture feeds with full transparency this avoids needing a separate live-stream overlay machine.

**Comment by Tyler-Ward** [comment]
updated #100 to account for new requirements

**Comment by Tyler-Ward** [comment]
I have created some of the OBS config will need to know what the final camera configuration is before I can finish it.

**Comment by trickeydan** [comment]
Blocked on #227

**Comment by PeterJCLaw** [comment]
@Tyler-Ward is currently doing this.

**Comment by Tyler-Ward** [comment]
Livestream is up
