### ISSUE TITLE
Setup youtube livestream

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#229]
As part of #77 we should test livestreaming to youtube

**Comment by RealOrangeOne** [comment]
We have an existing YouTube account, we should use it https://www.youtube.com/user/studentrobotics

(It does currently use the old branding)

**Comment by sedders123** [comment]
I have found a [guide](https://www.digitaltrends.com/computing/how-to-live-stream-on-youtube-with-obs/). Looks like we just need to grab the secret from youtube then do some minimal config in OBS

**Comment by Tyler-Ward** [comment]
@antoinepetty is going to get access to the youtube account so that we can register for streaming.

**Comment by antoinepetty** [comment]
I now have access. Will look into how to set it up for livestreaming

**Comment by antoinepetty** [comment]
All seems to be fine, I'm able to get the URL and key for OBS - will properly set up on Thursday or Friday
