### ISSUE TITLE
run a livestream console training session

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#230]
We should train the livestream (#77) volunteers on the system.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward roughly how long do you anticipate this session taking? Is it something which can be done with several people at once?

cc @Adimote for fitting this into the volunteer roles.

**Comment by Tyler-Ward** [comment]
I would expect about 10-15 minutes for this. assuming we don't have too many people this can probably be done for everyone who needs to know at once.

**Comment by Tyler-Ward** [comment]
A rough plan of what we should cover in this session.

* Basic use of OBS
* Checking the stream is working
* Camera and input switching
* Discussion of the shot plan and commentary options.

**Comment by Tyler-Ward** [comment]
training done
