### ISSUE TITLE
Create quick use barcodes for inventory use

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#231]
as the bar-code scanners can load in arbitrary text, we can create some useful commands as bar-codes to speed up inventory tasks. e.g. 
* go to box with inventory code
* goto competition folder
* git status

**Comment by PeterJCLaw** [comment]
Why is this task set for completion by this competition? I really don't see us using the inventory at the competition event -- the additional faff of needing a computer whenever we move stuff (regardless of how slick the interface is) is going to overwhelm the amount of kit we have to move around.

**Comment by Tyler-Ward** [comment]
here are some useful inventory bash oneliners as barcodes, these still needs testing to make sure they read ok

move item
sr inv-mv $(read varN && echo $varN))
![mv](https://user-images.githubusercontent.com/3390465/54873534-c4fd1480-4dcf-11e9-98fb-0176f1b27166.png)


cd to competition folder
cd `git rev-parse --show-toplevel`/competition
![comp](https://user-images.githubusercontent.com/3390465/54873519-aac33680-4dcf-11e9-97e9-bad89f850e23.png)

cd to container
cd $(sr inv-findpart $(read varN && echo $varN))
![container](https://user-images.githubusercontent.com/3390465/54873527-b7e02580-4dcf-11e9-8760-12526b71091a.png)


cd to tla
cd `git rev-parse --show-toplevel`/teams/2019/$(read varN && echo $varN)
![team](https://user-images.githubusercontent.com/3390465/54873532-bf073380-4dcf-11e9-85e5-4ee4700aceb0.png)

**Comment by Tyler-Ward** [comment]
these have been tested and are working

**Comment by Tyler-Ward** [comment]
The remainder of the useful code have been compiled here as two printable docs.
https://drive.google.com/drive/u/1/folders/1_VLw_1NcNYvv8AuTgo1-20UobmyD8RR0

**Comment by RealOrangeOne** [comment]
Unfortunately, the move code doesn't do bulk, you have a to scan it for each thing you want to move. We should add another one which lets you do bulk. For now we can push them into a text file and replay that later on

**Comment by PeterJCLaw** [comment]
Some quick commands which are useful for bulk scanning:

The following will scan an item at a time, validate the part code and the move it:
```
$ cd new/place
$ xargs --max-lines=1 sr inv-mv
```

The following will wait for you to scan a bunch of items, then validate all of them and move them:
```
$ cd new/place
$ xargs sr inv-mv
```

Note that if you use the second one, the trade-off is:
- you don't get validation of what you've scanned immediately
- if there _are_ any errors, you have to scan everything again
