### ISSUE TITLE
Purchase assorted stationary

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#232]
We need stationary things to be used around the event

- Files for storing completed forms (~£30 for 5)
- ~Pens + other writing implements (£10 for 50)~

**Comment by PeterJCLaw** [comment]
There's a box of _many_ pens in storage, I don't think we need more.

**Comment by Tyler-Ward** [comment]
@RealOrangeOne do you have a link for the box files?

**Comment by RealOrangeOne** [comment]
I suspect https://www.amazon.co.uk/Concord-Paper-lock-Finger-pull-Foolscap-Assorted/dp/B002RDR59M/ref=sr_1_7 will suffice

**Comment by Tyler-Ward** [comment]
Given we have two reception lanes will 5 be enough for reception and other areas (assuming we use box files for all paperwork?)

**Comment by RealOrangeOne** [comment]
we need boxes for media consent, broken kit, and kit return. We have a folder for scoresheets. Are we missing anything from that list? We could get 2 orders and consider that enough? We can re-use them for future events anyway.

**Comment by Tyler-Ward** [comment]
Currently the fright list has boxes of paperwork at:
Reception:
 * one for completed forms (i guess we will need to double this for two lanes).
 * one for blank forms (i guess we will need to double this for two lanes). (can also reuse for kit handback forms)
Helpdesk:
* Kit replacement forms:
* Account forms and battery lending forms (these don't need a full folder though)
Score entry:
* Somewhere for blank score-sheets
* Incident forms
Competion admin:
* generally there is a lot of stuff we should have printed off 

I think 5 will be fine but it is probably with getting some general thin card paper folders as well.

Approved for £28.34 for one set of box files will look at the rest when we can work out what we need.

**Comment by RealOrangeOne** [comment]
I can get a pack of 50 of [these card wallets for £8](https://www.amazon.co.uk/Q-Connect-Document-Wallet-Foolscap-KF01490/dp/B0071HDNRC/). Do you want me to add those to the order?

**Comment by Tyler-Ward** [comment]
Approved

**Comment by RealOrangeOne** [comment]
These have now been ordered at a total of £37.06, and will arrive at my office tomorrow and Friday. Adding to #200 to track delivery.

Receipt has been emailed to @Tyler-Ward.
