### ISSUE TITLE
Plan volunteer travel reimbursement

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#236]
We should plan how we are going to do this and make sure we don't promise things we cant afford. (ideally I would like to fund everyone's full travel but cant promise this until we know how much people have spent).

@Adimote any thoughts

**Comment by Tyler-Ward** [comment]
per core team discussion suggestion is to reimburse by percentage out of the available budget. @Adimote are you happy to collect the expenses post competition and create a list in google drive somewhere.

**Comment by Adimote** [comment]
Sure, that's fine by me. I think not much more planning is needed until post-competition, other than what @Tyler-Ward just said, and telling volunteers to keep receipts for travel, which has been done in the email I sent yesterday.

**Comment by Tyler-Ward** [comment]
will move the collection and actual reimbursement to a separate ticket as we have a plan now.
