### ISSUE TITLE
Investigate beach flags

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#237]
@TomWheal came up with a good idea for outside of the venue which is to get a pair of verticial flags. these have a very short leadtime so can still be ordered if we have the funds. @TomWheal what was the cost of these?

**Comment by TomWheal** [comment]
https://www.helloprint.co.uk
£ 226.74
https://www.displaywizard.co.uk
£194

both of those are with the base and pole.
It very much depends on what type of flag we want, https://www.helloprint.co.uk/beachflag-printing, this site has most types on it. I would suggest just putting the logo with text on it as is or rotating the text to be verticle, this can be decided if we decide to get some.

**Comment by RealOrangeOne** [comment]
I fear the name 'flags', whilst accurate, may lead to confusion with robot flags (I know it did for me!). Is there a better name for them we can use when referring to them?

**Comment by PeterJCLaw** [comment]
If I recall correctly, SR already owns a number of sandwich board signs which we could use for this (though we'd want to get suitable inserts printed) (I don't know where these ended up, though I suspect they're in the broomcupboard) and/or we could use the banner #89.

**Comment by TomWheal** [comment]
Given this probably won't happen before the competition I suggest we close this.

**Comment by trickeydan** [comment]
"++"

@mildlyincompetent  and I think that getting these is an excellent idea.

**Comment by RealOrangeOne** [comment]
@TomWheal I'm somewhat tempted to agree, especially considering the likely lead time. I think these are a good idea to have, but I don't think we need them this competition cycle. We can just remove it from this milestone, and add the "next competition cycle".

With that being said, assuming we have the budget, I've got nothing against you or @trickeydan investigating, although considering your comment, it's likely the latter.

**Comment by TomWheal** [comment]
I'll move it to next competition cycle then, feel free to take this over if you really want to get some @trickeydan

**Comment by samjmartin04** [comment]
We bought these a couple of years ago.
