### ISSUE TITLE
Collect volunteer travel expense receipts and arrange reimbursment.

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#239]
We need to collect travel costs from volunteers and arrange reimbursement.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward do you have a preferred format for volunteers who will be driving? (Do you want actual fuel receipts, or will mileage estimates be ok?)

**Comment by Tyler-Ward** [comment]
I think a millage will be fine, will use whatever the standard miles/cost ration is to work out the cost.

**Comment by Tyler-Ward** [comment]
These where collected and paid
