### ISSUE TITLE
Print Helpdesk documents

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#244]
- [x] 2 x [Rulebook](https://studentrobotics.org/docs/resources/2019/rulebook.pdf)
- [x] 1 x [Helpdesk Instructions](https://srobo.github.io/runbook/competition/team-support/helpdesk/)
- [x] 1 x [Kit Swap form](https://docs.google.com/document/d/1tvzO0WEqL8m0B0QEBJziylZGAx0bpNe0RP6K1INMVZA/)
- [x] 15 x [Venue Map](https://github.com/srobo/tasks/files/3038699/event-map.pdf)
- [ ] 1 x Eduroam Passwords (Ask Anton)

**Comment by PeterJCLaw** [comment]
@Adimote when you get time, please could you contribute the Kit Swap Form to https://github.com/srobo/kit-coordination-documents/?

**Comment by Adimote** [comment]
added venue map

**Comment by TomWheal** [comment]
Done apart from the eduroam passwords, this can be printed "in house"
