### ISSUE TITLE
Print Reception documents

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#245]
- [x] 75 x [Media Consent Form](https://4-173567015-gh.circle-artifacts.com/0/media-consent.pdf)
- [x] 2 x [Reception Instructions](https://srobo.github.io/runbook/competition/teams/role-descriptions/reception/)
- [x] 2 x [Arrivals Desk Instructions](https://srobo.github.io/runbook/competition/teams/role-descriptions/arrival-desk/)
- [ ] 1 x [Volunteer Sign-in Sheet](https://drive.google.com/file/d/13YJ6E9-eEoqHIt3S3La4dVaoXNU30hE_/view) (restricted for privacy, need to request access for this)
- [ ] 1x Team Sign-in Sheet (Link TBD, will need to get the [CircleCI artifact](https://circleci.com/gh/srobo/kit-coordination-docs), ask Jake)
- [x] 15 x [Overnight battery loan form](https://github.com/srobo/kit-coordination-documents/tree/master/overnight-battery-loan)
- [x] 27 x [Kit contents checklist](https://github.com/srobo/kit-coordination-documents/tree/master/kit-contents-checklist)
- [x] 27 x [Missing kit form](https://github.com/srobo/kit-coordination-documents/tree/master/missing-kit-form)

**Comment by PeterJCLaw** [comment]
(I could be argued that this was a must-have, rather than a should-have, but without a label at all we'll likely overlook it)

**Comment by TomWheal** [comment]
Done
