### ISSUE TITLE
Acquire flag mounting parts

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#246]
We should purchase the following to allow for flag mounting on robots without the capability

2* https://www.screwfix.com/p/jg-speedfit-pem0215w-l-equal-tee-white-15-x-15-x-15mm-5-pack/74470 for flag mounting
1* hot glue gun
1* glue sticks

I will head to homebase/screwfix lin an hour or so and pick some up.

**Comment by PeterJCLaw** [comment]
Does a hot glue gun count as a power tool? Do we really want to be providing them to teams?

**Comment by Tyler-Ward** [comment]
I wouldn't want to give it to the teams but either we or they can stick the flag mount on with it at help-desk.

**Comment by Tyler-Ward** [comment]
The glue gun and a good supply of glue sticks have now been purchased for £19 the mounts came to £24.30

**Comment by PeterJCLaw** [comment]
cc @Scarzy for information that we've got a hot-glue gun for this.

**Comment by Scarzy** [comment]
> Does a hot glue gun count as a power tool?

Last I checked, all hot glue guns were powered, so yes.

Considering the risk assessment specifically states:
> Student Robotics will not provide any tools to competitors.

At best it is irresponsible to disregard this and purchase a power tool for their use. This is in line with what has been stated on there in previous years, and providing any tool sets a precedent that could be difficult to reverse in future years.

I suggest this:
> either we or they can stick the flag mount on with it at help-desk

changes to:
> we can stick the flag mount on with it at the power tools area

Alternatively, another solution should be found. Re-opening until this is clarified.

**Comment by RealOrangeOne** [comment]
I'd suggest that _we_ mount the flag mount for teams. Having specific wording in the risk assessments that we may provide tools for specific uses feels weird, for something which can easily be done by a volunteer for the teams which need it (which I _hope_ is actually very few)

**Comment by PeterJCLaw** [comment]
@Scarzy I think we're agreed that only volunteers should use the hot-glue gun, is there anything else outstanding here?

**Comment by Scarzy** [comment]
Agreed, only we use it.

There is 1 potential issue r.e. the insurance that might affect this. Me
and Alistair are chasing that through and can then update this.

**Comment by Scarzy** [comment]
Chased. Non-issue.
