### ISSUE TITLE
Purchase volunteer snack fruit

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#247]
Extended from #157, we need to purchase fruit. As this would be better bought fresh, we should buy this on the setup days. 

A budget of £15 has been pre-approved for this by @Tyler-Ward in the above ticket.

(I'm technically assigned to the order, but leaving the ticket unassigned depending on how things go on the setup day)

**Comment by Tyler-Ward** [comment]
Purchaced
