### ISSUE TITLE
Purchase broken biscuits for volunteers

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#248]
Broken out from #157, we need to purchase broken biscuits (pre-broken) from the SUSU shop. 

There's a pre-approved budget of £15 in the above ticket.

**Comment by kierdavis** [comment]
I don't mind picking these up during one of the setup days.

**Comment by RealOrangeOne** [comment]
@kierdavis that would be great! Please assign yourself to confirm (you _should_ have permission to do this)

**Comment by kierdavis** [comment]
I have bought 4 1300g boxes, totalling £13.96.
