### ISSUE TITLE
Purchase more misc stationary

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#249]
@RealOrangeOne is going to go to the office supply store again soon any extra stationary should be listed here for purchase and approval.

- [ ] Permanet markers (2xpack of sharpies or similar)
- [ ] temporary labels/writable tape.
- [ ]  post it notes

**Comment by RealOrangeOne** [comment]
I'll go tomorrow on my way home from work, so I'd want this list committed to by around 17:30 so I can reserve it.

## Price estimate

Permanent markers: 12 black for £19
Labels: 675 for £13 (63.5 x 29mm)
Post-it notes: 6 pads (450 notes) for £12.99

**Comment by RealOrangeOne** [comment]
Apparently the office outlet near me has actually already shut, therefore I'll probably head to the one in Southampton on Wednesday.

Therefore, i'm moving this to a setup day task.

**Comment by PeterJCLaw** [comment]
For posterity/future planning, could someone who knows please comment on this ticket what these items are for?

**Comment by Tyler-Ward** [comment]
Permanent markers are mainly for labelling things as they write on most things.
the labels are for using on things we don't want to damage by writing on them e.g. borrowed kit.
the post-its are for helpdesk @Adimote can provide more details.

Also @PeterJCLaw do we have a stock of paper in storage.

**Comment by PeterJCLaw** [comment]
There was a pack of regular printer paper in storage, yes.

**Comment by trickeydan** [comment]
> Therefore, i'm moving this to a setup day task.

Changing the milestone

**Comment by RealOrangeOne** [comment]
Requesting budget signoff @Tyler-Ward

**Comment by RealOrangeOne** [comment]
These items were purchased without signoff, but came in under the above budget anyway.
