### ISSUE TITLE
Allocate team TLAs for SR2019

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#25]
We need TLAs for the teams. TLAs are usually derived from the name of the school/college. We should probably re-use old TLAs where possible to keep things easy for team-leaders.

If (though only if) we're shipping the tablets (#24, #27), then this is a blocker for the Kit Packing session. Otherwise this is only needed by Kickstart.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne would you like to take this? I can provide lists of previous TLAs if you like.

**Comment by RealOrangeOne** [comment]
I'm happy to take this. An existing list would be great, and some kind of instruction as to how we generated those, in case I have to make up some new ones. Would be good to generate them in the same way.

_Generate_ here can likely be replaced for 'make up'!

**Comment by PeterJCLaw** [comment]
Generally the TLA derives from the name of the school or college, though it doesn't really matter. As far as we're concerned it's just a unique identifier. However we do want teams to be able to build an identity around it.

Here's a recent selection of teams & TLAs:
```
ABD Abingdon School
BAL Bales College
BDF Bedford School
BLE Blenducate Ltd
BPV Barton Peveril College
BRK Brockenhurst College
BRN St Brendan's Sixth Form College
CAR Carshalton College
CAT CATS College Cambridge
CCR Cirencester Sixth Form College
CGS Colston's Girls' School
CHB King Edward VI Camp Hill School for Boys
CHW The Cherwell School
CLF Clifton High School
CLY Collyer's
CRB Cranbrook School
CRS Clitheroe Royal Grammar School
DCG Dr Challoner's Grammar School
DUL Dulwich College
FAL Fallibroome Academy
FRC Frome College
GDC Godalming College
GRD Gordano School
HAM Hampton School
HAY Haydon School
HRS Hills Road Sixth Form College
HSO Headington School
JLS The John Lyon School
KDE Kennet District Explorer Scouts
KEG KEGS (King Edward VI Grammar School, Chelmsford)
KES King Edward VI School, Southampton
LFG Lion-Feuchtwanger-Gymnasium
LSS Lawrence Sheriff School
MAI Gymnasium Markt Indersdorf
MCS Magdalen College School
MFG The Mirfield Free Grammar and Sixth Form
PSC Peter Symonds College
QEH Queen Elizabeth's Hospital
QMC Queen Mary's College
RGS Royal Grammar School Guildford
SCS Silcoates School
SEN Southend High School for Boys
SPH St Philomena's High School
SUF Suffolk One
SWI South Wilts Grammar School
TCS The Cooper School
TLC The Ladies' College, Guernsey
TTN Richard Taunton 6th Form College
TWG Tunbridge Wells Grammar School for Boys
WGS Wisbech Grammar School
WHS Westcliff High School for Girls
```

**Comment by RealOrangeOne** [comment]
We're not shipping the tablets, although according to the task (https://github.com/srobo/docs/issues/63), we're still shipping the wifi interface. The TLAs are still used to define the SSIDs, right? So we still need to have these done soon ish, we just don't need to pre-register the tablets with those networks

**Comment by PeterJCLaw** [comment]
@RealOrangeOne you're correct, however the TLAs make their way onto the kits by way of the zip file from the IDE rather than being baked into the kits.

My comment was more about this no longer being a blocker for kit packing. It's still a blocker for a bunch of other things.

**Comment by RealOrangeOne** [comment]
This has now been done. TLAs have been added to MailChimp, as well as the teams list in Drive.
