### ISSUE TITLE
Acquire HDMI-VGA adaptors

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#250]
Two of the screens we want to use have VGA in. 

We can buy some from amazon for fairly cheap.
https://www.amazon.co.uk/Gold-Plated-Computer-Projector-Chromebook-Raspberry-HDMI-VGA-Adapter/dp/B07F6XXTH8/ref=sr_1_1_sspa?crid=3M19AQL5R5S27&keywords=hdmi%2Bvga%2Badapter&qid=1554045338&s=gateway&sprefix=hdmi%2Bvga%2Ba%2Caps%2C156&sr=8-1-spons&th=1

I think we can get these delivered for free if someone with prime orders them.

**Comment by PeterJCLaw** [comment]
Hrm, my reading of the delivery details is that they need adding to an order over £20?

**Comment by sedders123** [comment]
@Tyler-Ward If these have budget sign off I am happy to order (with my prime) for delivery to SUSU

**Comment by Tyler-Ward** [comment]
Budget is now approved for this.

**Comment by sedders123** [comment]
A '2 Pack' has been ordered for delivery to SUSU tomorrow

**Comment by RealOrangeOne** [comment]
Does that mean we can consider this ticket closed?

**Comment by sedders123** [comment]
I think this can now be closed
