### ISSUE TITLE
Acquire Desk lamps

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#251]
We need a desk lamp for score entry to use.

**Comment by trickeydan** [comment]
@antonnikitin97 What happened to the desk lamp that SRO has?

**Comment by PeterJCLaw** [comment]
I have a compact desk lamp I can lend for this. It would be handy to have one on the mezzanine too I suspect, so if there's another one around we can use for scoring so much the better.

**Comment by RealOrangeOne** [comment]
I also have one which could be used if necessary, although for logistical reasons i'd need to know soon if we wanted it. I'd highly recommend prioritizing anyone already in Southampton with a lamp over me.

**Comment by trickeydan** [comment]
I'm downgrading this as we can survive with a phone torch.

**Comment by PeterJCLaw** [comment]
Since there are I think three of us planning to bring lamps for various purposes including this, can we call this fixed?

**Comment by trickeydan** [comment]
I agree.
