### ISSUE TITLE
Make an arena reset checklist

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#252]
Update the runbook with an arena resetting checklist.

**Comment by Adimote** [comment]
@sedders123 you've done a lot of arena-based tasks, do you want to take this? Otherwise I can do it later

**Comment by sedders123** [comment]
Sorry I won't have time to do this today, but I'm happy to do this tomorrow evening if it can wait

**Comment by PeterJCLaw** [comment]
Meta thought: as this will change a _lot_ between years, is the runbook the right place for it?
The answer might be "yes, as long as we name the file something like sr2019-arena-reset-checklist", though an alternative might be the https://github.com/srobo/arena repo, within the year-specific folder.

**Comment by sedders123** [comment]
I'm looking to start on this later today. Just to clarify what is required, my understanding of an 'Arena Reset Checklist' would be everything that happens from a match ending to the next match beginning, is that correct?

**Comment by PeterJCLaw** [comment]
That matches my understanding.

**Comment by sedders123** [comment]
Have created https://github.com/srobo/arena/pull/2 though can't request review on it (cc @RealOrangeOne). @Adimote @PeterJCLaw Are you ok to take a look?

**Comment by PeterJCLaw** [comment]
@sedders123 great, thanks! I don't have time to look this evening, but I'll try to find time tomorrow.
