### ISSUE TITLE
Acquire timelapse camera

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#253]
it would be nice to get timelapses of setup and the event

Does anyone have a timeleapse camera we can use?

**Comment by RealOrangeOne** [comment]
@mltnhm Does the go-pro you have do time lapse? If so, can that be used?

**Comment by mltnhm** [comment]
It does indeed. Will be sure to bring that with me tomorrow

**Comment by mltnhm** [comment]
It does indeed. Will be sure to bring that with me tomorrow

**Comment by trickeydan** [comment]
> It does indeed. Will be sure to bring that with me tomorrow

Can we now consider this issue resolved then?

**Comment by mltnhm** [comment]
I'm just about to get home so I'll close this once I've tested and packed it

**Comment by mltnhm** [comment]
We're all good. Just charging it up
