### ISSUE TITLE
Acquire knives for cutting carpet

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#256]
We need some knives or similar to cut the carpet as SRO don't have these in the current arena toolbox. @PeterJCLaw do you think there are any of these in storage 

if not A pair of these or similar would cover this.
https://www.amazon.co.uk/Stanley-010481-FatMax-Snap-Knife/dp/B0024LG06Q/ref=sr_1_14?keywords=stanley+fatmax+knife+snap+off&qid=1554146357&s=gateway&sr=8-14

**Comment by PeterJCLaw** [comment]
I'm not aware of SR having any of these.

**Comment by sedders123** [comment]
Happy to get these delivered to SUSU if that's helpful, would we want any additional blades?

**Comment by Tyler-Ward** [comment]
That would be great if you could. I think they come with 6 blades each which should be plenty.
Budget is approved for this.

**Comment by sedders123** [comment]
👍 Just to confirm, we want 2 of these?

**Comment by sedders123** [comment]
These should be arriving tomorrow. Added to #200 for tracking

**Comment by Scarzy** [comment]
This strikes me as more of a craft knife. Those blades are designed to snap
out the way to give a fresh blade 1cm further back.

Are we confident any sideways movement on the (rather tough compared to
most craft things) carpet won't just keep snapping them off?

**Comment by Tyler-Ward** [comment]
These knives are fairly commonly used for event carpet (I have specked the same style and brand as the one we borrowed from a volunteer for the carpet for small-piece). These are the same style as the craft ones but the blades are quite a bit larger.
