### ISSUE TITLE
Prepare spare kit for Helpdesk

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#257]
Follows from #144 and depends on #206 and #207.

This task involves working through the spare kit we bring to the venue and ensuring that we have a clear separation between kit which is tested and can immediately be used to help fix teams' issues and that which is in an unknown state.
For batteries, we should ideally also have someone who is familiar with batteries check them over in case any have become less good over the year.

Ideally we wouldn't bring any unknown kit to the venue, but it seems likely that that will happen by accident.

This would also _ideally_ involve updating the inventory to record which pieces of kit are at the venue for this purpose, mostly so that if we run out we don't then think that there is more elsewhere we can go and get (and the find is not actually where we thought it was).

**Comment by PeterJCLaw** [comment]
cc @Adimote if you could work this into the setup plans, including a person for the batteries, that would be good.

For clarity: I think it's ok for the battery re-check can happen at a different time to when the other items are checked, though doing the battery check second may be easiest.

**Comment by sedders123** [comment]
There was kit available, but not sorted
