### ISSUE TITLE
Create post competition reports

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#258]
We should give a report on the SR2019 competition cycle and details of the event to the trustees once everything from the event has been sorted out. This will also include a spending report for the year.

**Comment by Tyler-Ward** [comment]
Budget report has been created

**Comment by PeterJCLaw** [comment]
Are there any other written reports we need to create here? We did a bunch of in-person reporting at the Core Team disillusion meeting a couple of months back, so I'm not sure if that covers this?

**Comment by PeterJCLaw** [comment]
@Tyler-Ward are you able to clarify what, if anything, is outstanding here?

**Comment by PeterJCLaw** [comment]
@andybusse do we know what reports were given and what (if any) are outstanding? I'm trying to work out how to include this task for SR2020.

**Comment by PeterJCLaw** [comment]
This almost certainly isn't going to happen now.
