### ISSUE TITLE
Allocate funds for potential insurance claims

### ISSUE THREAD

**Issue by Scarzy** [srobo/tasks#259]
The insurance (#147) comes with a "deductible" (what all other insurers call "excess") of £250 per claim to property damage. In the event a claim is made we will have to cough up these funds, as such I highly recommend we allocate funds to support potential claims now.

If we can allocate £1000, this covers us for 4 claims, which should be more than sufficient.

Bodily harm carries no "deductible".

**Comment by Tyler-Ward** [comment]
I think this would likely be best covered by the contingency pot if we claim on this, unless you think it is likely we will be making a claim in which case i will set aside a specific budget line for it. This should be considered when doing budgets in future years though. 

For info what property is the insurance covering?

**Comment by Scarzy** [comment]
> best covered by the contingency pot

So long as it is sufficiently sized, that's good enough.

> For info what property is the insurance covering?

A long list of inclusions and exclusions, all defined by the insurer. I don't really see the need to duplicate that on the ticket.

**Comment by Tyler-Ward** [comment]
Worded that last question badly I was meant as in is it covering Hired property, Student robotics property, volunteer property or property of competitors and volunteers.

**Comment by PeterJCLaw** [comment]
(I'm reviewing some old tickets)
@Tyler-Ward or @Scarzy what do you see as the way to progress ticket to a useful conclusion? Specifically, how do we achieve the pot allocation? Is this something we can do ourselves, or something we need to hand over to the trustees?

**Comment by Scarzy** [comment]
This was brought up at a trustees meeting last night. This is something accounted for by the trustees every year, and does not need to be worried about at a team/event level.
