### ISSUE TITLE
Get a new microSD card for the compbox Pi

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#261]
While trying to set up the in-venue compbox for SR2019 (#118) it emerged that the microSD card SR has for the compbox Pi was not writable. It seems to have the data from SR2017 on it just fine (it boots ok), and it _seems_ to let you write data, but when you try to read the data back it's wrong.

I suggest that we get a card which is at least class 8 and ideally class 10 as the higher write speed of such cards makes quite a substantial difference to the performance of a Pi. (The current one is either class 6 or 8, I unfortunately can't read it clearly enough to tell which)

Note: this is not a blocker for SR2019 as I have a bunch of micro SD cards I'm happy to lend for now.

**Comment by Tyler-Ward** [comment]
We have a box of SD cards in the venue.

**Comment by PeterJCLaw** [comment]
I suggest let's use the one I've prepared for this year, but let's put a new one in the box for next year. If someone could provide me with the new one at some point I'll add it to the box.

**Comment by PeterJCLaw** [comment]
This was fixed at the competition. @Adimote (thanks!) had some spare microSD cards that he donated, so there's a fresh mciroSD card (in packaging) in the same box which contains the compbox Pi 3 and its charger.
