### ISSUE TITLE
Create mechanism to gather feedback from teams

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#265]
As part of feeding in to #258 and for our own learning, we should gather feedback from teams, both team-leaders and competitors, about how the competition went.

We'll want to include this in our email out to the teams as part of our wrap-up email (#266) and it should capture data in a format which is possible to analyse somewhat quantitatively (i.e: bias towards ratings options rather than free text, though obviously there will be plenty of things where we do want free text inputs too). Google forms are pretty good for this.

We should also consider what we actually want to capture here in terms of how we'll use it. It is very easy to design feedback forms which yield data but not actionable information.

I believe this could be a good task for someone who has attended the competition (and so has the context on what SR is) but is otherwise fairly new to SR as it is fairly independent of other things and would involve asking other volunteers about the competition, our structure and organisation.

-----

If there's a topic you think we should gather feedback on, please do add it here.

**Comment by jimmythompson** [comment]
> I believe this could be a good task for someone who has attended the competition (and so has the context on what SR is) but is otherwise fairly new to SR as it is fairly independent of other things and would involve asking other volunteers about the competition, our structure and organisation.

Does this not apply to #267 more than this?

**Comment by jimmythompson** [comment]
In order to help fundraising and as part of our annual report to the Charities Commission, we (@srobo/trustees) need some information and feedback from teams and volunteers. We were hoping to have this done pretty quickly so we can start fundraising for next year. 💸

That said, you're all probably exhausted and deserve a break, so I'd be happy to pick this up. Anyone wanna join me?

**Comment by trickeydan** [comment]
@kierdavis and I did gather some qualitative data from a limited selection of teams yesterday afternoon, so I think it'd be a good idea if we had a chat or at least for me to send you my notes.
