### ISSUE TITLE
Print Photography Studio documents

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#269]
- [x] 1 x [Team checklist](https://docs.google.com/spreadsheets/d/e/2PACX-1vThrXK87yHYc8HGvNwC8ZEeOg6Jmb1a5Z_s7RV5FhxwcuIIt8GDQwUcVdToCMzL8FBYNP-lINBuTyt6/pub?gid=1578555677&single=true&output=pdf)
- [x] 1 x [Venue map](https://github.com/srobo/tasks/files/3038699/event-map.pdf)

**Comment by TomWheal** [comment]
Done
