### ISSUE TITLE
Prepare the tablets for SR2019

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#27]
Once tested (#24) it would be great to inject the team WiFi passwords (#26) into the tablet issued for that team.

Note: only needed if we are actually shipping the tablets _and_ we want to make them really easy to use. (We can ship the tablets even if we don't do this task).

**Comment by RealOrangeOne** [comment]
If we decide not to ship the tablets, I suggest we ship some documentation which shows how to use the same interface from another device (laptop, phone, whatever).

**Comment by PeterJCLaw** [comment]
@RealOrangeOne such as this https://studentrobotics.org/docs/kit/wifi ?

**Comment by PeterJCLaw** [comment]
We decided that we're not shipping tablets this year.
