### ISSUE TITLE
Create livestream screen page

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#273]
This needs to embed the livestream form youtube and somehow exist on the compbox. This could either be a page in the srcomp-puppet repo, or in the srcomp-screens repo.

**Comment by antoinepetty** [comment]
Working on this. Current status: YouTube has no automatic full screen flag, and JavaScript won't let you make something full screen without user input.

**Comment by Tyler-Ward** [comment]
I beileve this is working @trickeydan

**Comment by PeterJCLaw** [comment]
This isn't working as originally descripbed, instead we're just linking direct to the `embed` page. If that's worked as we want, great :)
