### ISSUE TITLE
Publish post-competition blog 

### ISSUE THREAD

**Issue by antoinepetty** [srobo/tasks#274]
Following from #117, we need to publish the posts we prepared.

**Comment by PeterJCLaw** [comment]
@antoinepetty do you know roughly when you'll have this in PR?

**Comment by antoinepetty** [comment]
@PeterJCLaw Ready for review now. https://github.com/srobo/website/pull/147

Not sure whether to wait for the additional photos and maybe a central place where we are putting all photos.
