### ISSUE TITLE
Add consenting volunteers to mailing list

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#275]
We had a checkbox to hear more about future events in the volunteer sign up form, which is effectively giving permission to add them to our mailing list. We need to actually do this

**Comment by PeterJCLaw** [comment]
@Adimote ping on this? It strikes me that it would be really useful to do this before the SR2020 planning kicks off in earnest and specifically before https://github.com/srobo/volunteer-emails/pull/15 is sent.

**Comment by Adimote** [comment]
Better late than never, done!
