### ISSUE TITLE
Ask teams to convince competitors to volunteer

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#276]
As we forgot to mention that we need more volunteers at the end of the prize giving talk, the next best idea is to send an email to teachers to remind their students to volunteer.

(We should make sure its okay for teachers to ask students to share their details with external groups first)

**Comment by RealOrangeOne** [comment]
> (We should make sure its okay for teachers to ask students to share their details with external groups first)

Not sure how relevant this is. All teachers need to do is remind students that SR is volunteer-lead, and where to go, nothing more than that. We don't want volunteers who are still at the college for obvious reasons, so after that it's on the student whether they want to give us their _details_ (in this case, basically just an email address)

**Comment by RealOrangeOne** [comment]
This will be done as part of https://github.com/srobo/tasks/issues/266
