### ISSUE TITLE
Collect photos of SR2019 together

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#277]
Throughout the event, we had lots of volunteers taking photos, we should ensure they're in 1 place so they can be used in future marketing, admired by other volunteers, and competitors.

Really we want this location to be public. In the past, we've used Flickr for this, which has worked out really well.

We'll need to send out an email to volunteers requesting access to their photos (by uploading them, they allow SR to use them), or get them to upload them to a public flickr group.

**Comment by PeterJCLaw** [comment]
We should probably ask volunteers to tag their images with a suitable license if they're happy to do so, or at least explicitly email us with permission to use them if they'd rather not license them freely for all.

While Flickr has worked well in the past, I'm not sure how good a fit it is now that it's under new ownership and their terms have changed a lot. For clarity here: I'm not saying that I know it's a bad fit, only that we should check that it's still a good fit.

**Comment by RealOrangeOne** [comment]
Flickr has changed it pricing policy such that it's no longer a suitable fit. There's warnings when you log in saying existing photos may be deleted (something we may need to look into in future).

My current suggestion is a google photo album, as we can manage permissions as part of the existing gsuite accounts, and add external parties very easily if necessary. Unfortunately it doesn't look like there's licensing options in there, so we may have to go with the implicit "by uploading them here, you allow SR to use the images in accordance with their media consent forms", or alike.

**Comment by RealOrangeOne** [comment]
I've created a Google Photo album (https://photos.app.goo.gl/8vtBZiuM8FXSf79Z8) to store this. I encourage people to upload them there.

**Comment by RealOrangeOne** [comment]
A large number of volunteers have now uploaded their photos here (which is great!), and we've got the high-res versions of the finals and team photos. Only remaining ones are the photo-booth ones, which are apparently with @antonnikitin97.

**Comment by RealOrangeOne** [comment]
We've now got the photo-booth photos in the album now (thanks @antonnikitin97!), so i'm fairly happy to consider this closed. 

As a result, i'll be closing the album from having further photos uploaded, just so it doens't get abused. If volunteers want to upload more, they can contact an existing collaborator (I think, or me) to get it unlocked again.
