### ISSUE TITLE
Investigate USB stick failure mode with Ruggeduinos

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#278]
QMC had an issue in SR2019 with their issued USB stick somehow interacting with their Ruggeduino in a manner which caused their ODROID not to boot. The issue was definitely related to the USB stick because:
- using that USB stick on another (minimal) kit with an equivalent setup showed the same failure mode
- swapping out the USB stick on both the duplicate setup and their kit resolved the issue immediately

On the failing case, the power board's start-button LED would reach a solid on state (but not flashing) and the ODROID's blue LED would come on, but to the point of half brightness.

Other peripheral boards didn't experience the same issue. I can't recall whether the team were using a camera nor whether that was affected.

When the voltage on the USB and various power lines were measured, all seemed to be as expected.

@TomWheal helped investigate this at the time and suggested that if the USB stick had a dead chip on it, then that could be causing the USB host to enter a safe mode of sorts which would interfere with the boot process and detection of the Ruggeduino.

**Comment by TomWheal** [comment]
I’m happy to do this, if I can get QMCs kit

**Comment by PeterJCLaw** [comment]
@TomWheal as you've now got the QMC USB stick, would you like to grab this ticket?
No rush on actually doing the investigation though -- I'm aware it's exam season.

**Comment by TomWheal** [comment]
Ill grab it, but yeh might have to wait a few weeks

**Comment by PeterJCLaw** [comment]
@TomWheal I think you mentioned (in Slack?) that you'd looked at this, was there anything which came from that?

**Comment by TomWheal** [comment]
It was still functional from a pc, however, was drawing enough current to limit set the Odroid into a usb protect function, which isolates the data lines but stupidly still provides power. Nothing can really be done on this apart from suggesting USB replacement when debugging.

**Comment by PeterJCLaw** [comment]
Ah, that sucks. I don't suppose we can detect that that's what's happened somehow?
That said, I'm not sure how we'd alert about it even if we could detect it.

Anyway, thanks for investigating and reporting back. I'm going to close this now the investigation is done. We can still discuss here if there's interest, though I suggest any remediation work have its own ticket.
