### ISSUE TITLE
Replace the yellow and white usb sticks

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#279]
A number of teams during SR2019 had issues with their USB sticks which were resolved by using different ones of their own (e.g: https://github.com/srobo/tasks/issues/278, though other issues were also seen).
If we're keeping on using USB sticks for loading code onto the robots (which seems likely as doing so is a proven and reliable way to do so), then we should replace the USB sticks with some new ones.

The Kingston ones we have for the competition-mode USB sticks are likely suitable replacements.

**Comment by TomWheal** [comment]
Done
