### ISSUE TITLE
Create Instagram Account

### ISSUE THREAD

**Issue by antoinepetty** [srobo/tasks#281]
A few teams at SR2019 were using Instagram instead of Twitter and Facebook. It's probably worth us setting up an account there to promote SR and monitor team progress as we currently do on other Social Media.

(This should probably be handled by Trustees?)

**Comment by trickeydan** [comment]
Pretty sure that trademarks do not cover social media handles... Have you tried @srobo?

**Comment by antoinepetty** [comment]
> Have you tried @srobo?
Yep, srobo is also taken

**Comment by RealOrangeOne** [comment]
Had the accounts `@studentrobotics` and `@srobo` been attempting to impersonate "Student Robotics", we'd have a case. Besides that, it's highly unlikely. `@student_robotics` is almost certainly fine.

**Comment by TomWheal** [comment]
If the accounts have been inactive, Twitter is usually pretty good at reallocating them.

**Comment by trickeydan** [comment]
> If the accounts have been inactive, Twitter is usually pretty good at reallocating them.

Unfortunately, we have to deal with the folks at Facebook for Instagram.  In my experience they try to be as unhelpful as possible. (e.g they wanted a signed letter from SRO president to confirm that we were no longer MiniBots.)

**Comment by RealOrangeOne** [comment]
@antoinepetty can we consider this done now?

**Comment by antoinepetty** [comment]
Yes
