### ISSUE TITLE
Write up notes from Kit Interviews

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#282]
I need to write these up and publish the conclusions.

**Comment by trickeydan** [comment]
This was done a long time ago and sent out via email iirc. I do not have the original notes anymore.

**Comment by PeterJCLaw** [comment]
@trickeydan Any chance you can recall the subject line of the email? (Just trying to find it, mostly for curiosity)

**Comment by trickeydan** [comment]
I believe it was `Conclusions from SR2019 Team Interviews`, and was sent to the old `core-team` mail group.

**Comment by PeterJCLaw** [comment]
Huh, I don't seem to have that email (or variations on that either); most odd.

**Comment by trickeydan** [comment]
> Huh, I don't seem to have that email (or variations on that either); most odd.

I'll attempt to dig it out later do you :)
