### ISSUE TITLE
Have the first post-SR2019 Kit Collation event

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#284]
We need to clean & tidy the kits which were issued for SR2019, plus test them so we know which need fixing before the next competition.

As we've not got all the kits back yet this event will be for the kits which we have available, though hopefully that's most of them. This will also put us in a better position to know what kit remains unaccounted for so that we can chase schools. This is the first child event within #283.

This is documented as a [Kit Collation Event](https://srobo.github.io/runbook/kit/hardware/kit-collation/). @PeterJCLaw is organising this event and has taken on the Kit Coordination related roles.

The primary objective of this event is to Checkin, Visually inspect and Clean the kits we currently have. If we can also Test the parts, that would be ideal.

Sub Tasks:
- [x] book room (thanks @trickeydan!)
- [x] advertise to volunteers
- [x] obtain supplies
- [x] bring kits from storage (thanks @prophile @andybusse @RealOrangeOne)
- [x] return kits to storage

Required equipment (inspection & cleaning):
- Laptops, barcode/QR scanners, label printer
- Bowl, J cloths, washing up liquid, IPA, label residue remover

Required equipment (testing, from https://github.com/srobo/kit-maintenance-docs/, excluding that which we'll have on hand from kits):
- Batteries:
  - Multimeter
  - 20A load
  - Thermometer
  - Stopwatch
  - Hobby King Cell Meter 8 LiPo cell monitor
  - Insulation tape
- Motor board:
  - Bench PSU
  - [7.5mm CamCon plug](https://uk.farnell.com/3882275) to fork terminals
  - 2x motors with [5mm CamCon plugs](https://uk.farnell.com/3881854)
- Power board:
  - Bench PSU
  - High-current PSU (>30A @ 12V)
  - Multimeter, 4× 1.3Ω--1.5Ω loads
  - XT60 male to fork terminals (for Bench PSU)
  - XT60 male to [7.62mm CamCon plug](https://uk.farnell.com/1793033) (for high current PSU)
- Servo Board: Bench PSU, 1x servo
- USB Chargers: (optionally) 2x 4-way extension leads

Rough (work-in-progress) schedule for the day:
- Driving crew meet at the container about 10am
- Volunteers meet in Southampton at 11am
- Unpack the cars (10 minutes)
- 11:15 (ish, traffic etc. depending) welcome, intro the plan
- 1pm break for lunch (likely Sainsbury's?)
- 5pm start packing up
- 6pm leave, driving crew return things to the container

This event _may_ also provide opportunities to do the following tasks, however they are _secondary_ to the task of kit tidying and cleaning and will happen _only_ if we have a surplus of time or people.
- #209 Storage inventory audit
- #210 Southampton inventory Audit
- #285 Kit return pack for HRS

**Comment by PeterJCLaw** [comment]
On the required equipment: most of it is in the container. The scanners are the main thing we'll need to look out for. I'm not too worried if we don't bring the kit to test the parts as I suspect we may not get that far.

@prophile would you be able to lend us some washing up bowls?

Ideas on where to get isopropyl alcohol or label residue remover would be most welcome (Amazon has some IPA, but delivery times are likely an issue at this point). I can manage to get the rest of the cleaning supplies from Tesco easily enough.

@trickeydan do you think it would be OK for us to borrow from the cupboard/SRO:
- the Label Printer (I think it probably still has a reel of SR's labels in it from the competition)
- the motors attached to the Tudor robots (not that we'd detach them, though I'm given to understand that while the chasis are SRs, the motors may not be)

**Comment by PeterJCLaw** [comment]
https://www.amazon.co.uk/XMykal-Sticky-Stuff-Remover-250ml/dp/B00T22HKXM might do for label residue removal?

**Comment by trickeydan** [comment]
Label printer is fine as always.

You can borrow the Tudor motors if you want, but I'd recommend the Motor test rig instead.

**Comment by PeterJCLaw** [comment]
Oh, I'd forgotten about the test rig. That's definitely a better idea, thanks.

**Comment by PeterJCLaw** [comment]
We're going to get 2 × https://www.amazon.co.uk/Isopropyl-Rubbing-Alcohol-First-Antiseptic/dp/B007ECG29U/ and not worry about label residue remover.

**Comment by PeterJCLaw** [comment]
This happened.

We managed to [check-in](https://srobo.github.io/runbook/kit/hardware/kit-collation/#checkin) all the parts from the kits we had available, plus many of the battery-related parts. There were some boxes of other spare parts which we'd hoped to review, but didn't get around to.

In doing so we counted:
- 23 ODROID power cables in spec; 8 in various degrees of brokenness
- 26 screwdrivers
- 28 usb sticks; state unknown (many of these are the yellow and white type we [want to replace](https://github.com/srobo/tasks/issues/279) though)

We also managed to [visually inspect](https://srobo.github.io/runbook/kit/hardware/kit-collation/#visual) the majority of parts. Notably we didn't get this done for the battery-related parts.
@andybusse @sedders123 did the power boards get visually checked? I had thought that we'd run out of time for that, yet the inventory indicates that they were checked.

We were able to [clean](https://srobo.github.io/runbook/kit/hardware/kit-collation/#clean) the motor boards, odroids, ruggeduinos, servo boards and webcams.

As expected we didn't get around to testing any of the parts.

**Comment by PeterJCLaw** [comment]
Things we should improve for the future:
- need to have some way to labelling the contents/role of RUBs; in the past we've written on tape and stuck that to the boxes, but we overlooked that this time
- the current runbook instructions feel optimised for a small group (<= 4 people), different approaches work better when you have more people than that
- inevitably you end up using areas of the room or RUBs or both to denote the state of items (broken, checked, cleaned, etc.) before it can be recorded in the inventory. It would be great to have some physical signage to indicate this (maybe combine with the first point about being able to label boxes?)
- the approach to splitting tasks varies considerably if you have more than one person able to adjust the inventory; ditto for having multiple barcode scanners. While not everyone needs to be able to do this, this should be a consideration when planning the approach.

**Comment by PeterJCLaw** [comment]
Inventory commands I found useful:
```
sr inv-query 'path:kit-collation-location-2019 !type:*rub*' --codes | xargs sr inv-mv 
sr inv-query 'path:kit-collation-location-2019 !type:*rub*' --codes | xargs sr inv-set-attr physical_condition unknown 
sr inv-query 'path:kit-collation-location-2019 !type:*rub*' --codes | xargs sr inv-set-attr condition unknown 
```
Plus other variations on that theme.

`xargs -l sr inv-mv` was also useful as always.

**Comment by RealOrangeOne** [comment]
As we've now had this event, can we close this issue, and open another to track a potential future day?

**Comment by PeterJCLaw** [comment]
I'm holing this open pending a response from @andybusse and @sedders123 about the state of the power boards.

**Comment by sedders123** [comment]
I think they were checked as they were moved to the checked area of the room. Having said that I don't remember checking them myself.

**Comment by PeterJCLaw** [comment]
Hrm, in which case we probably really do have some which have gone missing.
