### ISSUE TITLE
Arrange to get a kit return pack to HRS

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#285]
It turns out that HRS managed to leave the competition venue without collecting a kit-return-pack, so we need to find/create one of those and send it to them.

There _might_ be one of these in the container, so we should see if we can find it easily when we're there for #284.

**Comment by trickeydan** [comment]
I believe that one of these may have been left in the Broom Cupboard after SR2019.

**Comment by PeterJCLaw** [comment]
Ah, now you mention it I do vaguely recall them being in a bag which ended up inside a Sainsbury's bag in the cupboard.

**Comment by PeterJCLaw** [comment]
It turned out that the pack I was thinking of was in the container.

However we've already replied to HRS with instructions otherwise, so this task is no longer relevant.
