### ISSUE TITLE
Get scaff invoice

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#293]
We are missing the copy of the scaff hire invoice @Adimote has this.

**Comment by Adimote** [comment]
I have the quote, not the invoice. The Invoice was sent directly to Diane via post

**Comment by Tyler-Ward** [comment]
This has now been paid although it would be good to get the quote added to our records for future reference.

**Comment by Tyler-Ward** [comment]
I have the quote and this has been saved for future use
