### ISSUE TITLE
Get missing recipts/claims

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#294]
We are still missing some receipts these need to be submitted soon.

**Comment by Adimote** [comment]
Diane probably has the itemised UPS receipt and the Scaff invoice, and I've confirmed the receipts are correct for competition refreshments, am I missing any other receipts?

**Comment by Tyler-Ward** [comment]
All but one receipt has been submitted, the remaining receipt will now need to be submitted direct to the trustees due to core team dissolution.
