### ISSUE TITLE
Investigate UPS cost disparity

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#296]
@Adimote I believe you have the details for this.

**Comment by Adimote** [comment]
Sadly it looks like the UPS website only lets you look up to 90 days in the past for previous shipments, and the only emails I received were shipment confirmations, not prices. We set Diane up with the actual payment account so I'd expect she will actually have access to the broken down payments

**Comment by Tyler-Ward** [comment]
This has been accepted in its current state, however we need to be better at storing receipts/itemised costs from suppliers in future.
