### ISSUE TITLE
check code syntax in Thonny 

### ISSUE THREAD

**Issue by MineringGuy** [srobo/tasks#298]
Is there a way to check code syntax in the Thonny before running a program
-- that is, a tool similar to Run | Check Module in IDLE?

**Comment by RealOrangeOne** [comment]
Thanks for the report, but I think you've raised this issue against the wrong repo. 

This issue tracker is specifically for tracking tasks for Student Robotics events. We have no control over Thonny or how it's operated.

It looks like the correct issue list for Thonny is https://github.com/thonny/thonny/issues, have you tried raising the issue there? I suspect you'll get some much better answers!

**Comment by MineringGuy** [comment]
Many thanks for your advice

________________________________
