### ISSUE TITLE
Record the Kickstart 

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#3]
Lots of teams miss out on the intro presentation, most teams really should be able to see it, and we're able to livestream competitions now, so surely we should be able to livestream/record Kickstart.

It's worth noting we don't have media consent at kickstart, so camera angles need to avoid seeing students.

**Comment by PeterJCLaw** [comment]
This didn't happen on our part, though there was a team in London who seemed to be filming it on a phone.
