### ISSUE TITLE
Have a second post-SR2019 Kit Collatoin event

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#301]
We need to clean & tidy the kits which were issued for SR2019, plus test them so we know which need fixing before the next competition. This athe first child event within #283.

This is documented as a [Kit Collation Event](https://srobo.github.io/runbook/kit/hardware/kit-collation/). @PeterJCLaw organised this event.

The primary objective of this event is to Checkin, Visually inspect and Clean the kits we currently have. If we can also Test the parts, that would be ideal.

**Comment by PeterJCLaw** [comment]
This happened. We had some of the kit parts from the first session (#284) (as well as another box of charger PSUs) and managed to:
- test:
  - servo boards
  - webcams
  - ruggeduinos
- physically check and clean:
  - battery charger power supplies
  - battery chargers
  - some lipos and lipo bags
 
We identified a small number of broken items, some of which are likely fixable.

The inventory is up to date as of https://github.com/srobo/inventory/commit/f0d4e4c1139139e0a0947e131b70167827c593d4

**Comment by kierdavis** [comment]
FWIW we also checked and cleaned (but not tested) power boards.

**Comment by PeterJCLaw** [comment]
Ah, so we did. Thanks; have updated the list so it's all in one place.
