### ISSUE TITLE
Have the third post-SR2019 kit collation event

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#303]
We need to clean & tidy the kits which were issued for SR2019, plus test them so we know which need fixing before the next competition.

While we (still) don't have all the kits in one place, we can usefully make progress on testing the kit which we have. This will also put us in a better position to plan for SR2020. This is a child event within #283.

This is documented as a [Kit Collation Event](https://srobo.github.io/runbook/kit/hardware/kit-collation/), though as we will be focussing on the "test" step, https://github.com/srobo/kit-maintenance-docs may be a more useful reference. @PeterJCLaw is organising this event and has taken on the Kit Coordination related roles.

The primary objective of this event is to Test the motor boards, power boards and Odriods we currently have. If we can also progress the parts from recently arrive kits (those still with @RealOrangeOne) too, that would be a bonus.

Sub Tasks:
- [ ] organise venue
- [ ] advertise to volunteers
- [ ] obtain supplies
- [ ] bring kits from storage
- [ ] (optional, venue depending) return kits to storage

Required equipment (testing, from https://github.com/srobo/kit-maintenance-docs/, excluding that which we'll have on hand trivially):
- Motor board:
  - Bench PSU
  - [7.5mm CamCon plug](https://uk.farnell.com/3882275) to fork terminals
  - 2x motors with [5mm CamCon plugs](https://uk.farnell.com/3881854)
- Power board:
  - Bench PSU
  - High-current PSU (>30A @ 12V)
  - Multimeter, 4× 1.3Ω--1.5Ω loads
  - XT60 male to fork terminals (for Bench PSU)
  - XT60 male to [7.62mm CamCon plug](https://uk.farnell.com/1793033) (for high current PSU)
- Odriod:
  - Odriod power cable
  - Power board on|off loop (CamCon + wire)

Rough (work-in-progress) schedule for the day:
- TBD

**Comment by PeterJCLaw** [comment]
I was originally planning for this to be this weekend, but for various reasons that won't be the case.

**Comment by TomWheal** [comment]
This is being merged into a kit prep weekend. #353 is keeping track of the organisation of this

**Comment by PeterJCLaw** [comment]
Should we close this task then?

**Comment by TomWheal** [comment]
Done
