### ISSUE TITLE
Announce dates for kickstart to teams

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#307]
Now that we've announced kickstart to teams, we need to define (and announce) the dates

## Defining the dates

- Pick a date (currently looking at 19th / 26th October)
- Book venues
    - [ ] Southampton (University of)
    - [ ] Cambridge (University of, Raspberry Pi Foundation)
    - [ ] Aldgate, London ([Thread](https://www.thread.com/) HQ)

The primary blocker on these is the availability of the Raspberry Pi Foundation. It's assumed there's rooms in Southampton (pending booking of course), and Thread HQ is generally free as it's a business, and we're after a booking on a weekend.

## Announcing the dates

- [x] Email (https://github.com/srobo/team-emails/pull/27)
- [ ] Social Media (@antoinepetty)
- [ ] Website event pages

**Comment by trickeydan** [comment]
Worth noting, there's a comment from Diane in the key dates Google doc asking for an early kick-start due to early exams this year. Have you considered this in the date decision?

**Comment by RealOrangeOne** [comment]
We have. 19th is definitely the ideal, but bringing things too early leads to less time to organise things, which means we end up rushing things, and likely miss things.
