### ISSUE TITLE
Create a budget for the SR2020 Competition Programme

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#310]
We need to prepare a budget for the SR2020 Competition Programme. We can almost certainly copy the one from SR2019 and lightly modify it. Per the discussion with the trustees at the SR2019 Core Team dissolution meeting, the budget we present to them doesn't need to be massively detailed, though we likely do want a fairly detailed budge for ourselves.

Our first expenditure is likely to be around materials for [Kickstart](https://github.com/srobo/tasks/milestone/6), so we'll almost certainly want a budget before then.

**Comment by PeterJCLaw** [comment]
@Adimote I believe you're responsible for budgetary matters this year?

**Comment by Adimote** [comment]
Can confirm

**Comment by Adimote** [comment]
I have a budget for Southampton, but not for alternative venues. I'll send what I have to the trustees to keep them in the loop
