### ISSUE TITLE
Arrange to get kits to teams not attending Kickstart

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#33]
Not all teams are coming to Kickstart. Those who aren't will need to get their kits another way.

This usually means getting them shipped via some form of delivery or courier service.

We'll need to arrange with each team an address for their kit to be delivered to and then have the kits picked up from somewhere (ideally from somewhere near where they were packed).

**Comment by Tyler-Ward** [comment]
The remaining kits in southampton have been bubble wrapped, they might still need some extra paper for padding. Also they have been labeld for their destination team.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward I saw some noise on Slack -- did this happen? (cc @Adimote @RealOrangeOne)

**Comment by Tyler-Ward** [comment]
some have been shipped some are still awaiting shipping

**Comment by Tyler-Ward** [comment]
All first kits have been delivered
