### ISSUE TITLE
Ship SR2020 kits to Kickstarts

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#334]
Teams will want kits at Kickstart so we need to ship the relevant kits to each of the Kickstart venues.

### Original

[kickstart/kit/ship-kickstarts](https://github.com/srobo/recurring-tasks/blob/master/kickstart/kit/ship-kickstarts.yaml)

### Dependencies

 * #325 Allocate SR2020 kits to teams

**Comment by RealOrangeOne** [comment]
The kits required for the Southampton kickstart are currently in @TomWheal 's garage, ready to be moved straight to the Southampton venue.

The remaining kits have been sent to the container. Getting these to the Cambridge and London kickstarts are the next challenge. I'll try and work out some method of doing this.

I'm open to suggestions, no matter how crazy!

**Comment by PeterJCLaw** [comment]
@RealOrangeOne is this now done? I think you did the handover this evening?

**Comment by RealOrangeOne** [comment]
I think it's done enough for this. Diane will deliver the kits to Cambridge Saturday morning.
