### ISSUE TITLE
Book venue for kit packing session

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#34]
We need somewhere (ideally near Southampton or our Storage locker, the former is better) where we can pack the kits.

**Comment by Tyler-Ward** [comment]
53/4025 booked

**Comment by PeterJCLaw** [comment]
Awesome, thanks @Tyler-Ward. Just to check -- is that just Saturday or both days? (I hope we won't need both days, but I'd rather have the fallback)

**Comment by Tyler-Ward** [comment]
it is booked for both days
