### ISSUE TITLE
Ship SR2020 kits to overseas Teams

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#352]
Teams overseas need their kits shipped to them. This has mostly been the German teams in the past few years, which have been shipped together to the German Kickstart. This is intentionally separate from the shipping to Kickstarts as it involves an international delivery.

### Original

[kickstart/kit/ship-overseas](https://github.com/srobo/recurring-tasks/blob/master/kickstart/kit/ship-overseas.yaml)

### Dependencies

 * #325 Allocate SR2020 kits to teams

**Comment by PeterJCLaw** [comment]
@antoinepetty is looking into what courier services we can use for this. Likely collection would be from either @PeterJCLaw or @RealOrangeOne.

**Comment by antoinepetty** [comment]
As mentioned in https://github.com/srobo/tasks/issues/343 UPS is looking like a reasonable option, costing £35.75 (unsure if this is VAT inclusive)

**Comment by RealOrangeOne** [comment]
See https://github.com/srobo/tasks/issues/343#issuecomment-549041339 for sequence of events.

**Comment by RealOrangeOne** [comment]
I've done all I can.

**Comment by PeterJCLaw** [comment]
I understand there are still some issues getting kits to overseas teams, presumably due to issues shipping the batteries?

If that is the case: is there a reason that we cannot ship the kit _without_ batteries, in order that the teams can make _some_ progress and then work out the batteries issue later?

As a specific suggestion on the batteries -- could we order some new batteries for delivery to the teams? This moves the delivery issue onto the delivery company of the shop we're using, who are likely well placed to solve the issue anyway.
