### ISSUE TITLE
Create team-leader accounts

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#36]
The team leaders need to have their user accounts before Kickstart so that they can issue team members with their accounts and so that they can do things at Kickstart.

Blocked on:
- #20 Deploy competitor services

**Comment by RealOrangeOne** [comment]
#25 has been closed, so this is partially unblocked.

**Comment by PeterJCLaw** [comment]
This happened this morning. Many have created competitor accounts. I think we're good here, but I'll check whether the team-leaders all got them ok at some point.
