### ISSUE TITLE
Setup team leader accounts for SR2020

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#362]
In order to allow the competitors to use the various hosted services we provide, we need to give them user accounts.
Typically we create the accounts fo the team leaders and let them create the accounts for the individual competitors. This task is therefore about the user accounts for the team leaders.
Included in this is creating the neccessary team and school groups within the auth system.

### Original

[kickstart/services/user-accounts/team-leaders](https://github.com/srobo/recurring-tasks/blob/master/kickstart/services/user-accounts/team-leaders.yaml)

### Dependencies

 * #312 Allocate TLAs for SR2020

**Comment by RealOrangeOne** [comment]
This has been done :tada: Credentials have been sent out.
