### ISSUE TITLE
Print disclaimer forms

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#38]

**Comment by Adimote** [comment]
Henry said he printed at least one, he hasn't confirmed he's printed multiple yet >.>

**Comment by Adimote** [comment]
Confirmed he's printed all of them

**Comment by PeterJCLaw** [comment]
@Adimote are you going to give some to @prophile, or do I also need to print some of these for London? If the latter, please can you link to the doc, re-open this and assign it to me (so I know it needs doing).

**Comment by PeterJCLaw** [comment]
For reference: https://drive.google.com/open?id=1iXGEjtjZUE3u9znHX8fTaf8m-EQO8SA9

@Adimote do you know where the source for that document is?
