### ISSUE TITLE
Update kit disclaimer forms for SR2020

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#389]
As the kits contain valuable and potentially dangerous components, many of which are not CE marked, we normally ask the team leaders to sign a form accepting responsibility for it and promising to return it at the end of the year.
We need to update the form to at least have the right year on it, as well as any other changes related to the kits which may have happened.

### Original

[kickstart/kit/update-disclaimer-forms](https://github.com/srobo/recurring-tasks/blob/master/kickstart/kit/update-disclaimer-forms.yaml)

**Comment by RealOrangeOne** [comment]
Thanks to https://github.com/srobo/tasks/issues/390#issuecomment-536171662, we now have access to the form source to make the changes.

I've made the changes required to the doc, and uploaded them as a PDF to https://drive.google.com/a/studentrobotics.org/file/d/1lPfv1ZyQ_BSrzYnhYxy0sCbzvkVq8zJP/view?usp=sharing.

In future, it might be nice to convert the document to something more versionable, ie LaTeX, although that's something for another time.
