### ISSUE TITLE
Print kit disclaimer forms

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#390]
As the kits contain valuable and potentially dangerous components, many of which are not CE marked, we normally ask the team leaders to sign a form accepting responsibility for it and promising to return it at the end of the year.
Once these have been updated, we need to print enough of them for each venue to have copies for team leaders to sign.

### Original

[kickstart/print-disclaimer-forms](https://github.com/srobo/recurring-tasks/blob/master/kickstart/print-disclaimer-forms.yaml)

### Dependencies

 * #389 Update kit disclaimer forms for SR2020

**Comment by RealOrangeOne** [comment]
@PeterJCLaw do you know where the source for this document is? Can't find it on cgit or GitHub. 

Alternatively, @Adimote, as I think you made the changes last year?

**Comment by PeterJCLaw** [comment]
According to the runbook (https://srobo.github.io/runbook/kit/#kit-disclaimer) it's in a repo on bitbucket. Unfortunately when logging into bitbucket, I can't see that repo. I suspect it's around somewhere though. I'll have a look at home.

Alternatively @richardbarlow or @jimmythompson may know where it is.

**Comment by richardbarlow** [comment]
I've emailed the source document from the BitBucket repo to competition-team@ (can't attach it to this comment).

**Comment by Adimote** [comment]
I'm told  Jake has updated the disclaimer form, @RealOrangeOne where did you put it?

**Comment by RealOrangeOne** [comment]
(For reference, said location is https://drive.google.com/a/studentrobotics.org/file/d/1lPfv1ZyQ_BSrzYnhYxy0sCbzvkVq8zJP/view?usp=sharing)

**Comment by TomWheal** [comment]
Ill be printing one for every kit. Do they need one outside the kit to sign as well?

**Comment by Adimote** [comment]
@TomWheal Yes. In the meeting we just had, we mentioned maybe modifying them to put the box part code on the form, so we can record the part code given to the team and their consent on the same form.

**Comment by RealOrangeOne** [comment]
@Adimote if we're doing that, could we add an issue for it, rather than trying to remember it's happened here.

I'm also not sure there's a need to do it anyway. The disclaimer form is specifically a form which states they understand about taking ownership of a kit, it's not a signout form for a kit. IIRC at previous SR competitions (namely SR2014), this was done using a separate form. If we want one of those forms (which is smarter than a Google Sheet created on the day), then we should create an issue for _that_.

**Comment by kierdavis** [comment]
Kit disclaimer forms were printed and put inside each team kit box during kit packing. I don't think any changes were made to the form since previous years.

Can this be closed now?

**Comment by RealOrangeOne** [comment]
The forms in the boxes have the wrong year on, and the rules link renders _weirdly_ (I blame libreoffice and late nights!).

We sent teams the forms out before the event this year to speed up signing and issuing of kits, so far we've had a couple back. We'll still need to print some for each event.

**Comment by PeterJCLaw** [comment]
This is now redundant in favour of #406.
