### ISSUE TITLE
SR2020 Kickstart: Southampton venue

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#394]
Per https://github.com/srobo/tasks/issues/313, we want a Southampton venue for Kickstart.

We've typically used B32's large lecture theatre for the presentation and, I think, the B25 computing labs for the micro games. There was a suggestion to investigate using the Zepler level 2 labs for the micro games this year though.

**Comment by PeterJCLaw** [comment]
@HopeShaw would you be able to own investigating and booking this?

**Comment by sedders123** [comment]
@RealOrangeOne has confirmed on slack that a lecture theatre in Building 7, and the computing labs in building 25 have been booked
