### ISSUE TITLE
SR2020 Kickstart: Cambridge venue

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#395]
Per #313, we'd like a Cambridge venue for Kickstart.

Suggestion was to explore either somewhere at the Uni (via @JennyLynnFletcher), or possibly @didottyd had some alternative spaces.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne were you in contact with @didottyd about this? If so, do you want to own this and/or would it make sense to hand over to @JennyLynnFletcher if she's up for that and it helps to have someone geographically closer?

**Comment by didottyd** [comment]
If there is a date, I can find out about booking rooms at Pi HQ. Happy to
liaise with Jenny! Di

**Comment by PeterJCLaw** [comment]
@didottyd great, thanks. We've been working on one of either Saturday the 19th or 26th October, depending on which is available across all the venues we're interested in. It would be great to know if Pi HQ is available on those dates.

**Comment by PeterJCLaw** [comment]
Apparently Pi HQ isn't available on the 26th and per https://github.com/srobo/tasks/issues/313#issuecomment-530259811 we're now only really looking at that date at this point.

**Comment by PeterJCLaw** [comment]
Closing as this is all booked.

**Comment by PeterJCLaw** [comment]
Reopening as there are still website updates which need to be made.

**Comment by PeterJCLaw** [comment]
The website has been updated.
