### ISSUE TITLE
SR2020 Kickstart: northern venue?

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#396]
We've been contacted by a teacher asking about a venue far in the north (and with some suggestions, which I'm deliberately not posting here for now). This could be great if there are enough teams for it to be useful and we have enough volunteers able to travel for it to be viable.

We also need to confirm that there would be a venue which meets our requirements (see #313).
This likely involves talking to the teacher more to see what the venues have and how viable this would be.

We probably won't have enough volunteers to run four Kickstarts, so this might mean not running one of the others if that makes sense.

**Comment by RealOrangeOne** [comment]
This isn't happening this year.
