### ISSUE TITLE
Create SR2020 kickstart presentation

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#397]
Kickstart events require a presentation to go through what student robotics
is, what the competition cycle looks like, and details of the game.

The presentation needs to be given at each venue, so will be presented by
multiple people.

The presentation usually covers:

1. What student robotics is
2. Who the volunteers are
3. Schedule for the year
    - How long the competition is
    - Tech days date, time, etc..
4. General robot design tips
5. The kit
    - Hardware
    - Software
    - The docs
    - The forums
6. Health and safety
    - How to charge your batteries
7. Awards
8. Schedule for the rest of kickstart

Historical presentations can be found on https://github.com/srobo/tasks/issues/13 and https://github.com/srobo/tasks/issues/10.

**Comment by RealOrangeOne** [comment]
I've started work on the presentation at a very high level, and will slowly be refining and adding detail. Comments welcome!

https://docs.google.com/presentation/d/15tmzBDA4j6sz8HpMMT2gyH8JeLh8QxvaTm2LypHmrXk/edit?usp=sharing

(Requires an SR Google account)

**Comment by PeterJCLaw** [comment]
First robot movement was missing from the presentation, I've added it.

**Comment by PeterJCLaw** [comment]
I've also put some comments in the docs.

**Comment by PeterJCLaw** [comment]
I think this is now created, should we close this?

**Comment by RealOrangeOne** [comment]
Now that it's both been created and reviewed, I think this is done enough.

**Comment by Adimote** [comment]
I've added some nice slides to the game at
https://docs.google.com/presentation/d/16SMAAMYt5uv2e9MVczxKy_U3NTmDlaH2ksoBuc0AblQ/edit?usp=sharing

**Comment by Adimote** [comment]
@PeterJCLaw  and @RealOrangeOne feel free to update your copy.
