### ISSUE TITLE
Decide who will present the SR2020 kickstart presentations

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#398]
The presentation needs to be given at each venue, so will be presented by multiple people. It's recommended the person who wrote the slides be one of the people to present.

## Venues

- [x] Southampton: @RealOrangeOne 
- [x] London: @PeterJCLaw 
- [x] Cambridge: @Adimote 

## Dependencies

- #397: Create kickstart presentation

**Comment by PeterJCLaw** [comment]
Assuming I'm at the London one (rather than ending up elsewhere #396), I'm happy tot give the presentation there.

**Comment by Adimote** [comment]
I'll do the Cambridge kickstart :)
