### ISSUE TITLE
Livestream kickstart?

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#399]
Every year, we have many teams which can't attend a kickstart, but may benefit from a more documented, formal introduction to Student Robotics and the year's game.

A way of achieving this would be to live stream the Southampton kickstart (#394) presentation (#397) so teams who can't attend can watch live, or after the fact.

## Requirements
- A camera (a standard webcam would be fine)
- A feed of the presentation ideally (screencapture off the presentation machine, somehow)
- A computer to run this (likely [OBS](https://obsproject.com/))
- Volunteer(s) to hang around in chat and relay questions to speaker

Would be interested to know other people's thoughts.

**Comment by RealOrangeOne** [comment]
We've announced to teams we may have a livestream, so upgrading the status a little.

**Comment by antoinepetty** [comment]
The planning for this is in progress. I don't have any particularly brilliant webcams capable of streaming, so if anyone has one in the Southampton area please let me know and I'll come and borrow it from you. :)

**Comment by RealOrangeOne** [comment]
I have an HD webcam which you're more than welcome to use, although it does have a manual focus ring, which may not be ideal.

The webcams in the kit are 720p, which might also be enough for this.

I also have access to a [Blue Yeti](https://www.bluedesigns.com/products/yeti/) if we need something slightly better than webcam mics?

**Comment by antoinepetty** [comment]
Both of those things would be very helpful. Will you be at the Southampton kickstart?

I have a 720p webcam (the same as the Logitech ones in the kit) 
The Blue Yeti mic may not be as good from a distance compared to close range, but still probably better than the webcam ones. Thanks

**Comment by RealOrangeOne** [comment]
Sure, i'll be sure to bring them down! We can always test it before actually streaming!

> Will you be at the Southampton kickstart?

I'm the one giving the presentation :stuck_out_tongue_winking_eye: :joy:

**Comment by antoinepetty** [comment]
Steam testing successful, I greenlight advertising this.

**Comment by antoinepetty** [comment]
Kickstart was livestreamed: https://www.youtube.com/watch?v=OHYT5iO352c
