### ISSUE TITLE
Create a demo bot

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#4]
Load it up with working code, so we can actually have a working demo at kickstart for the first time ever.

We should try to ship one of these in each venue

copied from https://github.com/srobo/core-team-minutes/issues/50

**Comment by Adimote** [comment]
> Need is a strong word. I think this something that would be nice to have, but is far from required. Previous competition video will probably make an appearance in #41, so teams will get an idea of what robots created with the kit are capable of.
from: @RealOrangeOne

**Comment by RealOrangeOne** [comment]
Southampton simply had a tudor on the table, which seemed to do well enough. Perhaps for future events we can revisit this requirement
