### ISSUE TITLE
Inject wire into the Southampton Kickstart's teams' kits

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#40]
Since the kits are now in separate places, we'll have to add the wire separately.

Teams should each get *2.5m* of each of the thinner colours of wire and *1.8m* of each of the thicker colours of wire.

Note: an earlier version of this ticket had the lengths wrong.

**Comment by PeterJCLaw** [comment]
@kierdavis do you know whether this happened?

**Comment by kierdavis** [comment]
@PeterJCLaw yeah, @Tyler-Ward and Dave Newman handled it the night before.

**Comment by PeterJCLaw** [comment]
Great, thanks Tyler & Dave.
