### ISSUE TITLE
Get tee-shirts for SR2020

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#400]
We'll need tee-shirts for volunteers for SR2020. We may have enough in stock, though that needs checking. Additionally or alternatively we may want to get some more.

**Comment by TomWheal** [comment]
I have the files and information used to buy the ones for the competition last year, I'd be happy to forward the email chain on to whoever is doing this so the exact same can be ordered if we want matching

**Comment by Adimote** [comment]
I've put in for a quote at Carolines, general impression was we have 'some' tshirts in storage, and I don't think we'll be re-designing them for the competition so I think it's safe to over-order slightly for kickstart

**Comment by Adimote** [comment]
Turns out Caroline's interpreted my quote as an order, we now have tshirts waiting for collection which Tom wheal will pick up for us.

The quantities are:
S - 4
M - 10
L - 7
XL - 1

This is in addition to the unknown amount in the cupboard.

**Comment by TomWheal** [comment]
I now have the new order for southampton
