### ISSUE TITLE
Write onboarding emails for volunteers

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#401]
Whenever someone signs up to the volunteer mailing list, we should automatically send them some onboarding emails to smooth their joining into the community.

The emails should contain:
- Link to slack,
- Link to the `srobo` google groups list?
- Link to runbook
- Link to tasks list?
- Link to ops manual
- {Add more here}

**Comment by trickeydan** [comment]
Not sure if it will be ready in time, but we should add info on team specific stuff here as well.

**Comment by PeterJCLaw** [comment]
@Adimote are you still planning to work on this? Alternatively, the @srobo/marketing-team have been handling this recently, perhaps it would make sense to sit with them?

**Comment by antoinepetty** [comment]
We changed the automated email to include some basic info but things like the tasks list are a bit heavy for new starters so we generally handle this on a follow up call. (We also don't directly link to Slack; we screen volunteers before sending them an invite. This is mostly just to confirm they're 18+)
