### ISSUE TITLE
Nominate a Head Judge

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#402]
We need a canonical person for rules queries, such that they have the final say on any rules queries.

This needs nominating before kickstart.

**Comment by trickeydan** [comment]
Is this open to any volunteer to nominate? If so, what would the mechanism for nomination be?

**Comment by mltnhm** [comment]
Oops, GitHub is terrible on mobile

**Comment by prophile** [comment]
I’m open to doing this if people are happy for me to do so.

**Comment by RealOrangeOne** [comment]
I'm certainly happy with that. Although I'd be interested in shadowing in an attempt to remove any bus factoring if that's cool?

**Comment by prophile** [comment]
Sounds eminently sensible.
