### ISSUE TITLE
Create post-kickstart news article for SR2020

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#407]
At Kickstart we'll be publishing the rules and getting the teams to do various kit things.
We should publicise this on {the website,social media,etc.} as soon after the event as we can, which will also keep up our online presence.

Things we should mention:
- that we had three locations, the number of teams who attended, etc.
- anything particularly interesting from the days (optional; if such things happen)
- a link to the rulebook (it'll be in the usual place in the docs)
- a summary of the game
- a link to the kickstart microgames (see also #8)

**Comment by PeterJCLaw** [comment]
(Antione agreed to look into this during our previous Competition Team meeting)

**Comment by PeterJCLaw** [comment]
@antoinepetty just wondering if you had an update on this?

**Comment by antoinepetty** [comment]
This is half done, see the 2019-post-kickstart branch on website. Aiming to finish tonight.

If you have some time, the thing that needs the most eyes is the game description. Thanks

**Comment by RealOrangeOne** [comment]
I've deleted said branch. It knew too much! (It had all the game details in).

I'm definitely happy to help review this evening :)

**Comment by RealOrangeOne** [comment]
This shipped.
