### ISSUE TITLE
Update the API (and overlay) for slightly smaller token markers

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#408]
The version of the API which we shipped in https://github.com/srobo/tasks/issues/365 has (I think) got the slightly larger token marker size that we were originally planning to use. The API therefore needs updating to use the slightly smaller size in the rules (and docs, etc.).

This has no impact on Kickstart, though we should fix it shortly thereafter.

**Comment by PeterJCLaw** [comment]
@kierdavis I think you were interested in doing this?

**Comment by kierdavis** [comment]
I would be happy to do this but I don't know what the process is for generating the base filesystem and target filesystem needed in order to create an overlay - AFAIK only @rgilton has this at the moment.

**Comment by rgilton** [comment]
I see the spec changed on Thursday, which was after the freeze-point for this weekend.  We will assess scheduling of work to perform this update in the next KTC meeting this coming Wednesday.

**Comment by kierdavis** [comment]
This happened: https://github.com/srobo/brain-zip-packager/commit/5306c16658726e89c7c735f86b45851ce21009ef
