### ISSUE TITLE
Inject wire into the non-Kickstart teams' kits

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#41]
Since the kits are now in separate places, we'll have to add the wire separately.

Teams should each get *2.5m* of each of the thinner colours of wire and *1.8m* of each of the thicker colours of wire.

Note: an earlier version of this ticket had the lengths wrong.

**Comment by PeterJCLaw** [comment]
@kierdavis do you know whether this was done at the same time as #40?

**Comment by kierdavis** [comment]
I don't know, maybe @Tyler-Ward can confirm?

**Comment by Tyler-Ward** [comment]
This was done on monday when we sorted the cupboard along with wrapping the others for packing

**Comment by PeterJCLaw** [comment]
Nice, thanks!
