### ISSUE TITLE
Announce the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#411]
The competition needs fanfare so that people know when & where it will happen. The following things should happen:
- [x] An events page (https://studentrobotics.org/events/sr2020/competition/)
- [x] A news article about the announcement (https://studentrobotics.org/news/2019-12-17-sr2020-competition-dates-announcement/)
- [x] Social media publicity linking back to the news article and/or event page
- [x] Email to the team-leaders (https://github.com/srobo/team-emails/pull/36)
- [x] Email to volunteers (https://github.com/srobo/volunteer-emails/pull/24)
- [x] Email to tech/STEM blogs and other external media outlets

### Original

[comp/announce](https://github.com/srobo/recurring-tasks/blob/master/comp/announce.yaml)

### Dependencies

 * #410 Find and book venue for SR2020

**Comment by PeterJCLaw** [comment]
@antoinepetty am I right in thinking that we've already publicised the competition dates on social media and to other organisations? (I vaguely recall you might have done that)

**Comment by antoinepetty** [comment]
To social media yes, to other orgs no not yet

**Comment by antoinepetty** [comment]
I should have some time next week to try that. Will probably need some help similar to last year though

**Comment by PeterJCLaw** [comment]
Ah nice! (I hadn't been meaning to imply you should pick this up, but if you'd like to do it that's great :)
Would you like to self-assign this if you're going to be working on it?

**Comment by antoinepetty** [comment]
https://github.com/srobo/tasks/issues/564

**Comment by antoinepetty** [comment]
Have sent invites to several news organisations as tracked in #564 
Will close this ticket and post any further updates on #564
