### ISSUE TITLE
Get PRS and PPL licenses for the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#415]
PRS and PPL both need separate licenses so we can play music at the competition.

### Original

[comp/venue/prs-ppl](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/prs-ppl.yaml)

**Comment by PeterJCLaw** [comment]
@RealOrangeOne am I right in thinking that Reading are providing this for us?

**Comment by RealOrangeOne** [comment]
Correct, PRS is handled for us by the venue.

I don't know what a PPL license is, but if it's related, it's likely covered too.

**Comment by WillB97** [comment]
In 2018 PRS and PPL licenses came together as TheMusicLicence, so if this is the license the venue has then this ticket is complete.

[Source](https://www.ppluk.com/about-us/difference-between-ppl-and-prs-for-music/)

**Comment by RealOrangeOne** [comment]
I confirmed yesterday the venue have the required licensing to play music.
