### ISSUE TITLE
Have a competition network

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#419]
This also requires that we have a pretty significant internet connection given the number of people that are coming and our video streaming requirement.
If possible this should be mostly configured in a corner of the venue as early as possible during setup and then, once working, deployed to the proper locations.

---- 

The network access in Reading is a little more complex than we're used to. We need to work out what our points of contact with their network is going to be and how we're going to ensure our devices can talk to each other over their network (where that happens, if needed).

As @RealOrangeOne notes, we can connect to wired ethernet though they want to know the MAC address ahead of time.

This likely relates to:
 * #507 Organise screens around the arenas
 * #539 Deploy the Compbox
 * #581 Organise the non-arena ("outside") display screens

----

### Original

[comp/venue/network](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/network.yaml)

**Comment by RealOrangeOne** [comment]
Reading have an ethernet upstream we can use (location unknown). We just need to send them the MAC address of the device connected.

**Comment by PeterJCLaw** [comment]
Things which need network:
- the Pi(s) in the tech cupboard; these connect direct to Reading:
 - outside screens driver (#581)
 - screens driver for in Mojos (using Reading's screens to show arena info, #503/#430)
- the livestream computer (#480/#584)
- the competition network; which should have its own router:
  - things on the stage/Tech Desk:
    - combox (#539)
    - the arena facing screen (on the table on the stage; #507/#503/#430)
    - score entry (#431/#540)
    - mixtape/finals sequencing (#533)
    - (possibly) commentator/judges screen
    - general ad-hoc machines (assume 3 ports worth)
  - staging screen (#507/#514)
  - shepherding screen (#507/#514)

The main question I think we have is whether the livestream computer should be inside the competition network or should be direct on Reading's network. If it's inside the competition network then this gives it direct access to the compbox and means we don't need to tell Reading it's MAC, both of which simplify things. However, this would mean we'd need to run network past a fire exit.
@RealOrangeOne @WillB97 can you recall if we'd worked out how that was going to work?

In any case, this gives a fairly good picture of the MACs we need to get Reading:
- a few of our Pis (so that it doesn't matter if we need to switch them out)
- the router
- possibly the livestream machine

**Comment by RealOrangeOne** [comment]
I don't believe it needs to be on the competition network, but it should probably be on a wired network for stability's sake.

**Comment by Tyler-Ward** [comment]
It will need to be on the comp network as he overlay needs access to the compbox to do the match info

**Comment by WillB97** [comment]
I see no advantage to not putting the livestream on the competition network since we still need to run a HDMI cable from the arena (where the competition network will be) and long cat5 is much easier to get than long HDMI.
