### ISSUE TITLE
Prepare a layout of the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#421]
This will need to specify where the arenas, team pits, reception, helpdesk and so forth are.

The outcome from this task should be an entry in https://github.com/srobo/comp-floorplans. We should (at some point) merge in the [SR2019 specific repo](https://github.com/srobo/event-maps-2019).

### Original

[comp/venue/layout](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/layout.yaml)

### Dependencies

 * #420 Get fire plans from the venue

**Comment by PeterJCLaw** [comment]
@WillB97 am I right that you're handling this?

**Comment by RealOrangeOne** [comment]
SR2019 map: https://studentrobotics.org/resources/sr2019/venue-map.png

src: https://github.com/srobo/event-maps-2019

**Comment by WillB97** [comment]
Also https://github.com/srobo/comp-floorplans
We should look at merging these

**Comment by WillB97** [comment]
Initial plans are up https://github.com/srobo/comp-floorplans/tree/SR2020/2020
Power is not marked yet but is pretty available everywhere

**Comment by Adivote** [comment]
Can we have an area for a test arena? (suggestion: the stage which does nothing)

**Comment by WillB97** [comment]
We're currently planning a test arena in the same room as the arena.
Probably 3-4m square so we only have to lay one piece of carpet.
