### ISSUE TITLE
Prepare equipment for transport to the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#424]
The things that we are taking to the competition needs to be prepared for transportation. Most of the things we need are in storage, however some may be elsewhere.

### Original

[comp/venue/transport/prepare](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/prepare.yaml)

### Dependencies

 * #423 Work out what we need from storage at the competition

**Comment by RealOrangeOne** [comment]
I've started working on a equiptment list for the competition. It's a rip off of the ones from SR2019, with a couple modifications, and the undefined items marked.

https://docs.google.com/spreadsheets/d/1Q6edANdYP632ChAhNcDj3Y2SIoPcNn-PNfV1E_A1EcM/edit?usp=sharing

This will need massive improvements over time, once we're sure what we need and where everything is, but it's a start. As people realise we need things, feel free to add the relevant items.

A lot of this becomes more defined after https://github.com/srobo/competition-team-minutes/issues/195
