### ISSUE TITLE
Hire a van for transporting things

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#425]
We need a van (probably from Thursday to Monday inclusive) to transport all the necessary equipment around.

### Original

[comp/venue/transport/van](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/van.yaml)

**Comment by RealOrangeOne** [comment]
I'm happy to hire / drive a van again as needed.

**Comment by Adimote** [comment]
This should be a long-wheel base van so it can hold the carpet which is currently stored in Southampton

**Comment by prophile** [comment]
How big does the van need to be?

**Comment by RealOrangeOne** [comment]
For SR2019 cleanup, we used a long wheelbase transit. Not sure this is large enough transport the 4m carpet or the 4ft stage decking. Would need to inquire.
