### ISSUE TITLE
Transport stuff to the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#426]
Many things will need to be moved from various locations to the venue.

### Original

[comp/venue/transport/main](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/main.yaml)

### Dependencies

 * #423 Work out what we need from storage at the competition
 * #424 Prepare equipment for transport to the competition
 * #425 Hire a van for transporting kit between storage and the venue

**Comment by RealOrangeOne** [comment]
I'm happy to hire / drive a van again as needed.
