### ISSUE TITLE
Organise cable protectors

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#428]
It's a bad idea to have loose cables trailing around on the floor. We should hire cable protectors to cover the cables anywhere necessary.
Note when ordering them: it turns out to be easier to setup shorter runs than longer ones. As a result where runs pass under tables (etc.) we should get several short pieces rather than single long ones.

### Original

[comp/venue/cable-protectors](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/cable-protectors.yaml)

### Dependencies

 * #421 Prepare a layout of the competition

**Comment by Tyler-Ward** [comment]
We should have most of a roll of cable protection tape from last year, this will be in storage.

This is what we bought last year
https://www.gaffatape.com/slipway-cable-cover-tape/default.aspx

**Comment by RealOrangeOne** [comment]
As the venue are providing power distro, they may have stock of protectors too. We should enquire!

**Comment by RealOrangeOne** [comment]
The venue are providing power distro, and _might_ have protectors. If not the number SR have already will likely suffice.

Will find out what their plans are and see.
