### ISSUE TITLE
Work out the day schedules for the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#436]
We need a list of what is happening at what times on the days of the competition:

- [x] ~What dates are we exactly going for?~ (done, see website)
- [x] Are we broadcasting all the sessions for a weekend in one go, or are we doing separate rounds?
     (solved: we're having two sessions per weekend, each having 2-3 rounds of matches)
- [x] How many matches are we going to run?
     (solved: we're having two sessions per weekend, each having 2-3 rounds of matches)
  - Depends somewhat on the number of teams (we currently have 12 teams)
- [ ] What times are we running the broadcasts?
  - suggestion A) both on Sunday: 11:30 and 14:00
  - suggestion B) same time both days, perhaps late afternoon
  - this is likely blocked on #590

### Original

[comp/day-schedule](https://github.com/srobo/recurring-tasks/blob/master/comp/day-schedule.yaml)

**Comment by RealOrangeOne** [comment]
2019 day schedule: https://studentrobotics.org/events/sr2019/competition/

It'll likely be very similar

**Comment by prophile** [comment]
Here are 2 outlines, based on 35 teams; one with a 5 minute match spacing, one on a four minute match spacing.

# Five minute spacing

## Saturday

```
0930  Doors open
1045  Intro + briefing
1115  Round 1
1215  Lunch
1300  Round 2
1345  Round 3
1430  Round 4
1515  Gap
1545  Round 5
1630  Round 6
1715  Begin packup
1730  All teams out
```

## Sunday

```
0930  Doors open
1030  Round 7
1115  Round 8
1200  Lunch
1300  Round 9
1345  Close arena / group photos
1430  Knockouts
1600  Knockouts end
1620  Prizegiving
1640  Kit return
1730  All teams out
```

# Four minute match spacing

## Saturday

```
0930  Doors open
1045  Briefing
1120  Round 1
1220  Lunch
1300  Round 2
1340  Round 3
1420  Tinker time
1540  Round 4
1620  Round 5
1700  Begin packup
1730  All teams out
```

## Sunday

```
0930  Doors open
1020  Round 6
1100  Round 7
1140  Round 8
1220  Lunch
1300  Round 9
1340  Close arena / group photos
1420  Knockouts
1550  Knockouts end
1610  Prizegiving
1630  Kit return
1715  All teams out
```

This needs adjustments based on the number of teams, which will change the length of a round and the design of the knockouts.

**Comment by RealOrangeOne** [comment]
Now that this is a virtual competition, we need to know how the event will look.

- What dates are we exactly going for?
- Are we broadcasting all the sessions for a weekend in one go, or are we doing separate rounds?
- How many matches are we going to run?
  - Depends somewhat on the number of teams

**Comment by PeterJCLaw** [comment]
The current plan for the broadcasts is to have two sessions per weekend, each session likely an hour or so in length.

In terms of the number of matches, if we assume that we want approximately the usual number of appearances per team (9-12) then for 12 teams that's ~120 appearances in total, or 30 matches (at four appearances per match).

At two sessions per weekend over two weekends that's four sessions.

We probably want to find a number which lets us have whole rounds in each session. With 12 teams, a round is three matches.

10 rounds doesn't divide by four, though having imbalanced sessions probably isn't a big deal. (I suspect the bigger issue is going to be running out of differing opponents to populate the rounds with, though that's something for #469 to worry about)

Assuming that we have 2 or 3 rounds per session, that gives a session length of {2,3} * 3 (matches per round) * 5 (minutes per match) == 30 or 45 minutes.

The remaining question is then: what times over the weekend to we do the broadcasts?

**Comment by PeterJCLaw** [comment]
Done in https://github.com/srobo/tasks/issues/590#issuecomment-653775787.
