### ISSUE TITLE
Produce handout flyers for the SR2020 Competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#437]
The primary target of these flyers are invited guests (both of SR and of the teams), who may not know very much about either Student Robotics or the game the robots are competing in.
These flyers should include:
 - descriptions of both SR and the game
 - a summary of the teams competing (a list of TLAs and names is fine)
 - the overall schedule of the competition weekend

Note: much of the content of these flyers does not need to actually be new -- the website already contains plenty of summaries of SR and the game, which can be copied liberally, as well as the day schedule.

### Original

[comp/flyers](https://github.com/srobo/recurring-tasks/blob/master/comp/flyers.yaml)

### Dependencies

 * #436 Work out the day schedules for the competition

**Comment by RealOrangeOne** [comment]
SR2019: https://github.com/srobo/tasks/issues/101

SR2019 flyer: https://github.com/srobo/tasks/files/3017824/flyer.pdf
