### ISSUE TITLE
Print the flyers for the SR2020 Competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#438]
Arrange printing of the flyers for handing out at the competition.

### Original

[comp/print-flyers](https://github.com/srobo/recurring-tasks/blob/master/comp/print-flyers.yaml)

### Dependencies

 * #437 Produce handout flyers for the SR2020 Competition

**Comment by RealOrangeOne** [comment]
SR2019: https://github.com/srobo/tasks/issues/129
