### ISSUE TITLE
Email teams about media consent

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#440]
Teams need to be sent an email with a link to the media consent form and instructions on how to return them to us.

### Original

[comp/media-consent/email](https://github.com/srobo/recurring-tasks/blob/master/comp/media-consent/email.yaml)

### Dependencies

 * #439 Update MCF and link for SR2020

**Comment by RealOrangeOne** [comment]
SR2019 email: https://github.com/srobo/team-emails/pull/18

We need to email teams about media consent forms, and why they're needed. The process will be exactly the same as last year.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne what's blocking this?

**Comment by RealOrangeOne** [comment]
I honestly don't remember. I suspect something around getting the approach to media consent this year narrowed down and confirmed, but if we're going with the standard process for forms, tickets, and _a_ reception flow, it's probably not blocked.
