### ISSUE TITLE
Design wristbands for SR2020

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#444]
We need to design some wristbands for the competition.

### Original

[comp/wristbands/design](https://github.com/srobo/recurring-tasks/blob/master/comp/wristbands/design.yaml)

**Comment by RealOrangeOne** [comment]
SR2019 Designs: https://github.com/srobo/promotional-material/pull/6

[Template for wristband design](https://idc.ftpstream.com/409692/98cc0531323877c6ecf310baaa1eaf83/festivals/marketing/Specs/Fabric_Metal_Ring_Woven_16mm.pdf)

https://github.com/srobo/tasks/issues/91 contains some very useful information.
