### ISSUE TITLE
Print arena labels for SR2020

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#447]
Since we have more than one arena we want a way to tell which is which. One possible mechanism is to colour-code them, though having printed name labels is easy and has been done in the past.
There are some handy large A and B label PDFs attached to #2964.
Note that since people need to use the label of the arena to clearly communicate which they're talking about it is best to stick to having a single name for each.

### Original

[comp/arena/labels](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/labels.yaml)

**Comment by sedders123** [comment]
We only have one arena this year so probably don't need to distinguish it with a label
