### ISSUE TITLE
Design score entry forms for marshals

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#449]
Score entry forms for use by marshals in the arenas need to be designed.

### Original

[comp/game/score-forms](https://github.com/srobo/recurring-tasks/blob/master/comp/game/score-forms.yaml)

**Comment by Adimote** [comment]
@PeterJCLaw this is normally a task you do, do you have some documentation on doing this or are you willing to do it yourself

**Comment by PeterJCLaw** [comment]
Either. There's general documentation for configuring scoring in SRComp at https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#configure-game-scoring, with a specific section about the paper score-sheets at https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#create-a-score-sheet.
