### ISSUE TITLE
Ship a battery charger power supply to team BLB

### ISSUE THREAD

**Issue by kierdavis** [srobo/tasks#45]
The battery charger PSU (1WR43) that was assigned to team BLB was left behind on the volunteer desk in the Kickstart venue, so they likely don't currently have one (unless they picked up another team's one).

**Comment by PeterJCLaw** [comment]
We should do this as part of #33.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward do you happen to know whether this was done as part of #33?
@RealOrangeOne have you had any contact from BLB about this? I suspect they'll struggle without a charger power supply.

**Comment by Tyler-Ward** [comment]
I haven't shipped any charger power supplies

**Comment by RealOrangeOne** [comment]
I've not heard anything from them, no. We should probably get that sent out fairly early in the new year.

**Comment by RealOrangeOne** [comment]
I've not. It's slightly worrying they've not noticed yet. I need to chase up the inactive teams, so i'll do this at the same time, as `BLB` are on the list

**Comment by RealOrangeOne** [comment]
This email has now been sent

**Comment by trickeydan** [comment]
Any update on this? We could sort this on Sunday

**Comment by PeterJCLaw** [comment]
I'm downgrading this as the team don't seem to be particularly bothered. That either means that they do actually have a charger, or aren't meeting often enough for it to be an issue. While we should definitely still do this, we've reached the point where their lack of response is the blocker, rather than a lack of effort on our part.

**Comment by RealOrangeOne** [comment]
I didn't get a chance to over the weekend, but I've now sent the chase-up email. Let's see if anything comes out of that.

**Comment by Tyler-Ward** [comment]
@RealOrangeOne I assume they didn't respond to you about this.

**Comment by RealOrangeOne** [comment]
correct, i've still heard nothing, which is a little worrying.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne any update here? Do we even know if they're coming to the competition?

**Comment by PeterJCLaw** [comment]
(They do seem to be active in the IDE, though only have a single team-leader and a single competitor user account)

**Comment by RealOrangeOne** [comment]
Correct, still nothing. I believe they were on the chaseup email I sent a couple weeks ago, but still haven't heard anything.

I don't think its useful keeping this ticket open. Realistically by now it would be easier to return said charger at the event itself rather than shipping it to them.
