### ISSUE TITLE
Kit handback arrangement

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#452]
Arrangements must be made for the kit handback procedure at the end of the competition.

There are some existing docs and forms which may be useful when planning this:
- https://srobo.github.io/runbook/competition/teams/role-descriptions/kit-return/
- https://github.com/srobo/kit-coordination-documents/tree/master/authorized-to-keep-kit
- https://github.com/srobo/kit-coordination-documents/tree/master/kit-contents-checklist
- https://github.com/srobo/kit-coordination-documents/tree/master/kit-return-form

### Original

[comp/kit-handback](https://github.com/srobo/recurring-tasks/blob/master/comp/kit-handback.yaml)

### Dependencies

 * #451 Plan how we will do extended kit loans to teams

**Comment by PeterJCLaw** [comment]
From our discussions at the venue (#578) yesterday, we're currently expecting:
- this to happen in the hallway on the in-venue side of the reception desks
- we'll put out several desks along one wall (so much of the hallway remains clear)
- kit boxes will be stacked alongside these desks and will remain there through teardown (so it remains separate from the rest of our RUBs)

**Comment by TomWheal** [comment]
Happy to take this on as apart of running the help desk:

## Some problems that occurred last year:

- Volunteers didn't know the kit, the list provided "useless and confusing"
- Teams blocked the desks by not having all of there kit ready
- As such stuff was missed and it was a disorganised mess
- Returned RUBs were hard to search through cause of wires and other junk

My suggestion, give every team a check list so they know what they are expecting to return. 
Create a simple QR code scanner GUI with pictures of the kit, so volunteers can quickly tell if all the important stuff is in the box. 
Give paper bags to the teams for them to put wires, camcons and other consumables in.

**Comment by RealOrangeOne** [comment]
> Volunteers didn't know the kit, the list provided "useless and confusing"

This feels like strange feedback. I wonder whether putting pictures of what the kit is next to the items would help? Alternatively considering kit familiarity when allocating volunteers might also be useful?

> give every team a check list so they know what they are expecting to return.

This is in the rules, we also mention it in the closing talk (#554 ).

**Comment by TomWheal** [comment]
> This feels like strange feedback.

This is just the feedback I've gotten from talking to people about it, both after the competition and recently. 

> This is in the rules, we also mention it in the closing talk.

Yes but the competitors are tired after the weekend and just want to get home

Ill write up the ideas I've had to solve both this weekend

**Comment by RealOrangeOne** [comment]
As was noted in the competition closing, kits will be kept by teams until the start of the next competition year, at which time we'll reclaim the kits for those teams who don't continue. 

At the same time, chasing https://github.com/srobo/tasks/issues/297 is also a good idea.
