### ISSUE TITLE
Print a copy of the rules for helpdesk

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#453]
Helpdesk will want a printed copy of the game rules.

### Original

[comp/pits/helpdesk/rules](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/helpdesk/rules.yaml)

**Comment by RealOrangeOne** [comment]
This should be done as close to the competition as is reasonably possible, to account for any last-minute changes to the rules.

**Comment by Scarzy** [comment]
They also probably want more like 5-10 copies
