### ISSUE TITLE
Organie safety-check validation for SR2020

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#456]
We need a mechanism to know which robots have been safety checked and are thus allowed into the arena/staging area. Since SR2015 we have issued checked teams with high-viz jackets which symbolised that the robot had passed checks. Only the member of the team wearing the high-viz jacket was allowed to bring the robot into the arena/staging area.

Prior to that (at least in SR2014) we used sticky labels with the team TLA, the words "Safety Checked" plus some boxes for the time of the check and the initials of the person who did the check.

### Original

[comp/safety/check-labels](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/check-labels.yaml)

**Comment by RealOrangeOne** [comment]
Historically this has been done by presenting teams with high-viz jackets (#511 ), we could just do this again?

**Comment by PeterJCLaw** [comment]
> Historically this has been done by presenting teams with high-viz jackets (#511 ), we could just do this again?

Yes, that seems sensible.

**Comment by PeterJCLaw** [comment]
I've reworked this in the tasks repo. I'm going to close this as a duplicate of #511, which we already have for sorting the high-vis jackets.

**Comment by Scarzy** [comment]
Yes, we'll do this again
