### ISSUE TITLE
Have name badges for volunteers at the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#457]
Name badges should be printed for all volunteers we know will be there.  We should also have blank badges for those we don't expect.

### Original

[comp/volunteers/name-badges](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/name-badges.yaml)

**Comment by RealOrangeOne** [comment]
Text people want on their namebadges have been collected when they signup to volunteer. 

We have some badge holders, I think, but generally not enough.
