### ISSUE TITLE
Have a means to record an incident

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#462]
We need a means to record and store details of an incident or near- miss occurring. At bare minimum this needs to store what happened and why, and what follow up occurred.
SR has an incident record book which was purchased for this purpose. We should check that it is still suitably & usable and ensure that it will be at the cmopetition venue.

### Original

[comp/safety/incident-record](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/incident-record.yaml)

**Comment by sedders123** [comment]
@Scarzy is this having a means to record an incident something that falls under your purview as Health and Safety Coordinator, or is it OK for someone else to pick this up?

**Comment by Scarzy** [comment]
Hi,

I believe this record book is still in my possession, and as such it will
be at the competition. I will double check this evening.

Scarzy
