### ISSUE TITLE
Create and publish risk assessments for the virtual competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#463]
The risk assessment for the competition needs updating for SR2020.

This will need to be updated for the virtual competition. Obviously much of the venue related concerns are moot, though we have some different safeguarding concerns to review.

### Original

[comp/safety/risk-assessments](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/risk-assessments.yaml)

**Comment by RealOrangeOne** [comment]
@Scarzy I believe risk assessments fall under your domain? Is this something you're working on as part of the other first-aid-y bits?

**Comment by Scarzy** [comment]
Yes, I'm working on this
