### ISSUE TITLE
Prepare an incident response plan

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#464]
We should ensure that our incident response plans are current & applicable to the selected venue; we should update them as needed.

### Original

[comp/safety/incident-plan](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/incident-plan.yaml)

### Dependencies

 * #410 Find and book venue for SR2020
 * #462 Have a means to record an incident
 * #463 Create and publish risk assessments for the virtual competition

**Comment by Scarzy** [comment]
Assign to me please

**Comment by PeterJCLaw** [comment]
We have a plan, it's basically the same as last year and involves telling Scarzy.
