### ISSUE TITLE
Ensure the SR2020 competition is safe

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#465]
The SR2020 competition event must be safe.

### Original

[comp/safety/main](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/main.yaml)

### Dependencies

 * ~#428 Organise cable protectors~
 * ~#456 Organise safety-check labels for SR2020~
 * ~#511 Organise high-vis jackets for the teams at the competition~
 * ~#459 Arrange first aid presence at the competition~
 * ~#460 Plan for disposal of sad batteries~
 * ~#461 Safety check the SR2020 robots~
 * #463 Create and publish risk assessments for the virtual competition
 * #464 Prepare an incident response plan

**Comment by PeterJCLaw** [comment]
@Scarzy has agreed to lead Health & Safety at the competition.

**Comment by PeterJCLaw** [comment]
Are there risks of any note now that the competition is virtual? Do we still need this tree of tasks?

**Comment by RealOrangeOne** [comment]
I don't think we do for this definition of "safe". There may however be tasks related to safeguarding we need to do which are different to an in-person competition, but those almost certainly fall under a separate ticket.

**Comment by Scarzy** [comment]
Yes.

Sorry, somehow I missed the e-mail about this

**Comment by Scarzy** [comment]
The event happened. It appeared to go through safely.

1 concern was raised about flashing lights, and mitigations were put in place.
