### ISSUE TITLE
Arrange a whiteboard at the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#466]
Whiteboards are useful for potentially many things, and particularly for organising tinker time.

SR owns a whiteboard, which has historically been used for this. It may need cleaning properly though.

### Original

[comp/whiteboard](https://github.com/srobo/recurring-tasks/blob/master/comp/whiteboard.yaml)

**Comment by RealOrangeOne** [comment]
We should check if the venue have one.

Historically it's been easier to do tinker time on paper, and it's been successful.

I tried doing it from a google sheet once. I'd advise against this.

**Comment by RealOrangeOne** [comment]
Demoting this issue. If there's one available at the venue / with little overhead, we can probably find a use for it, but it's not remotely critical for the competition

**Comment by RealOrangeOne** [comment]
Based on the above, I think we can close this issue, and re-open if we find a need for one.
