### ISSUE TITLE
Organise tinker time

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#467]
On the morning of the first day, teams are given a chance to tinker with their robots in the arenas. We're going to use a whiteboard to schedule this. Someone will be near the arena and will write teams into 15 minute time slots. Requires 1 Blueshirt to manage scheduling and changover.
Also requires that there is some kind of PA system that is audible in the Arena.

### Original

[comp/tinker-time](https://github.com/srobo/recurring-tasks/blob/master/comp/tinker-time.yaml)

### Dependencies

 * #416 Sort out sound system for the competition
 * #466 Arrange a whiteboard at the competition

**Comment by RealOrangeOne** [comment]
This is blocked on knowing the schedule for the day (#103, kinda). 

Documentation for how to run a tinker time is already in the runbook: https://studentrobotics.org/runbook/competition/team-support/tinker-time/

**Comment by RealOrangeOne** [comment]
Depending on which schedule we use from #436, there may not be tinker time in the conventional sense. We may want to have a schedule around using the test arena too, just so it doesn't become too messy!
