### ISSUE TITLE
Design the SR2020 knockouts

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#468]
We need to specify the structure of the knockouts.

### Original

[comp/game/knockout-design](https://github.com/srobo/recurring-tasks/blob/master/comp/game/knockout-design.yaml)

**Comment by Adimote** [comment]
Blocked on a realistic estimate of the number of teams which will turn up.

**Comment by PeterJCLaw** [comment]
Currently we're looking at 12 teams, so this can either be done manually or we can just go with what SRComp spits out. Since the latter is probably fine and we have very little time, I suggest we go with that.

With 12 (rounds up to 16) teams, this will have three layers, for a total of 7 matches. At ~5 minutes a match and with some spacing between the later matches that's about an hour at most.

There's a question on whether we bother to have the longer gaps between the later rounds. These are usually present to build tension (which we still want, but may not work quite the same on a live stream) and to allow teams to make any last-minute fixes.

Whether last-minute changes can happen is going to depend on #590, though I suspect we wouldn't want the gaps to be much longer than they might be at the real competition.

**Comment by PeterJCLaw** [comment]
I'm going to downgrade this to indicate that it's mostly done (see my previous comment), though there's room to tweak this nearer the time if needed.

**Comment by PeterJCLaw** [comment]
I'm calling this done. We'll use the SRComp knockout.

We still need to work out timings, however i think that's better handled as part of the overall tasks to work out the timings for the broadcasts.
