### ISSUE TITLE
Make a more on-brand forums theme

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#47]
It would be great if we could have a theme which was more on-brand.
Perhaps something based on one of these, with some colour tweaks:
- Basic (https://www.phpbb.com/customise/db/style/basic/demo/3.2)
- Elegance (https://www.phpbb.com/customise/db/style/artodia_elegance2/demo/3.2)

Note that I _don't_ think we should create a whole own theme of our own, rather we should find a theme which supports colour customisation ("Basic" above definitely does) and then customise the colours. We don't really want to be maintaining a theme ourselves.

**Comment by Tyler-Ward** [comment]
We dont ahve forums any more
