### ISSUE TITLE
Publish SR2020 layout maps

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#484]
We should have maps of the layout for reference. This should include maps with team locations.

This task is about providing these maps to people; digitally, physically or both.

### Original

[comp/venue/layout-map](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/layout-map.yaml)

### Dependencies

 * #421 Prepare a layout of the competition
 * #474 Work out layout of teams at the competition

**Comment by RealOrangeOne** [comment]
SR2019 map: https://studentrobotics.org/resources/sr2019/venue-map.png

src: https://github.com/srobo/event-maps-2019

**Comment by PeterJCLaw** [comment]
For clarity: the outcome from this task should be an entry in https://github.com/srobo-legacy/floorplans. We should (at some point) move that repo to the main org and merge in the SR2019 specific repo.

**Comment by PeterJCLaw** [comment]
> For clarity: the outcome from this task should be an entry in https://github.com/srobo-legacy/floorplans. We should (at some point) move that repo to the main org and merge in the SR2019 specific repo.

Correction: the above description relates to #474. This task is about publishing the result on the website (etc.).

**Comment by WillB97** [comment]
Given that the venue is on a single floor this will probably use the floorplan from #421 with the technical layers removed and a few additional labels added
