### ISSUE TITLE
Order additional blueshirts for the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#488]
We may need more.

### Original

[comp/volunteers/blue-shirts](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/blue-shirts.yaml)

**Comment by RealOrangeOne** [comment]
At the start of SR2020, we ordered a load of extra tshirts (currently with @TomWheal ? ). We should check that supply before even thinking about ordering any more!

**Comment by TomWheal** [comment]
I don't have them, they were in one of the rubs I gave to you at Kickstart

**Comment by RealOrangeOne** [comment]
Ah ok. That means they're either still in the back of my car, or with Diane.

**Comment by RealOrangeOne** [comment]
They are in fact with Diane, just awaiting confirmation on numbers.
