### ISSUE TITLE
Move remnants from kit packing from southampton to storage.

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#49]
There are several boxes of kit in southampton from the kit packing which can now be returned to storage.

**Comment by Adimote** [comment]
Was this done at the competition?

**Comment by trickeydan** [comment]
> Was this done at the competition?

If the freight handling was done properly on Monday, then yes. I have yet to confirm this.

**Comment by PeterJCLaw** [comment]
I thought the conclusion was that much of the SR stuff which was in the cupboard was going to stay there?
Without a concrete list of which boxes or kit/etc. this ticket refers to, I think it'll be hard to conclusively resolve it.

**Comment by trickeydan** [comment]
I will be inspecting the cupboard tomorrow and will be able to determine if action is required

**Comment by RealOrangeOne** [comment]
Given that we also plan to do a kit sorting day in Southamton in the coming weeks, that would be an ideal time to rectify the issue. Considering how little of SRs was sent back up to the cupboard, it's highly unlikely there's actually an issue.

**Comment by Tyler-Ward** [comment]
@trickeydan are we good to close this?

**Comment by PeterJCLaw** [comment]
As far as I can tell this is now done. When I proposed moving more of the SR stuff which is currently in Southampton (other than the things on loan) back to storage following Smallpeice, there seemed to be some push-back in favour of keeping it around in Southampton for the convenience of those there.

I'm therefore considering this done. If there are _specific_ things which need to go back to storage, then we should have fresh tasks for those. As it stands, this task is IMO too vague to be useful.
