### ISSUE TITLE
Create a list of available subject matter experts

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#499]
While helpdesk is the primary point of call for teams who need help, we also need a way for those manning it to escalate their request if they don't know how to resolve something. This is not intended to remove the need to replace broken kit, but rather to provide extended support for non-replaceable parts (e.g: complex vision system or rules questions).
We should create a list of subject matter experts and put it on helpdesk. Clearly the people on the list need to be actually available to help (i.e: both at the venue and not insanely busy), and aware that they're the point-of-contact for certain areas.

### Original

[comp/volunteers/experts-list](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/experts-list.yaml)

### Dependencies

 * #493 Schedule volunteer roles

**Comment by RealOrangeOne** [comment]
I've created a document which can serve to capture these.

So far I've thrown some names at the page, at immediate thoughts on people. If you're on a list and don't think you should be, or not in a list when you think you should be, please change it, and know it wasn't meant offensively!

**Comment by RealOrangeOne** [comment]
@TomWheal as the person organising helpdesk, would be good to get your opinion on these, both in terms of categories missing, and people missing!

**Comment by TomWheal** [comment]
Looks fine to me, this is likely a living document so will probably change as we get closer to the competition

**Comment by RealOrangeOne** [comment]
Based on that, i'm considering this closed. What we have is fit for purpose, and can be changed as and when necessary :+1:
