### ISSUE TITLE
Acquire tape for the SR2020 arenas

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#502]
For the competition we will need vast quantities of tape: - white - black - neon yellow, blue, green, pink - hazard - double-sided for laying the carpet with
We should check what stocks we have and order more if needed.

### Original

[comp/arena/tape](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/tape.yaml)

**Comment by RealOrangeOne** [comment]
We need to know how many are currently in the container before we can order more.
