### ISSUE TITLE
Hire extra screens for the arenas

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#505]
We do not have enough screens to cover both arenas, so we need to hire more.

### Original

[comp/arena/screens-hire](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/screens-hire.yaml)

**Comment by RealOrangeOne** [comment]
I believe we have enough to furnish 1 arena, and the venue has enough installed screens for there, so we can consider this issue resolved?

**Comment by PeterJCLaw** [comment]
I agree this is likely redundant this year. The chances of several of our screens failing are small and we can easily re-open this if needed.

**Comment by Tyler-Ward** [comment]
Do we have another ticket for the other screes we borowed? if not we should probably have one as we borrowed lots of screens last year.

**Comment by PeterJCLaw** [comment]
This task would normally cover borrowing or hiring screens, however this year there are _lots_ of screens built-in to the venue, which we'll have access to. We're not currently expecting to need to hire any more.

**Comment by Tyler-Ward** [comment]
The screens we borowed from ecs where with a couple of exceptions not used for venue signage but competiition operations and sat on desks

**Comment by PeterJCLaw** [comment]
Ah, good point about screens being used on the tech desk. I'd forgotten about those.

I don't think we currently have a task for those (I'll add one to the repo), though for this year I'm fairly sure that we can use some of the eight which SR already has for this purpose.
