### ISSUE TITLE
Organise screens around the arenas

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#507]
We have screens around the arena to display live information, we have monitors we can use for these, though we will need to arrange to get stands for them.

### Original

[comp/arena/screens](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/screens.yaml)

### Dependencies

 * #430 Organise drivers for the arena screens
 * #503 Provide network to the arena
 * #504 Provide power to the arenas
 * ~#505 Hire extra screens for the arenas~
 * #506 Organise stands for the arena screens

**Comment by PeterJCLaw** [comment]
Have updated the description to note that we need to get stands for the screens.

**Comment by WillB97** [comment]
The list of screens we would be using is:
- Arena screen
- Judge's screen
- Staging screen
- Shephearding screen
- Helpdesk (screen only)
- Livestream (x2)

**Comment by PeterJCLaw** [comment]
We don't have space for standing screens around the arenas, so we'll be using a combination of the screens in the room and a single screen facing the arena on a desk on the "stage" area within the room.

**Comment by PeterJCLaw** [comment]
Not applicable without a physical venue.
