### ISSUE TITLE
Build the arenas

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#509]
Build some arenas for the games.
This covers the physical construction of the arenas, including props needed for the game and markings for the start-position of any which are moveable. The arenas should also be marked so it's clear which is which.

### Original

[comp/arena/build](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/build.yaml)

### Dependencies

 * #447 Print arena labels for SR2020
 * #501 Acquire carpet for the SR2020 arenas
 * #502 Acquire tape for the SR2020 arenas
 * #503 Provide network to the arena
 * #504 Provide power to the arenas
 * #507 Put up screens around the arenas
 * #508 Organise tools for arena construction

**Comment by RealOrangeOne** [comment]
The arena will be the SR wooden arena, at a slightly smaller size than historically deployed.

**Comment by PeterJCLaw** [comment]
The virtual arenas have been built: https://github.com/srobo/competition-simulator
