### ISSUE TITLE
Prepare robot flags for the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#512]
During matches robots are given coloured flags so that the audience know which robot is from which scoring zone.
At least two complete sets of each badge are needed: one for the robots currently playing and another for the robots currently staging.
We also expect that not all teams will have suitable mounts for flags. To allow for this we should therefore obtain some mounting components they can use. We already own a hot glue gun, though we may need to get some more glue sticks. The mounting component has historically been https://www.screwfix.com/p/jg-speedfit-pem0215w-l-equal-tee-white-15-x-15-x-15mm-5-pack/74470.

### Original

[comp/game/robot-flags](https://github.com/srobo/recurring-tasks/blob/master/comp/game/robot-flags.yaml)

**Comment by RealOrangeOne** [comment]
Historically these have been borrowed from SRO, under the condition any damages be repaired or replaced.

We should enquire about this again.

**Comment by RealOrangeOne** [comment]
I've asked the SRO committee about borrowing them again this year. Under the condition that any damages be replaced.

**Comment by RealOrangeOne** [comment]
SRO have graciously let us borrow the robot flags, assuming we fix any damage we cause.

We should still get some fittings for teams to use.

**Comment by PeterJCLaw** [comment]
I've a feeling we have some fittings in storage, might be worth adding
that to the list of things to look for if we do a storage check.

**Comment by antoinepetty** [comment]
Closing this for the 2020 virtual competition because https://github.com/srobo/competition-simulator/issues/46
