### ISSUE TITLE
Put out the staging area

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#514]
Build the staging area for the arenas, where the teams will attach
and remove the robot-flags and competition-mode USB keys.

This should be designed as a one-way system, and include two sets of
tables:
* for the robots to placed on while waiting for their match (which
  should have sections labelled per-arena and -corner), used to mount
  the robot flags and for inspection if needed
* for the robots to be placed on after a match to have their flags
  removed

The second set of tables should also have a storage area for the
flags and USB keys, arranged such that it's clear which ones are
present. A volunteer should be assigned to managed this.

### Original

[comp/arena/staging-area](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/staging-area.yaml)

### Dependencies

 * #511 Organise high-vis jackets for the teams at the competition
 * #512 Prepare robot flags for the competition
 * #513 Prepare competition-mode USB keys

**Comment by WillB97** [comment]
We are looking at having a ingress and egress tables, these will be 2m each along the south arena edge.

There will also be a "sin bin" table for robotics that have been disqualified or failed safety checks.
