### ISSUE TITLE
Provide power to all team pits

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#515]
All the team pits and related areas need power provided.

### Original

[comp/pits/power](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/power.yaml)

### Dependencies

 * #417 Ensure there is power at the SR2020 competition

**Comment by RealOrangeOne** [comment]
We've recieved a quote from Reading for the power distro needed, however the quote value isn't quite confirmed yet. 

The value is very reasonable.
