### ISSUE TITLE
Have a supply of charged batteries by the SR2020 Arenas

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#517]
We should have a supply of charged batteries by the entrance to the arena so that teams don't need to go to helpdesk on the way to the arena to get one. This will also ensure that robots perform to their best since we can just given them new batteries if there's any uncertainty.

### Original

[comp/arena/batteries](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/batteries.yaml)

### Dependencies

 * #460 Plan for disposal of sad batteries
 * #509 Build the arenas
 * #516 Prepare battery charging station

**Comment by RealOrangeOne** [comment]
I don't think this is something we've ever done before. In the current venue map it's going to get pretty crowded if people are trying to install batteries around staging. With helpdesk so close, it's probably fine to discard this task? Or at the very least downgrade it.

**Comment by TomWheal** [comment]
I dont think we should do this

**Comment by RealOrangeOne** [comment]
Good enough for me!

**Comment by PeterJCLaw** [comment]
> I don't think this is something we've ever done before.

We had this for almost all the Newbury years and before that in Southampton. It proved valuable, especially during the knockout stages.

> In the current venue map it's going to get pretty crowded if people are trying to install batteries around staging.

Ah, the idea here is that this supply is _exclusively_ for teams _in staging_ -- i.e: robots which turn up but then realise their battery is dead. There won't be any announcement of this feature of staging, but we _really_ don't want dead batteries to cause robots to miss matches (especially in the knockouts).

> With helpdesk so close, it's probably fine to discard this task? Or at the very least downgrade it.

Helpdesk is definitely closer this year, but not really close enough given the time pressures of staging.

Importantly: I can't see any reason _not_ to do this -- it's very nearly zero effort and avoids dead robots.

**Comment by Scarzy** [comment]
>
> It proved valuable, especially during the knockout stages.
>


> Importantly: I can't see any reason *not* to do this -- it's very nearly
> zero effort and avoids dead robots.


I agree with Peter here, for the sake of a few batteries and a couple of
LiPo bags, I think this is very much worth doing.

And having dealt with several teams who were taken out of the knockouts and
feel it's our fault, it'd definitely reduce grumpyness.

I might suggest doing this only for the knockouts, that way during seeding
they pick up the idea that they have to keep an eye on their battery. But
come the knockouts these provide a nice safety net.

**Comment by TomWheal** [comment]
> Ah, the idea here is that this supply is exclusively for teams in staging -- i.e: robots which turn up but then realise their battery is dead. There won't be any announcement of this feature of staging, but we really don't want dead batteries to cause robots to miss matches (especially in the knockouts).

Ah, the task didn't make this clear, yeh there's no problem with that. I'll make sure it gets done.
