### ISSUE TITLE
Prepare generic music playlist for the compettion

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#519]
During matches we want music to be played into the arena. Typically this takes the form of a Spotify playlist.
Note that there is a separate task for the time-synchronised music played during the finals.

### Original

[comp/arena/music](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/music.yaml)

### Dependencies

 * #416 Sort out sound system for the competition

**Comment by RealOrangeOne** [comment]
Dramatic soundtrack: https://open.spotify.com/playlist/6xHgT3sk8F3OKy53Ri8nSq
_Chill_ soundtrack: https://open.spotify.com/playlist/4Nm71RKeTCWHKmzazR5X5x

These are now in a state where we could easily ship them, but I'll be constantly editing and refining them up until the competition, so it's not worth keeping the issue open.
