### ISSUE TITLE
Competition Program Documentation Platform

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#52]
We should have a single point of call for people to work out how things work at SR. How to get involved, and how to get something done. Some review on the above implementation would be appreciated. I'll make changes to it as comments come in.

## Features
- Searchable
- Re-usable task definitions
- Easily modifyable (Markdown on GitHub counts!)
- Incredibly low barrier to entry for usage and contribution
- Well sectioned and organised
- Not duplicating other resources
- Review before changes made (ideally backed by Git)

## Ideas of things to contain
- How to contribute to this system
- Git branching workflow
- Team comms suggestions
- Event runbooks
- https://github.com/srobo/comp-team-coord-docs
- https://github.com/srobo/community-guidelines
- How to email teams
- Game suggestion
- How to risk assessments (https://github.com/srobo/risk-assessments) (don't internalize!)

## Things it should not contain (examples)
- Documentation for team leaders / competitors (those stay in the existing docs)
- Kit maintenance docs (as those also contain test scripts)
- How to use the inventory

## Implementations
- Using GitHub to render markdown (_very_ quick to get up and running!)
- [GitBook](https://www.gitbook.com/). Free for non-commercial!
- Static site generator (probably Jekyll)

A repo already exists storing recurring tasks, which we should onboard. https://www.studentrobotics.org/cgit/recurring-tasks.git.

As well as storing _what_ we do, it's important to document _why_ we do it this way, so people understand why something in done a certain way. My current intention is to investigate if GitBook does what we need, and if it doesn't, roll something myself (with a Jekyll theme).

**Comment by PeterJCLaw** [comment]
@RealOrangeOne: could you clarify what the blocker is here?

Separately, could we clarify whether the latter two points in the "Things it should not contain" section are specifics or examples of a general class? (I'm assuming they're examples as I suspect there are plenty more things like them)

**Comment by RealOrangeOne** [comment]
The blocker is on some level of response to the approach, before I actually start implementing.

They were specific examples, but also outline the kind of thing it won't contain. I'm expecting this to be a somewhat growing list. eg there'll almost certainly be a page on the inventory, it just won't explicitly document how to use it, it'll primarily link to the repo

**Comment by PeterJCLaw** [comment]
I'm not sure that the approach used is something we can have strong confidence in getting right the first time without some prior experience in using whatever system we go with. Do you think you'd be able to put up some prototypes (perhaps with similar information) and then make a recommendation about which felt easiest to get content into?

**Comment by richardbarlow** [comment]
The Trustees already use GitBook for the Ops Manual (https://srobo.gitbook.io/ops-manual/). I contacted them about using their service for free and, at least at that point in time (about 6 months ago), they said that they do intend on doing that, but they didn't currently have any mechanism to do it. It would be good if you got in touch with them again to see if anything has changed so that we can have more users as part of the organisation on there.

Also, could I please request that you use the phrasing 'Student Robotics Competition Program' when referring to the thing that you are looking to document. This is to provide a clear distinction between the activity that the Core Team is responsible for running and the organisation 'Student Robotics' as a whole. As far as I can tell (and would expect), this run book is the manual for how to run a competition program. The documentation for the organisation as a whole is the the Ops Manual maintained by the Trustees.

Also, remember that there is a vast amount of potentially useful information contained in the old v2 ops manual: https://github.com/srobo/legacy-ops-manual/releases/download/v2/ops-manual-v2.pdf
Also in the tree of role docs, starting here: https://bitbucket.org/rspanton/sr-comp-programme/wiki/Home (make sure to fully traverse the tree via the 'subordinate roles' links to see all of the docs). Hopefully some of this will help with writing the run book.

**Comment by Tyler-Ward** [comment]
@RealOrangeOne I have started building a set of latex addons that I am using for the smallpiece runbook which might be useful e.g. inbuilt task list generation from tasks attached to activities.

**Comment by RealOrangeOne** [comment]
Quite possibly, although the format of this will be web-based rather than a PDF, so I won't be using the LaTeX directly, but it'll certainly be a good starting point for those things!

**Comment by PeterJCLaw** [comment]
Note also that the https://www.studentrobotics.org/cgit/recurring-tasks.git repo was originally designed to be a repository of tasks, so it already contains code to import them into task trackers.

**Comment by Tyler-Ward** [comment]
Given our current tooling works with it is it worth going back to using trac for documentation and the recurring tasks? https://trac.edgewall.org/

**Comment by RealOrangeOne** [comment]
I've completed some research, and I think the way to go is https://www.mkdocs.org/.

I've created a demo site at https://github.com/RealOrangeOne/mkdocs-sr-demo, with an example setup. I loaded in the docs content (unedited) so there's some pages and examples to flick through. There's a lot of markdown extensions enabled which it doesn't use fully however, which would make the render nicer.

## Benefits
- mkdocs is *designed* for documentation!
- We're allowed to assume those who want to work on  it have python setup locally
- Content is just markdown files in a repo
- Deployment using GitHub Pages and CircleCI is free (we should setup a custom domain for this!)
- Supports static files, and reading them into templates
- Well-indexed, easy to use search
- Backed by Git

## Drawbacks
- Mkdocs isn't quite as known as many other frameworks
- The deployment process is a little annoying to get your head around, although fairly simple
- No colour scheme for the chosen theme matches our colour scheme. This should be fairly simple to change https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/application-palette.scss#L66

## Issues with other implementations
- Raw GitHub doesn't look quite as nice
- Hugo can be interesting to install, and Go templates are fairly nasty
- GitBooks can only be rendered by their service. The CLI is deprecated. It's also harder to customize.
- Jekyll doesn't have very nice documentation themes which are powerful enough
- Netlify costs for organisations, and linking this to a single person is a bad idea. Also no SLA

My interpretation of the tasks is that they're static files stored in the repo, which scripts parse to action (create GitHub issues from most likely). In that case we don't need anything dynamic. The files can be statically created in here, and read from the web server by a script.

## Moving forward

I'm hoping to discuss this again in the next core-team meeting to collect any issues with this implementation, and anything i've forgotten. If it's all ok, I'll start committing and transferring the work i've done into an SR repo, and get deployment setup. I'll then work on moving in the existing recurring tasks repo (with history) so that can be utilized.

**Comment by PeterJCLaw** [comment]
Minor: Thoughts on using netlify for this over GitHub Pages (mostly as it avoids polluting a repo with build artefacts, but also for the various other benefits which we know that netlify has)?

**Comment by PeterJCLaw** [comment]
Scratch that, just seen your comment about netlify costing. Just a thought: do we know whether they have a charity tier?

**Comment by RealOrangeOne** [comment]
> Do we know whether they have a charity tier?

We don't, i'll enquire though. I agree the deploy previews are definitely worth having!

**Comment by Tyler-Ward** [comment]
> We're allowed to assume those who want to work on it have python setup locally

Needing python and command line knowledge to do any documentation tasks sounds like quite a barrier to non tech people submitting organisational documentation or is this just needed for development of the framework?

**Comment by RealOrangeOne** [comment]
Needing command line knowledge is kinda annoying, yes. But that's only to run the server. If someone wants to just write a markdown file, stick it in the right place, and commit it, there's nothing stopping them. 

I think PR previews will help eliminate this as a requirements. @PeterJCLaw i've contacted Netlify about charity pricing, but haven't heard back, will feed back on that once I hear back, but I don't consider it a blocker, just a massive benefit.

**Comment by trickeydan** [comment]
I think Mkdocs will work as long as we write a contribution guide.

**Comment by RealOrangeOne** [comment]
Implementation has started at https://github.com/srobo/runbook

**Comment by PeterJCLaw** [comment]
@RealOrangeOne the runbook is now getting started. At what point do you think we should close off this ticket?
If there are thinks you feel are outstanding, perhaps it would make sense for them to become separate tasks?

**Comment by RealOrangeOne** [comment]
I think now that the repository exists, has _some_ content, it's probably ok to close this. Any issues / commends relating to it should be made on the repo itself.
