### ISSUE TITLE
Plan helpdesk at the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#524]
Helpdesk is the single-point-of-contact for teams to get help with their robots. We need to plan who will run this on the day as well as the various things it needs to be able to help the teams.

### Original

[comp/pits/helpdesk/main](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/helpdesk/main.yaml)

### Dependencies

 * #454 Plan overnight kit & battery loans at the competition
 * #460 Plan for disposal of sad batteries
 * #499 Create a list of available subject matter experts
 * #515 Provide power to all team pits
 * #516 Prepare battery charging station
 * #523 Have spare kit available at the competition

**Comment by TomWheal** [comment]
Happy to take this on, as I can now confirm i can attend the compeition

**Comment by PeterJCLaw** [comment]
Moving conversation from #119 (Kit Team/Competition Team discussion about how to run helpdesk):

@RealOrangeOne wrote https://github.com/srobo/competition-team-minutes/issues/199#issuecomment-577408604:
> I had a chat with @TomWheal this evening, the outcome was:
> 
> * Those assigned to helpdesk should have a working knowledge of the kit, and how to use it.
> * "Team Kits" label is fine for separating issues, but as always, if someone sees an issue and can help, they can / should. It's not the competition team's task list!
> * Those assigned to helpdesk should not be the ones handing out batteries, there should be a (perhaps physical) divide
> * Tom, if available, will take the "Head Helpdesk" role. Remaining committee / team members should be scheduled as usual, however a skew towards kit-related roles is probably ideal.

@PeterJCLaw wrote https://github.com/srobo/competition-team-minutes/issues/199#issuecomment-578418832:
> Thanks, that mostly sounds good.
> 
> > * Those assigned to helpdesk should not be the ones handing out batteries, there should be a (perhaps physical) divide
> 
> I'm surprised and a little concerned about this. What's the rationale for this?
> 
> It strikes me that this is going to mean that a lot of requests for batteries will get the response "I can't help with that, go over there (_pointing along the desk_)" as well as mean that two volunteers are now needed to permanently sit at Helpdesk where previously only a single one was needed. Moreover the person sat handing out batteries will have very little to do but be unable to actually help teams.
> 
> Previously we have had a pot of batteries at Helpdesk and allowed any volunteer there to hand them out. I'm not aware that there have ever been issues with this.

@TomWheal wrote https://github.com/srobo/competition-team-minutes/issues/199#issuecomment-578423340:
> > I'm surprised and a little concerned about this. What's the rationale for this?
> 
> There were times last year where there was such a big queue for batteries it was causing a firerisk, becasue all the volenteers were busy handling technical problems with teams. Moving the technical help of the help desk will help with this as well, so its likley batteries will still be available on the help desk.

Ah, right. That's definitely undesirable -- both that we had queues and that they became problematic in themselves.

When helpdesk was first thought up, the original intent was that helpdesk was primarily a triage point, rather than being the place which actually solved the competitors' problems.
With that in mind, the protocol (a long time ago) was something like:
1. competitor briefly outlines their problem
2. if there's a known solution the competitor is told about it, otherwise
3. helpdesk records this and tells the competitor that someone will come to help them
4. when a volunteer is next free, they pick the next issue from the list

This should mean that helpdesk itself is low-latency and high throughput, with low chance of queueing. It also means that robot analysis (etc.) all happens in pits rather than at helpdesk, so the desk itself doesn't need a lot of space.

Aside: note that the above protocol also means we get a list after the competition of all the known issues and their solutions, which was intended to help us improve the kits. I'm not sure how much we actually used that information nor how useful it was though.

I've a feeling that at Newbury we were spoilt for space and so ended up doing a bunch of diagnostics at helpdesk itself, which was probably fine there, but works less well in a smaller venue.

Perhaps something closer to the original protocol could be considered?

**Comment by TomWheal** [comment]
That sounds like a reasonable idea, currently my idea was to have a seperate unadvertised desk where technical issues are dealt with. But what your suggesting could also work, Ill address this properly when I start the plan for the helpdesk

**Comment by PeterJCLaw** [comment]
This is redundant in light of the lack of venue. We'll still be doing mentoring, however it will happen naturally via the forums.
