### ISSUE TITLE
Roll out at team pits at the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#528]
### Original

[comp/pits/rollout](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/rollout.yaml)

### Dependencies

 * #474 Work out layout of teams at the competition
 * #515 Provide power to all team pits
 * #522 Organise tables and chairs for team pits
 * #526 Organise internet access for the team pits
 * #527 Determine and publish rules for the pits

**Comment by RealOrangeOne** [comment]
![](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fmemecollection.net%2Fwp-content%2Fuploads%2F2015%2F11%2F6824da61-roll-out.gif&f=1&nofb=1)

**Comment by WillB97** [comment]
How does this differ form #530?

**Comment by PeterJCLaw** [comment]
I _think_ this task is about doing the rollout on the actual setup day. The [recurring tasks](https://github.com/srobo/recurring-tasks) unfortunately contain tasks both for preparation and actual rollout, though I now think the latter are generally less useful.

There are some cases where the on-the-day task is more useful though, as they act like a checklist of things to do but which don't need a lot of preparation.

I did try to rationalise things a bit before this year's import, though didn't look at everything. PRs which tidy these up are most welcome!
