### ISSUE TITLE
Arrange a discount price for the hotel.

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#53]
We're pulling in 37 teams, so about 250 people, we can probably arrange a discount with a hotel.

**Comment by PeterJCLaw** [comment]
Might want to consider that:
* this might need to be more than one hotel
* volunteers need somewhere to stay too

**Comment by JennyLouise** [comment]
Do we have a more exact number than "about 250", and an accommodation budget? I'm happy to get in touch with places, but won't be available the week of the event so won't be a great point of contact.

**Comment by RealOrangeOne** [comment]
We can get a more accurate number, but there's no way to tell it's correct. We can enumerate the number of IDE logins, but there's no way of telling if that's a realistic number.

A side note of this, many teams will likely have already booked accommodation, so we're looking at drastically reduced numbers to this.

**Comment by Adimote** [comment]
we've left this a bit too late now sadly.
