### ISSUE TITLE
Prepare game equipment (props) for the arena

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#531]
We need to prepare the things that will go in the arena. See this year's [rulebook](https://studentrobotics.org/docs/resources/2020/rulebook.pdf) for details.
Sub tasks should be added to this task for each of the various props which are needed.

### Original

[comp/game/props](https://github.com/srobo/recurring-tasks/blob/master/comp/game/props.yaml)

### Dependencies

 * #448 Organise markers for the arena
 * #512 Prepare robot flags for the competition
 * #576 Organise tokens

**Comment by RealOrangeOne** [comment]
The primary piece of arena prop is the raised area in the centre. This is intentionally the size of 4ft stage decking.

@WillB97 Do you know any good places some could be _acquired_ ?

**Comment by WillB97** [comment]
It would likely be cheapest to get this from SUSU or Reading

**Comment by RealOrangeOne** [comment]
Reading have stage decking, but unfortunately not the right sizes to make the interior raised area.

Hiring from SUSU sounds like the safest bet.

@WillB97 as you have the contacts / experience / knowledge on this, are you ok to be assigned?
