### ISSUE TITLE
Prepare the finals music for the compettion

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#533]
We generally use a bespoke cut of various songs for the finals tracks, to build tension, ensure the music is dramatic enough, and is timed perfectly, with starting of matches and timing.
Previous years' playlists:

 - Smallpeice 2018: https://open.spotify.com/user/theorangeone97/playlist/5VvONyDmSpdErqseA75Vad?si=U1adYZc-QryZErjZFaAxrg
 - SourceBots 2018: https://open.spotify.com/user/theorangeone97/playlist/2mowt6maj0vhLUdrnCKtnw?si=AGzULOo7SFSn7o_eL6rY7g
 - Smallpeice 2017: https://open.spotify.com/user/theorangeone97/playlist/4ZaS9NTwF1erqqpE1IxHlP?si=DKExkDEUR9KF__ZswCdicg

Note that there is a separate task for the music played during the rest of the matches.

Since this is for a live stream this year, we need music which can be broadcast on the stream. We do still probably want to use "[mixtape](https://github.com/srobo/srcomp-mixtape)" though.

- [ ] Source suitable music (i.e: copyright free or where we have a license)
- [ ] Ensure mixtape works on the stream machine
- [ ] Ensure mixtape can output to OBS

### Original

[comp/game/finals-music](https://github.com/srobo/recurring-tasks/blob/master/comp/game/finals-music.yaml)

### Dependencies

 * #416 Sort out sound system for the competition

**Comment by RealOrangeOne** [comment]
This ticket will be slightly more interesting for a virtual competition, as we'd have to use copyright-free sound, which drastically limits options.

**Comment by PeterJCLaw** [comment]
We could get a license for broadcast? I've no idea what's involved for that though.

**Comment by PeterJCLaw** [comment]
Downgrading as this feels less important without a physical venue and because we'd need to sort different licenses anyway.

**Comment by PeterJCLaw** [comment]
https://www.youtube.com/user/NoCopyrightSounds is likely a useful source of music.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne I think you posted in Slack that you'd done this? Do you want to post the playlist here and then close this task?

**Comment by RealOrangeOne** [comment]
The finals playlist won't be the regular timed and triggered variety we've done for competitions in the past using [mixtape]().

There is however a more "intense" playlist which can be used for the knockouts and finals: https://www.monstercat.com/playlist/ba79ae21-35e6-4320-bcfe-22b5893eea95. It could do with being _slightly_ longer just to ensure it doesn't stop prematurely, but it's definitely shippable as-is.
