### ISSUE TITLE
Migrate existing documentation to new platform

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#54]
Following #52 we'll have a common platform for all our internal documentation. Once that's set up, we'll want to migrate existing sources of documentation to the new platform.

Sources of existing documentation:
* [Community Guidelines](https://www.studentrobotics.org/community-guidelines) (https://www.studentrobotics.org/cgit/community-guidelines.git and srobo/community-guidelines)
* [Volunteer Handbook](https://www.studentrobotics.org/volunteer-handbook) (https://www.studentrobotics.org/cgit/volunteer-handbook.git/)
* The _old_ ops-manual and subsidiary per-role documentation:
  * https://github.com/srobo/legacy-ops-manual/releases/download/v2/ops-manual-v2.pdf
  * https://bitbucket.org/rspanton/sr-comp-programme/wiki/Home
  * https://bitbucket.org/rspanton/sr-head-treasurer/wiki/Home
  * https://github.com/srobo/comp-team-coord-docs
* https://github.com/PeterJCLaw/recurring-tasks (forked from https://www.studentrobotics.org/cgit/recurring-tasks.git)
* https://studentrobotics.org/trac/

https://github.com/srobo/website/issues/13 is also of potential interest.

(Please do add to the above list)

A first step here is likely to establish whether we can use the above sources under ~https://creativecommons.org/licenses/by-sa/4.0/~ a suitably free license, which probably involve contacting the original authors.

**Comment by PeterJCLaw** [comment]
CC BY-SA 4.0 is what the [new ops-manual uses](https://srobo.gitbook.io/ops-manual/miscellaneous). For some reason I'd thought that it was also recommended for other documentation, though that seems not to be the case.

I'm open to other licenses, though I agree one aimed at documentation rather than code is a good choice.

**Comment by RealOrangeOne** [comment]
I've got no objection to CC BY-SA 4.0, but seeing as the new ops-manual uses it, it's as good of a license as any. I suspect that in discussions about relicensing the existing works, a suitable license may come out of that.

**Comment by trickeydan** [comment]
CC BY-SA 4.0 seems sane for documentation. 

I would also suggest adding in any (if any) useful information from the SourceBots volunteer docs.

**Comment by RealOrangeOne** [comment]
Having a quick look around, it doesn't look like there's much to take from the SB volunteer docs, besides the concept of a "How to update the docs" page, which we should *definitely* have

**Comment by PeterJCLaw** [comment]
I'd comment on #3 (except that for some reason I can't): CC BY-SA 4.0 seems to be what a lot of the existing docs use, so continuing that license seems most likely the easiest to me.

**Comment by PeterJCLaw** [comment]
While https://github.com/srobo/runbook/issues/18 exists for the outstanding content, since https://github.com/srobo/runbook/pull/8 has merged, I'm considering this done. Any future tasks will be issues on that repo.
