### ISSUE TITLE
Acquire trophies

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#544]
Some awards involve trophies being given to the winning teams. The trophies need purchasing.

Last year's task: #134. We probably want very similar things, so what we ordered last year is a good starting point.

### Original

[comp/prizes/trophies](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/trophies.yaml)

**Comment by PeterJCLaw** [comment]
For the virtual competition, we can do this once we know who we're sending it to.

**Comment by Adimote** [comment]
very sorry for the (really long) delay on this, I've made the order and am about to send an email to them to tell them about the weird shipping arrangements.

**Comment by Adimote** [comment]
For posterity here's the order info: 
Supplier: trophies2u.co.uk
Trophy: "great style slant jade glass award" https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html
Text:
```
Student Robotics
2020
Two Colours

<award name>
<team name>
```

I asked in the followup email about:
- confirming the logo they have on file is our logo, I used the white-vertical-logo, which I just made a PR for in the style repo at https://github.com/srobo/style/pull/19/files

- I sent them the mock of the trophy from last year, which is this image:
![trophy mock](https://user-images.githubusercontent.com/2551763/93273141-74ddf300-f7b7-11ea-8899-88fd1073b0fb.png)
I also noted that there should be one extra line for the team name

- I asked them about shipping each trophy to a different address, listing each address for each trophy.

**Comment by Adimote** [comment]
Their original quote for this (which I've paid) is £115.41 but they'll likely invoice for more for the additional shipping costs.

**Comment by Adimote** [comment]
They've asked for an additional £23.85 for shipping, bringing the total up to £139.26

The logo they had on file was not the latest, but they updated it for free because we're a returning customer.

**Comment by PeterJCLaw** [comment]
@Adimote I assume this is done now?

**Comment by Adimote** [comment]
Yes this is done!
