### ISSUE TITLE
Decide on the winner of the online presence award

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#549]
The online presence award is put to a vote of the community. This needs to happen before the competition.

### Original

[comp/prizes/web-presence](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/web-presence.yaml)

**Comment by antoinepetty** [comment]
As I'm handling the social media, it would make sense for me to own this task

**Comment by PeterJCLaw** [comment]
Once decided, let's put the result in the [same spreadsheet](https://docs.google.com/spreadsheets/d/1SDC-u-g_8dbP-0HuiQNLQEKMuKEtoi4Ir-JebuZMEeQ) as #550's result is in.
