### ISSUE TITLE
Organise the SR2020 post-finals sequence

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#554]
At the end of the competition we want to give out some prizes. We need to plan how we will transition from the finals, through any speeches and run the actual prize-giving ceremony.
We should ensure that anyone who is speaking (whether a volunteer or a guest speaker) knows how long they have, what we're expecting them to talk about and is well rehearsed.
We should include (somewhere) thanks to various people: teams, volunteers, sponsors, etc.

### Original

[comp/prizes/ceremony](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/ceremony.yaml)

### Dependencies

 * #455 Get envelopes & card for the prize ceremony
 * #548 Arrange a speaker for the prize ceremony
 * #549 Take a vote on the online presence award
 * #550 Establish the winner of the first movement award
 * #551 Establish the final results for the main prizes and the rookie award
 * #552 Decide on the recipient of the committee award
 * #553 Decide on the winner of the team image award

**Comment by RealOrangeOne** [comment]
As i'll most likely be the one presenting this, it makes sense for me to own organising it

**Comment by RealOrangeOne** [comment]
I've started working on this plan. https://docs.google.com/document/d/1y4dfJEriBm7oqAihC_DivKQXuL12NzfBywjtBinvB6M/edit?usp=sharing

It's heavily based on SR2019, however because there's no dedicated stage, the process has been altered to have the ceremony in the arena.

**Comment by RealOrangeOne** [comment]
This has been reviewed and considered fine, although specific details may be slightly changed closer to the time.

**Comment by PeterJCLaw** [comment]
Meta: the general idea of the recurring-tasks hierarchy is that parent tasks should remain open until all of their child tasks are complete. Closing this task therefore implies that we have established all the pre-determinable winners, got the card, know exactly the mechanics of the speakers within the venue, etc.

Has all that happened?

**Comment by RealOrangeOne** [comment]
Not directly, although the specific ordering and process of it has, where there is no better task.

Meta: Meta tasks in a flat task system lead to a lot of confusion

**Comment by PeterJCLaw** [comment]
This needs review in light of the virtual competition.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne any update on this?

**Comment by RealOrangeOne** [comment]
Aha, I knew I had an adapted plan somewhere: https://docs.google.com/document/d/1b97HKdstZaS-anYRtGtUFtgkkcbToYioF_CL9pVJfbA/edit?usp=sharing

Needs some polishing on how the awards loop looks depending on whether there's a guest speaker or not, but that's a minor point to fines.

**Comment by PeterJCLaw** [comment]
This happened.
