### ISSUE TITLE
Organise prizes for the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#556]
We need to decide what prizes we're having and what the trophies for each are going to be.

We also need to work out how/if we're going to do a prize-giving.

### Original

[comp/prizes/main](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/main.yaml)

### Dependencies

 * #544 Acquire trophies
 * #545 Acquire edible prizes
 * #554 Organise the SR2020 post-finals sequence
 * #555 Have a rehearsal of the post-finals sequence

**Comment by RealOrangeOne** [comment]
- What are the prizes going to be? (will there be physical prizes?)
- Where/to whom are we going to send the trophies/prizes?

**Comment by PeterJCLaw** [comment]
A recap of the prizes in the rulebook:
- 1st, 2nd, 3rd; trophies
- Rookie Award (highest in the leage); trophy
- Robot & Team Image; trophy
- First movement (video via the forums); edible
- Online Presence; edible

Of these, the one which seems hardest to judge is the Robot & Team Image. There aren't physical robots to judge and we're not going to see the teams themselves. I do think that some teams may still find ways to compete for this though.
I suggest therefore that we drop this award soon and explicitly so that their efforts aren't wasted. We could maybe roll such efforts into the Online Presence award?

We do still have a couple of rookie teams, so those prizes are still valid.

I suggest that we award First movement as we would have done normally -- videos of physical robots, though perhaps only allowing submissions from before lockdown.

**Comment by PeterJCLaw** [comment]
> Of these, the one which seems hardest to judge is the Robot & Team Image. There aren't physical robots to judge and we're not going to see the teams themselves. I do think that some teams may still find ways to compete for this though.
> I suggest therefore that we drop this award soon and explicitly so that their efforts aren't wasted. 

This happened.

**Comment by PeterJCLaw** [comment]
@Adimote any update on this?

**Comment by Adimote** [comment]
I've contacted our usual supplier ( trophies2u.co.uk ) and they say they are happy to process our order

**Comment by PeterJCLaw** [comment]
See also https://github.com/srobo/tasks/issues/614 for getting the trophies to the teams.

**Comment by Adimote** [comment]
very sorry for the (really long) delay on this, I've made the order and am about to send an email to them to tell them about the weird shipping arrangements.

**Comment by Adimote** [comment]
For posterity here's the order info: 
Supplier: trophies2u.co.uk
Trophy: "great style slant jade glass award" https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html
Text:
```
Student Robotics
2020
Two Colours

<award name>
<team name>
```

I asked in the followup email about:
- confirming the logo they have on file is our logo, I used the white-vertical-logo, which I just made a PR for in the style repo at https://github.com/srobo/style/pull/19/files

- I sent them the mock of the trophy from last year, which is this image:
![trophy mock](https://user-images.githubusercontent.com/2551763/93273141-74ddf300-f7b7-11ea-8899-88fd1073b0fb.png)

- I asked them about shipping each trophy to a different address, listing each address for each trophy.

**Comment by Adimote** [comment]
Their original quote for this (which I've paid) is £115.41 but they'll likely invoice for more for the additional shipping costs.

**Comment by antoinepetty** [comment]
Was this finished?

**Comment by PeterJCLaw** [comment]
Closing in favour of the sub-tasks.
