### ISSUE TITLE
Plan to take a group photo of everyone

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#558]
We should take a group photograph of all the teams and their robots.
We've managed this at a couple of previous competitions and generally the photos are useful for advertising ourselves in the future. They also serve as a useful tool when looking back to identify which robots appeared in which years.

### Original

[comp/photos/everyone](https://github.com/srobo/recurring-tasks/blob/master/comp/photos/everyone.yaml)

**Comment by RealOrangeOne** [comment]
If this ticket happens, it's critical we have the location for this decided and planned *before* the event. Each year this ends up a shamble, and with a new venue, forethought is even more important!

**Comment by PeterJCLaw** [comment]
When we were at Newbury this seemed to go fine. Agree we need to plan both time and location for it in advance.

**Comment by RealOrangeOne** [comment]
If weather is good, this can happen on the patio section outside the venue.

If weather is not so good, we might need to find an open place somewhere else in the venue.
