### ISSUE TITLE
Design "Business Cards" for core team functions

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#56]
We should design "buisness cards" for using when interfacing with other organisations

**Comment by mildlyincompetent** [comment]
These would have been really useful at today's careers fair, we should probably do it soon.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward meta: is there a reason that this issue is "pinned"?

**Comment by JordanTranchina** [comment]
Hey y'all. I'm a UX designer. Can I help? If so assign me to this issue.

Also what are the requirements for the business cards? front and back? can you give some example info with each field (so I can know character length limits)

**Comment by Tyler-Ward** [comment]
Hi Jordan, That would be great.

What we are after is a business card style card that has contact details for the various organisation emails  on a single card rather than for a single person (i have listed these below). We would be after an front and back similar to most business cards.

Some useful background info for you.
The SR style can be found at https://studentrobotics.org/style/
The about us page: https://studentrobotics.org/about/

Contact details to put on the card:
website: https://studentrobotics.org
Core team: coreteam@studentrobotics.org
Teams: teams@studentrobotics.org
Trustees: trustees@studentrobotics.org

**Comment by JordanTranchina** [comment]
Hey Team! See attached for some options on the front of the card. Let me know if you need the website on the front of the card as opposed to just the teams

![business card - front - version b](https://user-images.githubusercontent.com/41443492/52980365-b9b96200-33a7-11e9-9e47-a5afc5b74472.png)
![business card - front - version a](https://user-images.githubusercontent.com/41443492/52980366-b9b96200-33a7-11e9-8760-67c4c224da93.png)
![business card - back](https://user-images.githubusercontent.com/41443492/52980367-b9b96200-33a7-11e9-9205-ff81e202314f.png)

**Comment by Tyler-Ward** [comment]
Thanks @JordanTranchina those designs look great. I have added you as a contributor so I can assign you the ticket once you confirm.

I have created a repo at https://github.com/srobo/Promotional-material which you can submit a pull request to.

**Comment by Tyler-Ward** [comment]
see https://github.com/srobo/promotional-material/pull/3 for associated pull request

**Comment by Tyler-Ward** [comment]
Designs have been completed and merged thanks @JordanTranchina for your help with this.
