### ISSUE TITLE
Show the live stream within the venue

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#562]
It would be great to show the live stream of the competition is viewable within the venue. This enables everyone to see matches without actually being arena-side.
In the past the display has included a split-screen view of all the arenas which most people liked. It would be good to do this again.

### Original

[comp/livestream-local](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream-local.yaml)

### Dependencies

 * #480 Arrange a live stream from the competition

**Comment by PeterJCLaw** [comment]
Current plan is for the managing desk to be in a far corner of the room with the arena in. This should keep it close enough to the action, while being far enough away from the noise.

The presenters will likely face into the room, with their backs against the window. This gives us the option of having the outside (grass field) as the background, or pulling the blind closed behind the presenters.

**Comment by WillB97** [comment]
> Current plan is for the managing desk to be in a far corner of the room with the arena in. This should keep it close enough to the action, while being far enough away from the noise.
> 
> The presenters will likely face into the room, with their backs against the window. This gives us the option of having the outside (grass field) as the background, or pulling the blind closed behind the presenters.

This is more about arranging the livestream than showing it (#480)

**Comment by PeterJCLaw** [comment]
Oops, have duplicated on to that task, thanks!
----
Current plan is for this to be shown on one of the projectors in the non-arena rooms, which we can drive separately from the other screens in the room though only by putting a device right next to it.

**Comment by PeterJCLaw** [comment]
Downgrading to "Could have" given the comparatively easy layout of this year's competition -- most who want to watch the matches can trivially walk through to the arena room.
