### ISSUE TITLE
Publicise the competition on our Social Media

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#563]
In addition to the task-specific social media related to the competition announcement and the news article afterwards we should ensure that our social media accounts make a lot of noise about the competition.
In the lead-up to the competition this means we should be inviting people to attend and reminding competitors to get tickets.
During the competition we should consider including some summary commentary about how the teams are doing, as well as interacting with the accounts for the teams. We should also announce the results as they become available (i.e: during the prize-giving ceremony).

### Original

[comp/social-media](https://github.com/srobo/recurring-tasks/blob/master/comp/social-media.yaml)

### Dependencies

 * #411 Announce the competition

**Comment by antoinepetty** [comment]
I'm looking to largely repeat last year's social media activity in the lead up to and during the competition. The teams have a larger social media presence this year so it's easier to publicise their progress

**Comment by antoinepetty** [comment]
Still going ahead with this. I hope the teams will start posting bits about their progress on the simulator soon

**Comment by antoinepetty** [comment]
The competition has been publicised so I think it's worth closing this. We'll continue posting regularly for the next couple of weeks
