### ISSUE TITLE
Plan the welcome talk for competitors and guests

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#566]
This ticket exists mainly to ensure that things are announced to the competitors.

### Original

[comp/welcome](https://github.com/srobo/recurring-tasks/blob/master/comp/welcome.yaml)

### Dependencies

 * #516 Prepare battery charging station
 * #517 Have a supply of charged batteries by the SR2020 Arenas
 * #524 Plan helpdesk at the competition
 * #525 Set up a power tools area

**Comment by RealOrangeOne** [comment]
I will be the one giving this.

**Comment by RealOrangeOne** [comment]
SR2019 notes: https://docs.google.com/document/d/1AGI5pcDmrkBAjjoFuOSj4PGZyipmhmTJEliEie9wnwU/edit?usp=sharing

**Comment by RealOrangeOne** [comment]
I've now started work on this, review welcome. https://docs.google.com/document/d/1KJmPq3KHYK87ZLPgonFh-s5cCk1Vh0RhGL2bpXdVRbU/edit?usp=sharing

It's a complete rip of my 2019 notes, just modified slightly for this year.

I'm very much expecting it to be refined over time, but as a base this is probably ~90% done. Will leave it open until much closer to the event when we're more sure what needs covering

**Comment by RealOrangeOne** [comment]
Started drafting up some new points, as for the virtual competition it's going to be a little different.

https://docs.google.com/document/d/1SyKQL50hiwVFgNiq314j3bnqrPYDrP9lpwMqNUgMinQ/edit?usp=sharing

**Comment by PeterJCLaw** [comment]
Is this still relevant? Or is it more that these are notes for the commentators.

**Comment by RealOrangeOne** [comment]
I think this is still relevant. We definitely don't want to just suddenly start streaming matches, some sort of opener is a good idea!

**Comment by PeterJCLaw** [comment]
Things we learnt:
- we should include more information on the stream (both at the start an ongoing) about what the game is and how it works
