### ISSUE TITLE
Prepare signage for the SR2020 Competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#567]
We'll want to put up various signage of our own, even if the venue cover the basics. For example, we have our own giant banner which should go somewhere and we'll want directions to Helpdesk and the Areans.

### Original

[comp/venue/signage](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/signage.yaml)

### Dependencies

 * #421 Prepare a layout of the competition

**Comment by RealOrangeOne** [comment]
Some signage exists at https://github.com/srobo/signage, although should likely be updated.

@TomWheal IIRC you handled this for SR2019. Any idea where the designs ended up (if anywhere)?

**Comment by TomWheal** [comment]
They were just made in word on the day as they were needed, was quicker than faffing around with the script

**Comment by RealOrangeOne** [comment]
List of signs:

- Toilet Locations
- Entrances
- Exits
- Arena
- Do Not Enter
- Photography beyond this point
- No Robots beyond this point
- Power tools area
- Staging in/staging out
- Quiet zone / please be quiet (optional)

(src: https://github.com/srobo/tasks/issues/83#issuecomment-475879888)

When designing signs, best not to put any arrows on the printout. These can be printed off / drawn on later depending on where they're placed.

**Comment by tpoomlmly** [comment]
I've added some signs for 2020 to the signage repository: https://github.com/srobo/signage/pull/1

**Comment by RealOrangeOne** [comment]
@tpoomlmly great work, will review shortly! 

Are you ok being assigned this issue?

**Comment by tpoomlmly** [comment]
I'm fine with being assigned.
