### ISSUE TITLE
Reimburse volunteers

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#573]
We need to reimburse volunteers for all the things. This task exists mostly as a placeholder, the treasurer will of course be handling this ongoing anyway.

### Original

[comp/volunteers/reimbursement](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/reimbursement.yaml)

### Dependencies

 * #492 Plan reimbursement of volunteers

**Comment by RealOrangeOne** [comment]
The primary items left are https://github.com/srobo/tasks/issues/544 and https://github.com/srobo/tasks/issues/545

**Comment by PeterJCLaw** [comment]
@Adimote since you're (I think?) the only volunteer this affects, would you like to take this? I think at this point it'll need to go through the trustees directly anyway, as the SR2020 Competition Team doesn't really exist any more.

**Comment by PeterJCLaw** [comment]
Closing this as I believe this is sorted. In any cases the mechanism now is for reimbursements to go more directly to the trustees, so isn't something that the teams/committees orchestrate.
