### ISSUE TITLE
Prepare quote for (and buy) Tokens

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#576]
Specification from the rules:
> 3.5.1  Tokens are cuboid single-wall cardboard boxes with side length 260mm±15mm

We need at least 2 different suppliers which meet our needs, and total pricing for each.

SR2019: https://github.com/srobo/tasks/issues/105

**Comment by Adimote** [comment]
| Supplier | URL | price | quantity | price per box|
| --- | --- | --- | --- | --- |
| Cardboardboxes.co.uk | https://www.cardboardboxes.co.uk/product/10-inch-cubed-single-wall-cardboard-boxes-x-25/ | 15GBP | 25 | 0.60GBP |
| Davpack.co.uk | https://www.davpack.co.uk/cardboard-boxes/single-wall/brown-sw.htm |  23.51GBP | 25 | 0.94GBP |

**Comment by Adimote** [comment]
with my treasurer hat on, I think the 38GBP for 50 boxes is acceptable!

**Comment by PeterJCLaw** [comment]
Running the numbers here: 16 tokens per arena plus a full set of spares = 32 tokens

That seems a good number, but running at only a half set of spares might work if we absolutely needed to push it.

So 50 - 32 = 18 redundant tokens, which we can show/hand out if needed at Tech Days. Is 18 enough for that, or should we allow for more?

@Adimote are there benefits to buying at multiples of 25, or could we go to, say, 60 tokens?

If not, then 18 is probably enough for Tech Days I think.

**Comment by PeterJCLaw** [comment]
Thanks for putting together the quotes @Adimote :+1:

**Comment by PeterJCLaw** [comment]
Would be great to get these ordered in time for the tech day later this month (it's now too late to have them for this weekend).

**Comment by RealOrangeOne** [comment]
The current intention is for @Adimote to order them, and get them delivered to me at work, at which point I can bring a handful of them to whichever tech days need them.

**Comment by Adimote** [comment]
purchased!
