### ISSUE TITLE
Define Volunteer Roles

### ISSUE THREAD

**Issue by sedders123** [srobo/tasks#577]
The majority of our roles are documented in the [runbook](https://studentrobotics.org/runbook/), however, especially with a new venue, we should check to see if there are any roles that are no longer needed or any roles that need creating.

This list of roles can then feed into #493

**Comment by RealOrangeOne** [comment]
Based on the list of tasks in https://github.com/srobo/tasks/issues/81#issuecomment-471213510, and looking through the runbook, it looks like the roles are defined, however they're very difficult to find (without using the search). It would be good to normalise their location into the same section under "Competition" so they're easier to find.

**Comment by PeterJCLaw** [comment]
Downgrading as the competition can happen without this.

**Comment by WillB97** [comment]
From the discussion of roles and volunteer numbers at the tech day:

Role | Volunteers | Minimal Volunteers | Notes
--- | --- | --- | ---
__Control__ | | | __Role for entire event__
Event coordinator | 1 | 1
Volunteer coordinator | 1 | 1
Safety coordinator | 1 | 1
Producer | 1 | 0 | Could be merged with tech crew
__Match Officials__ | | | __Rotate roles within group throughout__
Marshals | 4x3 | 3 | Rotated with shepherd role and break
Shepherds | 4x3 | 1 | see above
Arena manager | 1 | 1
Timekeeper | 1 | 0 | Could be merged with Arena manager
__Team Facing__ | | | __Role for full day__
Helpdesk | 4 | 2 
_Battery charging_ | - | - | Merged with helpdesk
Reception | 2 | 1 | Could be merged with helpdesk depending on layout
Photographer | 1 | 0
__Team Facing__ |
_Power tool supervisor_ | 1 | 0 |
Roving volunteers | - | - | All non-allocated volunteers
__Ops__ |
srcomp/score entry | 1 | 1
Tech (sound/lights) crew | 2 | 1
Livestream operator | 2 | 0
Volunteer refreshments | 1 | 1
Runner | 1 | 0 | Could be merged with refreshments

**Comment by Tyler-Ward** [comment]
Whiteboard photo
![image](https://user-images.githubusercontent.com/3390465/74112386-21a62100-4b94-11ea-81b7-0ce8308605f3.png)

**Comment by RealOrangeOne** [comment]
Virtual competition roles:


-    Run the simulation (parallelises well)
-    Commentator ×2
-    Video mixer?
-    Scorer
-    Judge
-    In-chat mentors ⩾ 2
-    Coördinator (maybe)

**Comment by PeterJCLaw** [comment]
We know what we're doing for the virtual competition.
