### ISSUE TITLE
Have a venue visit Saturday 2020-02-15

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#578]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2020-01-08.md#specific

- First-aid / risk assessment checks (https://github.com/srobo/tasks/issues/420) (https://github.com/srobo/tasks/issues/464)
- Quiet areas?
- Volunteer Areas?
- Tech checks (https://github.com/srobo/tasks/issues/427)
- Final look around / confirmations of what we have
- Confirm any plans and layouts are realistic and accurate (https://github.com/srobo/comp-floorplans/pull/10)
- Work out where to take group photo? (https://github.com/srobo/tasks/issues/558)
- Find out how competitor networking will work (https://github.com/srobo/tasks/issues/526)
- Get numbers on tables and chairs (https://github.com/srobo/tasks/issues/522)
- Inquire about cable protectors (https://github.com/srobo/tasks/issues/428)
- Find out how many radios we can hire (https://github.com/srobo/tasks/issues/422)
- Confirm PRS etc license (https://github.com/srobo/tasks/issues/415)
- Do they have stage decking? (https://github.com/srobo/tasks/issues/531)
- Is the venue closed to the public?

**Comment by WillB97** [comment]
See also #579

**Comment by WillB97** [comment]
We should also consider srobo/comp-floorplans/pull/10 while we're there.

**Comment by PeterJCLaw** [comment]
Would it be worth bringing a printout of https://github.com/srobo/comp-floorplans/pull/10? I don't have a printer, otherwise I'd print a copy myself.

**Comment by RealOrangeOne** [comment]
This happened :tada: It was super productive.

I'll be updating the relevant tickets shortly.
