### ISSUE TITLE
Plan tech desk

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#579]
Things that are needed on the tech desk:
- Event scoring control (Peter's stuff) + printing
- Livestream
- Non-sync audio
- Networking
- Judging
- Radio charging
- Lighting desk
- Sound desk

Livestream can be placed elsewhere as direct-view of the arena is not necessary.
Radio charging is being handled by the venue.
Judging requires a view of the arena more than access to tech desk.

Half desk slots:
- Event scoring control
- Score-entry
- Event hot-desk
- (A corner for non-sync, sync audio and compbox)
- Sound desk
- Lighting desk

**Comment by PeterJCLaw** [comment]
Good spot. I think this has fallen under #543 in the past, though definitely worth having explicitly.

While these things have often been grouped together, many of them can be separated (and it's likely beneficial to do so).

As noted, radio charging & live streaming can easily be elsewhere. I'd also suggest that the networking hub be elsewhere too.

**Comment by WillB97** [comment]
We've come to the decision of 3 tables:

Table 1:
- Event scoring control
- Score entry

Table 2:
- Sound and lighting
- Mixtape machine

Table 3:
- Judge's screen
- Judge's Area

Livescreen will be elsewhere
