### ISSUE TITLE
Ping in Slack when tasks appear

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#58]
Previously we had an IRC bot which forwarded trac issues into IRC when they appeared or were edited. This meant that there was good visibility on changes as they happened.

Since the move to Slack we've lost that.

It would be great if we could emit at least messages when new tasks are created, though possibly also when they're assigned and at other times.

**Comment by RealOrangeOne** [comment]
We can use the GitHub integration to achieve this on the repo, and on any other repo we need.

**Comment by RealOrangeOne** [comment]
I've now installed this in our slack. I've linked `core-team-minutes` to `#core-team`. Would pointing the tasks repo to `#general` be too noisy?

**Comment by PeterJCLaw** [comment]
Not sure. Shall we try that and then review in a couple of weeks?

**Comment by RealOrangeOne** [comment]
works for me!

**Comment by PeterJCLaw** [comment]
Just for clarity what actions on tasks should we expect to be notified on?

**Comment by RealOrangeOne** [comment]
Currently enabled:

- Opened / closed issues
- New / merged PRs
- Commits to the default branch
- Deployments
- Releases

Currently disabled:

- PR Reviews
- Comments on PRs / Issues
- Created or deleted branches
- Any commit on any branch

We can enable or disable any of these on a per-repo, per-room basis. It doesn't appear possible to configure it globally, but there's only a handful of repos configured, so that's not a massive issue.

**Comment by PeterJCLaw** [comment]
> * Commits to the default branch

Interesting, since most (all?) of our repos require going via PR does this add much over the notification that the PR is merged?
(Or should we just disable this for branches with protected `master`?)

> * Deployments
> * Releases

Do we use these features anywhere? (I don't know, though I think it's reasonable for us to do so if we can so do usefully)

**Comment by PeterJCLaw** [comment]
@RealOrangeOne what's pending here? This seems to be working -- can we close this task now?

**Comment by RealOrangeOne** [comment]
It's working, but there's still a lot of noise. I'd like to go through the repos we've listened to and make the notifications less verbose (especially when merging a PR)

**Comment by RealOrangeOne** [comment]
I think for now we can consider this fine and functional. If we want to reduce verbosity, we can consider that a separate task, or just do it ad-hoc
