### ISSUE TITLE
Organise the non-arena ("outside") display screens

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#581]
Throughout the venue we typically have a number of general information screens which show the schedule of matches, state of the league, etc. We need to organise screens & drivers for these to run on. They also need power and internet connections.

This likely impacts #419

Steps:
- [x] Decide how we're driving these
- [ ] Prepare the Pi image for these Pi(s)
- [ ] Flash the Pi SD cards with that image

**Comment by PeterJCLaw** [comment]
The venue's three rooms have existing screens which we can use.

They can be configured to either:
- have an input map to a single room, or
- have an input map to multiple rooms

The plan is to put one of our usual display drivers (a Raspberry Pi) in the control cupboard for these and connect that up to the two pits rooms.

There is also a projector in one of the rooms which we could connect to a separate driver, which might be used to show the livestream.

**Comment by PeterJCLaw** [comment]
Decision: we'll put a single Pi in the tech cupboard which will drive the rooms with the pits in.
Not sure whether the screens in Mojos (around the arena) will be "Outside" or "Arena" displays, but they can either be driven off that Pi or off something else. Either way that doesn't impact this task.

**Comment by antoinepetty** [comment]
Is this task still valid? Not sure how it would fit in to a virtual competition

**Comment by PeterJCLaw** [comment]
Ah, possibly not. I think I'd left this open as we might use the screens in another capacity, but I think we can actually just rely on people looking on the website (which has all the same information).
