### ISSUE TITLE
Bus pricing logistics

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#582]
Find pricing for bus tickets and organise a way of distributing them to volunteers.

**Comment by JennyLynnFletcher** [comment]
Looks like the best option (cost/convenience) is to buy group tickets (up to four people) on the day, and try to ensure volunteers catch buses in small groups if possible. 

The group ticket is £6 for all day travel for 4 on weekends, and can be paid for by cash or contactless on the bus
