### ISSUE TITLE
Create a plan for volunteer lunch

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#583]
We should have a plan for volunteer lunch, weither that be providing one like last year or giving people information on where to go, also should take into account that not everone can disapear at once to get food.

**Comment by RealOrangeOne** [comment]
We're currently working out whether the fascilities on-site (literally in the venue) will be enough. If not, there's a co-op nearby.

I agree some sort of plan / documentation around this is definitely necessary!

**Comment by RealOrangeOne** [comment]
There is a starbucks on-site with sandwiches and drinks. Failing that there's a co-op very close to the venue. 

Based on that, I think we can consider this solved.
