### ISSUE TITLE
Acquire hardware for livestream

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#584]
Breaking out the tickets from #480  we will need some hardware for the livestream.

Minimal hardware:
- [ ] Arena camera
  - [x] Capture device for camera (if required) (@Adimote)
  - [x] Cabling to connect camera (@RealOrangeOne to HDMI, but cables won't be long enough)
  - [x] Camera itself (@RealOrangeOne)
- [ ] audio input
  - [x] Audio capture card for live stream machine (@Tyler-Ward)
  - [ ] Audio mix with commentators and no music
- [ ] Streaming PC
  - [ ] A streaming PC (should have dedicated graphics
  - [x] A monitor for said PC (SR)
  - [x] Wired network connection for PC (SR)
  - [ ] Keyboard and mouse

Good to have hardware:

- [x] Presenter camera (SR)
- [x] Microphone for presenter (@RealOrangeOne)
- [x] 2nd monitor for extra information (SR)
- [ ] Camera to capture awards ceremony

Luxuary hardware

- [ ] Second arena camera
- [ ] mixing desk for audio feeds
- [ ] Control surfaces (streamdeck or similar)

Super luxury hardware

- [ ] Portable camera setup for team pits interviews
  * this can be done with a pi with a hdmi capture interface and a camera with HDMI out and a MIC

**Comment by RealOrangeOne** [comment]
@Tyler-Ward what are the chances of being able to borrow the kit used for SR2019 again? Is this something you could look into?

**Comment by Tyler-Ward** [comment]
Not sure I will be able to borrow it again as I am no longer based in FW. give this is somthing we want to keep on doing it for both the competition and other events it would also make sense to buy some @Adimote are we likley to have any budget for this.

**Comment by RealOrangeOne** [comment]
The main thing we need is a way of getting a feed from the arena. A regular HD webcam would probably do the trick provided we can get enough cabling. 

I believe we have an audio mixer we can use to mix the audio, although getting it into a machine with decent quality may also be a challenge.

**Comment by tpoomlmly** [comment]
I've got a PC suitable for streaming, with a monitor, keyboard and mouse as well. I might also be able to borrow an audio mixer with a built-in USB ADC.

**Comment by RealOrangeOne** [comment]
@tpoomlmly Amazing! Would you be willing to bring it to the competition? Audio mixer too would be great!

**Comment by Tyler-Ward** [comment]
@Adimote has a capture card we can use for the arena feed

**Comment by RealOrangeOne** [comment]
I have a [mic](https://www.bluedesigns.com/products/yeti/) which can be used if needed.

For the presenter camera, I suggest we just use a C270 and be done with.

The floor plans currently have 2 monitors for livestream.

I have a 1080P webcam which can be used for an arena feed if needed, although it is manual focus.

I also have a _Go Pro_ (knockoff) which we've used before for the top-down feed of the arena. I'll definitely be bringing that (and adapters to HDMI female). That could be used for either the primary arena feed, competition feed, or livestream.

**Comment by tpoomlmly** [comment]
Is the livestream audio the same as that in the competition sound system (#416) or is a second mixer needed before going to the PC? 
@Tyler-Ward is your audio card USB or PCIe? (or Thunderbolt?)

**Comment by PeterJCLaw** [comment]
The livestream audio will be completely separate to (and deliberately somewhat isolated from) the main competition sound system (#416).

The in-venue sound will be used to play music that we'll have a license for (#415), though I don't expect we'll have a license to play that music on the stream. We therefore want to be able to capture different audio for the stream.

I _think_ we do want to be able to capture the in-venue commentators onto the stream though, so the two systems do want to be able to talk to each other.

**Comment by Tyler-Ward** [comment]
The mixing desk is a seperate one for the live stream it will mix a feed of the presenter mics managed by the main desk with the local mic for the livestream presenter.

The audiocard I have at the moment is USB (it is very basic but will let us get audio in). thinking about it onboard line in might actualy work better if we have it on the computer.

**Comment by tpoomlmly** [comment]
USB is good since the only PCIe slot in my computer is taken up by the GPU. There's an onboard line in too, which I haven't tested much but is definitely good enough for speech.

**Comment by WillB97** [comment]
My dante DSP is now functional and would likely be able to provide for the audio requirements of both this and #416 assuming that:
- OBS provides some way of muting the audio streams (since there is no physical desk)
- Someone could provide a dante virtual soundcard licence (mine will likely be used for mixtape)

**Comment by antoinepetty** [comment]
I think the only concern here is microphones. Jake has a decent one. Will have to double check with other commentators

**Comment by RealOrangeOne** [comment]
I have 3 mics, so I have spare. Unsure what @prophile has, but we may co-locate for some of the commentary, which makes sourcing easier.

**Comment by antoinepetty** [comment]
On the call, Alistair said he has one so it should be fine. The one he used on the call didn't seem to have any problems
