### ISSUE TITLE
Setup OBS config and rough livestream schedule

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#585]
As part of #480 we need an obs config and a plan of what will happen when e.g. start/stop times and any specific planed content this will feed into #80 for working out whwn people are needed.

This can be largley based on last years

**Comment by Tyler-Ward** [comment]
I have loaded up OBS and the previous config is still intact and wont take much effort to redeploy (just need to swap the video sources to whatever hardware we end up using (#584).

As for content plan this depends on #436 but my rougth thoughts assumeng the schedule was similar to last years is.

**Saturday:**
Tinker time: Extra content or closed if short on resources.
League: Match coverage
Lunch: Closed (Interval screen)
League: Match coverage

**Saturday:**
Tinker time: Extra content and summary of yesterdays events.
League: Match coverage (potential for interspaced extra content depending on match spacing)
Lunch: Closed (Interval screen)
League: Match coverage (potential for interspaced extra content depending on match spacing)
Knockouts: match coverage and post match discussion
Presentation: Coverage of presentation
Close: Summary of the event and Close (last year we had a volunteer recruitment video here)

**match coverage shot plan:**
In match: use arena feed with comentation from match commentators
Post match: Evaluation and discussion from livestream commentatiors
Interblock gaps (league): can be used for non match discussion or extra content
Interblock gaps: (knockouts): discussion of previous/next match blocks teams ect.

**extra content options:**
Interviews with teams (If we have a portable camera or sutiable location to do this (no teams in tech areas))
Discussions with volunteers about the competition.
Prerecorded content e.g. volunteering videos.
Chats with sponsors.

**Comment by PeterJCLaw** [comment]
This happened, we're streaming.
