### ISSUE TITLE
Follow best-practice around COVID-19

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#586]
We need to ensure we follow best practice around COVID-19.

https://www.nhs.uk/conditions/coronavirus-covid-19/ is a good article on this.

As a part of this, I think getting a source for additional hand sanitizer / tissues, and ensuring Reading are also prepared is a good idea. Schools are likely preparing themselves, however we need to make sure that continues at the venue.

The competition will go ahead unless the current PHE advise changes.

**Comment by RealOrangeOne** [comment]
This issue isn't _technically_ "Must Have", however considering it's ramifications, it basically is.

**Comment by RealOrangeOne** [comment]
@Scarzy as H&S, would be good to get your input on this.

**Comment by Scarzy** [comment]
The recommendations seem to be soap and water in preference to sanitiser. I would suggest we focus on ensuring that Reading have a sufficient stock of soap for the toilets, and perhaps ensure that there are posters around reminding people of what to do (some standard ones must exist).

A small amount of sanitiser would not be a bad idea, but my preference would be to deviate as little as possible from the professionally recommended advice - it'll be difficult to justify anything else to insurance companies etc.

**Comment by RealOrangeOne** [comment]
We're planning on writing an email to teams explaining what we're doing, what we will be doing, and best practice. Schools have also asked we try and ensure other schools are following best practice, so we're going to try and collect that too.

> deviate as little as possible from the professionally recommended advice

100%!

**Comment by Scarzy** [comment]
Today's announcements seem to be significantly relevant here.

I'm assuming the event counts as unnecessary travel, unnecessary social contact, and particularly critically the inability for emergency workers to cover events may mean that our first aid cover disappears (I'm willing to investigate this latter bit if still necessary)

**Comment by RealOrangeOne** [comment]
The competition team and trustees are meeting tonight to discuss things and what to do about the competition.

**Comment by RealOrangeOne** [comment]
Because the event has been postponed, how exactly this ticket will be implemented depends on the state of things closer to the event.

I think it's still worth leaving the ticket open, even if we end up closing it further down the line (however unlikely that may be).

**Comment by PeterJCLaw** [comment]
We're following the advice to stay well away from each other. The competition isn't happening.
