### ISSUE TITLE
Send safety email out to teams

### ISSUE THREAD

**Issue by Scarzy** [srobo/tasks#587]
It's long been my intention to send an e-mail out to teams around the middle of this month containing risk assessments and information about common violations robots have against the rules. 

What should be included:
- Risk assessments (#463)
- Common rules violations
- COVID-19 (#586)
Please suggest any missing topics

**Comment by Scarzy** [comment]
> I suspect something around pit rules (#527) can't hurt.

Agreed

Also, bringing tools with them.

**Comment by TomWheal** [comment]
Can we make sure suitable footwear is included please. The fact there were competitors walking around barefoot last year is unacceptable
