### ISSUE TITLE
Review competition reception setup

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#59]
The competition reception setup hasn't been used for a couple of years and (from what I recall) typically required a slightly finicky setup. We should check that it still works and that we understand how to configure it.

A useful outcome from this would be documenting how to set up the software, or linking to the existing docs if there are any.
A great outcome would be a one-click solution for deploying the software.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne I believe you've had a look at this, is there anything you can share here?

**Comment by RealOrangeOne** [comment]
I looked at the code, and whilst it's a little annoying to setup, it does look to run. . The frontend is a python project, which depends on things which don't ship in PyPI (annoying, but not a dealbreaker), and the server-side component is a simple PHP script, which could do with a rewrite (primarily for security reasons).

With questions being raised internally about GDPR, media consent and ticketting, I suspect we may not need to do ship tickets, which simplifies this a lot. In that case i'll write up some documentation on how we'd handle MCFs in that case.

**Comment by PeterJCLaw** [comment]
Like #61 this is on hold while we work out whether we're actually going to deploy media consent and/or tickets this year.

**Comment by RealOrangeOne** [comment]
Regarding whether we need this. Diane contacted the ICO, who didn't provide much useful info. Diane is going to reach out to other people who do events like this, and see what their policies / thoughts are.

I'm going to chase that up again early next week. If we've not had any kind of final decision by the 9th March tech day, then i'll try and spend that asserting that it works as we need it to.

**Comment by RealOrangeOne** [comment]
I got a message this morning from Diane, suggesting we go ahead shipping MCFs as we have done in previous years. If we keep some forms to hand at reception, we can ensure anyone who comes without a form can sign one on the day.

This does mean we have more work to do before the competition, but also means reception should move quicker than having to check MCFs at the gate.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne for clarity here -- what effect does that have on tickets? Are we still planning to do them?
How would we handle an under-18 who turns up but hasn't completed a form in advance?
(This ticket probably isn't the best place to discuss these things, though the outcome of those discussions will impact what we do and how much of the system we keep)

**Comment by RealOrangeOne** [comment]
My intention isn't that we run things exactly as we've done before. So yes, we use the ticket system. 

If an under-18 turns up, we get them to sign an MCF form at the door, and use that.

**Comment by PeterJCLaw** [comment]
> If an under-18 turns up, we get them to sign an MCF form at the door, and use that.

Ok, and we're definitely sure that _all_ under-18s can grant consent themselves?

**Comment by RealOrangeOne** [comment]
Unfortunately, it turns out this is __not__ the case. Therefore we're actually operating on the same basis as we've run previous competitions. 

> For young people under 18, you should also get parental consent to use an image. Make sure parents and carers are aware of your photography and filming policy statement. Ask them to sign a written consent form.

https://learning.nspcc.org.uk/research-resources/briefings/photography-sharing-images-guidance/

**Comment by RealOrangeOne** [comment]
This issue is _almost_ solved, we know how this is going to work.

Reception will have laptops (#99 ) with the software pre-installed and setup, with attached webcams, running the ticket software.

The final step is to check the software still works. It installs correctly, but I didn't check it scans a QR code and dispatches the right data.

**Comment by PeterJCLaw** [comment]
Following the completion of #61, we've just done a full stack test of this using a ticket generated from `patience` for a test user. I'm happy that this works, though we still need to create the setup docs.
