### ISSUE TITLE
How long before a match should teams submit their code?

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#592]
This impacts the choices around live-ness (#590 )

Trade-off here is around the live-feel of the matches for teams and how much they feel they can edit their code as they go

Proposed investigation: Time a full run-through of running simulation to finished video

**Comment by PeterJCLaw** [comment]
Conclusion: this will be 10am on the morning for a 3pm livestream, see https://github.com/srobo/tasks/issues/590#issuecomment-653775787. https://github.com/srobo/tasks/issues/606 for updating the website.
