### ISSUE TITLE
Define how teams will submit their code

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#593]
Teams need to get their code to us, in some form. 

This greatly depends on and impacts both #590 and #592.

**Comment by PeterJCLaw** [comment]
https://github.com/PeterJCLaw/code-submitter aims to help with this, though it has a number of [outstanding issues](https://github.com/PeterJCLaw/code-submitter/milestone/1)

**Comment by PeterJCLaw** [comment]
From a safeguarding perspective (cc @Scarzy), we should avoid this mechanism collecting any more information from the competitors than strictly necessary and limit the competitor information which is visible to volunteers. We should also keep records of all the submissions so we can review later if needed.

**Comment by PeterJCLaw** [comment]
The ultra-MVP here is that we have the teams submit their code into the IDE and tell us via the forums which project they want us to use.
Downgrading to Should Have since there _is_ a solution here.

**Comment by PeterJCLaw** [comment]
From the discussion today:
- do we actually want a hard deadline, or are we going to allow submissions slightly after it? (i.e: actually freeze at 10:05 rather than 10:00)
- how does that interact with teams using the same place for development and submission? Specifically what happens if they continue to develop after the given time assuming that their submission has already been frozen? Note: it's not easy to copy content between projects in the IDE, so this seems possible.

**Comment by RealOrangeOne** [comment]
> are we going to allow submissions slightly after it
I think being strict on this is just going to annoy people. I think reviewing submissions after (maybe even as late as 10:15) is likely just fine.

I'd suggest we dump their code at submission time to a sharable location (drive), and run simulations through that

**Comment by PeterJCLaw** [comment]
> > are we going to allow submissions slightly after it
> I think being strict on this is just going to annoy people. I think reviewing submissions after (maybe even as late as 10:15) is likely just fine.

Indeed, though this then has the interaction with teams who may be developing in the same place as the submission (if we use the IDE or another git repo form) -- a race condition between the actual deadline and them making changes after the published one.

I agree that being very strict on the timing likely isn't a good thing.

> I'd suggest we dump their code at submission time to a sharable location (drive), and run simulations through that

Yes, I definitely expect that we'd pull the relevant archives in a way which respected the fact that we'd logically frozen them.

**Comment by PeterJCLaw** [comment]
More stuff from the discussion:
- we should (obviously) authenticate uploads
- could we have them give us a commit id from the IDE?
- do we want a file or an archive; probably an archive so they can submit multiple files
- how bad if they see each others' code? (could they upload to the forums as an attachment? technically it's possible to not let them download from the forums, but does that break other things)
- we should define what happens for teams who haven't made a submission, both initially and between sessions. This also potentially has impacts on the cut-off time discussion
- are there existing tools we can use for this? e.g: coursework? (but are they all terrible?)

**Comment by PeterJCLaw** [comment]
https://studentrobotics.org/code-submitter/, a deploy of https://github.com/PeterJCLaw/code-submitter is now live. https://github.com/srobo/team-emails/pull/60 will announce that to teams.
