### ISSUE TITLE
Define how match commentary will work

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#595]
How will match commentary work? (relates to #590)

The feed between the commentators and the simulation playback needs to be as low-latency as possible. 

In the case of plain audio communication, low-latency platforms such as Mumble are an ideal choice, however it depends on how the simulation will be played.

**Comment by PeterJCLaw** [comment]
Commentary has been happening.
The commentators and livestream producer are in a shared Google Meet (though one which is isolated from general organisation), which is used for sharing the matches with the commentators and their commentary with the producer.
