### ISSUE TITLE
Downtime between matches

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#596]
Between matches, we need something to show on the livestream, and to talk over.

- Even just a logo which the commentators can talk over?
- Or maybe the score ranking?

**Comment by antoinepetty** [comment]
You could have them look at clips of past years and discuss them too if time needs filling? Always interesting to see different solutions to our games

**Comment by antoinepetty** [comment]
I have a spreadsheet of all team social media activity which could be used for commentary

**Comment by antoinepetty** [comment]
Given the short timescales, perhaps just a splash screen with scores and a screenshot of the previous end of match?

**Comment by antoinepetty** [comment]
Should schedule any filler after https://github.com/srobo/tasks/issues/469 is decided

**Comment by PeterJCLaw** [comment]
This is in the schedule and has been happening.
