### ISSUE TITLE
Celebrate Physical Robots

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#597]
Many teams have worked very hard on their physical robots, and it would be a shame to see that work go to waste.

However, it's possible some teams don't have access to their robot now, and it would be a shame to penalise them just for that.

**Comment by antoinepetty** [comment]
I vote we do some commentary on robots or maybe even just the drawn design during the livestream. However I don't think we should be scoring these in any way

**Comment by RealOrangeOne** [comment]
Ooh that's an interesting idea. It could also fit in with #596, and we do some kind of "Robot Showcase".

**Comment by Scarzy** [comment]
>
> I vote we do some commentary on robots or maybe even just the drawn design
> during the livestream.
>
That sounds like a good idea!

However I don't think we should be scoring these in any way
>
I agree that the main competition shouldn't be affected by this. However, I
don't think there would be any harm in having a robot design/construction
award based on what they are able to show.
The students almost certainly won't have access to the robot, but the
teacher probably will and be able to grab a picture or 2 (albeit not
guaranteed). So, as long as it's not made too serious, and some leeway is
given in the judging, I don't see any harm in awarding the equivalent of
what would normally be a box of Celebrations (other brands available).

Scarzy

**Comment by PeterJCLaw** [comment]
We have been celebrating this as part of the streams, notably off the back of the information gathered by #589.
