### ISSUE TITLE
Contact teams who have dropped out

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#598]
Now that the competition is virtual, some teams who have dropped out may be interested in entering again. 

We should contact them and see if they're interested. These teams haven't had emails since they dropped out, so may have missed everything.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne as this is marked urgent, just checking in on progress here?

**Comment by RealOrangeOne** [comment]
Damn, entirely unstarted. I'm not going to have the time to do this in any timeframe useful for us (unless these can be sent out early July :wink: ), so would appreciate it being taken over.

(I can provide the email addresses when it comes to sending)

**Comment by antoinepetty** [comment]
Pull request here: https://github.com/srobo/team-emails/pull/53

**Comment by antoinepetty** [comment]
Do I need to send these from my SR account, and if so can you send me the email addresses please?

**Comment by RealOrangeOne** [comment]
@antoinepetty I've sent them to you privately in Slack.

**Comment by PeterJCLaw** [comment]
> Do I need to send these from my SR account ...?

Not sure if the alternative you're expecting here is sending from a list or a personal account.
Just to be clear: all communication with teams should go from SR-provided addresses.

**Comment by antoinepetty** [comment]
> > Do I need to send these from my SR account ...?
> 
> Not sure if the alternative you're expecting here is sending from a list or a personal account.
> Just to be clear: all communication with teams should go from SR-provided addresses (and ideally list based rather than `you@sr`).

Oops didn't meant to imply personal account. I was wondering whether to send from my SR address or the teams@ address. I'll be sending them from mine
