### ISSUE TITLE
Confirm which teams are going to what venue

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#6]
We have (or are just about to) tell teams where to go, we need to confirm they're going there.

We should also get the team leader phone numbers when they confirm! so we can chase them up if they no-show

**Comment by RealOrangeOne** [comment]
An email has been scheduled for 9am tomorrow which confirms London placements, and probes about those who we had to move for space reasons. 

I'll get working on a version of this email for the Southampton kickstart shortly
