### ISSUE TITLE
Upgrade media consent/tickets system

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#60]
The current media consent/tickets system is comprised of a surprisingly large number of separate repos and the deployment parts are configured in some detail by puppet on the production server. This makes developing things around them somewhat complicated.

At the very least it would be good to document how the system works, though we should also look at simplifying it and possibly moving it into a single service.

**Comment by PeterJCLaw** [comment]
Here's my understanding of the system:
- there's about three repos which are combined to handle the web side of it. https://github.com/PeterJCLaw/sr-server-puppet/blob/master/modules/www/manifests/tickets.pp handles the deployment
- essentially the pre-competition flow is:
  - Get partially pre-populated MCF (as a PDF) from `/mediaconsent`; that url has basic auth on it, which checks against LDAP
  - submit MCF (on paper or by scan) to a Team Coordinator
  - Team Coordinator adds a group to your user (in LDAP), via a command in [srtools](https://srtools.readthedocs.io/en/latest/) which interacts with nemesis
  - Either see in `/userman` or be told by your teacher that your ticket is ready
  - Get ticket (also a PDF) from `/tickets`. The Ticket contains a QR code, which contains a blob of signed data. I can't remember what/where the key for that data comes from
- However the way the pieces fit together is a combination of things being "just so", server-side scripts & other goo. I think we even exec other processes inline at some point too.
- Much of it is Python, but there's some PHP thrown in for good measure.
- It all runs as CGI, which isn't bad on its own, however it's the only CGI style stuff we have left and isn't exactly easy to develop.
- There are no tests.
- At the competition it's also kinda messy:
  - turn up, with either a printout or screen on which you can show
  - reception scans your ticket's QR code; there's some software for this _somewhere_, though I'm not sure where.
  - the reception software checks that the _ticket_ is valid (i.e: at least that the signed blob is valid); I don't know whether it re-checks against the database (though arguably that shouldn't be necessary given the signing)
  - I _think_ the reception software prevents a given ticket being presented twice, but I'm not sure about this
  - I _don't_ think that reception does anything to check that the person holding the ticket is the person to whom the ticket was assigned

**Comment by RealOrangeOne** [comment]
Pending https://github.com/srobo/tasks/issues/59 as to whether we actually need this process still.

I suspect this doens't need to be done this competition cycle. We should aim to make as few modifications as possible to get the existing process up and working. After this competition, we can spend more time developing the system to fit closer to how we need it, and bring it up to date.

**Comment by PeterJCLaw** [comment]
Here's roughly what I imagine a replacement looking like:
* Probably a Python backend, with a minimal HTTP JSON API (SR is mostly Python, so sticking with that is a good idea)
* Maybe runs as a stateless service? (If so, how do we record that a user has already been checked in? Defer that to `nemesis`?)
* Defers to [`nemesis`](https://github.com/PeterJCLaw/nemesis/) for auth and user information (this means that if/when we move away from LDAP, we only need to change the backend support in `nemesis`, rather than everywhere)
* Just focusses on rendering Tickets and Media Consent Forms
* Uses a public/private key or signed-blob mechanism for Ticket authentication, so that reception can authenticate tickets without needing any private keys

The reception software could usefully get updated too, though that's actually somewhat ok. In the above plan it would need modifying to:
* Use the updated endpoint for validating ticket information
* Maybe use a _different_ endpoint for recording that people have arrived

Questions to ponder:
* Should we record which client marked a user as arrived, and extend this to ensure we can't accidentally process the same ticket twice concurrently? (Not sure how big a deal this is)
* Does it make sense to do the validation on the client, or should we POST the whole ticket to the server and validate there? If so, how would we do manual processing of tickets? (We currently have the option for manual processing, but I've no idea how much it's used)
* Does the reception software need to be a Python/GTK app? Currently it is because that's convenient, but would it make sense to instead have a web UI? (Camera stuff in JS has improved a lot since the reception software was written; this is definitely a separate follow-on piece of work though)
* Are there existing ticketing systems we can use/integrate with (ideally FOSS ones) rather than building that ourselves?

**Comment by PeterJCLaw** [comment]
I'm considering this blocked on https://github.com/srobo/tasks/issues/286.

**Comment by PeterJCLaw** [comment]
With Python 2 reaching end-of-life in January and us still needing this system for at least this year, I think this is now high enough priority that it's worth doing even if we did want to do something different in the future.

I'll likely pick this up once the conversion to Python 3 is done for the user management related things (see #287 for an overview of that conversion work).

**Comment by PeterJCLaw** [comment]
Update on this, from some previous thinking and research this evening:

- we have a bunch of barcode scanners, it would be good to support using them
- https://github.com/nimiq/qr-scanner exists and can do in-browser QR code recognition from a webcam
- mobile phones with cameras are now ubiquitous, so supporting them would be good too
- therefore a web based solution for the reception side is a good fit

> * Probably a Python backend, with a minimal HTTP JSON API (SR is mostly Python, so sticking with that is a good idea)

Still yes, though maybe consider going `async` (maybe [`starlette`](https://www.starlette.io/)?). Might want to use form POST rather than JSON as the former is easier for integrating with a barcode scanner (they pretend to be a keyboard and emit keypresses for text ending with an "enter" press, which can be used to trigger a form submission).

> * Maybe runs as a stateless service? (If so, how do we record that a user has already been checked in? Defer that to `nemesis`?)

Still unknown. `sqlite` databases are pretty easy though if we don't need to be stateless.

> * Defers to [`nemesis`](https://github.com/PeterJCLaw/nemesis/) for auth and user information (this means that if/when we move away from LDAP, we only need to change the backend support in `nemesis`, rather than everywhere)
> 
> * Just focusses on rendering Tickets and Media Consent Forms

Still yes. Would want to be a separate service from `nemesis` for these reasons too.
Use a "backends" pattern to allow for development separate from `nemesis`, simplifying the setup.

> * Uses a public/private key or signed-blob mechanism for Ticket authentication, so that reception can authenticate tickets without needing any private keys

Maybe. If we're moving to a web based system anyway, then the private keys can stay entirely on the server so this becomes less important.

> The reception software could usefully get updated too, though that's actually somewhat ok. In the above plan it would need modifying to:
> 
> * Use the updated endpoint for validating ticket information

Assuming we're moving to a web page, then it would need a new system anyway, since we don't want to put the private key on the page. This is therefore definitely needed.

> * Maybe use a _different_ endpoint for recording that people have arrived

Not sure what benefit this part serves. Keeping the API simple is probably more valuable.


> * Does it make sense to do the validation on the client, or should we POST the whole ticket to the server and validate there? If so, how would we do manual processing of tickets? (We currently have the option for manual processing, but I've no idea how much it's used)

Turns out that we don't really currently have a manual solution here. While you can validate the HMAC locally with just the private key, the software isn't configured to let that do much.

Since we rely already on an internet connection and we're likely to move to a web-page solution we should move as much validation to the server. This particularly plays well with keeping all the keys entirely on the server.

> * Does the reception software need to be a Python/GTK app? Currently it is because that's convenient, but would it make sense to instead have a web UI? (Camera stuff in JS has improved a lot since the reception software was written; this is definitely a separate follow-on piece of work though)

No, see above. A web-page is definitely possible.

Q: Could we do just the backend update and keep the current frontend?

Maybe. We could definitely shim the exiting HTTP portion of the reception software and/or just replace that part with something else.

This would however mean that we'd still need to have the private key on the reception machines and that we'd need to actually set up the software on them. Likely it would be as much effort to build the web-page version as it would be to go through this setup work.

> * Are there existing ticketing systems we can use/integrate with (ideally FOSS ones) rather than building that ourselves?

Searching doesn't yield anything useful. There are plenty of hosted systems for _selling_ tickets, though none of them talk about what happens on the door of the event.

It would definitely be nice not to have this be specific to us, but I don't currently think there's anything out there which fits our requirements.

**Comment by PeterJCLaw** [comment]
> > * Maybe use a _different_ endpoint for recording that people have arrived
> 
> Not sure what benefit this part serves. Keeping the API simple is probably more valuable.

One reason we might want this -- so we can scan a ticket and then bail out, without recording that we let the person in. This might happen if the person presented the wrong ticket and when we validate that the person is right for the ticket that check fails.

We do that check _after_ scanning, since we don't trust the non-signed data on the ticket so can't just read the plaintext.

**Comment by PeterJCLaw** [comment]
Proposed system:

## Ticket generation

This remains on the server as a Python HTTP app:
 - uses [`nemesis`](https://github.com/PeterJCLaw/nemesis/) for auth and user information
 - uses swappable "backends" to enable development without needing a nemesis instance to talk to

The flow here (all on server) is:
 1. user logs in, likely plain basic auth to start with. We can extend this to be a nicer UI later.
 2. we check their credentials and that they have granted media consent
 3. we generate a ticket against their username (use the existing logic), including a QR code around their signed username
 4. we log that we've done so
 5. we serve up the ticket and show the user a success page

The current system also caches the ticket (the current system does), though there's not a lot of benefit really. The main benefit we currently get is that it forms a record that the user has generated the ticket. We can achieve this by explicitly logging it (see the semi-structured logging in nemesis for an example) which is much simpler.

## Ticket scanning:

Scanning will be a web-page, accessible only to internal users (we have existing permissions sets for this).

0. SR volunteer logs in, selects scanning mode:
    - in-browser webcam via https://github.com/nimiq/qr-scanner
    - barcode scanner
    - manual mode (maybe? maybe behind a different/additional permission?); see later notes
1. Client prompts user to scan a ticket
    - for webcam mode, this should include a preview from the camera and should just pick up any scanned QR codes
    - for a barcode scanner, the page should feature a single large HTML `input` element with autofocus (no need for a submit button or any JS in this mode -- scanning the barcode will submit the form)
2. Minimal validation that the scan is in the expected format (i.e: `username:base-64-encoded-hmac`, as currently)
3. `POST` the whole thing to server
4. Server validates it (again using nemesis) and replies with one of:
    - success: the user's name and organisation/team
    - error: unknown username
    - error: no media consent
    - error: already seen this ticket
5. On error: this should show the prompt UI again (back to 1.), with the error clearly displayed
6. On success: display the user's name and team, plus a prompt to check with the team leader (i.e: a _different_ person) that they are correct
    - if the user confirms they are correct, the POST (again the whole blob) to a second endpoint confirming the ticket
    - otherwise, back to 1., with a clear message that the ticket hasn't been recorded
7. Server validates the input again, then replies with one of:
    - success:
         - server records that a ticket has been seen
         - client should go back to 1., with a clear message that the ticket _has_ been recorded
    - error: unknown username
    - error: no media consent
    - error: already seen this ticket

We may also need a mechanism to cope with competitors who turn up without tickets and/or without media consent. This could handled by a manual page capturing:
 - username (optional)
 - full name
 - team TLA
 - full name of the adult vouching for them
 - a checkbox that the volunteer has a media consent form from for the person
 - a molly-guarded submit button

There are essentially the following pages in this system:
- login
- mode selection (webcam, barcode scanner, manual)
- barcode scanner mode scan page
- webcam mode scan page
- user details confirm page
- manual mode page (maybe)

The mode selection would be remembered, likely via a session variable, so that the user is always redirected back to the proper scan page.
Aside from login errors, the scan page is the one which shows any errors since the only thing the user can do to fix errors is to try another scan.

**Comment by RealOrangeOne** [comment]
Recently found out about https://pretix.eu/, which might be a viable option for our ticketting system (there's a self-hosted option). It'd be probably tie in to whatever we need via its REST API. GIven our constraints on _who_ can purchase tickets, we might need to manually create tickets with the rest API, or find some way to do invite-only tickets (might be already supported).

Might be something to look into to save us building something ourselves.

**Comment by PeterJCLaw** [comment]
For SR2022 we moved away from tickets (see https://github.com/srobo/tasks/issues/750#issuecomment-1034198031) and aren't likely to go back to the previous system. We have some ideas which may reintroduce the idea of tickets (as markers of media consent) to enable multi-event consent, however I think we can either re-open this task if/when we decide to pick that up and/or start a fresh discussion.
