### ISSUE TITLE
Update media consent template for live-stream interviews

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#600]
It looks like we're going to pre-record some interviews with the teams for inclusion into the live stream.
We should check that this is covered by our media-consent template and update it if needed.

Originally raised in https://github.com/srobo/team-emails/pull/57#discussion_r446092187

**Comment by RealOrangeOne** [comment]
The consent form is at https://github.com/srobo/media-consent, and is year agnostic, so we don't need to do anything about that :tada: 

As for if things are covered. In theory we're fine:

> I give my consent for Student Robotics to use the images and sounds, to store, reproduce, publish and broadcast them in the manner and context and in conjunction with such sounds, images and captions as Student Robotics deems fit.

**Comment by PeterJCLaw** [comment]
cc @Scarzy in case you know much about this/any overlap with the safeguarding side.

**Comment by Scarzy** [comment]
I've had a look through it, from a safeguarding perspective it's fine. Though obviously it will need to be in place before the interview takes place (by which I mean we have a physical or digital copy in SR's systems before the call even starts, not merely they wave a signed copy at us within the first minute of the interview)

**Comment by PeterJCLaw** [comment]
"Could have" because this is only needed for #603. If we are doing that then this becomes "Must have".

**Comment by PeterJCLaw** [comment]
@RealOrangeOne since you originally raised this but have since reviewed the form -- do you think there's anything we need to actually do here? Otherwise I think we should close this task.

**Comment by RealOrangeOne** [comment]
For updating, no I think we're good here. As @Scarzy says what we have should cover our needs.

As for ensuring we deploy said form, that's a separate question, and comes more under #603.
