### ISSUE TITLE
Brief volunteers before the Virtual Competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#602]
Topics:
- safeguarding
- how the competition will run operationally
- communications (what platforms for what, which Slack channels are being used, etc.)
- Who's doing what

**Comment by RealOrangeOne** [comment]
The intention is to run a quick 1-hour meeting the Friday before a weekend to quickly go through things, brief those involved, ensure people know what they're doing, and reduce any logistical issues.

**Comment by PeterJCLaw** [comment]
This happened for today. We're probably going to want to brief again next week.

**Comment by PeterJCLaw** [comment]
This happened again. Twice.
