### ISSUE TITLE
Interview teams for inclusion in the live stream

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#603]
We need to plan how we're going to do this, both from a practical perspective and also wrt safeguarding.

This contributes towards #589 and #596.

### Dependencies

* #600 Update media consent template for live-stream interviews
* #463 Create and publish risk assessments for the virtual competition (wrt safeguarding)

**Comment by PeterJCLaw** [comment]
cc @Scarzy wrt safeguarding. Form our chat:
- we need to keep the full original recording
- we need a third person (ideally a teacher or the competitor's parents) on the call

**Comment by PeterJCLaw** [comment]
See also https://github.com/srobo/team-emails/pull/57 for the email where we asked teams about this.

**Comment by Scarzy** [comment]
So, having done some more digging around this, I think we need to have 2 SR volunteers as well as either the parent/teacher/carer. Crucially to have someone in the call who is legally responsible for the competitors welfare, and is DBS'd (if appropriate). Preferably the teacher as they are the ones we normally deal with, and as an additional benefit have a lot of recent experience with working with their students remotely.

I've got a good number more thoughts/details for this, but it's not sensible for them to be in a comment, so they'll appear more in some form of document.

**Comment by PeterJCLaw** [comment]
We've not had any teams express interest in this, so this is highly unlikely to happen now.
