### ISSUE TITLE
Give "chat helpers" access to SR alias

### ISSUE THREAD

**Issue by antoinepetty** [srobo/tasks#607]
For the volunteers in the livestream chat, they shouldn't need to use their personal accounts to help people

**Comment by antoinepetty** [comment]
Have messaged Jimmy to find out what the best option for this would be

**Comment by PeterJCLaw** [comment]
I think we have a solution for this? Maybe let's document how that works and then close this?

**Comment by antoinepetty** [comment]
The decided solution for this year has been for the chat helpers to create a YouTube channel with just their first name, then setting their profile picture to the SR logo. These channels are then marked as moderators from the SR YouTube account
![image](https://user-images.githubusercontent.com/36314396/87880347-f77d4880-c9e8-11ea-9a5d-584c374cb275.png)
