### ISSUE TITLE
Gather feedback from teams

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#611]
Send to everyone who was signed up for SR2020.
As well as the usual things, it would be good to understand the challenges for the teams who were unable to take part in the virtual competition.

Usual things:
- demographics
- prior experience
- did they get the support they needed
- are Tech Days useful to them? Do they feel that they have the resources in school now? If not, why aren't they coming/what can we do to make them more useful? Is more real-competition testing the key factor here?

(please add to this list)

**Comment by RealOrangeOne** [comment]
Feedback form: https://docs.google.com/forms/d/1HE8b1oRF6dHc3wbBUICJV5CsXHv3qR7egcMtud6pfd4/edit?usp=sharing

**Comment by antoinepetty** [comment]
Some comments on the form:

- Could add a question about how often they tuned in to the livestream (To compliment the engagement one).
- I find the "What percentage of your team were female?" question wording to be quite jarring. Is that what the trustees wrote? Is it possible to have some sort of slider which goes from 100% female to 100% male or something?

**Comment by sedders123** [comment]
>What percentage of your team were female?

I feel this also ignores non-binary individuals, as it implies we can take the percentage away from 100 and that's percentage for males. Would it be better to gather percentages for all three explicitly?

**Comment by RealOrangeOne** [comment]
Have added a "What are the gender proportions of your team?" question (suggestions welcome for a better name!)

**Comment by antoinepetty** [comment]
I had considered this covered by https://github.com/srobo/team-emails/pull/62 although so far there haven't been too many responses. I think a separate email can be decided in the next competition team meeting
