### ISSUE TITLE
Create post competition reports

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#612]
We should give a report on the SR2020 competition cycle and details of the event to the trustees once everything from the event has been sorted out. This will also include a spending report for the year.

### Dependencies

* #611: Gather feedback from teams
* #613: Gather feedback from volunteers

**Comment by RealOrangeOne** [comment]
Blocked on having the data

**Comment by RealOrangeOne** [comment]
An email has been sent out with the relevant links / information.
