### ISSUE TITLE
Gather feedback from volunteers

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#613]
As part of feeding in to #258 and for our own learning, we should gather feedback from volunteers, both on how the competition event went and the preceding competition year.

If there's a topic you think we should gather feedback on, please do add it here.

* ...

**Comment by RealOrangeOne** [comment]
Send this to the volunteers who signed up for the virtual competition

**Comment by RealOrangeOne** [comment]
Feedback form: https://docs.google.com/forms/d/1nIG36tZNykCxgilKXOT6TJiY2je3iHR2YNMtoXeLeJw/edit?usp=sharing

**Comment by antoinepetty** [comment]
Some comments on the form:

- Could add a question about how often they tuned in to the livestream (To compliment the engagement one).
- I find the "What percentage of your team were female?" question wording to be quite jarring. Is that what the trustees wrote? Is it possible to have some sort of slider which goes from 100% female to 100% male or something?
