### ISSUE TITLE
Wrap-up email to teams

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#614]
This would cover things like:
* thanking them for taking part
* trophy delivery address (and check they're happy for the address to be given to the trophy company)
* gathering feedback about the competition (see #611)
* ideally, confirmation or repetition of the dates for SR2021, though that will depend on how it interacts with the next Competition Team's structure
* maybe get input on likelihood of them being able to come to Kickstart and/or a physical competition next year (are they likely to run a school trip in October)

**Comment by antoinepetty** [comment]
https://github.com/srobo/team-emails/pull/62

**Comment by antoinepetty** [comment]
Also https://github.com/srobo/team-emails/pull/63
