### ISSUE TITLE
Prepare forums for SR2021

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#622]
In order to allow the competitors to chat to each other and request help from mentors, we setup forums each year. These are typically an instance of [phpBB](https://www.phpbb.com/) hosted on a VM of ours.
The forums allow login using the competitors' user accounts and when they post in the forums, updates are cross-posted into Slack.
We usually have forums as follows:
 - *General Discussion* (General chitchat.)
 - *Programming* (Python, libraries and concepts.)
 - *Electronics* (Electrons, holes and joules.)
 - *Mechanics* (Pulleys, sprockets, hinges and gudgeon pins.)
 - *Teams on the web* (A place to show off your team blogs, videos, and bat-based memes.)
 - *<name of the game>* (Discussion about the game.)

**TODO**:
* [ ] hook up the forums to our Slack
* [ ] rename the game forum

### Original

[kickstart/services/forums](https://github.com/srobo/recurring-tasks/blob/master/kickstart/services/forums.yaml)

### Dependencies

 * #620 Decide on the SR2021 game

**Comment by PeterJCLaw** [comment]
@RealOrangeOne I think you've done this?

**Comment by RealOrangeOne** [comment]
I did, but we're now going in a different direction, so won't need this.

**Comment by PeterJCLaw** [comment]
Reopening as we have a lot of places which link to the forums. We should either update those links and/or redirect the url to the Discord. Either way, I think having this open until those links are suitably updated is useful.

**Comment by RealOrangeOne** [comment]
There is no canonical page for discord, but i'll create a docs page on it with some information, and have `/forum/*` redirect there
