### ISSUE TITLE
Determine Area Locations

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#64]
SUSU is large. We have the following bits of SUSU:

- Concourse
- Bar Two
- Bar Three
- Cafe Area
- Cube
- Clubs & Societies Room

We need to work out where the following bits of the competition go within SUSU:

- [x] Reception
- [x] Team Pits
- [x] Arena
- [x] Volunteer Area
- [x] Helpdesk
- [x] Tech Desk
- [x] Battery Charging
- [x] TV Studio
- [x] Photo Studio
- [x] Powertool Zone (#124)

**Comment by RealOrangeOne** [comment]
It might be nice to leave the seating of Bar 2 devoid of teams, so it can be used as a quieter area, and means we don't risk damaging the likely expensive seating and tables with teams.

Thoughts?

**Comment by trickeydan** [comment]
> It might be nice to leave the seating of Bar 2 devoid of teams, so it can be used as a quieter area, and means we don't risk damaging the likely expensive seating and tables with teams.
> 
> Thoughts?

I guess we could if we have the space to leave them free? However, I'm unsure whether we'll have the space.

**Comment by Tyler-Ward** [comment]
@WillB97 have you done anything towards this i believe you where looking at floorplans but not sure how far you got.

**Comment by WillB97** [comment]
My initial thoughts would be:

* Concourse
  + Reception
  + Photo Studio?
* Bar Two
  + Team Pits
  + Powertool Zone (South end/patio?)
* Bar Three
  + TV Studio (South end)
  + Tech Desk
  + Battery Charging
  + Helpdesk (or Concourse?)
* Cafe Area
  + ~25x Team Pits
* Cube
  + Arena
* Clubs & Societies Room
  + Volunteer Area

Although what enquiries would go to help desk vs tech desk, and would it be worth moving help desk to concourse?
And are there any specific requirements for the photo studio or do they just need an area of free space?

Also how is battery distribution handled, i.e. do teams need to collect batteries from battery charging prior to their matches? 
If so it may be worth moving to Bar 2 so downstairs teams don't have to go in the opposite direction to the cube.

**Comment by Tyler-Ward** [comment]
Tech desk is the SR name for the FOH desk in the cube so competitors wont be coming there.
For the photo studio , just an area of free space, the entrance to the bridge was suggested in the past for this.
battery's are usually charged somewhere out of the way and then taken to the helpdesk where teams will collect them. so might be worth having the tech desk to L2 so it is closer to the cube for last minute battery changes.

**Comment by WillB97** [comment]
Revised layout:
* Concourse
  + Reception
  + Photo Studio
* Bar Two
  + Team Pits
  + Helpdesk
  + Powertool Zone (South end/patio?)
* Bar Three
  + TV Studio (South end)
* Cafe Area
  + ~25x Team Pits
* Cube
  + Arena
* Cube balcony
  + Tech desk
  + Battery charging
* Clubs & Societies Room
  + Volunteer Area

Bar 3 seems under-utilised.

**Comment by WillB97** [comment]
See WillB97/comp-floorplans@3f8216759bd7a4abf104d4a2c9d4894f15307483 for current general layout.

Exact numbers and layout of pits is going to require more accurate measurements of the cafe.
Also is there a strict requirement for the pits to be a 3x3m square or can the area be slightly narrower e.g. 2.5m

**Comment by RealOrangeOne** [comment]
Suggested changes:
- Move battery charging to _stage_
- Block off part of left hand side of arena for staging area
- Add volunteer area
- Add team pits to L4
- Move reception location to other side of doors

**Comment by PeterJCLaw** [comment]
@RealOrangeOne what's the reasoning for putting the battery charging on the stage (I'm assuming this means the stage in the Cube)? Surely we want people to be able to use the stage for viewing the arena and separately want to keep the battery charging away from the general public?

**Comment by trickeydan** [comment]
> @RealOrangeOne what's the reasoning for putting the battery charging on the stage (I'm assuming this means the stage in the Cube)? Surely we want people to be able to use the stage for viewing the arena and separately want to keep the battery charging away from the general public?

We were concerned about the morale of the volunteer doing the battery charging, so wanted to place them somewhere where they could see what was going on.

**Comment by RealOrangeOne** [comment]
As @trickeydan says, morale is a big concern. The battery charging will be obscured behind staging, so won't be accessible to the general public. We generally don't let competitors on the stage, but if we do, we can just block off a part of it, as we're going to do with the area in front of the stage.

**Comment by TomWheal** [comment]
They'll be able to see what's going on better from the balcony than from the stage tho? Probably more entertaining too as they can talk to whoever is running the tech desk. (If I were looking after the charging, which is possible I will be at some point, I'd much prefer to be up on the balcony than the stage.)

**Comment by sedders123** [comment]
If I remember correctly the number of power points was also a consideration, we didn't think there were enough up on the balcony to provide power to all the chargers.

**Comment by trickeydan** [comment]
I think there were also points raised about lack of space as there is
seating up there

**Comment by WillB97** [comment]
I believe this is sorted and ready for closing

**Comment by PeterJCLaw** [comment]
> > @RealOrangeOne what's the reasoning for putting the battery charging on the stage (I'm assuming this means the stage in the Cube)? Surely we want people to be able to use the stage for viewing the arena and separately want to keep the battery charging away from the general public?
> 
> We were concerned about the morale of the volunteer doing the battery charging, so wanted to place them somewhere where they could see what was going on.

While I appreciate the premise here, I strongly disagree with the conclusion. The location of battery charging _must_ adequately take into account the safety concerns. I'd very much rather have considerable distance between battery charging and members of the public than a the couple of feet and a sign (which _will_ be ignored). We ran battery charging (a few meters) behind the HelpDesk at Newbury without any issues regarding morale.
Bear in mind also that volunteers will (I assume) only be on each role for short periods at a time, so there's plenty of time to view matches when not doing things.

I would also be concerned about the noise which the chargers make being rather annoying to people watching matches and about the volunteers managing the charging becoming distracted.

Separately, I would very much rather leave the stage free as a space for viewing of matches (you can after all only get so many people around an arena able to see; the stage greatly increases that). As the staging area is eating a good portion of that, this is especially important.
