### ISSUE TITLE
Setup code submission for SR2021

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#641]
In order to allow the competitors to submit their code we need to set up a way for them to authenticate to the code submission service. Currently that service expects to use the user-accounts and LDAP, however as we're not doing user-accounts this year we need another approach.

One thing we could do is to create some specific LDAP users, perhaps per-team, and hand out those credentials. That would avoid needing to write code for this. It would keep us tied to LDAP though, so we'd need to work out what would happen if those users tried logging in to the IDE or to the user management interface.

### Dependencies

 * #616 Allocate TLAs for SR2021

**Comment by trickeydan** [comment]
Username: TLA
Password: sha256(TLA + common_secret)[:16]

Positives:

- Stateless, no need for any LDAP or user account management
- Relatively easy to implement
- No risk of ide / user management logins

Negatives:

- Passwords are difficult to change individually.
- Admin passwords would need thinking about.

**Comment by PeterJCLaw** [comment]
https://github.com/PeterJCLaw/code-submitter/pull/15 implements support for configuring the credentials via a YAML file.
The remaining work here is to actually configure the submitter to use a YAML file.
