### ISSUE TITLE
Team Mentoring

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#645]
We should offer mentoring to teams, especially those who performed less well in the first league session.

Talking on discord isn't necessarily mentoring.

- Advertise to volunteers about mentoring
- Check in with teams about mentoring (#644 )

**Comment by PeterJCLaw** [comment]
See also https://github.com/srobo/tasks/issues/646 and https://github.com/srobo/tasks/issues/647

**Comment by PeterJCLaw** [comment]
This is now happening. We have emailed the team-leaders a number of times and contacted all the teams via Discord. We've had a couple of teams reply via Discord to say that they're doing ok as they are (which is great :)) and one team who have asked for a mentor. That team has been allocated a mentor.

As this is now under way I'm going to close this ticket.
