### ISSUE TITLE
Change contrast of title on rules screen

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#648]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-06-league-2-retro.md#specific

**Comment by RealOrangeOne** [comment]
I've now done this.

(Note that this image has not yet been updated for module 3)

https://drive.google.com/file/d/19lwuYC7NlrYXSalkviNa4JB510y4wFrI/view?usp=sharing
