### ISSUE TITLE
Determine Layout of Areas

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#65]
Once we've worked out where we're putting each area (#64), we need to work out exactly what we're putting in the areas, and write down this layout in some sane fashion.

The following areas need layouts:
- [ ] Reception
- [ ] Team Pits
- [ ] Arena
- [ ] Volunteer Area
- [ ] Helpdesk
- [ ] Tech Desk
- [ ] Battery Charging
- [ ] TV Studio
- [ ] Photo Studio
- [ ] Powertool Zone (#124)

**Comment by WillB97** [comment]
What detail is needed for this, srobo/comp-floorplans#3 now has tables and required numbers of power sockets needed for each location

**Comment by RealOrangeOne** [comment]
It looks like that now contains the required information, which is great! The only thing missing is any power / table requirements for the 'photo studio', of which there likely are some.

**Comment by WillB97** [comment]
do we have any information about the photo studio or should we assume it needs 1 table and 2 power sockets?

**Comment by RealOrangeOne** [comment]
We dont, but I think that's a pretty fair assumption.

It might be nice to have an additional table for use in the photos. IIRC SUSU have some white bar tables which can light up, can we use those / get the power adapters for them? Those could look quite cool in the pictures to put the robot on!

**Comment by Tyler-Ward** [comment]
looking through the plans here are some comments broken down by Area.

#### L4
* Reception will need at least two tables possibly three.
* The photo studio will need a small tall table for a robot, two power sockets for the studio flashes, a backdrop, and a small table with laptop for the photographer to make notes ect.
* there will need to be a score display for the teams on this floor.

#### L3
* significantly more power sockets are required at the tech desks and CIC I expect at least 20.
* there will need to be a score screen in the cafe and possibly another on bar3.

#### L2/Cube
* needs display screen for team pits
* helpdesk will need more power sockets
* score entry is missing from the staging area.
* will need about 32 sockets at battery charging (one per charger).
* will need some sockets + tables in the volunteer area

**Comment by RealOrangeOne** [comment]
> Reception will need at least two tables possibly three.

I suggest we get a couple more than that, and split the reception into 2 channels during check-in, and then fall back to a couple of tables during the event. 

> there will need to be a score screen in the cafe and possibly another on bar3

IIRC, there's screens on the walls, are we able to hook into those at all?

Comments on power sockets can probably be resolved by using some 4-ways, especially on help desk as the power draw will be quite low. We'll need to make sure the power available to the battery charging is fairly high, so we don't risk drawing too much through only a few sockets.

**Comment by WillB97** [comment]
The white led tables are battery powered so just need to be charged each night.

What is CIC and is it separate from tech desk. If not 20 sockets seems very high for a single location.

Overall with the amount of power  being requested for the cube I'm not sure if SUSU has enough distro so more may need to be hired in.

**Comment by Tyler-Ward** [comment]
CIC is the event management desk that is next to the tech desk. on the cube balcony.

We also have quite a few 4 ways in the cupboard we can use to provide extra sockets

**Comment by WillB97** [comment]
I believe srobo/comp-floorplans#3 is contains all the necessary information and is ready for review.
We'll hold off on merging until the cafe sockets can be added.

We should also consider the amount of upstream power needed to run 32 battery chargers.

**Comment by Tyler-Ward** [comment]
I have commented on srobo/comp-floorplans#3 with some extra info. once those final changes listed in the pull request and cafe power are done we can merge in these and mark this as done, we can open more pull requests for extra detail if it is required.

**Comment by Scarzy** [comment]
Level 2:
The gap between the 2 pits top right appears to be rather narrow. This is the route through to the lift, as such is likely to see a fair amount of traffic, especially as I'd rather robots went via the lift rather than the stairs, as we've done in previous years, for safety reasons.

Level 3:
The pit nearest the lift is rather blocking the corridor next to it.  From what I can see, I see no reason why that entire column of pits can't butt up against the column to the left of them, it would open up a few walkways.

**Comment by Tyler-Ward** [comment]
Unfortunately the passenger lift in SUSU is very small, it will just about fit two people and robots, and is very slow as i remember so moving the robots needed using it will be tight with the current schedule. We could probably do it but would need volunteers on each floor to manage lift traffic.

**Comment by Scarzy** [comment]
> Unfortunately the passenger lift in SUSU is very small...and is very slow

Hmm... That's inconvenient. Still, that passageway should be opened up. Any disabled competitors or visitors will need to use it, and that shouldn't be impeded by other teams pits. Especially as for anyone just coming out of the lift that is their fire escape route.

**Comment by RealOrangeOne** [comment]
We're planning to relocate teams with disabled competitors to L2, which removes the pressure on the lift (#211). I suspect teams will not use the lift for robots, considering the stairs will be much faster, even if they walk slow enough to be considered more than safe.

**Comment by WillB97** [comment]
> Level 2:
> The gap between the 2 pits top right appears to be rather narrow. This is the route through to the lift, as such is likely to see a fair amount of traffic

The 4 teams along the bar in level 2 were placed rather arbitrarily and there is space to move them along towards the cube entrance.
 
> Level 3:
> The pit nearest the lift is rather blocking the corridor next to it. From what I can see, I see no reason why that entire column of pits can't butt up against the column to the left of them, it would open up a few walkways.

That is already a narrow corridor and the main walking route is through the large doors past the lift. We could but those columns together, my thinking was having several walkways reduced the concentration of traffic.
