### ISSUE TITLE
Try and make webcam feeds be horizontal (and hide names)

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#650]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-06-league-2-retro.md#specific

**Comment by PeterJCLaw** [comment]
This seemed to happen. @RealOrangeOne perhaps to close this off we could have a runbook change which documents how this was done?

**Comment by RealOrangeOne** [comment]
It was as simple as just resizing the window to be landscape rather than portrait
