### ISSUE TITLE
Have larger match spacing

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#651]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-06-league-2-retro.md#specific

**Comment by PeterJCLaw** [comment]
@prophile @RealOrangeOne what spacing did we want to go for?

**Comment by RealOrangeOne** [comment]
I'd say probably the same as we had for SR2020, giving us 90 seconds match spacing https://github.com/srobo/sr2020-comp/blob/master/schedule.yaml#L2
