### ISSUE TITLE
Allocate a Q&A moderator, post questions (with answers) in Slack for the commentators to talk about

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#652]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-06-league-2-retro.md#specific

We should allocate a Q&A moderator, to post questions (with answers) in Slack for the commentators to talk about. The goal is to ensure that we can reason about our responses ahead of announcing any desiccations.

**Comment by PeterJCLaw** [comment]
We didn't have a moderator as such, however we did have a buffer between the chat and the commentators.
@sedders123 thoughts on whether this fits into the checklist or other runbook docs somewhere?

**Comment by sedders123** [comment]
Think we already have some points under the 'Module Announcement' already kind of cover this?

> - Chat Mods collect questions from the livestream and Discord then paste into a Slack channel
> - Available volunteers comment on questions (in threads) with any answers or thoughts
> - Presenters read the questions, any answers in the thread, and add their own comments

**Comment by PeterJCLaw** [comment]
So we do. Turns out I can't read.
Hrm, wonder if we should have something earlier on which alludes to the need to prep for this? Maybe not worth it.
