### ISSUE TITLE
Prepare music more in advance, and have more of it

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#657]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-06-league-2-retro.md#specific

**Comment by RealOrangeOne** [comment]
Relevant slack thread https://studentrobotics.slack.com/archives/C0EEJ0ASY/p1612620733009500

**Comment by sedders123** [comment]
We have more music now 🎉 https://drive.google.com/drive/u/2/folders/19caXDe7KOXoBclJ7z8K-ZJmmI9fkYkxf
