### ISSUE TITLE
Competition Risk Assessments

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#66]
We need risk assessments for the competition, with venue taken into account.

Will probably require #64 at minimum and probably #65 also.

Note, #1 referred to Kickstart (I think, it was poorly named), this is regarding the actual competition.

**Comment by kierdavis** [comment]
I've done risk assessments for Smallpeice events before, but not for SR. What are the key differences that I need to be aware of?

> with venue taken into account
Please could someone clarify what is required here? Do we want separate risk assessments for each room/area within the venue?

**Comment by PeterJCLaw** [comment]
> > with venue taken into account
> 
> Please could someone clarify what is required here? Do we want separate risk assessments for each room/area within the venue?

I think this is more about accounting for aspects of the venue itself which might present risks -- for example: care carrying robots down the stairs (or requiring that robots travel by lift).

**Comment by PeterJCLaw** [comment]
Note also that we have some historic risk assessments which are likely useful as a reference or basis (https://www.studentrobotics.org/cgit/risk-assessment.git/)

**Comment by Adimote** [comment]
Scarzy is doing this too, please add him once he's invited.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne have any teachers asked for this? (I'm assuming that they would have done so)

**Comment by RealOrangeOne** [comment]
Yes, 2. I was hoping these would have been done a long time ago. I tried to hunt some out from previous years to save time but couldn't find any.

@Scarzy what's the status of these?

**Comment by Scarzy** [comment]
@RealOrangeOne I started working on these over this weekend. They are mostly done but I need a couple more days.

I raised a couple of concerns on #65 which I'd also like some feedback on before I can finalise them.

**Comment by Scarzy** [comment]
There's now a pull request for this

**Comment by Tyler-Ward** [comment]
https://github.com/srobo/risk-assessments/pull/5
