### ISSUE TITLE
Document the OBS setup

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#660]
For livestreams. If we can get this to a point where it's import/export of configuration, that would be great.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne I'm currently exploring using [obs-websocket](https://github.com/Palakis/obs-websocket) as a replacement video setup. It would be great to have some details about how the current setup works, so that I can fit things roughly into how this currently works rather than starting afresh.

In particular it would be useful to know roughly what the Scene/Source hierarchy you have is and where you think it would make sense for the match videos to fit in.

I'm broadly guessing that you perhaps have a Scene which does all the match related stuff -- livestream overlay, match videos and the like, with the things like the presentation & commentator views as different Scenes?

**Comment by RealOrangeOne** [comment]
Correct. This is the current list of scenes I have, which get used for a combination of different things.

![image](https://user-images.githubusercontent.com/6527489/107890156-46ec0e80-6f0f-11eb-8e62-87efa31103de.png)

I'm hoping to document this in the next few days, so hopefully that'll give you the insight needed for developing something to do actual scene automation like that.

**Comment by PeterJCLaw** [comment]
Cool. Any chance you could list the sources (scene items) you have in the Matches scene?

**Comment by RealOrangeOne** [comment]
It's currently just the overlay as a browser, and the scheduler as a browser. Although the scheduler browser is swapped out to a window capture with the video issues.

The order of those is important, as the "Overlay" source has a chroma key filter applied, so most of the content is transparent.
