### ISSUE TITLE
Gather feedback from teams

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#661]
Send to everyone who was signed up for SR2021.
As well as the usual things, it would be good to understand the challenges for the teams who were unable to take part in the virtual competition.

Usual things:

- demographics
- prior experience
- did they get the support they needed
- are friendly matches useful to them? If not, why aren't they coming/what can we do to make them more useful?
- are league sessions distributed throughout the year useful to them? Did they feel rushed/encourged to keep improving? Would they be interested in something along this line during a "physical competition" year
(please add to this list)

See also #689 Gather feedback from teams

**Comment by PeterJCLaw** [comment]
Note: capturing demographic information will likely be handled separately.

**Comment by PeterJCLaw** [comment]
We might want to merge this with https://github.com/srobo/tasks/issues/309.

https://github.com/srobo/competition-team-minutes/issues/284 exists for the demographics.

**Comment by PeterJCLaw** [comment]
This is live. Leaving this open until we've looked at the results (likely a week or so after the competition).

**Comment by RealOrangeOne** [comment]
The forms have been out there long enough, and we've gathered some good feedback. I think we can consider this done.

**Comment by PeterJCLaw** [comment]
I'd ideally like to see us actually do something with the feedback. I realise that as a group we've looked through it and that it's therefore in the team notes, however it still feels easy to overlook in future.
I'm not sure where to put it, however a summary document of the key points and/or something to prompt next year's Competition Team to read it would be really useful IMO.
