### ISSUE TITLE
Publicise that code for league session 4 may be carried over to knockouts if teams don’t resubmit

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#665]
From https://github.com/srobo/competition-team-minutes/pull/289.
This is partly so that it's easier for us to schedule the knockouts.

**Comment by PeterJCLaw** [comment]
Some thoughts on the ways that we could do this:
- in Discord
- via Email
- mention during the league 4 livestream

I suspect the answer here is that we do all of these.

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/team-emails/pull/82 somewhat covers this, though I'm expecting that we'll send a variant of that email next week, which will repeat this. We should also mention this in the livestream, so keeping this open is a useful reminder.

**Comment by RealOrangeOne** [comment]
This was mentioned both in the above email, and in the League 4 livestream. I think we can consider this done.
