### ISSUE TITLE
List Items To Hire From / Through SUSU

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#67]
We will be hiring a variety of items from SUSU or through SUSU's suppliers. We need to determine whether we need to hire the following items and if so, their quantity. This is dependent on #64 and #65.

- [ ] Tables
- [x] Radios (#196 )
- [x] Lighting
- [x] Carpet
- [x] Display Screens
- [x] Confetti
- [ ] Chairs
- [x] Power (Extensions etc)
- [x] Fire extinguishers (?)
- [x] Rope Barriers

**Comment by trickeydan** [comment]
SUSU don't have enough tables for us, so we will likely need to use a third party supplier also

**Comment by RealOrangeOne** [comment]
Does ECS have a supply of tables we can use also?

**Comment by trickeydan** [comment]
> Does ECS have a supply of tables we can use also?

Unfortunately not.

**Comment by WillB97** [comment]
Estates or hospitalities should have loads for events like the bunfights

**Comment by RealOrangeOne** [comment]
A meeting is needed with SUSU to purchase these

**Comment by trickeydan** [comment]
We need to unblock this so that a meeting can be arranged.

**Comment by Tyler-Ward** [comment]
https://docs.google.com/document/d/1ttxDknpWHnQCxbrbfjZkgUrBXSjPGfyfhm9rP6jUM_s/edit#heading=h.azfybopb5e70 for the list of things we are requesting, will be sent off early next week

**Comment by Tyler-Ward** [comment]
Have had a meeting with SUSU and everything from them is fine, will order tables and chairs seperatley
