### ISSUE TITLE
Acquire trophies

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#670]
Some awards involve trophies being given to the winning teams. The trophies need purchasing.

### Original

[comp/prizes/trophies](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/trophies.yaml)

**Comment by Adimote** [comment]
Some possible suppliers (Thanks @JennyLynnFletcher!)
For international teams:
Australia:
https://www.prestigetrophy.com.au/glass-awards (trophy is on page 48)

Malaysia (Sending from Singapore):
http://www.usi.com.sg/webphp/product.php?mod=detail&id=62

**Comment by Adimote** [comment]
I'll send a quote tomorrow to trophies2u.co.uk, as soon as I get their 10% discount code email.

Here's a mockup of what we'll be requesting:
![trophy-mockup](https://user-images.githubusercontent.com/2551763/117579953-b54b0200-b0f5-11eb-95db-1e4e836d543e.png)

Note: I had to wrap the game name onto a new line, and we're able to put the team names on, which may also need wrapping

**Comment by Adimote** [comment]
I've also sent a quote request off to prestigetrophy.com.au

**Comment by Adimote** [comment]
for provenance, the trophy I'm ordering from trophies2u is: https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html (I added it to archive.org)

**Comment by Adimote** [comment]
the credit card payment button for trophies2u.co.uk didn't work, so I emailed them directly at their `enquiries` email.

I've submitted a quote for all trophies, with the expectation to remove australia/malaysia/france if they are too expensive.

Also MCK haven't replied to the trophies email, so had to give a rough location estimate in the request for a quote.

Here are the sizes I ordered:

| Prize           | Size   |
|-----------------|--------|
| 1st Place       | 24.5cm (Large)|
| 2nd Place       | 21.5cm (Medium)|
| 3rd Place       | 20cm (Small)|
| Rookie Award    | 20cm  (Small) |
| Committee Award | 21.5cm (Medium) |

**Comment by Adimote** [comment]
I've received the quote from trophies2u, surprisingly it's more expensive to ship to France than it is to Australia!
Also, the prices are lower than I thought, it's actually cheaper to ship from the UK than order in AUS!
![image](https://user-images.githubusercontent.com/2551763/118876763-ea253900-b8ed-11eb-93b3-7829c35f537d.png)
![image](https://user-images.githubusercontent.com/2551763/118876780-f0b3b080-b8ed-11eb-8606-b3d5623450d5.png)

**Comment by RealOrangeOne** [comment]
Not sure I see the difference between these 2 images. So long as we have space in the budget, i'd say go for it. It's been long enough, we should get these shipped and closed off.

**Comment by Adimote** [comment]
Trophies were shipped on Monday 7th at a total cost of 246.40GBP

**Comment by prophile** [comment]
Thanks for sorting this Andy!
