### ISSUE TITLE
Organise the SR2021 post-finals sequence

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#676]
At the end of the competition we want to give out some prizes. We need to plan how we will transition from the finals, through any speeches and run the actual prize-giving ceremony.
We should ensure that anyone who is speaking (whether a volunteer or a guest speaker) knows how long they have, what we're expecting them to talk about and is well rehearsed.
We should include (somewhere) thanks to various people: teams, volunteers, sponsors, etc.

### Original

[comp/prizes/ceremony](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/ceremony.yaml)

### Dependencies

 * ~#672 Take a vote on the online presence award~
 * ~#674 Establish the final results for the main prizes and the rookie award~
 * ~#675 Decide on the recipient of the committee award~
 * #677 Have a rehearsal of the post-finals sequence
 * #690 Render the awards graphic

**Comment by RealOrangeOne** [comment]
I've started writing this up https://docs.google.com/document/d/1GXapV3wEvejVOHiNmMstPLegn3dQ-mE6tP7gRYFtULs/edit

Reviews welcome!

**Comment by PeterJCLaw** [comment]
This happened.
