### ISSUE TITLE
Have a rehearsal of the post-finals sequence

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#677]
At the end of the competition we want to give out some prizes. We need to rehearse how we will transition from the finals, through any speeches and run the actual prize-giving ceremony.

### Original

[comp/prizes/rehearsal](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/rehearsal.yaml)

**Comment by PeterJCLaw** [comment]
Since the competition is virtual and there is no venue to worry about this doesn't need to happen on the day.

**Comment by RealOrangeOne** [comment]
- Moving between matches and prize giving
- Prize giving loop
- Closing remarks / thanks
- Sign-off

**Comment by PeterJCLaw** [comment]
This may have happened? Doesn't really matter now.
