### ISSUE TITLE
Acquire Guest Accounts For Competitors

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#68]
Competitors will need WiFi at the competition venue, and the easiest way to accomplish this is to give them access to eduroam. This will require eduroam guest accounts for competitors.

**Comment by antonnikitin97** [comment]
I will look into this :)

**Comment by RealOrangeOne** [comment]
The perfect-world plan is to have 1 account per team (given to the team leaders), and a handful for volunteers.

**Comment by antonnikitin97** [comment]
I've spoken to someone within iSolutions and they said one account is £25

**Comment by RealOrangeOne** [comment]
I heard somewhere that it was £25 + £1 for every additional account. Is that still the case? I doubt we have the budget to purchase the required number of accounts at that rate.

**Comment by antonnikitin97** [comment]
I will follow this up :)

**Comment by antonnikitin97** [comment]
According to https://www.southampton.ac.uk/isolutions/forms/accounts-for-conference-visitors.page
@RealOrangeOne is correct! :)

**Comment by trickeydan** [comment]
@antonnikitin97 Please email Joyce for these. She will likely cover them happily.

**Comment by antonnikitin97** [comment]
Fantastic. Will do :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PeterJCLaw** [comment]
@antonnikitin97 do you have an update on this? I think we should look at fallbacks if we don't hear something soon.

**Comment by trickeydan** [comment]
>  I think we should look at fallbacks if we don't hear something soon.

Not needed. I spoke to @antonnikitin97 about this yesterday. He has it handled.

I can handle a fallback if needed, although it won't.

**Comment by antonnikitin97** [comment]
Update - I've spoken to Joyce on the 18th and have informed her of our requirements :) waiting to hear from her again.

**Comment by Tyler-Ward** [comment]
@antonnikitin97 I believe these are done now can you confirm, if so who are the details being delivered to.

**Comment by PeterJCLaw** [comment]
@antonnikitin97 can you provide an update here?

**Comment by antonnikitin97** [comment]
update - received email from Joyce saying she'll chase it up

**Comment by antonnikitin97** [comment]
Update, we now have the accounts! I'm closing this issue!
