### ISSUE TITLE
Invite potential sponsor representatives to the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#681]
We should send out invitations to various people from both our current and any prospective sponsoring organisations to come along to the competition.

### Original

[comp/press/invite-sponsors](https://github.com/srobo/recurring-tasks/blob/master/comp/press/invite-sponsors.yaml)

**Comment by PeterJCLaw** [comment]
@Scarzy do you know if we have any sponsors you'd like to invite to watch the livestream?

**Comment by WillB97** [comment]
This isn't particularly valid for a livestream
