### ISSUE TITLE
Gather feedback from the team leaders

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#689]
Would be really useful to gather some feedback from the team leaders.

See also #661 Gather feedback from teams

**Comment by RealOrangeOne** [comment]
The forms have been out there long enough, and we've gathered some good feedback. I think we can consider this done.

**Comment by PeterJCLaw** [comment]
I'd ideally like to see us actually do something with the feedback. I realise that as a group we've looked through it and that it's therefore in the team notes, however it still feels easy to overlook in future.
I'm not sure where to put it, however a summary document of the key points and/or something to prompt next year's Competition Team to read it would be really useful IMO.
