### ISSUE TITLE
Design certificates for SR2021 winners

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#692]
Some teams have asked for certificates this year, lets get them designed and sent out.

**Comment by Adimote** [comment]
Here's my proposed design for the certificate, feedback would be most welcome!
![image](https://user-images.githubusercontent.com/2551763/119367615-6c2cad80-bcb2-11eb-9903-6eb3f753b951.png)

**Comment by Adimote** [comment]
one part I'm not sure on is if we should put the team name in, or the school name, or both the team and school name. (which might be repetitive, as some teams use their school name)

**Comment by Adimote** [comment]
also for your consideration, a rounded corner variant: 
![image](https://user-images.githubusercontent.com/2551763/119369066-09d4ac80-bcb4-11eb-9de2-6936ae6af969.png)

**Comment by RealOrangeOne** [comment]
> For the Student Robotics competition ~year~

I'd say drop the "year".

> from ~the~ team

Probably also worth dropping "the" here too. I think for both an institution name and a team name, without the "the" reads slightly nicer IMO.

I'd say we follow the same guide we do when asking what people want engraved on the trophy, and put that there in place.

+1 for the square variant.

**Comment by Adimote** [comment]
With Jake's suggestions: 
![image](https://user-images.githubusercontent.com/2551763/119370180-48b73200-bcb5-11eb-82d4-e632e0110f7e.png)

**Comment by RealOrangeOne** [comment]
Regarding its future home, I just transferred https://github.com/srobo/certificates to the org. However it transferred archived, and I don't have permissions to change that and give us access, so will require @srobo/trustees. I think that would be a good place to put this and keep track of it for future years.

**Comment by PeterJCLaw** [comment]
What do we normally do for years on awards, should this be SR2021 rather than just 2021?

**Comment by PeterJCLaw** [comment]
Looks great though :+1:

**Comment by JennyLynnFletcher** [comment]
Is there some way of changing the "Student Robotics" text in the background to make it look a little less like a confidential watermark. Or maybe that's just my brain making weird associations?

**Comment by Adimote** [comment]
![image](https://user-images.githubusercontent.com/2551763/120875218-093cef80-c5ab-11eb-9441-ffabf00772ae.png)
Version 2, opinions?

**Comment by RealOrangeOne** [comment]
This looks great!

- The "SR logo in the background" is pretty hard for my brain to pick out. With that said I don't think we should remove it, it's nice that it's not just straight lines.
- Should we include a spot for the team name too? eg "Presented to Joe Blogs from Collyer's..."?
- I'd be interested in moving the main text down a little more, to give more space between it and the logo, and as a result both reduce the padding around and shrink the signatures.

**Comment by Adimote** [comment]
With Jake's fixes:
![image](https://user-images.githubusercontent.com/2551763/120894389-691daf80-c618-11eb-8ca8-51f0be6a1cd7.png)

Also the 'SR Logo' is meant to be a bit of an easter egg, so it's good that it's hard to pick out!

**Comment by RealOrangeOne** [comment]
> From Team

I'd say either drop the "Team" (preferred), or make it lower case

I also still think the signatures should be a little smaller, but happy to be told i'm wrong. Wording just feels a little cramped, as there's a lot of it.

**Comment by Adimote** [comment]
Final version 
![image](https://user-images.githubusercontent.com/2551763/120902269-a21d4a80-c63f-11eb-9f4a-24652c18bc3f.png)

**Comment by Adimote** [comment]
I couldn't attach the final svg to the issue, and the git repo is archived, so I've uploaded it here: https://drive.google.com/file/d/1xAXSHr_XWZm33pTWnnIWyrtSAzamF1UJ/view?usp=sharing

**Comment by RealOrangeOne** [comment]
Pinging @srobo/trustees again to un-archive the https://github.com/srobo/certificates repository, and making sure we have access to it.

**Comment by Adimote** [comment]
I'm gonna mark this as fixed. see https://github.com/srobo/tasks/issues/693 for storing the certificate in git
