### ISSUE TITLE
Budget for regional competitions

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#696]
We're considering doing multiple regional competitions, where we hire a van to move equipment between venues on differing weekends. However before we commit to this, we need to assess the feasability of it, by calculating some expenses

**Comment by Tyler-Ward** [comment]
Is this still useful exercise to do if not it can probably be closed

**Comment by PeterJCLaw** [comment]
Closing as this is a year-by-year consideration and this ticket isn't especially useful in its current form.
