### ISSUE TITLE
Competition Network Physical Layout

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#70]
We need to work out where we're putting the competition network hardware including cabling, devices, etc.

Blocking on #69, #65.

**Comment by WillB97** [comment]
As #69 appears that we are intending to use the installed network for displays outside the Cube srobo/comp-floorplans#3 probably covers this.

**Comment by PeterJCLaw** [comment]
Since we've outsourced this, do we need this ticket any more (cc @trickeydan as you're managing #69 and the outsourcing of this)?

**Comment by trickeydan** [comment]
I think we can safely close this ticket. Chris has it planned, it's difficult, but doable.

I have asked him to document all of his decisions for future reference.

Meta: There's going to be a 5GHz radio link between Bar 3 and concourse due to fire safety restrictions.

**Comment by Tyler-Ward** [comment]
Were we not planning on this data being put into the floorplans before closing per earlier in person discussions?

**Comment by trickeydan** [comment]
> Were we not planning on this data being put into the floorplans before closing per earlier in person discussions?

Yes, but that is a separate issue to planning the layout imo. The layout has been planned, just isn't in our docs yet. I'll mention it to Chris.

**Comment by Adimote** [comment]
Given the history, I'd advocate that someone reviews Chris' plans and certifies them as "not overcomplicated"

**Comment by RealOrangeOne** [comment]
I really think we should have updated our plans (or at least documented exactly what's being done) _before_ closing this ticket, to match how we've done everything else. A plan isn't really a plan until it's documented somewhere.

**Comment by WillB97** [comment]
I agree with @Adimote, if the proposed design is sufficiently complicated that there are likely to be issues implementing it, we should explore simpler solutions which require less on the day setup.

**Comment by trickeydan** [comment]
> Given the history, I'd advocate that someone reviews Chris' plans and certifies them as "not overcomplicated"

@Tyler-Ward and I can vouch for this.
