### ISSUE TITLE
Add internal link checking to our Jekyll sites

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#701]
It's currently far too easy to typo a link (or remove a page) and end up with broken links in sites. While these can be checked manually, it should also be possible to automate this. We'd likely want to ignore links to external pages, but that should be easy enough.

Sites:
- [x] website (https://github.com/srobo/website/pull/320)
- [x] docs (https://github.com/srobo/docs/pull/215)
- [x] style (https://github.com/srobo/style/pull/24)
- [x] competition-website (https://github.com/srobo/competition-website/pull/25)

**Comment by Tyler-Ward** [comment]
see also https://github.com/srobo/docs/issues/213

**Comment by PeterJCLaw** [comment]
I had a quick play with some tools:
- https://pypi.org/project/link-checker/ seems promising but is Python and Jekyll is Ruby, so it would be nice not to need another language runtime. This might be a good fit for the runbook though.
- https://github.com/gjtorikian/html-proofer seems promising, but does _way_ more than just link checking. It seems pretty configurable, however does have some issues that would create problems for us (notably https://github.com/gjtorikian/html-proofer/issues/618 and https://github.com/gjtorikian/html-proofer/issues/552)

**Comment by PeterJCLaw** [comment]
This is now done (for Jekyll sites).
There's obviously plenty this doesn't cover -- notably cross-site links or non-Jekyll things (like the runbook), but we can pick those up separately.
