### ISSUE TITLE
VoIP for event communicatons

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#71]
Work out a potential IP telephony network for volunteer communication (expected to work in conjunction with SUSU Radios).

Initial planning will be relatively independent of the physical locations of things, so we can start working things out right away, but later this will need to be taken into account when planning the physical network layout.

**Comment by RealOrangeOne** [comment]
Only relevant if we decide to ship VoIP, which depends on https://github.com/srobo/tasks/issues/149

**Comment by RealOrangeOne** [comment]
We're not doing this!

**Comment by RealOrangeOne** [comment]
Re-opening, but bumping out of this competition cycle.

**Comment by PeterJCLaw** [comment]
I believe we now regularly have (VoIP?) phones at events -- can we close this?

**Comment by WillB97** [comment]
We now have a supplier that is happy to provide us with both deskphones and softphones (through the 3CX app). These have proved useful in clearing up operational communications.
