### ISSUE TITLE
Announce the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#715]
The competition needs fanfare so that people know when & where it will happen. The following things should happen:
 - [x] An events page
 - [x] A news article about the announcement (somewhat optional)
 - [x] Social media publicity linking back to the news article and/or event page
 - [x] Email to the team-leaders
 - [x] Email to volunteers
 - [ ] Email to tech/STEM blogs and other external media outlets

### Original

[comp/announce](https://github.com/srobo/recurring-tasks/blob/master/comp/announce.yaml)

### Dependencies

 * #714 Find and book venue for SR2022

**Comment by sedders123** [comment]
We think at this point we'd gain more from inviting external media to the actual event rather than just telling them we've announced the dates and locations.
