### ISSUE TITLE
Prepare an article for after the SR2022 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#716]
After the competition we want to have a news article which describes how the event went, which teams won, etc.
The post-competition news article can take some time to write. We should write a skeleton one as soon as possible, and just fill in the blanks immediately after the competition followed by high-speed review and shipping.

### Original

[comp/prepare-news-afterwards](https://github.com/srobo/recurring-tasks/blob/master/comp/prepare-news-afterwards.yaml)

### Dependencies

 * #714 Find and book venue for SR2022

**Comment by sedders123** [comment]
See https://github.com/srobo/website/pull/402

**Comment by PeterJCLaw** [comment]
Is this done now? That article feels prepared. (There's a separate task https://github.com/srobo/tasks/issues/717 for updating and publishing it afterwards)

**Comment by PeterJCLaw** [comment]
This is done.
