### ISSUE TITLE
Work Out Power Layout

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#72]
We need lots of power (especially for team pits). We should work out where this goes.

Blocking on #65.

See also #70 as the cabling likely wants to run together.

**Comment by WillB97** [comment]
You will want to account for the locations of available plug sockets and minimising the number of cables crossing walkways

**Comment by RealOrangeOne** [comment]
We will almost certainly need come cable floor covers for the places cables will inevitably need to be run over walkways

**Comment by PeterJCLaw** [comment]
Historically we've used the [floorplans](https://github.com/srobo/comp-floorplans) to record this, there might be utility in doing that again.

**Comment by PeterJCLaw** [comment]
For reference, there are some old plans in https://www.studentrobotics.org/cgit/arena.git/tree/comp13/floorplans which _might_ be useful as references.

**Comment by prophile** [comment]
How much of this can we punt to SUSU?

**Comment by WillB97** [comment]
Barring sorting out power for battery chargers (see https://github.com/srobo/tasks/issues/65#issuecomment-469398555), I believe srobo/comp-floorplans#3 covers this as SUSU can handle routing the cable runs and organising chaining.

**Comment by Tyler-Ward** [comment]
Fixed in https://github.com/srobo/comp-floorplans/pull/3
