### ISSUE TITLE
Have a competition network

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#723]
This also requires that we have a pretty significant internet connection given the number of people that are coming and our video streaming requirement.
If possible this should be mostly configured in a corner of the venue as early as possible during setup and then, once working, deployed to the proper locations.

### Original

[comp/venue/network](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/network.yaml)

### Dependencies

- #899 Organise Eduroam accounts for SR2022

**Comment by trickeydan** [comment]
I can lend a Cisco 3750G for this and am happy to help with configuration if needed.

**Comment by trickeydan** [comment]
(I may also be able to provide a Cisco router, but I suspect we want something with an AP in it too)

**Comment by RealOrangeOne** [comment]
I can provide a https://www.gl-inet.com/products/gl-mt1300/, which can function both as a router and AP.

**Comment by RealOrangeOne** [comment]
There are 2 large (~36 port) switches in the container. Which would have been great for this, if they weren't 10/100 :vomiting_face:

**Comment by trickeydan** [comment]
> All we really need extra is a basic switch to give us some more ports.

This is already solved:

> I can lend a Cisco 3750G for this and am happy to help with configuration if needed.

**Comment by WillB97** [comment]
> There are 2 large (~36 port) switches in the container. Which would have been great for this, if they weren't 10/100 vomiting_face

For most of what we're doing 10Mbit is fine, even with the livestream, 100Mbit is plentiful. The uplink for SR2019 and several smallpeice's has been 100Mbit.

> This is already solved:
> > I can lend a Cisco 3750G for this and am happy to help with configuration if needed.

Great, we just need a flat layer 2 configuration for the tech desk.

**Comment by Tyler-Ward** [comment]
Some of the kit that is expecting to be used will require POE (Power over Ethernet) which I believe that switch will provide

**Comment by WillB97** [comment]
What is expecting PoE? The only devices I'm expecting are:
- The 4 corner pis
- The compbox
- The lighting desk
- The livestream computer
- My AP
- Various laptops

**Comment by Tyler-Ward** [comment]
The PoE things I am thinking of are the skycam pi, and the three status stack lights.

Also on the network will need to be.
* Mixtape machine (mixtape controls the lighting desk)
* additional display pis in the arena area e.g. staging/sheparding and judges display

**Comment by PeterJCLaw** [comment]
The staging/shepherding displays can be on the public network if that's easier (they can use the public compbox easily enough).

It's not clear to me why the skycam pi needs to be on the competition network? Could it not use the public compbox if needed? Obviously that doesn't change the desire for PoE to it.

What are status stack lights?

**Comment by WillB97** [comment]
> The staging/shepherding displays can be on the public network if that's easier (they can use the public compbox easily enough).
> 
> It's not clear to me why the skycam pi needs to be on the competition network? Could it not use the public compbox if needed? Obviously that doesn't change the desire for PoE to it.

To clarify, the intention is that there will be a single wired network which will only be in the cube. It is less a case of public vs comp network and more a case of wired vs eduroam. Half the point of having the switch is so that there will be sufficient ports to wire all the devices that require a reliable connection to A) the compbox or B) the internet. I believe SR has plenty of ethernet to do this in the container (#734).

> > Some of the kit that is expecting to be used will require POE (Power over Ethernet) which I believe that switch will provide
>
> Yes it does PoE.

Since the switch does have PoE, adding these devices are not an issue.

As a side note, the 13A sockets in the truss can be switched on and off from the booth if future events decide something different.

**Comment by WillB97** [comment]
Having started on the floorplan, we may need 2 switches in the cube since the arena corner is likely to fall quite far from the edge of the balcony.

**Comment by Tyler-Ward** [comment]
I have a 48 port Gigabit switch we can use, it doesn't have POE though. I do however have a small POE switch I can extract from my network if we need POE at both switches.

**Comment by WillB97** [comment]
The balcony would need PoE for the skycam, whether the stage switch requires PoE depends on where the stacklights are used.

**Comment by WillB97** [comment]
Assigned to the people provideing equipment.

**Comment by PeterJCLaw** [comment]
Is there anything in particular we need to arrange to ensure the network has a connection to the internet? For example are we going to be able to plug into a hardwire port somewhere (ideally) or are we going to need a WiFi situation?

**Comment by WillB97** [comment]
I have an uplink sorted.

**Comment by WillB97** [comment]
See https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing
