### ISSUE TITLE
Work out what we need from storage at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#727]
#### Comp Ops

- [ ] Monitors: all 6 of the boxed ones, plus at least a couple of the other assorted ones

#### Matches

- [ ] Clipboards (for the marshals)

### Original

[comp/venue/transport/work-out](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/work-out.yaml)

**Comment by WillB97** [comment]
The freight list is at: https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing see the current location column.
