### ISSUE TITLE
Prepare equipment for transport to the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#728]
The things that we are taking to the competition needs to be prepared for transportation. Most of the things we need are in storage, however some may be elsewhere.

### Original

[comp/venue/transport/prepare](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/prepare.yaml)

### Dependencies

 * #727 Work out what we need from storage at the competition

**Comment by WillB97** [comment]
The freight list is at: https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing see current location column.
