### ISSUE TITLE
Competition Schedule

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#73]
We need a schedule for the competition.

Pulling to the top for ease of access (from https://github.com/srobo/tasks/issues/73#issuecomment-466637195): https://hackmd.io/7vwAw5xmSJ6d20CqvO5siQ?edit

**Comment by PeterJCLaw** [comment]
What level of detail are we after here? Does this include the match schedule, or is this about the main blocks of time?
Does this include planning for setup/teardown, or is this just so we can publish the public parts?

**Comment by RealOrangeOne** [comment]
I suggest we write up both public and private parts (ie setup / teardown), and then just publish the public part. 

I'd expect the schedule to look something like https://studentrobotics.org/events/sr2017/competition/#schedule, which looks to contain all the information teams would need

**Comment by Tyler-Ward** [comment]
I have started a rough schedule here
https://hackmd.io/7vwAw5xmSJ6d20CqvO5siQ?edit

**Comment by PeterJCLaw** [comment]
@Tyler-Ward nice!
A couple of things:
- The league matches on Saturday go beyond the end of day (17:30 vs 17:00), I'm guessing that's an oversight?
- Does the arena takedown scale to _all_ our volunteers? (I'd be surprised if so) Perhaps we should have some other take-down happening then, perhaps under the leadership of a couple of volunteers who've done take-down a few times before?

**Comment by Tyler-Ward** [comment]
> * The league matches on Saturday go beyond the end of day (17:30 vs 17:00), I'm guessing that's an oversight?

Fixed
> * Does the arena takedown scale to _all_ our volunteers? (I'd be surprised if so) Perhaps we should have some other take-down happening then, perhaps under the leadership of a couple of volunteers who've done take-down a few times before?

we cant start much other takedown until the venue is clear or competitors but we can clear the cube earlier hence it having its own takedown slot (the early arena take-down tasks are very parralisable here as well e.g fabric and padding and cable removal) we will also need a good number of volunteers for kit handback and other competitor facing roles.

**Comment by PeterJCLaw** [comment]
What's "Empty case return"?

**Comment by Tyler-Ward** [comment]
Getting back out the boxes stuff came in so it can be packed back into them, as they will likely be stored out of the way.

**Comment by PeterJCLaw** [comment]
Not sure if it's intentional -- the amount of time currently allocated to the league is 9¾ hours. That works out at exactly 117 match slots!

SR has run the first round of matches (i.e: eveyone's first appearance) at double spacing to get things going (both for shepherds and for the teams) which means this allows for 108 slots. At 12 matches per team, I think that's plenty.

This aspect also relates to #103.

**Comment by PeterJCLaw** [comment]
I've had another look at the schedule.
I think we're going to need more time for the knockouts (currently the schedule generated by SRComp is 45 minutes longer than what's allocated, and I don't think a manual schedule will be able to lose all of that).
I also think we're going to want more than 15 minutes for the prize giving - I suspect we'll want about 20 minutes for the actual talking & prizes, plus some gap between the final and the proper start of it. This is gut feel though, I can't recall how long we usually take for it.

**Comment by prophile** [comment]
Now updated.

**Comment by RealOrangeOne** [comment]
To me, this looks fine. I can't comment on if the provided time for the league / heats is enough, but I trust you've done the maths.

There doesn't seem to be any accounting for #120. There were suggestions we could fit it in before the prize giving (#128), but I doubt we're going to fit everyone in the arena for this, I suspect we're going to need an outside area, which is going to take yet more time.

If we don't think we can account for this, we should either close #120, or shrink a tinker time slot to account for it.

**Comment by PeterJCLaw** [comment]
I don't think we need a specific slot for #120 -- doing them revolving during the _league_ matches seems completely reasonable to me, as long as we're upfront with the teams about when they'll need to be there (and I'd encourage we do them on Saturday if possible).

I _do_ think we need a slot for a whole-group photo. I don't know if we have a ticket for that, nor if we've planned where it will happen? Previously we've done this in the gap between the league and the knockouts and that's worked fairly well.

**Comment by PeterJCLaw** [comment]
Please can we change the line:
>  14:40 - 16:55 Heats
to be called "Knockouts"?

We've always called them "Knockouts" in the past and especially as we now have a specific stage called the "Heats" I'm finding it confusing.

**Comment by Tyler-Ward** [comment]
#120 is the group photo, #198 is for individual teams. we could do it at the end of the Sunday lunch slot that way it doesn't interfere with the end timings.

**Comment by PeterJCLaw** [comment]
Aha, I've clarified those tickets.

**Comment by RealOrangeOne** [comment]
Regarding the whole competition photo, I see a few options:

- Do it just after lunch on Saturday, and push the whole schedule back ~30 minutes
- Use some of the padding between league matches and knockouts on Sunday, and push the rest of the schedule back ~15 minutes. I doubt we'd need to change the time we close, as 45 minutes to clear out teams sounds quite high anyway.

I'm personally leaning towards option 2, although I elect @prophile or @Tyler-Ward to make the final decision.

**Comment by Tyler-Ward** [comment]
Option 2 is probably the best of these, I expect some teams may use the full 45 minutes but there is going to be plenty to do elsewhere that delaying takedown in some areas wont be an issue.

**Comment by RealOrangeOne** [comment]
I agree. If we're happy with that I can update the HackMD and https://github.com/srobo/website/pull/138

**Comment by Tyler-Ward** [comment]
Sounds good, lets do it.

**Comment by RealOrangeOne** [comment]
Added as https://github.com/srobo/website/pull/138/commits/61c1fd24a641167c25606c349cf7df39374d94b2.

**Comment by Adimote** [comment]
Can we close this now?

**Comment by Tyler-Ward** [comment]
I have split the setup schedule into #220 so this can be closed
