### ISSUE TITLE
Transport stuff to the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#730]
Many things will need to be moved from various locations to the venue.

### Original

[comp/venue/transport/main](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/main.yaml)

### Dependencies

 * #727 Work out what we need from storage at the competition
 * #728 Prepare equipment for transport to the competition
 * #729 Hire a van for transporting kit between storage and the venue

**Comment by WillB97** [comment]
@prophile has agreed to move most of the stuff from the container to his house on Wednesday so we'll have things early on. Importantly this will mean we have the arena walls on Thursday morning.

**Comment by WillB97** [comment]
@RealOrangeOne can transport any remaining items on Thursday morning, if neccessary.

**Comment by WillB97** [comment]
@prophile can do this at some point early next week, @trickeydan can he get the key from you?

**Comment by PeterJCLaw** [comment]
Much stuff has been transported to @prophile's house.

**Comment by PeterJCLaw** [comment]
Stuff is now in the Cube.
