### ISSUE TITLE
Organise arena lighting

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#731]
We need lighting on the arenas.

### Original

[comp/venue/arena-lighting](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/arena-lighting.yaml)

### Dependencies

 * #721 Ensure there is power at the SR2022 competition

**Comment by Tyler-Ward** [comment]
I have created a rough guidance doc for what we need to do to setup the lighting at https://docs.google.com/document/d/13CSzQOcftihG6FSnl5RJtzMc0fBntSiiSuCBaDFkdTc/edit# @WillB97 any thoughts from your end

**Comment by WillB97** [comment]
We have lights booked and a plan
