### ISSUE TITLE
Organise cable protectors

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#732]
It's a bad idea to have loose cables trailing around on the floor. We should hire cable protectors to cover the cables anywhere necessary.
Note when ordering them: it turns out to be easier to setup shorter runs than longer ones. As a result where runs pass under tables (etc.) we should get several short pieces rather than single long ones.

### Original

[comp/venue/cable-protectors](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/cable-protectors.yaml)

### Dependencies

 * #725 Prepare a layout of the competition

**Comment by WillB97** [comment]
These are included in the tech
