### ISSUE TITLE
Pre competition storage trip

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#734]
We'll need to visit storage at some point before the competition, to check quantities of consumables (tape etc.) and to pick up other things which need checking/fixing/updating etc. This task exists to track the things we should do on that trip.

- [x] Collect the display Pis for checking & flashing
- [x] Collect the compbox Pi for checking & flashing
- [x] Check for robot flag fittings 
- [x] Check tape quantities 
- [x] Check on stationery (pens, paper)
- [x] Check on high-vis jackets (are they clean?)
- [x] Check for the table cloth
- [x] Check for / count empty name badges
- [x] See if Media Consent Forms are in the container
- [x] What is the display output on the displays?
- [x] How many displays do we have?
- [ ] Collect tape
- [x] Check network cables
- [x] Look for old MCFs

Please do add to the above list.

### Original

[comp/pre-comp-storage-trip](https://github.com/srobo/recurring-tasks/blob/master/comp/pre-comp-storage-trip.yaml)

**Comment by RealOrangeOne** [comment]
This ticket may benefit from being in 2 parts. 1 for the "pre competition trip" which fetches parts which need prepping shortly before the competition, and another "pre pre competition trip", which checks quantities and state of resources.

I am happy to do the latter (pre pre competition trip), and will likely be around that way 16th Feb.

**Comment by RealOrangeOne** [comment]
> Check tape quantities

There is a lot of tape. Have added specifics to https://github.com/srobo/tasks/issues/807#issuecomment-1029384978

> Check on stationery

Clipboards were there. I couldn't find pens, although I distinctly remember buying a large box.

> Check on high-vis jackets

These are definitely here, and there are tonnes.

> Check for the table cloth

The fancy one used for prize giving, and the branded ones for reception are all accounted for.

> Check for / count empty name badges

I had a bit of a hunt, but couldn't seem to find these. It was dark, and I was tired, so I could have missed them.

**Comment by Scarzy** [comment]
>> Check on high-vis jackets
> These are definitely here, and there are tonnes

What state are they in? If they are graffiti-ed all over then they aren't usable.
I've unchecked this from the list above so this can be confirmed.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne do we have a date for when the next storage visit will be?

**Comment by RealOrangeOne** [comment]
I'll be going mid-afternoon on Friday 8th April, where I can check most of these things again to get more concrete numbers, and check the state of more things (it won't be dark this time when I go).

**Comment by PeterJCLaw** [comment]
That feels rather close to the competition to me, especially with Easter in between, but if there isn't a way to do it sooner I guess it'll have to do.

**Comment by WillB97** [comment]
Items to check the container for: https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit#gid=1181706331&fvid=686293370

**Comment by RealOrangeOne** [comment]
> Collect the compbox Pi for checking & flashing

I now have the compbox and display Pis

> Check tape quantities

See https://github.com/srobo/tasks/issues/807

> Check on stationery (pens, paper)

We have plenty of pens. Given the amount we need to print, we should get a pack of paper.

> Check on high-vis jackets (are they clean?)

Yes, they're clean, however many still have the labels on (paper). Tape looks to work fine for attaching, and some have safety pins. We should reuse the safety pins, and tape the rest.

> Check for / count empty name badges

Sadly, I couldn't find these

> See if Media Consent Forms are in the container

MCFs from 2019 are indeed in the container

> What is the display output on the displays?
> How many displays do we have?

We have a total of 12 displays. 6 boxed all of the same kind, and 6 misc. Of the 6 misc, 5 have DVI / VGA, and 1 has just VGA. There are no cables for any of them. 

Mirrored to https://github.com/srobo/tasks/issues/737

> Check network cables

There is a RUB of network cables, many of which are quite long.

<details>

![IMG_20220408_160333](https://user-images.githubusercontent.com/6527489/162499971-33ce8ae1-9fa9-4915-9efb-ac412e350a92.jpg)

</details>
