### ISSUE TITLE
Acquire screens

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#737]
We do not have enough screens to cover everything, so we may need to hire more.
4 screens per arena, plus 2 for staging / shepherding.
Plus however many neeeded for non arena screens ("outside").

### Original

[comp/arena/acquire-screens](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/acquire-screens.yaml)

### Dependencies

 * #900

**Comment by WillB97** [comment]
The outside screens should be provided by the venue, although we will need to resolve how we display things on them. Since we only have 1 arena, I believe that we have enough screens for the arena and staging.

**Comment by RealOrangeOne** [comment]
We have 6 identical screens in the container. 1 for each corner, plus 2 for staging. There are ~4 other "assorted" screens in the container, which can be used elsewhere as needed.

**Comment by PeterJCLaw** [comment]
Yup, given that the venue quote includes two 65" screens for the outside (which itself is #738 anyway), I think we're good here. Our screens obviously need to make it to the venue, but I'm not sure that this task is useful to keep open for that purpose.

**Comment by Tyler-Ward** [comment]
We will need extra screens for various other areas such as livestreaming ect, should those come under this to keep the requirements in one place?

**Comment by WillB97** [comment]
Surely that would come under #788

**Comment by Tyler-Ward** [comment]
Have reopened so we can use this to avoid the screens we have being allocated to multiple locations. for info https://github.com/srobo/tasks/issues/99 has a list of screens we used at the last susu competition

**Comment by WillB97** [comment]
These are now being tracked in https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing

**Comment by RealOrangeOne** [comment]
We have a total of 12 displays. 6 boxed all of the same kind, and 6 misc. Of the 6 misc, 5 have DVI / VGA, and 1 has just VGA. There are no cables for any of them.

**Comment by PeterJCLaw** [comment]
> We have a total of 12 displays. 6 boxed all of the same kind, and 6 misc. Of the 6 misc, 5 have DVI / VGA, and 1 has just VGA. There are no cables for any of them.

For clarity: were there cables for the boxed ones? I really hope so as those are ones we've bought & had for a long time and they've always had cables in the past.

Also: do we need power cables for any of them? If so, do we know which flavour they need?

**Comment by RealOrangeOne** [comment]
I never checked the boxed monitors i'm afraid, but I'm fairly sure we store all the cables with those monitors.

As for the others, I didn't note it down, but I'm fairly confident they were all standard kettle plugs

**Comment by PeterJCLaw** [comment]
Yup, not worried about not checking the boxed ones. Just wanted to be sure what it was that was meant.
