### ISSUE TITLE
Organise the non-arena ("outside") display screens

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#738]
Throughout the venue we typically have a number of general information screens which show the schedule of matches, state of the league, etc. We need to organise screens & drivers for these to run on. They also need power and internet connections.
This may also include stands to mount the screens on. These screens are typically larger-format than the screens used within the arena.

### Original

[comp/arena/non-arena-display-screens](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/non-arena-display-screens.yaml)

### Dependencies

 * #723 Have a competition network
 * #734 Pre competition storage trip
 * #737 Acquire screens

**Comment by PeterJCLaw** [comment]
The venue quote includes provision of these screens.
