### ISSUE TITLE
Plan Arena Lighting

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#74]
Work out how the lighting will look and work in the arena.

The most important aspect is that during matches we have a good even level of light in the arena. This needs to be sufficiently bright and flat to ensure good vision pickup on the markers, without being so bright that it introduces glare or shadows.

For between matches we need a level of light which enables the marshalls to record the end-state of the arena for scoring as well as for seeing and carrying the robots around.

Secondary to that, it would be nice to have an interesting (though not too showy) transition into and out of the match mode, optionally with the possibility of a slightly more spectacular variant for the knockouts.

**Comment by Adimote** [comment]
Will be concluded in the SUSU meeting.

**Comment by TomWheal** [comment]
@WillB97 is probably best suited to this

**Comment by sedders123** [comment]
@WillB97 Assigning to you as @TomWheal mentioned you have started/done this.

**Comment by PeterJCLaw** [comment]
I've updated the description with some requirements.

**Comment by WillB97** [comment]
The current plan would be to test vision with a slight rearrangement of the standard rig to see if additional lighting is required.

We'll probably do this on the Thursday.

**Comment by WillB97** [comment]
What's above is the plan for this.
