### ISSUE TITLE
Provide network to the reception desks

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#740]
The reception desk(s) need an internet connection for computers running the admission software.

### Original

[comp/reception/network](https://github.com/srobo/recurring-tasks/blob/master/comp/reception/network.yaml)

### Dependencies

 * #723 Have a competition network
 * #899 Organise Eduroam accounts for SR2022

**Comment by WillB97** [comment]
The intention would be that the reception machines connect to eduroam so no phyiscal infrastructure will be needed. Guest accounts will be need to be obtained.

**Comment by RealOrangeOne** [comment]
Our [new process](https://github.com/srobo/tasks/issues/749#issuecomment-1029385326) doesn't require a network
