### ISSUE TITLE
Produce booklets for the SR2022 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#744]
The primary target of these booklets are invited guests (both of SR and of the teams), who may not know very much about either Student Robotics or the game the robots are competing in.
These booklets should include:
 - descriptions of both SR and the game
 - a summary of the teams competing (a list of TLAs and names is fine)
 - the overall schedule of the competition weekend
 - sponsors

Note: much of the content of these booklets does not need to actually be new -- the website already contains plenty of summaries of SR and the game, which can be copied liberally, as well as the day schedule.

### Original

[comp/flyers](https://github.com/srobo/recurring-tasks/blob/master/comp/flyers.yaml)

### Dependencies

 * #743 Work out the day schedules for the competition

**Comment by WillB97** [comment]
Also depends on:
* #782

**Comment by PeterJCLaw** [comment]
These have been sent to the printers. @sedders123 shall we close this or do you want to keep it open until they arrive?

**Comment by sedders123** [comment]
These have been sent to the printers, will close this one but keep https://github.com/srobo/tasks/issues/745 open until they arrive (should be this Thursday 14th)
