### ISSUE TITLE
Print the booklet for the SR2022 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#745]
Arrange printing of the booklets for handing out at the competition.

### Original

[comp/print-flyers](https://github.com/srobo/recurring-tasks/blob/master/comp/print-flyers.yaml)

### Dependencies

 * #744 Produce handout flyers for the SR2022 Competition

**Comment by WillB97** [comment]
Once this is done can you update #902

**Comment by sedders123** [comment]
These have been sent to the printers, will close when they arrive (should be this Thursday 14th)

**Comment by sedders123** [comment]
These have arrived 🎉
