### ISSUE TITLE
Plan Competition Sound System

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#75]
We need to work out how the sound system will work for the competition, where/how we will play music, etc.

**Comment by RealOrangeOne** [comment]
Music will come from a laptop of mine running Mopidy with a custom playlist. It'll require a network connection (wireless), and a 3.5mm output.

**Comment by WillB97** [comment]
The balcony in the Cube has an audio input that can be sent to Bar 2, 3, Cube and possibly the concourse and cafe.

**Comment by RealOrangeOne** [comment]
Concourse and Cafe would be ideal, just so everyone can hear announcements etc. I'm sure we can run a super-janky cable setup if needed :stuck_out_tongue_winking_eye:

**Comment by PeterJCLaw** [comment]
Related to: #148 & #74 (for the finals at least)

**Comment by Adimote** [comment]
Will be concluded in the SUSU meeting.

**Comment by sedders123** [comment]
Assigning to @WillB97 as a SUSU task
