### ISSUE TITLE
[Meta] Organise media consent for SR2022

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#750]
We need media consent from everyone at the competition.

### Original

[comp/media-consent/main](https://github.com/srobo/recurring-tasks/blob/master/comp/media-consent/main.yaml)

### Dependencies

 * #746 Update MCF and link for SR2022
 * #747 Email teams about media consent
 * #748 Print spare MCFs for visitors
 * #749 Organise tickets for SR2022

**Comment by Scarzy** [comment]
I'm looking at a potential wording update, so assigning to myself (for now)

**Comment by PeterJCLaw** [comment]
Proposed plan for media consent management in the venue:
- issue red, yellow or blue lanyards on the door (see https://github.com/srobo/tasks/issues/749#issuecomment-1029385326 for arrangements)
- inform everyone that the Cube is being livestreamed and photographed and they should stay out if they're withholding consent
- let people know that during the prize-giving the stage is being livestreamed/photographed and that they may wish to not go there if they're not granting consent
   - if there's anyone who's not granting consent and wins a prize we can remove the livestream from the VoD version of the livestream
- inform other media organisations that our media consent does not cover their usage and they'll need to get their own consent

We anticipate having a full sized test arena, so there's minimal disadvantage to teams who aren't able to use the match arena during tinker time.

**Comment by sedders123** [comment]
Is it possible for volunteers with media consent to have no lanyard? From a competitors perspective finding out someone's name may be easier from a badge rather than a lanyard that could spin/be at weird angles. Volunteers will be identifiable by a blueshirt anyway.

**Comment by PeterJCLaw** [comment]
Ideally no, the presence of a {yellow, blue} lanyard is an affirmative signal of granted consent. Since consent is opt-in rather than opt-out, the proxy should match that. (Essentially: consider what happens if a red-lanyard person takes their lanyard off momentarily)

**Comment by sedders123** [comment]
👍 Thanks, that makes sense missed that case!

**Comment by trickeydan** [comment]
> issue red (no media consent), yellow (media consent) or blue (blueshirt with media consent) lanyards on the door (see 

What about visitors? At SR2019, we didn't allow anybody to enter the building without media consent iirc.

Buying 4 colours of custom lanyard will not be cheap either. I suggest we go for wristbands again, as we did at SR2019 and SR2017 (at least, possibly earlier years too)

**Comment by RealOrangeOne** [comment]
> What about visitors?

They're non-blueshirts, So they'd get either red or yellow, depending on whether they give media consent.

One could argue that we probably don't need the distinction of whether the person is a blueshirt with media consent, as we already know whether they're a blueshirt or not (as the name suggest). That also makes lanyards become strictly a mechanism of media consent, rather than mixing in anything else unnecessarily.

**Comment by sedders123** [comment]
Our approach for this year has been agreed upon and plans are being actioned
