### ISSUE TITLE
Order wristbands + lanyards for SR2022

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#752]
We need to order lanyards.

### Original

[comp/wristbands/order](https://github.com/srobo/recurring-tasks/blob/master/comp/wristbands/order.yaml)

### Dependencies

 * #751 Design wristbands for SR2022

**Comment by sedders123** [comment]
Think it was mentioned we were doing lanyards this year. Can change back to wristbands if needed

**Comment by Tyler-Ward** [comment]
We have previously used wristbands as they cannot be removed non destructively hence preventing them being shared between people (as they also signified media consent). Not sure if this is still a concern.

**Comment by RealOrangeOne** [comment]
I would say this is blocked on https://github.com/srobo/tasks/issues/750

**Comment by antoinepetty** [comment]
They've been ordered. Waiting for them to arrive to check quality

**Comment by sedders123** [comment]
Lanyards have been ordered

**Comment by sedders123** [comment]
We now have 500 wristbands and 25 red lanyards.
