### ISSUE TITLE
Arrange a reception desk at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#753]
This is needed for entry control. Everyone (competitors, team-leaders, blueshirts and guests) who wants to come in must have a ticket or a completed media consent form.
In SR2015 this consisted of four individual desks arranged such that one was on each side of two lanes. Each desk had its own queue, and one was reserverd for special-case handling (e.g: competitors without tickets). Crowd barriers were used to enforce these queues.
A volunteer was stationed on the door reminding people of the things they needed to hand over (ticket, batteries, charger), which further improved things.
On each desk the validation of tickets was separated from the crimping of the wristbands, with a different volunteer manning each. A small number of additional volunteers were also placed around the desks to direct people towards their proper pit area.

### Original

[comp/reception/main](https://github.com/srobo/recurring-tasks/blob/master/comp/reception/main.yaml)

### Dependencies

 * #733 Organise computering kit for the competition reception desk
 * #740 Provide network to the reception desks
 * #741 Provide power to the reception
 * #742 Source tablecloths for the reception desks
 * #745 Print the flyers for the SR2022 Competition
 * #750 Organise media consent for SR2022
 * #752 Order wristbands for SR2022

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
