### ISSUE TITLE
Print arena labels for SR2022

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#754]
Since we have more than one arena we want a way to tell which is which. One possible mechanism is to colour-code them, though having printed name labels is easy and has been done in the past.
There are some handy large A and B label PDFs attached to #2964.
Note that since people need to use the label of the arena to clearly communicate which they're talking about it is best to stick to having a single name for each.

### Original

[comp/arena/labels](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/labels.yaml)

**Comment by WillB97** [comment]
I assume this is refering to putting vision markers on the arena, since we only have one competition arena this year.

**Comment by PeterJCLaw** [comment]
No, this task is about having labels to know which arena is which on years when we have more than one arena. Since we only have the one arena this year, this doesn't apply. There _should_ be a separate task for sorting vision labels for the arenas.
