### ISSUE TITLE
Print score entry forms for marshals

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#757]
The actual sheets to be filled in need to be printed.

The source for the sheets is at https://github.com/srobo/arena/tree/master/comp22, though only as SVG.
It compiles to a PDF for printing: 
- [score-sheet-2022.pdf](https://github.com/srobo/tasks/files/8501916/score-sheet-2022.pdf)
- ~[colour-score-sheet-2022.pdf](https://github.com/srobo/tasks/files/8501917/colour-score-sheet-2022.pdf)~

Please print in greyscale (i.e: first file above).

### Original

[comp/game/score-forms-print](https://github.com/srobo/recurring-tasks/blob/master/comp/game/score-forms-print.yaml)

### Dependencies

 * #756 Design score entry forms for marshals

**Comment by PeterJCLaw** [comment]
@Tachy0n1c has offered to bulk print things this week.

**Comment by PeterJCLaw** [comment]
I've added printing details in the description.

**Comment by Tachy0n1c** [comment]
@PeterJCLaw Thank you for the details. Could you please let me know how many copies you need?

**Comment by PeterJCLaw** [comment]
Good question. The schedule currently has 92 matches (league and knockouts), we need two blanks per match. Allowing for some spares 210 copies should be enough please @Tachy0n1c.

**Comment by Tachy0n1c** [comment]
@PeterJCLaw Thank you! I confirm I've now printed 210 B&W single-sided copies, which I'll leave at The Cube tomorrow (Friday).

**Comment by PeterJCLaw** [comment]
Awesome, thanks :)
