### ISSUE TITLE
Print helpdesk documents

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#760]
Helpdesk will need a number of documents:

- [x] Rulebook
- [x] Helpdesk instructions
- [ ] Kit swap form
- [ ] Venue map
- [x] https://github.com/srobo/tasks/issues/830

This list may need adding to.

### Original

[comp/pits/helpdesk/print-documents](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/helpdesk/print-documents.yaml)

**Comment by PeterJCLaw** [comment]
@RealOrangeOne looks like the formatting on this one didn't quite work :(

**Comment by PeterJCLaw** [comment]
I assume this happened.
