### ISSUE TITLE
Plan overnight kit & battery loans at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#761]
Many teams will want to take their kits home with them overnight at the competition, in order to work on them. We usually require these teams to fill in some paperwork to record this, in order to ensure we know which team have done this and which parts they have taken with them. The latter is important as they will likely not be taking with them the same batteries as they had for the rest of the year and so the inventory will not track this loan.
See https://studentrobotics.org/runbook/kit/event-operations/overnight-battery-loan/ for details.

### Original

[comp/pits/overnight-loans](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/overnight-loans.yaml)

**Comment by PeterJCLaw** [comment]
Discussion from this evening:

- have a single list at helpdesk which is populated by helpdesk with teams that are leant a battery charger & batteries overnight
- teams must check out and into the venue, so we can grab them at check in on the Sunday morning and get the batteries & charger over night

- mention the check in & out procedure (generically) on the website, at reception and in the welcome talk

@Adimote can you cross link this with details of the check-in/out process & when we'll be telling the teams about it. (likely also impacts #879 cc @RealOrangeOne)

**Comment by RealOrangeOne** [comment]
Thanks, updated #879

**Comment by raccube** [comment]
Have printed 3 copies of the form.

**Comment by prophile** [comment]
This happened.
