### ISSUE TITLE
Organise high-vis jackets for the teams at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#763]
At the competition we use high-vis jackets to signify that a robot has passed the safety checks and which member of the team is responsible for the robot.
As only a team member wearing the high-vis jacket may enter the staging area, this keeps the number of people in the staging area low while making it exceedingly clear who to talk to about each robot.
We need to ensure that
 - we have enough jackets for all the teams
 - the jackets are marked clearly with the teams' TLAs (both front and back)

Lamited printouts safety-pinned to the jackets are usually a good way to add the TLAs.

### Original

[comp/safety/high-vis](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/high-vis.yaml)

### Dependencies

 * #734 Pre competition storage trip

**Comment by RealOrangeOne** [comment]
There are definitely high-viz in the container, and definitely enough.

We just need the TLA cards, and some way of attaching them.

**Comment by PeterJCLaw** [comment]
Are we sure there are enough unmarked high-viz jackets in the container? From memory quite a lot of them have been scrawled on by teams in the past.

**Comment by WillB97** [comment]
The hi-viz jackets are now being tracked in https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing

**Comment by RealOrangeOne** [comment]
The high-viz in the container are clean, however many still have the labels on (paper). Tape looks to work fine for attaching, and some have safety pins. We should reuse the safety pins, and tape the rest.

We'll need some paperwork to stick to the back

**Comment by Scarzy** [comment]
Paperwork is already designed and in the shared drive

**Comment by RealOrangeOne** [comment]
https://docs.google.com/presentation/d/1UoWSGmfbMRwFzQ5nrxfIRtJpkb-Lh8dxQWccp9LFO-A/edit?usp=sharing

In that case, I think this is done, we just need to print the labels and attach them to the hi-viz in the container.

**Comment by WillB97** [comment]
> The high-viz in the container are clean, however many still have the labels on (paper). Tape looks to work fine for attaching, and some have safety pins. We should reuse the safety pins, and tape the rest.

What kind of tape?

**Comment by Scarzy** [comment]
> What kind of tape?

If memory from 3 years ago serves, it was some kind of duck. I think white.
(So maybe a swan?)

**Comment by RealOrangeOne** [comment]
For 2019, it looked like it was more a canvas-y tape:

<details>

![IMG_20220408_160703](https://user-images.githubusercontent.com/6527489/162567007-5f7f8776-947b-402c-94b6-c9b13294ef20.jpg)

</details>
