### ISSUE TITLE
Print all the things for SR2022

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#765]
We need various stuff printing before we get to the venue.

### Original

[comp/printing](https://github.com/srobo/recurring-tasks/blob/master/comp/printing.yaml)

### Dependencies

 * #745 Print the flyers for the SR2022 Competition
 * #748 Print spare MCFs for visitors
 * #754 Print arena labels for SR2022
 * #755 Organise markers for the arena
 * #757 Print score entry forms for marshals
 * #759 Kit handback arrangement
 * #760 Print helpdesk documents
 * #761 Plan overnight kit & battery loans at the competition
 * #762 Get envelopes & card for the prize ceremony
 * #763 Organise high-vis jackets for the teams at the competition
 * #764 Have name badges for volunteers at the competition
 * #820 Setup battery charging station
 * #912 Print Volunteer sign-in form for Reception
 * #913 Print Reception documentation

**Comment by WillB97** [comment]
Should include all of these https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit#gid=1181706331&fvid=959286077

**Comment by antoinepetty** [comment]
A printed copy of the volunteer schedule and some key docs might be helpful - I'm thinking safeguarding and battery charging

**Comment by RealOrangeOne** [comment]
I will print everything which doesn't need to be done in bulk, which is:

- Spare MCFs
- Parking permits
- Score entry sheets

**Comment by WillB97** [comment]
We also need to print the eduroam accounts (#899) and a table to record which account number went to who.

**Comment by RealOrangeOne** [comment]
Much of the non-bulk printing has now been done, and the freight list updated.

@Tachy0n1c has offered to do the bulk printing using Southampton printers. I'll liaise around what needs printing.

**Comment by WillB97** [comment]
Can we get a few copies of the freight list and the setup schedule ("setup plain" tab).

**Comment by WillB97** [comment]
Can I also get 2-3 copies of the venue plan, can be double-sided.
[Venue_map.pdf](https://github.com/srobo/tasks/files/8521370/Venue_map.pdf)

**Comment by Tachy0n1c** [comment]
@RealOrangeOne kindly sent me the list of documents I needed to print, and I've printed everything from his emails:
- "Hi-viz labels": 1 copy, totalling 26 pages (single side), B&W
- "[Media consent form](https://studentrobotics.org/resources/sr2022/media-consent.pdf)": 100 copies (single sided), B&W
- "Kit contents checklist": 26 copies (single sided), B&W
- "Kit return form": 26 copies (single sided), B&W
- "Missing kit form": 26 copies (single sided), B&W
- "Incident management procedure": 10 copies (double sided), B&W
- "Marathon Parking Permit": 50 copies (single sided), B&W

I also printed 3 colour double-sided copies of the revised venue map as requested by @WillB97. These were all left in The Cube on Thursday.
