### ISSUE TITLE
Safety check the SR2022 robots

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#768]
We need to inspect all the robots to ensure they are safe.
The inspectors will want a list of the teams' first matches so they can visit them in order.

### Original

[comp/safety/check-robots](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/check-robots.yaml)

### Dependencies

 * #763 Organise high-vis jackets for the teams at the competition

**Comment by WillB97** [comment]
We should also verify that electromagnets are not energised before the start button is pressed.

**Comment by PeterJCLaw** [comment]
> We should also verify that electromagnets are not energised before the start button is pressed.

Why? It's not clear to me that an electromagnet being energised inherently unsafe.

**Comment by Scarzy** [comment]
My feeling on this is that so long as they are turned off when the power button is pressed to turn off the robot then this isn't an issue.

It being turned on ahead of time might inconvenience the person carrying it, but I don't feel it's a safety issue any more than the servos homing before the start button is pressed would be

**Comment by Scarzy** [comment]
I've created a form for recording these checks in the competition shared drive at SR2022/safety/Safety Check form

All teams, including those who have dropped out, are included

**Comment by PeterJCLaw** [comment]
I believe this happened.
