### ISSUE TITLE
Plan Event Video Feeds

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#77]
We would like to stream the event, probably through SUSU TV. This will require us to liaise with SUSU TV (or whoever else will be streaming the event) and work out what / where we want to stream.

**Comment by PeterJCLaw** [comment]
@mildlyincompetent has there been any progress on this? It's blocking a bunch of other things (not just #162, but also the other things which we'd do to support this such as #172 and #99/#100), so it would be good to have this sorted (or conclude that we're not doing it) soon.

**Comment by trickeydan** [comment]
This needs to be organised ASAP due to blocking, email is Ben McQuigg `bm7g16@soton.ac.uk`

@mildlyincompetent

**Comment by Tyler-Ward** [comment]
Although mentioned on slack the current status for reference: SUSU tv have been contacted but are not sure on availability we are waiting for them to get back to us to confirm.

**Comment by Tyler-Ward** [comment]
SUSU TV are unable to provide a stream, new plan inbound.

**Comment by Tyler-Ward** [comment]
This has now been split into separate tickets.
