### ISSUE TITLE
Update and publish risk assessments for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#770]
The risk assessment for the competition needs updating for SR2022 and publishing to schools.

### Original

[comp/safety/risk-assessments](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/risk-assessments.yaml)

**Comment by RealOrangeOne** [comment]
The previous risk assessment is here: https://github.com/srobo/risk-assessments/blob/master/competition.tex. And helpfully is based on a previous Southampton competition.

@Scarzy is this one for you? Just had a team enquire about them, which reminded me.

**Comment by Scarzy** [comment]
Pending details from the venue as to their own risk assessments

**Comment by Scarzy** [comment]
Received and filtering through the response from the venue

**Comment by Scarzy** [comment]
https://github.com/srobo/risk-assessments/pull/8

**Comment by Scarzy** [comment]
These are now updated. Needs publishing.

**Comment by RealOrangeOne** [comment]
How do you imagine these being published? We can simply put a link to them on the website? I'm not sure we necessarily need to email them out to team supervisors explicitly?

**Comment by Scarzy** [comment]
Here, perhaps: https://github.com/srobo/website/pull/408

> I'm not sure we necessarily need to email them out to team supervisors explicitly?

If they had asked, we should, however it is now far too late for them to be able to receive them

**Comment by Scarzy** [comment]
Merged, so this is done
