### ISSUE TITLE
Prepare an incident response plan

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#771]
We should ensure that our incident response plans are current & applicable to the selected venue; we should update them as needed.

### Original

[comp/safety/incident-plan](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/incident-plan.yaml)

### Dependencies

 * #714 Find and book venue for SR2022
 * #769 Have a means to record an incident

**Comment by Scarzy** [comment]
I've gone over this, and pending confirmation of where radios are going to be, it should now be ok.

**Comment by Scarzy** [comment]
Waiting on https://github.com/srobo/runbook/pull/142 passing circleci checks

**Comment by RealOrangeOne** [comment]
https://github.com/srobo/runbook/pull/142 CI has passed and been merged - is this now complete?

**Comment by Scarzy** [comment]
No, stalled on needing details from the venue and details on how radios are distributed, both of which may provoke further update.

**Comment by Scarzy** [comment]
Update on radios received. Now just waiting on the venue.

**Comment by Scarzy** [comment]
Update received, working through it

**Comment by Scarzy** [comment]
No further update is required.

Dependency #769 is still open simply to ensure the book gets to the event, but this task I'm going to close

**Comment by PeterJCLaw** [comment]
@Scarzy was that email reply on the right thread? This task is for last year (SR2022).
