### ISSUE TITLE
Ensure that we will have fire extinguishers at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#772]
We should ensure that venue has suffucient fire extinguishers for our needs and that the correct type of extinguisher is in the correct location.
This includes but is not limited to having powder fire extinguishers for LiPo batteries.

### Original

[comp/safety/ensure-fire-extinguishers-are-present](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/ensure-fire-extinguishers-are-present.yaml)

**Comment by Scarzy** [comment]
This task is not our responsibility. This is on the venue.

This task should be removed from the re-occuring tasks.
