### ISSUE TITLE
[Meta] Ensure the SR2022 competition is safe

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#773]
The SR2022 competition event must be safe.

### Original

[comp/safety/main](https://github.com/srobo/recurring-tasks/blob/master/comp/safety/main.yaml)

### Dependencies

 * #732 Organise cable protectors
 * #763 Organise high-vis jackets for the teams at the competition
 * #766 Arrange first aid presence at the competition
 * #767 Plan for disposal of sad batteries
 * #768 Safety check the SR2022 robots
 * #769 Have a means to record an incident
 * #770 Update and publish risk assessments for the competition
 * #771 Prepare an incident response plan
 * #772 Ensure that we will have fire extinguishers at the competition
 * #895 Update COVID guidance

**Comment by WillB97** [comment]
All the prep here seems done.
