### ISSUE TITLE
Organise tinker time

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#775]
On the morning of the first day, teams are given a chance to tinker with their robots in the arenas. We're going to use a whiteboard to schedule this. Someone will be near the arena and will write teams into 15 minute time slots. Requires 1 Blueshirt to manage scheduling and changover.
Also requires that there is some kind of PA system that is audible in the Arena.

### Original

[comp/tinker-time](https://github.com/srobo/recurring-tasks/blob/master/comp/tinker-time.yaml)

### Dependencies

 * #720 Sort out sound system for the competition
 * #774 Arrange a whiteboard at the competition

**Comment by RealOrangeOne** [comment]
This tinker time booking will need to cover schedules for both the main arena and test arena.

I've started working on a document to track this for the main arena, complete with times https://docs.google.com/document/d/14c5qSLTlS492ZZnN9wvZi0tYxVic7uqubH3V-HmhmkU/edit?usp=sharing. The test arena one will be similar, just with many many more slots.

RFC: Should we allow longer slots for the test arena?

**Comment by Scarzy** [comment]
I suggest for the test arena we just run 4 stop watches at ~15 minutes, and
when it hits the limit if there is a new team waiting we turf out the old
team, if there isn't a new team waiting we let them stay until a new one
shows up.

**Comment by RealOrangeOne** [comment]
I like this idea. Given I suspect it's not going to be as high contention as regular tinker time slots, this makes things a lot easier.

We'll probably need a way to write record entry time, rather than 4 stopwatches (which we don't have), but I think this ad-hoc process is definitely much better!

**Comment by RealOrangeOne** [comment]
I've created a similar document for the test arena tinker time, simply to help keep track of teams' comings and goings in the test arena.

https://docs.google.com/document/d/1xWYztISzNWikzQK0PI3CBQt5xS_UblFT02Q4-JXOgQ4/edit?usp=sharing

I'm fairly happy with these documents / processes, but will leave the issue open for review.

**Comment by samjmartin04** [comment]
Both of these tinker time files look good.

**Comment by RealOrangeOne** [comment]
Sheets have been printed
