### ISSUE TITLE
Create SR2022 game score format

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#778]
The format for the game data YAML files which record match outcomes needs to be designed.
There is guidance for how to do this for SRComp at https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#configure-game-scoring

### Original

[comp/game/score-format](https://github.com/srobo/recurring-tasks/blob/master/comp/game/score-format.yaml)

**Comment by sedders123** [comment]
In progress at https://github.com/srobo/sr2022-comp/pull/2
