### ISSUE TITLE
Write scoring scripts for the SR2022 game

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#779]
The scoring script provides automatic computation of the scores based on the data input from the score sheets.
See https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#implement-scorepy for details.

### Original

[comp/game/score-script](https://github.com/srobo/recurring-tasks/blob/master/comp/game/score-script.yaml)

### Dependencies

 * #778 Create SR2022 game score format

**Comment by sedders123** [comment]
In progress at https://github.com/srobo/sr2022-comp/pull/2
