### ISSUE TITLE
Competition Logistics

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#78]
We have a lot of stuff that needs moving in and out of the competition venue, we need to work out and plan how this will be done.

**Comment by RealOrangeOne** [comment]
Many volunteers have cars, we should use this to the fullest ability possible!

**Comment by trickeydan** [comment]
Given that #185 is unlikely to be completed now, we need to consider how this will work and if we need to book other areas of the university

**Comment by trickeydan** [comment]
We also need to consider if we want to borrow any equipment, e.g ECS trolley.

**Comment by Tyler-Ward** [comment]
I have split of several sub tasks from this to turn them in to more manageable chunks.

**Comment by Tyler-Ward** [comment]
see https://docs.google.com/spreadsheets/d/13jDdRkZxgKdROVau9VaZiKZbiDV34_rlcZhWcpzQZO8/edit#gid=0 for a list of kit needed at each location we can use this to help with #205 and #207 and #208

**Comment by WillB97** [comment]
List has been filled
