### ISSUE TITLE
Prepare the Compbox

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#781]
We have a Raspberry Pi 3 (part code `srL1CX`) which is typically used as the compbox.
This task is to prepare the micro SD card and validate that the Pi itself functions, so that deployment in the venue is as simple as plugging the Pi into the competition network.
The steps here are usually:
1. Flash the SD card with the latest Raspbian stable
2. Clone https://github.com/PeterJCLaw/srcomp-puppet onto the Pi
3. Run `srcomp-puppet/scripts/install` on the Pi
4. Use the `scripts/check-pages.py` to validate from outside the Pi that the expected pages can be reached

### Original

[comp/ops/prepare-compbox](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/prepare-compbox.yaml)

### Dependencies

 * #734 Pre competition storage trip

**Comment by PeterJCLaw** [comment]
This afternoon I've done a fresh deploy of https://github.com/PeterJCLaw/srcomp-puppet/ onto my own Pi3 using the latest Raspberry Pi OS Lite (version from 2022-01-28) and that worked fine (mostly relying on the check script in the puppet repo). I've done some small updates too, so we're on the latest NodeJS now.

Still outstanding here is preparing the actual Pi, though that should now be something that's very straightforward to do.

**Comment by sedders123** [comment]
I have collected the box of Pis from Jake (https://github.com/srobo/inventory/commit/c39448020013b32c63dd68c48c91a6e755ae3bae) so can look at getting this set up

**Comment by sedders123** [comment]
This has been done
