### ISSUE TITLE
Work out layout of teams at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#782]
The layout of team pits in the venue needs to be worked out. There are constraints such as keeping teams under the same teacher close together, and keeping overseas teams near each other.
This task covers both the placement of the pits within the venue and the allocation of specific teams to pits.
Ideally the pits should be internally numbered and kept with an ordered list of teams which fit to those locations. This helps ensure that the compstate can easily be kept in step with the physical locations of each team.

### Original

[comp/pits/layout](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/layout.yaml)

### Dependencies

 * #725 Prepare a layout of the competition

**Comment by RealOrangeOne** [comment]
Blocked on knowing which teams have access requirements.

**Comment by sedders123** [comment]
This was done in https://github.com/srobo/comp-floorplans/pull/13
