### ISSUE TITLE
[Meta] Prepare the SR2022 Compstate

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#784]
The competition software has state about the competition which is used to drive the matches, live displays of scores (etc.) both within the venue on the website.
This task is to create the initial state for the competition; see https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#create-a-compstate and https://github.com/search?q=topic%3Acompstate+org%3Asrobo&type=Repositories.

### Original

[comp/ops/compstate](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/compstate.yaml)

### Dependencies

 * #725 Prepare a layout of the competition
 * #743 Work out the day schedules for the competition
 * #776 Design the SR2022 knockouts
 * #777 Schedule the league matches
 * #778 Create SR2022 game score format
 * #779 Write scoring scripts for the SR2022 game
 * #780 Organise shepherding
 * #781 Prepare the Compbox
 * #782 Work out layout of teams at the competition
 * #783 Deploy a public compbox

**Comment by sedders123** [comment]
This is now in progress https://github.com/srobo/sr2022-comp

**Comment by PeterJCLaw** [comment]
Closing as this has been deployed & used. There may be further updates, but that's expected anyway.
