### ISSUE TITLE
Publish day schedule on website

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#785]
The schedule for the days needs to be published on the website so people know what's going on.

### Original

[comp/website/schedule-day](https://github.com/srobo/recurring-tasks/blob/master/comp/website/schedule-day.yaml)

### Dependencies

 * #743 Work out the day schedules for the competition

**Comment by antoinepetty** [comment]
Blocked on confirmation of https://github.com/srobo/tasks/issues/743
