### ISSUE TITLE
Plan video feeds

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#787]
The livestream will need to have a few different camera feeds to show different parts of the venue

- Arena (likely multiple) 
- Hosts (who may be different to commentators) 
- Stage (only needed for prize giving)

### Original

[comp/livestream/plan-video-feeds](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/plan-video-feeds.yaml)

**Comment by RealOrangeOne** [comment]
Current plan:

- Hosts (webcam)
- Arena top-down (skycam)
- Stage for prize-giving (DSLR)

We will likely also have an additional arena feed from the side, likely powered by a webcam. If we do, it is likely better to prioritise a better-quality webcam for this, as it will be full screen, whereas hosts won't be.

**Comment by antonnikitin97** [comment]
Hi @RealOrangeOne , I can provide a DSLR for the cause if it's still needed? It's a Nikon D3200.

**Comment by RealOrangeOne** [comment]
Please do! Worst case it's another camera to take photos of the event. Best case it's a life-saver!
