### ISSUE TITLE
Organise hardware to run livestream

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#788]
This ticket relates to providing the actual machine that will be used for the livestream.
Requirements:
- Video mixer PC (With dedicated GPU, capable of running OBS)
- 2× HDMI capture card
- 2× preview monitors
- 2× cameras (depending on feed plan)
- Audio mixers

### Original

[comp/livestream/hardware](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/hardware.yaml)

### Dependencies

 * #787 Plan video feeds

**Comment by Tyler-Ward** [comment]
I don't believe I can borrow all the kit we used previously I have therefore broken down the minimum requirements and then the extra features we have added in previous years. If we have more kit than this we can look at adding other features

### Minimum requirements

This will give us a single arena feed with both play by play and flavour commentary.

* Video mixer PC (preferably with a dedicated GPU)
* 1x arena capture device (preferably a gopro or similar wide angle camera and a hdmi capture card but a webcam could be used if needed)
* 1* preview monitor
* 1* Audio input from arena presenters (any standard capture card should cover this on the livestream end)
* 1* presenter camera (a good webcam will be fine for this)
* 2* headphones for presenters

### Streaming Skycam upgrade

Gives us an overhead view of the arena (has also been found to be useful for play by play commentators in the past although the smaller arena may change this)

* 1* gopro or similar wide angle camera
* 1* truss mounting setup
* 1* HDMI capture card
* 1* cable to connect camera to PC

### Awards capture

* 1* camera for pointing at the stage (can reuse a hdmi input from one of the other cameras)

### Production upgrades

All of these are largely independent so we don't need all of them

* 1x second preview monitor (used for production preview display)
* 1x small mixing desk
* 1x good presenter microphone
* 1x macro keypad

**Comment by RealOrangeOne** [comment]
My laptop has a GTX 950 in, which may be enough for this - I'll try and do some testing.

The camera of mine we've used for the top-down arena camera, I can provide again. I have an HDMI cable for it, but will need some way of extending it (venue may have this). Because it's cylindrical, the mounting can be done simply with tape.

I can provide a Logitech C920 for presenters, as well as a [Q2U](https://www.amazon.co.uk/Samson-SAQ2U-Microphone-Recording-Pack/dp/B001R747SG) with mic arm and required cables. It's a dynamic mic rather than condenser, but _hopefully_ that shouldn't be much of a problem RE ambient noise. I also have a Blue Yeti which may be more appropriate.

I have one of those cheap USB capture devices, capable of 1080@30 IIRC, which should be useful for something.

@WillB97 IIRC you mentioned that an audio mixing desk can be provide by the venue. Would that also function as a digital input, or would we need some way to feed that into the livestream?

We should have a few spare monitors in the container, which could be used for preview.

My primary concerns for the kit are around the input captures. Sourcing extra cameras, monitors and mics is generally _reasonably_ simple, however audio / video capture is much more niche.

**Comment by WillB97** [comment]
The sound desk will be analog only so it will need an audio interface to connect to the computer.

> The camera of mine we've used for the top-down arena camera, I can provide again. I have an HDMI cable for it, but will need some way of extending it (venue may have this). Because it's cylindrical, the mounting can be done simply with tape.

We will need to come up with a better solution to mount the camera so that #669 can be satisfied that that it does not pose a risk of falling objects. This likely involves clamping it and adding a secondary safety bond.

**Comment by Tyler-Ward** [comment]
Call for additional hardware
* A dslr with clean output to use to film the awards (can be used as a camera the rest of the time)
* macro keypad or similar
* audio capture cards
* any other kit that people think is useful let us know as it may let us improve things

**Comment by RealOrangeOne** [comment]
Turns out my laptop has a 960M in it, which is definitely more powerful than I thought. I've done some testing with OBS, pulling in 3 different camera feeds in the same scene, and it's able to output 1080@60 with around 40% GPU usage, and 20% CPU usage. Given that, I'm pretty confident with the hardware.

It runs windows now, as that seems to support the capture cards we have more reliably, as well as is likely more familiar to those on livestream, and hopefully minimises the chances of technical issues on the day.

I intend to do some more testing around USB bus bandwidth, as that's something which has bitten us in previous years.

**Comment by Tyler-Ward** [comment]
We should also have suitable storage attached to the machine in order to save a local copy of the stream. A high capacity SSD would be preferable if someone has one available

**Comment by RealOrangeOne** [comment]
The laptop has a 750GB drive in it, which is mostly empty, and should be ample for archival storage. It's mechanical, but for this I don't think that matters.

**Comment by RealOrangeOne** [comment]
We have a plan to acquire everything we need for the livestream. The freight list has been updated with items and owners.
