### ISSUE TITLE
Organise livestream scenes

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#789]
The livestream requires a number of different scenes and views, made up of static images, video feeds, overlays etc.
Most of the assets have already been created, but some may require updating or new ones created
See https://studentrobotics.org/runbook/competition/livestream/scenes/.

### Original

[comp/livestream/configure-scenes](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/configure-scenes.yaml)

### Dependencies

 * #787 Plan video feeds

**Comment by Tyler-Ward** [comment]
Do we think it would be useful to have a detailed league score view that the presenters can bring up between matches if they want to discuss scores. If so might be a second page that can be added to the overlay.

**Comment by RealOrangeOne** [comment]
During the virtual competition, we used an additional scene in OBS with the competition website embedded for things like this: Knockout table, league table etc. The ability to manually switch is very useful, and also keeps the overlay being exactly that: an overlay.

**Comment by Tyler-Ward** [comment]
https://github.com/srobo/tasks/issues/305 for ideas from the last in person livestream

**Comment by Tyler-Ward** [comment]
per https://github.com/srobo/tasks/issues/791 the plan is to start at 10:45 so intro scenes should take account of that

**Comment by Tyler-Ward** [comment]
on Sunday we will need to allocate some volunteers to handle vehicle movements into campus due to the marathon

**Comment by Tyler-Ward** [comment]
Sponsor image slides should be the same as the banner

**Comment by RealOrangeOne** [comment]
I've initialized the OBS scenes based on the applicable ones from [the runbook](https://studentrobotics.org/runbook/competition/livestream/scenes/).

Some more will need creating, but those are blocked on having the camera feeds. We'll likely want to do some polishing to scenes anyway on the day, so I'm not concerned about this.

**Comment by Tyler-Ward** [comment]
I have added the artwork for this years waiting slides to https://drive.google.com/drive/u/3/folders/1vGwv0RUQoDanH5sptwoDYKBEGEGr5Br5

**Comment by PeterJCLaw** [comment]
@Tyler-Ward is the source code for the livestream images around somewhere? There are some changes we need to make for tomorrow following from https://github.com/srobo/website/pull/411.

**Comment by Tyler-Ward** [comment]
The svg is in Google drive

**Comment by PeterJCLaw** [comment]
Ah, I'd interpreted that file as just being for the intermission slide. I'll rename it to be clearer.

**Comment by PeterJCLaw** [comment]
Have updated the source and generated a new image for the schedule change.
