### ISSUE TITLE
Identify Food And Drink Destinations

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#79]
While we aren't explicitly providing food and drink facilities, we should still work out where competitors can go to obtain food and drink so that we may communicate this to them.

May be worth talking to SUSU to see if they would be interested in opening the SUSU shop considering the considerable numbers of competitors we will have.

**Comment by JennyLouise** [comment]
I made a little mymaps map with a "Food and Drink" layer and added a few places nearby, feel free to add and change stuff.
https://drive.google.com/open?id=1qoHe63RdrX2YHUXuJjmBDcyFmy-L65G7&usp=sharing

**Comment by RealOrangeOne** [comment]
@Adimote created https://goo.gl/yYlfs5 for a tech day a while back

**Comment by JennyLouise** [comment]
Nice. Do we know the opening hours for uni cafes over easter, or should we email hospitality and check that?

**Comment by jcwilliamson** [comment]
[Restaurants.txt](https://github.com/srobo/tasks/files/2948413/Restaurants.txt)

This is a somewhat comprehensive list of a lot of the restaurants in town, categorized by the location and then type of food.

**Comment by jcwilliamson** [comment]
https://drive.google.com/open?id=1hjl-4NoiBrHLdAMWKlgyWYGxnRctPdOV&usp=sharing

**Comment by trickeydan** [comment]
This has been done
