### ISSUE TITLE
[Meta] Arrange a live stream from the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#790]
We should have a live stream of the competition.
We'll need to work out:
 - what hardware & sofware will be used to drive the stream (both cameras and
 mixing desk/driver computer)
 - where the cameras for the stream should go

### Original

[comp/livestream/main](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/main.yaml)

### Dependencies

 * #723 Have a competition network
 * #786 Have livestream training sessions
 * #788 Organise hardware to run livestream
 * #789 Organise livestream scenes

**Comment by PeterJCLaw** [comment]
The livestream is happening.
