### ISSUE TITLE
Put stream on website

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#791]
The live stream needs to be linked or embedded from the website.

### Original

[comp/website/livestream](https://github.com/srobo/recurring-tasks/blob/master/comp/website/livestream.yaml)

### Dependencies

 * #790 Arrange a live stream from the competition

**Comment by antoinepetty** [comment]
Waiting on https://github.com/srobo/tasks/issues/743 to confirm when the stream should start

**Comment by sedders123** [comment]
Proposing we start at 10:45 if day schedule doesn't change from its original proposal

**Comment by antoinepetty** [comment]
See https://github.com/srobo/competition-website/pull/29 and https://github.com/srobo/website/pull/392

**Comment by antoinepetty** [comment]
Those were merged
