### ISSUE TITLE
Publish SR2022 layout maps

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#794]
We should have maps of the layout for reference. This should include maps with team locations.

### Original

[comp/venue/layout-map](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/layout-map.yaml)

### Dependencies

 * #725 Prepare a layout of the competition
 * #782 Work out layout of teams at the competition

**Comment by sedders123** [comment]
This is done floor plans for the venue can be found https://github.com/srobo/comp-floorplans

**Comment by PeterJCLaw** [comment]
Are these on the website? That's kinda what this ticket is about.

**Comment by PeterJCLaw** [comment]
@sedders123 where can we find the map SVG like the one included in the booklet? Would be great to get a copy of that onto the website.

**Comment by sedders123** [comment]
The SVG can now be found in [a PR](https://github.com/srobo/comp-floorplans/pull/15) on the comp-floorplans repo
