### ISSUE TITLE
Put directions to the venue on the website

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#795]
To make things easier for teams, we should publish a map and some directions to the venue on the website.

### Original

[comp/website/directions](https://github.com/srobo/recurring-tasks/blob/master/comp/website/directions.yaml)

### Dependencies

 * #714 Find and book venue for SR2022

**Comment by sedders123** [comment]
Already live on the event page https://studentrobotics.org/events/sr2022/competition/
