### ISSUE TITLE
[Meta] Update the website for the live SR2022 competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#796]
There are website alterations to be made to enable its use live at the competition.

### Original

[comp/website/main](https://github.com/srobo/recurring-tasks/blob/master/comp/website/main.yaml)

### Dependencies

 * #715 Announce the competition
 * #783 Deploy a public compbox
 * #784 Prepare the SR2022 Compstate
 * #785 Publish day schedule on website
 * #791 Put stream on website
 * #792 Switch the website (proxy) to Competition Live mode
 * #793 Uprate the competitor-services server _before_ the competition starts
 * #794 Publish SR2022 layout maps
 * #795 Put directions to the venue on the website

**Comment by PeterJCLaw** [comment]
@sedders123 @antoinepetty just wondering if you're planning to do a pass over the competition website homepage (i.e: https://studentrobotics.org/comp/) to streamline it? The current state is somewhat at the cobbled together developer-art stage.

**Comment by antoinepetty** [comment]
It would be useful to have our regular homepage "about us" kind of material available during the competition. I'll put this in the agenda + a general review

**Comment by Scarzy** [comment]
I'll second that. Potential sponsors at the event will still need to access
the sponsor material, and potential new teams that see us on social media
etc. will still want to access the details to allow them to sign up for
next year whilst still excited.

They can currently be accessed from the menu, but it'd be nice to have them
more visible, as the tiny 3 bar menu icon will probably be easy to miss.

**Comment by PeterJCLaw** [comment]
@antoinepetty did anything come out of the marketing meeting on this? Is there a concrete proposal for improvements to the competition mode homepage?

**Comment by antoinepetty** [comment]
The notes we have from the meeting:
- Keep the hero image but replace bottom text with "Live from Southampton University"
- Put competition links where our normal "latest post" etc bits are

I don't think we made further progress on it though. The general idea was to base it on our new regular homepage and have the competition links/stream there too

**Comment by PeterJCLaw** [comment]
> * Keep the hero image but replace bottom text with "Live from Southampton University"

Is the location really important? We've struggled in the past to shake off the public perception that SR is run by Southampton Uni (rather than being an independent entity; something I felt we achieved in about 2016/2017), so I think we need to be really clear/careful when mentioning them.

> * Put competition links where our normal "latest post" etc bits are

That's kinda where they are? Unless you're suggesting keeping the whole of the top of the page?

**Comment by PeterJCLaw** [comment]
> Unless you're suggesting keeping the whole of the top of the page?

I can't read. This is what you're suggesting. I think this pushes the actual competition stuff too far down. On desktop the hero image and grey links bar occupy the top 60% or so of the page, which doesn't leave a lot of space for the competition stuff before the fold.

**Comment by PeterJCLaw** [comment]
Ok, I've had a go at this in https://github.com/srobo/competition-website/pull/32; see screenshots there.
