### ISSUE TITLE
Get stationery for scoring the SR2022 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#797]
Once printed we need something to store the score entry forms in (as there will be a couple of hundred sheets).
We also need folders to store the completed sheets in. Ideally these would be lever-arch style with dividers to separate chunks of matches. Previously the sheets were grouped into batches of four match slots (eight games; 16 sheets) at twenty dividers (80 match slots) per folder. This seems a reasonable rate to use again.
Unless they are pre-punched, the score-entry people will want a decent hole-punch for punching the entry forms before putting them in the folders.
The marshals will also want clipboards and pens to use to fill out the score sheets. We should have some clipboards in storage from previous years.

### Original

[comp/game/scoring-stationery](https://github.com/srobo/recurring-tasks/blob/master/comp/game/scoring-stationery.yaml)

### Dependencies

 * #734 Pre competition storage trip

**Comment by PeterJCLaw** [comment]
There miiight even be some lever-arch or box files in the container that we could re-use. One to check on #734.
If not, these should be easy enough to pick up from amazon or a poundland or similar.

**Comment by WillB97** [comment]
The clipboards and box files are now being tracked in https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing

**Comment by sedders123** [comment]
The sheet suggests we have a Box File in the container but I can't see any in the inventory (though I may be missing something obvious!) and I don't think they were checked in any of the storage trips yet (at least I can't see any mention on #734 about them) just want to double check we definitely have one :)

**Comment by WillB97** [comment]
Jake thought there was one. He's intending to check items marked on the freight list in #734.

**Comment by RealOrangeOne** [comment]
Box files are not inventorised items. I purchased ~5 for SR2019, and I am around 99% sure they are in there.

However, one of the things I don't recall seeing in the container is pens, so we may need to purchase those.Will be checked as part of #734.

**Comment by RealOrangeOne** [comment]
Still to confirm:
- A4 paper
- Pens
- Box files

Pens are probably in the container (checked as part of #734)

**Comment by RealOrangeOne** [comment]
We have pens, box files, and _some_ paper. To be safe, we should get another pack of paper.

**Comment by RealOrangeOne** [comment]
[500 sheets](https://www.tesco.com/groceries/en-GB/products/253580351) is ~£3.

Happy to purchase pending sign-off

**Comment by Adimote** [comment]
Purchase approved

**Comment by RealOrangeOne** [comment]
I bought 2 packs of paper, thus 1000 sheets. It was only £5.90. Plus the stash we have in the container, that should be more than enough.

Given we already have everything else, this is done.
