### ISSUE TITLE
Collect blue shirts for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#798]
We may need more.

### Original

[comp/volunteers/blue-shirts](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/blue-shirts.yaml)

**Comment by RealOrangeOne** [comment]
I have our entire supply of spares. I will count these someday.

**Comment by sedders123** [comment]
We need to order new shirts because of new sponsors

**Comment by antoinepetty** [comment]
We are ordering Gildan Royal Blue Unisex Heavy Cotton t-shirts with this design https://github.com/srobo/promotional-material/tree/master/shirts/SR2022

**Comment by WillB97** [comment]
Once this is done can you update #902

**Comment by antoinepetty** [comment]
These are printed, awaiting pickup. Will pick them up on the Thursday setup

**Comment by antoinepetty** [comment]
Picked up and look good
