### ISSUE TITLE
Volunteer Schedule

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#80]
We need to plan schedules for volunteers at the event, depending on roles required and volunteer ability. Blocking on #73.

Document with the schedule: https://docs.google.com/spreadsheets/d/1AlRaHS50rYIRt8TZ0rxRZQ_MhG7j584JKETPd5zZMeI/edit?usp=sharing

**Comment by Tyler-Ward** [comment]
relies on #168

**Comment by Tyler-Ward** [comment]
I have created a quick template for planning this at https://docs.google.com/spreadsheets/d/1I-rmo0lgdR2t4zCgqpjr5J_sAtkC427vVwoUH_USHWA/edit#gid=0 we now need to fill in roles

**Comment by Adimote** [comment]
Apologies for the duplicate effort, but I've created a copy of the sheet I created for last years' competition.

I think we should use it because it has a lot of useful features:
- Creates a table of tasks ordered by volunteers, so the volunteers get an easily readable schedule
- Calculates how free each person is, thus creating a priority list of who should be assigned if there's a new task available.

**Comment by Adimote** [comment]
We discussed this offline, We'll be using my sheet: https://docs.google.com/spreadsheets/d/1AlRaHS50rYIRt8TZ0rxRZQ_MhG7j584JKETPd5zZMeI/edit?usp=sharing (Restricted to the SR org because of PII)

**Comment by Adimote** [comment]
@Tyler-Ward What time do we need the photography studio to be open from/to?

**Comment by Tyler-Ward** [comment]
Speed can be a bit variable for the team photos. Given the number of teams I would suggest opening it when matches start on the Sunday so it will be done before the knockouts start.

**Comment by Adimote** [comment]
@Tyler-Ward Is it okay if I schedule it for Saturday? Mainly because I didn't spot this reponse until just now, and I've already allocated people for it on Saturday

**Comment by Tyler-Ward** [comment]
Saturday should be fine but we should push back the start as teams will likely not be ready for the photos early on the Saturday.

**Comment by Adimote** [comment]
I think it's worth having people on it during tinker time. I expect most robots will be photogenic enough after the intro talk, and if teams aren't ready, the photography team can just come back later. (We should give them a list of all teams to tick off)

**Comment by WillB97** [comment]
@Adimote any reason this is still open?

**Comment by Adimote** [comment]
Nope

**Comment by Tyler-Ward** [comment]
The key roles involved in the post finals actions should have 2 hours (hopefully will take less) allocated on the Friday setup day so we can perform the rehearsal and adjust plans as needed per #868
