### ISSUE TITLE
Organise hotels and travel for volunteers

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#801]
It's important that volunteers are able to get to the competition, therefore hotels and other travel arrangements need to be organised.
This should also include travel between the venue and the hotels on each of the competition days.

### Original

[comp/volunteers/hotels-and-travel](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/hotels-and-travel.yaml)

### Dependencies

 * #800 Recruit volunteers for the competition

**Comment by RealOrangeOne** [comment]
We unfortunately won't be covering hotels for volunteers, and likely not travel.

We could make an "unofficial" plan to coordinate a group discount for somewhere, though.

**Comment by Scarzy** [comment]
This was done. A couple of latecomers are trying to be dealt with, but this task is considered solved
