### ISSUE TITLE
Plan reimbursement of volunteers

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#802]
After the competition we will need to reimburse volunteers for various things. We need to plan (and annouce) what things are eligible for reimbursement.
Typically the hotel stays are covered directly by SR, though we should also consider what/how much travel we can reimburse.

### Original

[comp/volunteers/plan-reimbursement](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/plan-reimbursement.yaml)

### Dependencies

 * #801 Organise hotels and travel for volunteers

**Comment by sedders123** [comment]
There is now a process in place to be reimbursed by the trustees which was sent to all volunteers. Claim form can be found (https://docs.google.com/document/d/1rYpWmxDG-XtN2D9WV_K9KPYDuaqbc3t34vvc8W3KyEA/edit)
