### ISSUE TITLE
Schedule volunteer roles

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#803]
We need to work out how many people we need doing each role and then come up with a timetable which shows who is doing which role when.

### Original

[comp/volunteers/schedule](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/schedule.yaml)

### Dependencies

 * #743 Work out the day schedules for the competition

**Comment by Scarzy** [comment]
Notes from discussions today:
We need someone staffing the test arena. This can be whoever is staffing reception during most of the time, however will need to be a separate person during the initial reception rush on Saturday morning.
Previously Helpdesk has been close to the power tools area, so if something happens they can react. Now we have moved helpdesk to a different floor, we possibly want a pair of eyes on the power tools area.

**Comment by antoinepetty** [comment]
Have added a Test Arena Supervisor role. We should probably do the same for the power tools area

**Comment by antoinepetty** [comment]
Would like to have approval of https://github.com/srobo/tasks/issues/743 before doing this so that we don't need to repeat it if there are changes

**Comment by Tyler-Ward** [comment]
Per previous discussions it was suggested that all key roles have backups incase of illness or other issues

**Comment by Tyler-Ward** [comment]
on Sunday we will need to allocate some volunteers to handle vehicle movements into campus due to the marathon

**Comment by Tyler-Ward** [comment]
The key roles involved in the post finals actions should have 2 hours allocated on the Friday setup day so we can perform the rehearsal and adjust plans as needed per #868

**Comment by WillB97** [comment]
Can we allocate 1-2 people to kit handback from 3pm Sunday (start of knockouts) to deal with teams leaving after being knocked out. We probably still need a separate person on reception until after the finals/prize giving. (We should probably also equip reception to handle the odd team leaving during the leagues, but that's a different discussion)

**Comment by Adimote** [comment]
I think the volunteer schedule is as final as it's going to get, may still make changes if some people cannot turn up: https://docs.google.com/spreadsheets/d/1ySUYgPVvNLKVa_5ngS3M5H6SsB9pBt6Ie5WhWjWXhz4/edit#gid=65055694
