### ISSUE TITLE
Prepare and send out volunteer information pack

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#804]
We should email all the volunteers with information about where to go on the day, parking, who to contact, and any other info we need to tell them.
We should aim to send this out at least a few weeks before the competition.

### Original

[comp/volunteers/information](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/information.yaml)

### Dependencies

 * #802 Plan reimbursement of volunteers
 * #803 Schedule volunteer roles
 * #905 Plan volunteer lunches

**Comment by Scarzy** [comment]
I suggest @Adimote just emails those in the accommodation plan directly, and not put it in here. As it affects less than 25% of those volunteering and is no longer adaptable it would be a bit spammy.

**Comment by Scarzy** [comment]
Removing #801 as a dependency

**Comment by Scarzy** [comment]
This should also include reminding everyone to read/action the safeguarding part of the ops-manual to avoid the need for a separate e-mail reminder

**Comment by Scarzy** [comment]
Begun a draft of this here: https://github.com/srobo/volunteer-emails/pull/53

**Comment by sedders123** [comment]
Information sent, schedules to be sent in a follow up email. Keeping task open until schedules have been sent

**Comment by PeterJCLaw** [comment]
I think the schedules got sent this evening by @Adimote?

**Comment by RealOrangeOne** [comment]
Fixed in https://github.com/srobo/volunteer-emails/pull/55
