### ISSUE TITLE
Brief the marshals for the SR2022 game

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#805]
The marshals need to know:
* what the rules are
* who the expert on them is
* who the judge is
* how to use the score entry forms
* the circumstances under which they should turn a robot off

### Original

[comp/volunteers/marshals-briefing](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/marshals-briefing.yaml)

**Comment by prophile** [comment]
They were briefed.
