### ISSUE TITLE
Move carpet for the SR2022 arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#806]
We currently use carpet as the flooring of the arenas. Usually the venue doesn't have an equivalent flooring underneath the arena area so we need to get some ourselves.
We need enough for all the arenas plus some spare for a testing area.

### Original

[comp/arena/carpet](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/carpet.yaml)

**Comment by Tyler-Ward** [comment]
I believe there is some in 32 either under the stairs or above the cupboard

**Comment by WillB97** [comment]
The carpet stored in 32 should have ~34m remaining which will be enough to do both the main arena and a practice arena.

**Comment by WillB97** [comment]
This will be at the venue by the setup days.
