### ISSUE TITLE
Provide network to the arena

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#808]
The arena needs network for the screens and score entry.

### Original

[comp/arena/network](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/network.yaml)

### Dependencies

 * #723 Have a competition network

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
