### ISSUE TITLE
Provide power to the arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#809]
The arenas need power for displays.

### Original

[comp/arena/power](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/power.yaml)

### Dependencies

 * #721 Ensure there is power at the SR2022 competition

**Comment by WillB97** [comment]
See https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing
