### ISSUE TITLE
Define Volunteer Roles

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#81]
We need to define roles for the competition and document these.

**Comment by Tyler-Ward** [comment]
needed for #80 see https://docs.google.com/spreadsheets/d/1I-rmo0lgdR2t4zCgqpjr5J_sAtkC427vVwoUH_USHWA/edit#gid=0 as well

**Comment by sedders123** [comment]
Roles needed around shepherding and in/around the arena
- 1 X Head Shepherd
- 2 X Marshalls
- 2 X Badgers (shepherds)
- 4 X team Shepherd
- 1 X roving shepherd
- 2 X score entry

**Comment by Adimote** [comment]
@sedders123 why 2 score entry people? Surely the marshalls fill the score sheets and pass it to the single scorer to score it?

**Comment by sedders123** [comment]
This was a request from @PeterJCLaw. I believe the idea was that we have two marshalls as a form of error detection so having two score entry people will further help to spot any potential errors, either on the sheets or upon entering into the scoring system.

**Comment by trickeydan** [comment]
Also if there are two score entry volunteers, one can handle other things (e.g illegible scoresheets) without causing a pause in scoring.

**Comment by PeterJCLaw** [comment]
@sedders123 is correct about my reasoning here; the main part being preventing errors in entering the scores.

While @trickeydan's point is theoretically valid too, score-entry usually completes before the next match starts; there's therefore almost never a backlog, so coping with an illegible or conflicting score-sheet doesn't normally block things (other than that one pair of sheets).

**Comment by Tyler-Ward** [comment]
I have added a load of comments to the doc on various roles, will fill in setup and other missing tech roles this evening.

**Comment by WillB97** [comment]
> I have added a load of comments to the doc on various roles, will fill in setup and other missing tech roles this evening.

Which docs is this referring to?

**Comment by Adimote** [comment]
He means the Google Doc I linked to in an earlier comment. I'll add it to
the issue description

**Comment by Tyler-Ward** [comment]
per #77 we need volunteers for running the livestream

**Comment by Tyler-Ward** [comment]
the setup and livestream roles have now been added

**Comment by Adimote** [comment]
@sedders123 We have a slight excess of volunteers right now, so I'm going to create a role of 'Reserve Marshal', because I remember having issues in previous competitions of marshals arriving on time, and we don't want to delay the competition for this.

**Comment by PeterJCLaw** [comment]
@Adimote perhaps ensure that the marshal roles either overlap by a bit, or that marshals start their role shortly before matches begin (and that they have a gap beforehand)?

**Comment by Adimote** [comment]
Okay, I'll make sure everyone who performs the marshalling role is either free or doing a non-urgent task straight after, so if the other marshal doesn't turn up, they can just continue their role.

**Comment by Adimote** [comment]
I've now created every role and assigned people to it, and got reviews from them. I note I haven't sent this out for general review so I'm happy to get feedback on this. I've already had reviews from @Tyler-Ward and @RealOrangeOne.

The defined roles are:

Logistics/Setup
--
- Setup/Teardown co-ordinator
- Freight co-ordinator cupboard
- Freight co-ordinator Venue
- Van Driver
- Van Assistant
- Tech Setup/takedown lead
- Arena setup/takedown lead
- Pit setup lead
- Pit L4 Takedown lead
- Pit L3 Takedown lead
- Pit L2 Takedown lead
 
Infrastructure
--
- Networking
- Networking Kit Support
- Tech Deck
- SUSU Tech
- Event Coordinator
- Event Coordinator 2
- Technical Director
 
Shepherding
--
- Head Shepherd
- Monitor/Timekeeper (shepherd)
- Badger (shepherd)
- Badger (shepherd)
- Team Shepherd
- Team Shepherd
- Team Shepherd
- Team Shepherd
- Roving Shepherd
 
Matches
--
- Head Judge
- Competition Software Coordinator
- Marshal
- Marshal
- Score Entry
- Score Entry
- Commentator 1
- Commentator 2
- Tinker Time Manager
 
Special Events
--
- Speech Giver
- Group photo photographer
- Photo Studio photographer
- Photo Studio assistant
 
Roving
--
- Health & Safety Co-ordinator
- Robot Safety Inspector
- Robot Safety Inspector
- Robot Safety Inspector
- Roving Helper
- Roving Helper
- Roving Helper
- Roving Helper
- Refreshments
 
Reception
--
- Receptionist
- Wristbander
- Receptionist
- Wristbander
- Chaperone
- Chaperone
- Chaperone
- Chaperone
- Kit Return handler
- Reception Battery Shuffler
 
Helpdesk
--
- Head Helpdesker
- Helpdesk
- Helpdesk
- Battery Charger
- Battery Charger
 
Other
--
- Livestream mixer
- Livestream support
- Photographer

See the spreadsheet on https://docs.google.com/spreadsheets/d/1AlRaHS50rYIRt8TZ0rxRZQ_MhG7j584JKETPd5zZMeI/edit#gid=65055694 for how long each of these roles is needed. My next step is to document the volunteer roles in #235
