### ISSUE TITLE
Put up screens around the arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#811]
We have screens around the arena to display live information, these need putting up.

### Original

[comp/arena/screens](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/screens.yaml)

### Dependencies

 * #735 Organise drivers for the arena screens
 * #737 Acquire screens
 * #900 
 * #808 Provide network to the arena
 * #809 Provide power to the arenas
 * #810 Organise stands for the arena screens

**Comment by WillB97** [comment]
Stands are provided in the tech quote.

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
