### ISSUE TITLE
Build the arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#813]
Build some arenas for the games.
This covers the physical construction of the arenas, including props needed for the game and markings for the start-position of any which are moveable. The arenas should also be marked so it's clear which is which.

### Original

[comp/arena/build](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/build.yaml)

### Dependencies

 * #754 Print arena labels for SR2022
 * #806 Acquire carpet for the SR2022 arenas
 * #807 Acquire tape for the SR2022 arenas
 * #808 Provide network to the arena
 * #809 Provide power to the arenas
 * #811 Put up screens around the arenas
 * #812 Organise tools for arena construction

**Comment by WillB97** [comment]
See https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing and https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
