### ISSUE TITLE
Put crowd barriers around the arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#814]
Since SR2015 we have used short wood-only walls for the actual arenas and had separate crowd barriers around the arena area (including the staging area).
We need to ensure that these barriers are procured in advance and then put into place before the first matches. They also need a mechanism to prevent them from moving (tape on the feet has been used in the past).

### Original

[comp/arena/barriers](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/barriers.yaml)

### Dependencies

 * #813 Build the arenas

**Comment by Tyler-Ward** [comment]
Regarding the cube is seem to remember that If the barriers are placed further away from the arena the safe capacity of the cube will be reduced, This may be worth checking. I think this was noted at a smallpiece but cant remember any details on how much the capacity was reduced to.

**Comment by WillB97** [comment]
The intention to stop the crowd barrier sliding was to have the carpet extend beyond the arena so that the barrier sits on the edge of the carpet.

**Comment by RealOrangeOne** [comment]
@WillB97 with this change of milestone, does that imply that we don't need to _source_ the crowd barrier, and that the venue will have enough for us?

**Comment by WillB97** [comment]
They should be included as part of the venue but we are clarifying this.

**Comment by WillB97** [comment]
See https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
