### ISSUE TITLE
Prepare robot flags for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#816]
During matches robots are given coloured flags so that the audience know which robot is from which scoring zone.
At least two complete sets of each badge are needed: one for the robots currently playing and another for the robots currently staging.

### Original

[comp/game/robot-flags](https://github.com/srobo/recurring-tasks/blob/master/comp/game/robot-flags.yaml)

### Dependencies

 * #734 Pre competition storage trip
 * #815 Purchase spare robot flag mounting hardware

**Comment by RealOrangeOne** [comment]
If we want to purchase our own flags, we can purchase the pipe for £5, and reuse tape and card we already have.

We almost certainly have the budget for this, and it'd make life a lot easier.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne is this something which can be worked on now, or are we blocked on getting stuff from storage?

**Comment by RealOrangeOne** [comment]
There are 2 options here:

1. We borrow the flags from SRO, as we have done before
2. We purchase the PVC pipe, for about £10, use some of the tape we have and make our own.

IMO we should do 2, as we clearly want to use the flags in future, and it would be good to have our own .

If someone on the committee agrees this makes sense, I can purchase the parts, get the tape from the container and make them.

**Comment by Adimote** [comment]
Happy to sign off for the PVC pipe spend, spend up to £15

**Comment by RealOrangeOne** [comment]
I have purchased the PVC pipe, and cut it down into the desired lengths. We have more than enough to do 2 full sets of flags, so I suggest we use the couple spare to create some _dummy_ flags which can be used for size testing / demonstrations, without needing to use the actual competition ones.

I have spare cardboard which I will cut into the right sizes for the fly part, so it'll just need very quick taping together once it's all in the same place.

**Comment by RealOrangeOne** [comment]
3 sets of robot flags have been created, plus 1 black flag for demonstration.
