### ISSUE TITLE
Provide power to all team pits

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#819]
All the team pits and related areas need power provided.

### Original

[comp/pits/power](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/power.yaml)

### Dependencies

 * #721 Ensure there is power at the SR2022 competition

**Comment by WillB97** [comment]
See https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing
