### ISSUE TITLE
Order Branded Items

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#82]
We need lots of branded things, like T-Shirts. We should work out exactly what these are and order them.

- [x]  T-Shirts [needed-quantity](https://docs.google.com/spreadsheets/d/1z2mtfowI8tyXXr3AA3D6wxDkwznLBI8KkxGiX24zCEI/edit?usp=sharing)
- [x] Business Cards
- [x] Wristbands

Blocking on designing most of said branded items.

**Comment by PeterJCLaw** [comment]
@mildlyincompetent is there a ticket for the design?
Related: if we're blocking on _design_, does that mean that we've decided what item's we're going to produce? (If so, is there a list somewhere?)

**Comment by Tyler-Ward** [comment]
The design label should list all of them https://github.com/srobo/tasks/labels/design

**Comment by Adimote** [comment]
I've added a sheet which calculates the number of needed t-shirts (plus a buffer)
https://docs.google.com/spreadsheets/d/1z2mtfowI8tyXXr3AA3D6wxDkwznLBI8KkxGiX24zCEI/edit?usp=sharing

**Comment by Tyler-Ward** [comment]
The buffer has been increased so the total is 50 t-shirts . For purchasing I expect that the cost will be around £300 so if it is less than £320 go ahead an place it. @TomWheal

**Comment by RealOrangeOne** [comment]
This ticket is no longer blocked

**Comment by TomWheal** [comment]
50 shirts will be £250 + vat, still okay too order those

**Comment by Tyler-Ward** [comment]
@TomWheal That sounds good to me, so they are good to order.

**Comment by TomWheal** [comment]
T-Shirts have been ordered, will pop into the shop to pay this week, turn around is 4 days so no rush.

**Comment by mltnhm** [comment]
Wristbands have been ordered (#164), is this ready to be closed?

**Comment by RealOrangeOne** [comment]
it is :tada:
