### ISSUE TITLE
Setup battery charging station

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#820]
There are many batteries that need charging and we need to set up the charging station. This should be somewhere safe to charge the batteries and with reasonable access to helpdesk (as that is where teams will get batteries from).
Note: the battery charging station should reconfigure the chargers to a higher current than we allow the teams to use as this substantially reduces the charge time. Instructions on how to do this should be made available to those running the charging station.

### Original

[comp/pits/battery-charging](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/battery-charging.yaml)

### Dependencies

 * #767 Plan for disposal of sad batteries
 * #819 Provide power to all team pits

**Comment by Scarzy** [comment]
This needs a number of RUBs for flat batteries, charged batteries, and dead batteries.
https://studentrobotics.org/runbook/kit/event-operations/battery-charging/ should also be printed out and available.

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
