### ISSUE TITLE
Have a supply of charged batteries by the SR2022 Arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#821]
We should have a supply of charged batteries in the staging area next to the arena so that teams on their way into matches don't need to go to helpdesk to get one. This ensures that robots perform at their best during matches.
This is important during the knockouts, though less so during the leagues.

### Original

[comp/arena/batteries](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/batteries.yaml)

### Dependencies

 * #767 Plan for disposal of sad batteries
 * #813 Build the arenas
 * #820 Prepare battery charging station

**Comment by WillB97** [comment]
For the odd batteries that need moving shepherds/roving helpers can do this.

**Comment by PeterJCLaw** [comment]
Ok, do we have a plan to ensure that this does actually happen for the knockouts?
