### ISSUE TITLE
Station fire extinguishers next to the SR2022 Arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#822]
~At least one powder fire extinguisher should be placed within easy reach next to each arena in case of LiPo fires.~

### Original

[comp/arena/fire-extinguishers](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/fire-extinguishers.yaml)

### Dependencies

 * #772 Ensure that we will have fire extinguishers at the competition
 * #813 Build the arenas

**Comment by Scarzy** [comment]
Do we have anyone who is trained to use fire extinguishers?
What justification was used to decide powder fire extinguishers were the appropriate choice?
Do the venues fire plans support us tackling a fire ourselves?

**Comment by Scarzy** [comment]
So, having received advice from Surrey Fire and Rescue Service, we should be dropping fire-y batteries into a bucket of water, but realistically they reckon that "they are prolifically difficult to extinguish".

Powder fire extinguishers are not recommended.

**Comment by Scarzy** [comment]
Possibly a large RUB at battery charging with a lid on for if anything happens there, though it would have to be far from the actual charging or wiring. I don't think water near the arena is practical or sensible.

**Comment by Scarzy** [comment]
Having reviewed and discussed the layout around battery charging, we think a container full of water near battery charging is probably safe enough, and gives a method to potentially extinguish a battery.

The problems are more practical - how to get the battery into the container, and what container to use. A RUB isn't practical as the battery will sink to the bottom and melt through, I've managed to borrow a metal bucket from a scout group, we should then use a rope crowd barrier to ensure no-one can walk into it.
In terms of getting it into the bucket - if it is in a state whereby it can be picked up by hand and thrown into the bucket; great. If not, then we will just have to leave it to do its thing, sweeping all other batteries and chargers out of the way and cutting the power if safe to do so. Either way, if a battery goes up then it's a hit the fire alarm and evacuate territory, the aim is merely to minimise damage to aid restarting as soon as possible.

**Comment by PeterJCLaw** [comment]
I'm not sure if this happened in the end. Either way it's past now. It definitely sounds like we should update the recurring tasks and runbook about this though.

**Comment by Scarzy** [comment]
It happened.

The runbook was updated prior to the event.
