### ISSUE TITLE
Prepare generic music playlist for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#823]
During matches we want music to be played into the arena.
We typically have 2 playlists: one for during matches, and one for during breaks. Generally the former is more "intense" than the latter.
Note that there is a separate task for the time-synchronised music played during the finals.

### Original

[comp/arena/music](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/music.yaml)

### Dependencies

 * #720 Sort out sound system for the competition

**Comment by Tyler-Ward** [comment]
We have started collecting suggestions for the competition music, suggestions can be added to https://docs.google.com/spreadsheets/d/1IsIaHodA6T5E5H99MII6AOv0EYLy40TI8ittHm_vsLk/edit#gid=0

The competition has the following playlists with the described musical styles

Calm playlist
A randomised playlist of music in calmer times e.g. tinker time and breaks.
Songs with vocals are fine in this list

Match playlist
A randomised playlist of music to play during matches 
Songs with vocals are ok but should not be soo promiant as to interfeer with judging/commentating

Special function tracks
This playlist is for tracks with specific functions during the event e.g. opening the cube for match mode ect

Finals playlist
A syncronsed playlist for the finals, this is often built out of the contents of the other playlists and songs used here will be removed from the other playlist
This playlist is not being tracked in this sheet

Exit playlist
A non randomised playlist for after the awards comprised largley of music from film credits and similar ofen inlduing thingks like "want you gone" after the playlist has been playing for a bit

**Comment by sedders123** [comment]
Music is playing so calling this done
