### ISSUE TITLE
Have an arena

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#825]
Central ticket for hanging arena things from.

### Original

[comp/arena/main](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/main.yaml)

### Dependencies

 * #763 Organise high-vis jackets for the teams at the competition
 * #813 Build the arenas
 * #814 Put crowd barriers around the arenas
 * #818 Put out the staging area
 * #821 Have a supply of charged batteries by the SR2022 Arenas
 * #822 Station fire extinguishers next to the SR2022 Arenas
 * #823 Prepare generic music playlist for the compettion
 * #824 Make an arena reset checklist

**Comment by WillB97** [comment]
This is now covered by https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
