### ISSUE TITLE
Train marshals for the SR2022 game

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#826]
The marshals should have a chance to run through the process of running a competition match sequence.

### Original

[comp/volunteers/marshals-training](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/marshals-training.yaml)

### Dependencies

 * #805 Brief the marshals for the SR2022 game
 * #825 Have an arena

**Comment by prophile** [comment]
Marshals were trained and drilled.
