### ISSUE TITLE
Ensure we can get refreshments to static volunteers

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#828]
Many volunteers are in a single place and cannot move because they are continuously active for a long duration (marshall, judges).
We need a volunteer to take these refreshments to these stationary posts, especially those who are permanently in a single role and cannot get refreshments for themselves.

### Original

[comp/volunteers/refreshment-delivery](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/refreshment-delivery.yaml)

### Dependencies

 * #827 Plan refreshments for volunteers

**Comment by sedders123** [comment]
Volunteer schedule has roles for this (https://github.com/srobo/runbook/pull/158)
