### ISSUE TITLE
Competition Signage Design and Printing

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#83]
We need signs for the competition, which will need designing and printing. This includes signage such as

- Toilet Locations
- Entrances
- Exits
- Parking
- Do Not Enter
- Danger of Death
- Robot Uprising In Progress

and probably quite a few more.

**Comment by WillB97** [comment]
The comical signs need to be placed such that they don't obscure, or make the installed safety signage unclear, so as not to impact on pre-existing safety measures.

**Comment by trickeydan** [comment]
> The comical signs need to be placed such that they don't obscure, or make the installed safety signage unclear, so as not to impact on pre-existing safety measures.

This comes under the separate issue of installing the signs during setup. This ticket only relates to the design and production of the signs.

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/signage (from https://studentrobotics.org/cgit/signage.git) is relevant here, as are https://github.com/srobo/brand/ and https://github.com/srobo/style. See also the hosted version of the latter: https://studentrobotics.org/style/

**Comment by TomWheal** [comment]
Spoken to @antonnikitin97, as I've got all the style stuff ill be doing this instead.

**Comment by jcwilliamson** [comment]
# List of signs
- Toilet Locations
- Entrances
- Exits
- Arena
- Do Not Enter
- Photography beyond this point
- No Robots beyond this point
- Power tools area
- Staging in/staging out
- Quiet zone/ please be quiet (optional)

**Comment by Scarzy** [comment]
First Aid area should probably be signed

Staging out I believe should just be "Do Not Enter"

**Comment by TomWheal** [comment]
I have made Team pit signs. I've made a framework for the other signs, I suggest that this is finished and printed on the setup days so the signs can be designed for where they need to go, I'm happy to do this on Thursday or Friday and use my printer credit on the uni printers.

[TeamSigns_01.pdf](https://github.com/srobo/tasks/files/3025391/TeamSigns_01.pdf)

(I can only upload the test team sign as my internet isn't good enough where I'm at currently)

**Comment by TomWheal** [comment]
Team Signs have been printed

**Comment by TomWheal** [comment]
This has been pretty much done
