### ISSUE TITLE
Create a list of available subject matter experts

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#830]
While helpdesk is the primary point of call for teams who need help, we also need a way for those manning it to escalate their request if they don't know how to resolve something. This is not intended to remove the need to replace broken kit, but rather to provide extended support for non-replaceable parts (e.g: complex vision system or rules questions).
We should create a list of subject matter experts and put it on helpdesk. Clearly the people on the list need to be actually available to help (i.e: both at the venue and not insanely busy), and aware that they're the point-of-contact for certain areas.

Example domains:
- Rules - Kit
  - Python API
  - Hardware
  - Competition operations
- Event
  - Tech

### Original

[comp/volunteers/experts-list](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/experts-list.yaml)

### Dependencies

 * #803 Schedule volunteer roles

**Comment by PeterJCLaw** [comment]
@RealOrangeOne how does this compare to https://github.com/srobo/tasks/issues/835?

**Comment by RealOrangeOne** [comment]
I have created this list based on the previous years'.

https://docs.google.com/document/d/1Nxe2qJIA0MMrS8zK6vBKaZH_SftlvepQjBLzjOcmAAw/edit?usp=sharing

Will leave this open a while to collect feedback.
