### ISSUE TITLE
Brief Volunteers on Competition Event

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#832]
The volunteers need to know:
  - Key Roles & Point of Contacts
  - Health and Safety
    - COVID-19 Requirements
  - Safeguarding
  - Venue layout (if applicable)
  - Schedule of Event

### Original

[comp/volunteers/brief-volunteers](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/brief-volunteers.yaml)

### See also

 * #799 Brief volunteers on communications at the SR2022 Competition

**Comment by prophile** [comment]
All briefings complete.
