### ISSUE TITLE
Create domain expert list

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#835]
If there is a problem at helpdesk, that those on helpdesk cannot solve, they need to know who to escalate to.
There will be different experts depending on the domain.
Example domains:
- Rules - Kit
  - Python API
  - Hardware
  - Competition operations
- Event
  - Tech

Note that this list of people should also take into account who is likely to be available.

### Original

[comp/pits/helpdesk/expert-list](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/helpdesk/expert-list.yaml)

**Comment by PeterJCLaw** [comment]
@RealOrangeOne how does this compare to https://github.com/srobo/tasks/issues/830?

**Comment by RealOrangeOne** [comment]
Looks like this is a duplicate of #830. As #830 is better integrated into the task tree, I'll close this in favour, and migrate the relevant checklist.
