### ISSUE TITLE
[Meta] Plan helpdesk at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#836]
Helpdesk is the single-point-of-contact for teams to get help with their robots. We need to plan who will run this on the day as well as the various things it needs to be able to help the teams.

### Original

[comp/pits/helpdesk/main](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/helpdesk/main.yaml)

### Dependencies

 * #761 Plan overnight kit & battery loans at the competition
 * #767 Plan for disposal of sad batteries
 * #819 Provide power to all team pits
 * #820 Prepare battery charging station
 * #830 Create a list of available subject matter experts
 * #834 Have spare kit available at the competition
 * #835 Create domain expert list

**Comment by prophile** [comment]
Helpdesk occurred.
