### ISSUE TITLE
Set up a power tools area

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#837]
Rather than letting teams use power tools in their team pits, we ask them to go to a separate area.

### Original

[comp/pits/power-tools](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/power-tools.yaml)

### Dependencies

 * #725 Prepare a layout of the competition
 * #819 Provide power to all team pits

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
