### ISSUE TITLE
Organise internet access for the team pits

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#838]
Teams need access to the internet to use the IDE and get at documentation. We therefore need network access in all the team pits.
Past experience with WiFi-only network provision has been mixed, so hard-wire network provision should be considered unless the venue has well proven capacity.
Some venues' internet provision requires the use of guest accounts. If these are needed, We should ensure (as part of this task or by adding a sub-task) that suitable accounts are obtained, ideally at least per-team as well as for volunteers.

### Original

[comp/pits/network](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/network.yaml)

### Dependencies

- #899 Organise Eduroam accounts for SR2022

**Comment by Tyler-Ward** [comment]
If at SUSU there will be eduroam in the building but guest accounts will need to be acquired from the university in order for teams to use.

**Comment by WillB97** [comment]
Part of #899

**Comment by WillB97** [comment]
We have these they just need printing
