### ISSUE TITLE
Roll out at team pits at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#840]
### Original

[comp/pits/rollout](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/rollout.yaml)

### Dependencies

 * #782 Work out layout of teams at the competition
 * #819 Provide power to all team pits
 * #833 Organise tables and chairs for team pits
 * #838 Organise internet access for the team pits
 * #839 Determine and publish rules for the pits

**Comment by WillB97** [comment]
So how does this differ from #842 and do both of them need to be kept?

**Comment by PeterJCLaw** [comment]
Likely this should depend on #842 and be in the setup milestone while that one is for doing the relevant preparations. There's an existing issue for sorting out the meta tasks (https://github.com/srobo/recurring-tasks/issues/32).

**Comment by WillB97** [comment]
See https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
