### ISSUE TITLE
Prepare team pits at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#842]
Teams need team pits to work in, and these need setting up.

### Original

[comp/pits/main](https://github.com/srobo/recurring-tasks/blob/master/comp/pits/main.yaml)

### Dependencies

 * #782 Work out layout of teams at the competition
 * #819 Provide power to all team pits
 * #833 Organise tables and chairs for team pits
 * #836 Plan helpdesk at the competition
 * #837 Set up a power tools area
 * #838 Organise internet access for the team pits
 * #839 Determine and publish rules for the pits
 * #840 Roll out at team pits at the competition
 * #841 Furnish each pit with a clearly visible label

**Comment by WillB97** [comment]
See https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
