### ISSUE TITLE
Prepare game equipment for the arena

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#843]
We need to prepare the things that will go in the arena. See this year's [rulebook](https://studentrobotics.org/docs/resources/2022/rulebook.pdf) for details.
Sub tasks should be added to this task for each of the various props which are needed.

### Original

[comp/game/props](https://github.com/srobo/recurring-tasks/blob/master/comp/game/props.yaml)

### Dependencies

 * #755 Organise markers for the arena
 * #816 Prepare robot flags for the competition

**Comment by WillB97** [comment]
The arena props this year consist of:
- a 4ft x 4xft stage deck
- 28 cans

The stage deck is included in the tech quote. @sedders123 has purchased the cans, I'm not certain how many.

**Comment by WillB97** [comment]
Once the additional cans have been purchased we can close this, remembering that the labels need to be removed.

**Comment by WillB97** [comment]
We also need ~4ft x 4ft of hardboard to clad the sides of the stagedeck.

**Comment by WillB97** [comment]
These are being tracked in https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit?usp=sharing and also include hardboard to make the sides of the stagedeck solid, as defined in the rules.

**Comment by PeterJCLaw** [comment]
Does the closure of this issue indicate that the props for the arena have been all purchased and constructed (at least as much as can be done ahead of time)?

I don't think it's a great idea to be moving task tracking away from our primary task tracker as doing so decreases visibility, making it harder for others to help out.
