### ISSUE TITLE
Prepare the finals music for the compettion

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#845]
We generally use a bespoke cut of various songs for the finals tracks, to build tension, ensure the music is dramatic enough, and is timed perfectly, with starting of matches and timing.
Note that there is a separate task for the music played during the rest of the matches.

### Original

[comp/game/finals-music](https://github.com/srobo/recurring-tasks/blob/master/comp/game/finals-music.yaml)

### Dependencies

 * #720 Sort out sound system for the competition
 * #784 Prepare the compstate
 * #776 Design the SR2022 knockouts

**Comment by prophile** [comment]
Time and mixtape issues have precluded a specific finals playlist here, @Tyler-Ward is taking over running of this (thanks!)

**Comment by PeterJCLaw** [comment]
There were finals. There was music.
