### ISSUE TITLE
Have the SR2022 knockout matches

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#846]
The knockout matches need to happen.

### Original

[comp/game/knockout](https://github.com/srobo/recurring-tasks/blob/master/comp/game/knockout.yaml)

### Dependencies

 * #776 Design the SR2022 knockouts
 * #844 Have the SR2022 league matches
 * #845 Prepare the finals music for the compettion

**Comment by PeterJCLaw** [comment]
These happened.
