### ISSUE TITLE
Create score data entry system (update the scorer UI)

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#848]
We need a data entry system for converting from the score entry forms to the YAML file format.
This task is both the root for preparing this system and covers the updating of the scorer UI for this year's game.
See https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#update-srcomp-scorer for details of the latter.

### Original

[comp/game/score-entry](https://github.com/srobo/recurring-tasks/blob/master/comp/game/score-entry.yaml)

### Dependencies

 * #756 Design score entry forms for marshals
 * #778 Create SR2022 game score format
 * #779 Write scoring scripts for the SR2022 game
 * #847 Get desk lamp for score entry

**Comment by sedders123** [comment]
In progress at https://github.com/srobo/sr2022-comp/pull/2/files
