### ISSUE TITLE
[Meta] Organise scoring for the SR2022 game

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#849]
We need to be able to score matches.

### Original

[comp/game/scoring](https://github.com/srobo/recurring-tasks/blob/master/comp/game/scoring.yaml)

### Dependencies

 * #756 Design score entry forms for marshals
 * #757 Print score entry forms for marshals
 * #778 Create SR2022 game score format
 * #779 Write scoring scripts for the SR2022 game
 * #797 Get stationery for scoring the SR2022 Competition
 * #848 Create score data entry system (update the scorer UI)

**Comment by PeterJCLaw** [comment]
This is as organised as it's going to get. The printing needs to happen, but that's tracked separately.
