### ISSUE TITLE
Design T-Shirts

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#85]
We would like some branded T-Shirts. These need designing.

**Comment by PeterJCLaw** [comment]
Related resource: https://studentrobotics.org/style/

**Comment by Tyler-Ward** [comment]
Leadtime: 1 week

**Comment by RealOrangeOne** [comment]
It's come up many times that a lack of t-shirts can lead to some volunteers feeling unwanted, due to their being a second tier of volunteers with t-shirts.

As we've got many different generations of t-shirts, we should just get a whole new set made.

**Comment by trickeydan** [comment]
We budgeted for a whole new set of t-shirts I believe so that should be feasible

**Comment by TomWheal** [comment]
I'm happy to do this, are we wanting volunteer specific ones or generic ones like the design found here, https://studentrobotics.org/cgit/shirts.git/

**Comment by RealOrangeOne** [comment]
The t-shirts should be completely generic. 

I suspect that repo is a good starting point, although we'll need to update the colours and logo

**Comment by trickeydan** [comment]
A significant consideration for this is finding a supplier who has the right colour shirts.

**Comment by PeterJCLaw** [comment]
The blue we've used in the past (i.e: before the most recent Kickstart) is probably about as good as we'll get. Frankly, that blue is a lot closer to the new brand colour than the new shirts were, so I'd say going with that blue is fine.

**Comment by trickeydan** [comment]
> Frankly, that blue is a lot closer to the new brand colour

I completely disagree. The old blue is noticeably darker. I personally didn't have an issue with the kickstart shirts.

**Comment by RealOrangeOne** [comment]
The kickstart shirts were incredibly off-colour. The old blue was much closer to the current brand colours than that. If we can't get the exact colour (which is unlikely) we should go for the one which is closest, which the existing shirt colour is. Obviously the logo and sponsors are still off, so we need a complete new batch anyway.

**Comment by trickeydan** [comment]
We could just ask for the closest we can get. Unlike Kickstart, we're not ordering these in a rush so the supplier will be able to buy in the correct colour and we can ask to see the colour beforehand also.

**Comment by TomWheal** [comment]
Do you happen to know what printing shop/website you got them from (both kickstart and previously)? I'll have a look at what wholesale supplier they use and see if we can get a sample of all options on the cheap. Getting the exact colour is going to be impossible as most printing companies buy shirts in bulk from a wholesale supplier which will have fixed colours. Unless we want to commission a custom colour which for ~40 shirts is going to be pointless...

**Comment by RealOrangeOne** [comment]
We used http://www.carolinestshirts.com/ for the ones at kickstart. I don't know where we got the previous SR ones. I think finding a reasonably-similar dark-ish blue should work fine, although the closer the better. I suspect simply looking around will yield some somewhat reasonable solutions.

**Comment by TomWheal** [comment]
Some initial concpets, Ill refine the design more after this, just checking this is the sort of thing people are happy with.

Keeping the Front Simple
![shirtmockupfront](https://user-images.githubusercontent.com/7452669/53751433-27838480-3ea4-11e9-8f88-d05e5f2d6c82.png)
I personally think a polo looks better than a t-shirt.
![shirtmockuppolo](https://user-images.githubusercontent.com/7452669/53751434-27838480-3ea4-11e9-93aa-33a741537586.png)
Ignore The fact the the back is printed on the front in this mockup
![shirtmockupback1](https://user-images.githubusercontent.com/7452669/53751435-27838480-3ea4-11e9-8eea-065d466b443b.png)
QR code concept currently pointing to http://srobo.org/qr so that its link location can be customised. 
![shirtmockupback2](https://user-images.githubusercontent.com/7452669/53751432-27838480-3ea4-11e9-8485-8a4f137eaf7b.png)

(I used the old logo for motorola from the studentrobotics.org git, is there a newer one, i couldnt find any brand/style info on their website)

**Comment by RealOrangeOne** [comment]
These look great, couple bits of feedback:

The colour of these looks perfect! I assume the template is from a company who can print in that colour?

I quite like the minimal nature of the front. Although, it could probably use 'Student robotics' on it.

It might also look nice to have the logo on the sleeves as well, depending on how much printing on those is extra.

If we can fit it in budget, then we should definitely get polo shirts, they just look so much nicer!

I don't think it's useful to have a large QR code on the back, especially not if it means moving the sponsors.

I'm not sure we need the words 'Volunteer', we're all volunteers, and it would mean we could make the words 'Student Robotics' larger, and just reuse the existing logos.

I think we should also move the sponsor logos up on design 1. When sat down, the lower back portion is invisible. It also leaves a large empty area in the middle.

**Comment by PeterJCLaw** [comment]
Nice, thanks for doing the mock-ups.

I agree we should have "Student Robotics" on the front. I suggest going with the usual layout of immediately under the logo, with each word on its own line (this is what we've had in the past, prior to Kickstart). https://studentrobotics.org/style/ notes the font to use, though we probably need to convert any text to pure vector before submission to ensure it renders as we want.

I don't think we need to repeat the logo on the back, nor include "volunteer" as an override to the logo (https://studentrobotics.org/style/ is also pretty clear that we shouldn't do the override thing, see the notes on logo use and spacing). It'll be really obvious we're all that as we'll all have matching shirts.

For the similar reasons I don't think the QR code is useful here. It's an interesting idea, and I can see uses for it elsewhere, but at the competition there's going to be some much SR stuff around that people are going to be able to work out for themselves what our website is. I also don't want people trying to chase me to scan my back! (I can think of all sorts of ways that can go awry).

We've sometimes had the year on the sleeves. That might also be somewhere to put "volunteer" - more as a memento than an advertisement. I don't have a strong opinion about the sleeves.

For the sponsors, I suggest going as big as we reasonably can with them on the back. Motorola remain our largest sponsor (as I understand it), so we should probably have them biggest or at least top. (Stacking vertically lets them be much bigger too)

I'd be more in favour of tee-shirts than polos (just personal preference).

**Comment by TomWheal** [comment]
I initially made this shirt, which pretty much meets all the points you made... however, I'm personally not the biggest fan.  The QR code was a bit of gimic in retrospect, I agree with you on that. 
![shirtmockupback](https://user-images.githubusercontent.com/7452669/53792521-ce5b3580-3f23-11e9-828b-952d7ae920e1.png)

My thinking for adding volunteer is that I don't think that for people, (not regulars at the competition) that it's obvious we are running the comp, some events have matching t-shirts for the participants, so making this clear would be a benefit. (Most University Hackathons are a good example of this)

Also, the colour is the one from the SR style page, however, royal blue seems to be a standard colour and is very close to this in the online samples. I have emailed carolines and have asked if I can get a sample of 3 different shirts, Royal Blue Tee and Polo,  Galaxy Tee (I believe this is what was used at the kickstart).

@RealOrangeOne This isn't a template from any provider, its actually a mockup photoshop file which I used to design the t-shirts for the SR Team I was in back in the day. Moving it to a template is very simple once the design has been decided.

**Comment by kierdavis** [comment]
@TomWheal Nice work! I like your thinking about including "volunteer" on the back to distinguish from competitors - however I think the distinction between volunteers and competitors will already be clear since only the former will be wearing shirts like these, so I agree with Jake and Peter that it's not needed.

I'd advise against including the year on the shirt so that we don't have compromise between buying a whole new set of shirts every year or deploying outdated shirts at future events.

Also, I was under the impression that the University of Southampton was no longer a sponsor of ours (although I cannot find any evidence of whether this is true or false). Is this something we need to chase up with the trustees?

**Comment by TomWheal** [comment]
@kierdavis That's an interesting point about the Sponsorship, it might be worth confirming with the trustees about the sponsors. (I'm not sure how to go about this, alongside that do they need to approve any designs?) I somehow doubt that all the money comes from the Motorola Foundation and the Uni? I recall in previous years there was a third sponsor?

Also completely agree with not including the year.

**Comment by RealOrangeOne** [comment]
We can contact the trustees if necessary, but I suspect @Tyler-Ward already knows the answer.

**Comment by TomWheal** [comment]
Following the Discussion at the techday day, here is the latest iteration of t-shirt/Polo. It has also been discussed ordering both Tees and Polos. 

![ShirtMockupBack1](https://user-images.githubusercontent.com/7452669/54071520-4ea3d280-4265-11e9-890a-dc3bf6df6b5b.png)
![ShirtMockupFront](https://user-images.githubusercontent.com/7452669/54071521-506d9600-4265-11e9-8cb7-60889e4bba9d.png)

**Comment by TomWheal** [comment]
And another Update.

![ShirtMockupBack1](https://user-images.githubusercontent.com/7452669/54071656-7300ae80-4267-11e9-9b76-d5026a559425.png)

**Comment by TomWheal** [comment]
This Can be Closed

**Comment by mltnhm** [comment]
People ok with that? @Tyler-Ward @RealOrangeOne @PeterJCLaw

**Comment by Adimote** [comment]
LGTM!

**Comment by Tyler-Ward** [comment]
Design not yet merged, will close when merged

**Comment by RealOrangeOne** [comment]
https://github.com/srobo/promotional-material/pull/7 has now been merged.
