### ISSUE TITLE
Have the SR2022 games

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#850]
We need to run all the matches at the competition.

### Original

[comp/game/main](https://github.com/srobo/recurring-tasks/blob/master/comp/game/main.yaml)

### Dependencies

 * #780 Organise shepherding
 * #817 Prepare competition-mode USB keys
 * #825 Have an arena
 * #843 Prepare game equipment for the arena
 * #844 Have the SR2022 league matches
 * #846 Have the SR2022 knockout matches
 * #849 Organise scoring for the SR2022 game

**Comment by PeterJCLaw** [comment]
These are under way.
