### ISSUE TITLE
Deploy the Compbox

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#851]
The compbox VM will need deploying onto the host machine and ensuring that it works.
This should also include confirming that it's got a static name/address and that the relevant pages can be seen from other machines.

### Original

[comp/ops/deploy-compbox](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/deploy-compbox.yaml)

### Dependencies

 * #781 Prepare the Compbox
 * #808 Provide network to the arena
 * #809 Provide power to the arenas

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
