### ISSUE TITLE
Deploy the score entry system

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#852]
The machine which will be used for score entry need setting up. At least one of these is expected to be a permanent machine placement.
This should also include confirming that the relevant pages and ops software things can be accessed.

### Original

[comp/ops/deploy-score-entry](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/deploy-score-entry.yaml)

### Dependencies

 * #736 Organise machine to run score entry
 * #808 Provide network to the arena
 * #809 Provide power to the arenas
 * #848 Create score data entry system (update the scorer UI)

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
