### ISSUE TITLE
Deploy Ops for the SR2022 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#853]
Ops needs a table and network connection to work from. It should be located somewhere protected from the competitors, but vaguely near the arena so the people manning it can see what's going on and easily communicate with the Master(s) of Ceremonies.

### Original

[comp/ops/deploy](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/deploy.yaml)

### Dependencies

 * #784 Prepare the SR2022 Compstate
 * #851 Deploy the Compbox
 * #852 Deploy the score entry system

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
