### ISSUE TITLE
Import the (final) teams data into the compstate

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#854]
We need to run the teams import into the compstate as part of the setup so that it's got the latest team images.
This import may also need re-running during the competition.

### Original

[comp/ops/teams-import](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/teams-import.yaml)

### Dependencies

 * #784 Prepare the SR2022 Compstate

**Comment by sedders123** [comment]
We don't have any systems to export this data from (think it's talking about the IDE). Teams have been imported into the compstate from the Google Sheet
