### ISSUE TITLE
Plan the Tech Desk

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#855]
Ensure we have enough table top space, power and networking for all necessary equipment at the tech desk.
Things that have previously been on tech desk include: 
- Event scoring control + printing 
- Livestream 
- Networking 
- Judging 
- ~~Radio charging~~
- ~~Lighting desk~~
- ~~Sound desk~~
- ~~Score-entry~~
- A corner for various servers for:
  - Non-sync audio (background music not running through mixtape)
  - sync audio (currently [mixtape](https://github.com/srobo/srcomp-mixtape))
  - compbox

### Original

[comp/ops/plan-tech-desk](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/plan-tech-desk.yaml)

**Comment by WillB97** [comment]
This year lighting, sound and radio charging can stay in the booth. Score-entry will be in the cube.

**Comment by WillB97** [comment]
Tech desk has 2 tables with a separate table for livestream. The tech desk will be for:
- Comp ops + printing
- Judging
- A corner for various servers for:
  - Non-sync audio machine
  - mixtape
  - compbox
- Network switch
