### ISSUE TITLE
[Meta] Have Ops at the SR2022 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#856]
We need ops.

### Original

[comp/ops/main](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/main.yaml)

### Dependencies

 * #784 Prepare the SR2022 Compstate
 * #851 Deploy the Compbox
 * #853 Deploy Ops for the SR2022 Competition
 * #854 Import the (final) teams data into the compstate
 * #855 Plan the Tech Desk

**Comment by WillB97** [comment]
This is covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
