### ISSUE TITLE
Acquire trophies (SR2022)

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#857]
Some awards involve trophies being given to the winning teams. The trophies need purchasing.

### Original

[comp/prizes/trophies](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/trophies.yaml)

**Comment by Tyler-Ward** [comment]
For the sponsored awards will the trophies have the branding of the sponsor?

**Comment by WillB97** [comment]
This also requires us to know which sponsor is sponsoring which award.

**Comment by PeterJCLaw** [comment]
Looks like https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html is still available. Lead time looks like 5-7 days, so we should assume 2 weeks.

**Comment by PeterJCLaw** [comment]
The prices have also increased somewhat.
We want: 1×large (£23.99 each), 2×medium (£21.99 each), 2×small (£18.99). On each of those we want both our logo and some text engraved, which is another £15 each.
This would total ~£180.

**Comment by Tyler-Ward** [comment]
Some updates after extracting information from the trustees. 
* Apparently it was decided in a doing on the 26th that the trophies will contain the sponsors name and not the logo.
* Two sponsors pf three have selected which awards they wish to sponsor and one has not. knowledge of hat award they are sponsoring is not yet been provided by the fundraising team.

We therefore need to create a design that accommodates the sponsors name. @Adimote as you have ordered them before how do we submit this to the trophy company do we just send the text and logo and they sort out the placement or do we send a full layout to them?

**Comment by Adimote** [comment]
@Tyler-Ward worth reading https://github.com/srobo/tasks/issues/670 if you haven't already. 

Their form just asks for text, you check a box to say you have an image, then they follow up via email for the image.

In that email I sent them a quickly-thrown-together mock in GIMP as an example layout (in the old ticket), and clarified what text for each trophy. I'd recommend doing something similar but it's probably optional.

**Comment by Adimote** [comment]
Actually I'm misremembering, I sent them an email directly last year because their site's payment system was broken. I'm happy to forward the email, @Tyler-Ward are you intending to sort purchasing this year?

**Comment by Tyler-Ward** [comment]
Looking at the Leadtime the dispatch is 5-7 days then shipping (assume 2 days), given there is 2 bank holidays over Easter.  Therefore we should order mid this week, I will let the trustees and fundraising know about this deadline.

@Adimote If you are able to handle purchasing them as you have dealt with them before that would be great.

**Comment by Tyler-Ward** [comment]
The sponsored awards are as follows:

Southampton Uni: Rookie Award
ITDev: Committee Award
Adventurous Machines: Robot and Team Image

**Comment by Adimote** [comment]
Sent email to their enquiries@ address, for posterity I've put it verbatim here:

> <html>
> <body>
> <span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Hi Trophies2u!</span><br clear="all" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div>I'd like to order 5 trophies, to arrive in time for an event on April 23rd.</div><div><br></div><div>The shipping address is:</div><div><br></div></div><blockquote style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0px 0px 40px; border: none; padding: 0px;"><div><div> (ADDRESS)</div></div></blockquote><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div><br></div><div>All trophies are of the <a href="https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html&amp;source=gmail&amp;ust=1649364549157000&amp;usg=AOvVaw3LkuTJwJJAHDpesg2KbXkB" style="color: rgb(17, 85, 204);">'Great Style Slant Jade Glass Award'</a> type (sizes will vary).</div><div>All trophies will need our logo engraved, along with some text. Student Robotics has ordered from you before, so our logo should be on file, I've also attached it just in case.</div><div><br></div><div>Additionally, I've also attached a mock-up of what I'm imagining would look best., both for awards with and without sponsors.</div><div><br></div><div>Here's the information for each trophy (also available in <a href="https://docs.google.com/spreadsheets/d/1heyZMwoqlj2VJT05EnRO8AfNw5KIqXVVtEjcB6sY1pQ/edit?usp=sharing" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://docs.google.com/spreadsheets/d/1heyZMwoqlj2VJT05EnRO8AfNw5KIqXVVtEjcB6sY1pQ/edit?usp%3Dsharing&amp;source=gmail&amp;ust=1649364549157000&amp;usg=AOvVaw0fmLQbSBuPpcf_CMYvc0mH" style="color: rgb(17, 85, 204);">google sheets</a>):</div><div><div><br></div><div>
> 
> (All Trophies are the Great Style Slant Jade Glass Award) |   |  
> -- | -- | --
> Size | Code | Engraving
> 24.5cm | GL-290/JC006B | 2022This Way Up1st Place
> 21.5cm | GL-290/JC006A | 2022This Way Up2nd Place
> 20cm | GL-290/JC006AA | 2022This Way Up3rd Place
> 20cm | GL-290/JC006AA | 2022This Way UpRookie AwardSponsored byUniversity of Southampton
> 20cm | GL-290/JC006AA | 2022This Way UpRobot and Team ImageSponsored byAdventurous Machines
> 
> </div><div><br></div><div>Looking forward to hearing back from you!</div><div><br></div><div>Thanks,</div><div>Andy Barrett-
Sprot</div></div></div><br class="Apple-interchange-newline">
> </body>
> </html>

![trophy-mockup-2022-nosponsor](https://user-images.githubusercontent.com/2551763/162068760-fdc08eef-2db5-4912-92c8-68bb2b62d78e.png)

![trophy-mockup-2022-longtext-nosponsor](https://user-images.githubusercontent.com/2551763/162068755-5a7a8335-69e8-425f-9402-ce6f63467478.png)

![logo-text-black-vertical](https://user-images.githubusercontent.com/2551763/162068838-9e78518a-02e9-4cec-9e9a-eeb77bdd1108.png)

**Comment by Adimote** [comment]
Oops my initial email missed the committee award, here's my follow-up email:

> <html>
> <body>
> <span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Oops - Apologies, I actually need 6 trophies, not 5. Here are the updated details: (also available on<span> </span></span><a href="https://docs.google.com/spreadsheets/d/1heyZMwoqlj2VJT05EnRO8AfNw5KIqXVVtEjcB6sY1pQ/edit#gid=0" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://docs.google.com/spreadsheets/d/1heyZMwoqlj2VJT05EnRO8AfNw5KIqXVVtEjcB6sY1pQ/edit%23gid%3D0&amp;source=gmail&amp;ust=1649365410832000&amp;usg=AOvVaw1vwv4YDEAWVDG9SNUOJCK9" style="color: rgb(17, 85, 204); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">google sheets</a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">)</span><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
> 
> (All Trophies are the Great Style Slant Jade Glass Award) |   |  
> -- | -- | --
> Size | Code | Engraving
> 24.5cm | GL-290/JC006B | 2022<br/>This Way Up<br/><br/>1st Place
> 21.5cm | GL-290/JC006A | 2022<br/>This Way Up<br/><br/>2nd Place
> 20cm | GL-290/JC006AA | 2022<br/>This Way Up<br/><br/>3rd Place
> 20cm | GL-290/JC006AA | 2022<br/>This Way Up<br/><br/>Rookie Award<br/><br/>Sponsored by<br/>University of Southampton
> 20cm | GL-290/JC006AA | 2022<br/>This Way Up<br/><br/>Robot and Team Image<br/><br/>Sponsored by<br/>Adventurous Machines
> 20cm | GL-290/JC006AA | 2022<br/>This Way Up<br/><br/>Committee Award<br/><br/>Sponsored by<br/>ITDev
> 
> </div>
> </body>
> </html>

**Comment by Adimote** [comment]
received confirmation that they received the order today

**Comment by Scarzy** [comment]
Have they confirmed the delivery date?

**Comment by Adimote** [comment]
They confirm it will be next-day shipped on Thursday

**Comment by PeterJCLaw** [comment]
@Adimote did this ship? Did the arrive?

**Comment by Adimote** [comment]
Yup, they're on the cube balcony right now

**Comment by Adimote** [comment]
Yup, they're on the cube balcony right now
