### ISSUE TITLE
Specify and Design Certificates

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#86]
We need to spec what awards / certificates we want and then design them. These designs must be done in such a way that they can be very quickly populated, and can handle long names.

**Comment by PeterJCLaw** [comment]
Are we doing certificates? SR hasn't done for several years.

Separately, a related resource: https://studentrobotics.org/style/

**Comment by RealOrangeOne** [comment]
Blocked on the decision of whether we're doing certificates or not (My vote is no)
