### ISSUE TITLE
Decide on the winner of the online presence award

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#862]
The online presence award will be decided by the Marketing Team (https://studentrobotics.slack.com/archives/C02C3LDGFP0/p1643237589033200). This needs to happen before the competition.

### Original

[comp/prizes/web-presence](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/web-presence.yaml)

**Comment by PeterJCLaw** [comment]
This is decided (see Slack for details).
