### ISSUE TITLE
Organise the SR2022 post-finals sequence

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#867]
At the end of the competition we want to give out some prizes. We need to plan how we will transition from the finals, through any speeches and run the actual prize-giving ceremony.
We should ensure that anyone who is speaking (whether a volunteer or a guest speaker) knows how long they have, what we're expecting them to talk about and is well rehearsed.
We should include (somewhere) thanks to various people: teams, volunteers, sponsors, etc.

### Original

[comp/prizes/ceremony](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/ceremony.yaml)

### Dependencies

 * #762 Get envelopes & card for the prize ceremony
 * #861 Arrange a speaker for the prize ceremony
 * #862 Take a vote on the online presence award
 * #863 Establish the winner of the first movement award
 * #864 Establish the final results for the main prizes and the rookie award
 * #865 Decide on the recipient of the committee award
 * #866 Decide on the winner of the team image award

**Comment by Scarzy** [comment]
Some sponsors will be sponsoring prizes

**Comment by antoinepetty** [comment]
We should have a short section near the end for how to sign up as a volunteer (we'll likely have a form at the competition to collect this info)

**Comment by Tyler-Ward** [comment]
I have created the following google doc to start documenting the plan https://docs.google.com/document/d/1GZvXxx1lcLcTWxszDB_0w3EEHSC8SThxMImdzev2SXY/edit

**Comment by RealOrangeOne** [comment]
I've populated the plan based on previous years, it could now use a review.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne @Tyler-Ward is there an update on this? Would be great to know where we stand given that the competition is nearly upon us.

**Comment by RealOrangeOne** [comment]
I'm pretty happy with the plan we have. It will need rehearsal, during which some details may change.
