### ISSUE TITLE
Have a rehearsal of the post-finals sequence

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#868]
At the end of the competition we want to give out some prizes. We need to rehearse how we will transition from the finals, through any speeches and run the actual prize-giving ceremony.

### Original

[comp/prizes/rehearsal](https://github.com/srobo/recurring-tasks/blob/master/comp/prizes/rehearsal.yaml)

### Dependencies

 * #867 Organise the SR2022 post-finals sequence

**Comment by Tyler-Ward** [comment]
The key roles involved in the post finals actions should have 2 hours allocated on the Friday setup day so we can perform the rehearsal and adjust plans as needed #80

**Comment by prophile** [comment]
We rehearsed this on Saturday evening.

**Comment by prophile** [comment]
NB: Given the flow of things to happen here, a checklist would be 👌
