### ISSUE TITLE
Publicise the competition on our Social Media

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#876]
In addition to the task-specific social media related to the competition announcement and the news article afterwards we should ensure that our social media accounts make a lot of noise about the competition.
In the lead-up to the competition this means we should be inviting people to attend and reminding competitors to get tickets.
During the competition we should consider including some summary commentary about how the teams are doing, as well as interacting with the accounts for the teams. We should also announce the results as they become available (i.e: during the prize-giving ceremony).

### Original

[comp/social-media](https://github.com/srobo/recurring-tasks/blob/master/comp/social-media.yaml)

### Dependencies

 * #715 Announce the competition

**Comment by sedders123** [comment]
Competition Team have also asked for us to do some recruitment tweets

**Comment by sedders123** [comment]
We have scheduled some posts for a countdown to the event and there is a role for posting social media during the event
