### ISSUE TITLE
Plan the welcome talk for competitors and guests

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#879]
This ticket exists mainly to ensure that things are announced to the competitors.

### Original

[comp/welcome](https://github.com/srobo/recurring-tasks/blob/master/comp/welcome.yaml)

### Dependencies

 * #820 Prepare battery charging station
 * #821 Have a supply of charged batteries by the SR2022 Arenas
 * #836 Plan helpdesk at the competition
 * #837 Set up a power tools area

**Comment by Tyler-Ward** [comment]
Have created a google doc to start drafting the welcome talk contents at https://docs.google.com/document/d/1wp-tph-HSNqUMeHRtkv5kzvMcrsR0aSAC_W0NkOlZm4/edit

**Comment by RealOrangeOne** [comment]
I've now imported the script from SR2019, and made sure it covered your suggestions.

The highlighted areas are still in progress.

**Comment by PeterJCLaw** [comment]
We should mention the pits rules (#839) as part of the welcome talk.

**Comment by prophile** [comment]
Welcome talk happened.
