### ISSUE TITLE
Design Trophies

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#88]
We should work out what trophies we want to award, and then design them.

http://www.trophies2u.co.uk/ is our standard supplier of Trophies

Lets get: https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html (they were used for SR2016 and SB2018)

**Comment by Tyler-Ward** [comment]
Leadtime: 1 week

**Comment by Adimote** [comment]
I can get the source for trophies from trello

**Comment by Adimote** [comment]
http://www.trophies2u.co.uk/ is our standard supplier of Trophies

Lets get: https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html (they were used for SR2016 and SB2018)

**Comment by Tyler-Ward** [comment]
That supplier looks fine, I assume we will get different sizes for each position. 

Some observations (not sure if we care about all of these).
* The engraving font is fixed so wont match the style
* these come without boxes (there is an option at slight increased cost that comes with a presentation box).
* re the font above we should think about how we do the logo part do we want just the round element or the round element with text underneath or to the side.
* also what do we want to have engraved on them.

**Comment by PeterJCLaw** [comment]
Should we consider other suppliers to compare prices?

> I assume we will get different sizes for each position.

:+1:

> Some observations (not sure if we care about all of these).
> 
> * The engraving font is fixed so wont match the style
> * re the font above we should think about how we do the logo part do we want just the round element or the round element with text underneath or to the side.

I think that's fine, as long as the logo has the right font (which we can achieve by rendering the font to a path). I suggest we want the vertically stacked form of the logo (i.e: the same as we're getting on the tee-shirts #85).

> * these come without boxes (there is an option at slight increased cost that comes with a presentation box).

I think that's fine, we've never had presentation boxes in the past.

> * also what do we want to have engraved on them.

- our logo (as noted above)
- the year (2019)
- the name of the prize (from [the rulebook](https://studentrobotics.org/docs/resources/2019/rulebook.pdf))

Do we have any imagery from previous years to compare to? (I think I've seen a photo somewhere, but doubt I'd be able to find it).

**Comment by RealOrangeOne** [comment]
This is what we used in the kickstart presentation, which is the trophies from 2013.

![image](https://user-images.githubusercontent.com/6527489/54476562-a5c21e00-47f6-11e9-9a9f-ece117602f89.png)

**Comment by PeterJCLaw** [comment]
Aha, nice. Let's go with approximately that design unless there's a strong reason not to.

Hrm, we don't seem to have a canonical vertically stacked version of the logo. Should we?
(cc @jimmythompson was it intentional not to have a vertically stacked version of the logo?)

Sizing suggestion, based on getting trophies from @Adimote's [link](https://www.trophies2u.co.uk/products/glass-and-crystal/economy-glass-awards1/great-style-slant-jade-glass-award.html) above:
- 1st Place: 24.5cm
- 2nd Place: 21.5cm
- 3rd Place: 20cm
- Rookie Award: 20cm
- Committee Award: 21.5cm
- Robot and Team Image: 20cm
- ~First Robot Movement~ (edible, #130)
- ~Online Presence~ (edible, #130)

```
      (SR)
Student Robotics
      2019
    Caldera

  <Prize name>
```

This comes to **166.44**:
* 3 × 9.99 (20cm)
* 2 × 10.99 (21.5cm)
* 1 × 11.99 (24.5cm)
* 6 × 5.00 (logos on all)
* 6 × 10.00 (engraving on all)
* 12.50 (logo setup cost)

I'm not sure what our budget for this is, however that's more than I was expecting the total to be. Do we know of any places which do the engraving more cheaply (that seems to be the expensive part here)?

**Comment by Tyler-Ward** [comment]
In previous years we have budgeted about £130 which I assume included edible prizes as well so this would be quite a but higher.

For engraving If someone has access to a laser cutter we could engrave ourselves. But this might be difficult to arrange. @prophile also mentioned somewhere in southampton we have used which might be worth a look.

**Comment by Scarzy** [comment]
> For engraving If someone has access to a laser cutter we could engrave ourselves. But this might be difficult to arrange.

We really don't want these to look knaff. Unless you know someone who can do a REALLY good job of it, then get it's definitely worth getting it done by a proper professional engraver.

**Comment by Adimote** [comment]
I had a look around for other suppliers:

- https://www.trophystore.co.uk/peak-jade-glass-plaque-award-20-5cm More expensive for larger sizes, 17.50 per engraving. Not worth calculating.

- https://www.crystal-awards-supplier.co.uk/10in-tall-jade-glass-mountain-award.html is 3x more expensive for everything. Not worth calculating.

- https://www.trophymaster.co.uk/peak6-jade-glass-8mm-03-thick-203mm-8-525615-p.asp no logo set-up cost, flat £14 fee for logo + text. This totals £148.

We could go for Trophymaster. I'm happy to co-ordinate this as long as I have an address to send them to.

**Comment by PeterJCLaw** [comment]
@Adimote nice :+1:
If they come in (roughly) the same sizes, Trophymaster seems likely to be fine. Do you want to grab #134 as well?

Related question: how do the lead times compare?

**Comment by Tyler-Ward** [comment]
£148 for trophies is fine if you are able to order.

**Comment by Adimote** [comment]
The design choices are:
A:
![image](https://user-images.githubusercontent.com/2551763/54567866-93eaa180-49d5-11e9-8cff-1643fe618d4e.png)

or

B:
![image](https://user-images.githubusercontent.com/2551763/54567890-a369ea80-49d5-11e9-8d7e-fe22fc8f7462.png)

**Comment by Adimote** [comment]
B:
![image](https://user-images.githubusercontent.com/2551763/54567890-a369ea80-49d5-11e9-8d7e-fe22fc8f7462.png)

**Comment by PeterJCLaw** [comment]
I'm mildly in favour of the latter as it's closer to what we have on the tee-shirts and is more what I'd expect from a vertically stacked logo (the text to be similar in width to the roundel).

**Comment by PeterJCLaw** [comment]
Do we have any control over the font/size/formatting/etc. of the other text? If so, I'd suggest going with one of our house styles and it being neither italicised or emboldened.

**Comment by Adimote** [comment]
I can ask but it looks like we don't have control of the font

**Comment by Adimote** [comment]
I think I'll go for option B, as it doesn't look too bad after staring at it for a while, and I'm worried the font will be too small in A, as I was a bit generous with the logo sizing when making the mocks

**Comment by Adimote** [comment]
for the "Robot and Team Image" award, should the text be "Robot and Team Image" or "Robot and Team Image Award"?

**Comment by PeterJCLaw** [comment]
I don't feel strongly; I'd look at whether the longer name would cause the text to wrap.

(a)
```
Robot and Team Image
```
is fine

(b)
```
Robot and Team
     Image
```
is kinda weird

(c)
```
Robot and Team Image Award
```
is also fine

(d)
```
Robot and Team Image
       Award
```
is kinda weird, though probably better than (b)

(e)
```
Robot and Team 
  Image Award
```
is almost worse


In summary; I think any of (a), (c) or (d) are probably fine (with a preference for (e) over (b) if we're stuck with one of those).

**Comment by Adimote** [comment]
I went for option A, as I'm conscious of line length for C.

I've now placed the order, so I'll close this ticket.
