### ISSUE TITLE
Prepare signage for the SR2022 Competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#880]
We'll want to put up various signage of our own, even if the venue cover the basics. For example, we have our own giant banner which should go somewhere and we'll want directions to Helpdesk and the Areans.

### Original

[comp/venue/signage](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/signage.yaml)

### Dependencies

 * #725 Prepare a layout of the competition

**Comment by sedders123** [comment]
We have a [signage](https://github.com/srobo/signage) repository that we can likely use a base

**Comment by Scarzy** [comment]
We probably want some COVID related signage too

**Comment by RealOrangeOne** [comment]
Signage: https://docs.google.com/presentation/d/12wD2JXHxDHOTe5ymerCehyfl5H_GK0lfUasdEOIRIQQ/edit?usp=sharing

**Comment by RealOrangeOne** [comment]
> We probably want some COVID related signage too

What did you have in mind?

**Comment by Scarzy** [comment]
>> We probably want some COVID related signage too
>
> What did you have in mind?

Some general reminders based on the COVID policy.

Also, we should have signage related to any theatrical effects we intend to use in the cube, and signs telling third parties that SUSU is off limits during the setup days

**Comment by Scarzy** [comment]
COVID sign added (I couldn't easily find any free to use logos)
No theatrical effects expected, so no sign
