### ISSUE TITLE
Plan setup schedule and organisation

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#881]
We need to plan tasks for the setup days

### Original

[comp/setup-plan](https://github.com/srobo/recurring-tasks/blob/master/comp/setup-plan.yaml)

### Dependencies

 * #725 Prepare a layout of the competition

**Comment by WillB97** [comment]
Setup schedule is at https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
