### ISSUE TITLE
Install things on the set-up day

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#882]
### Original

[comp/setup](https://github.com/srobo/recurring-tasks/blob/master/comp/setup.yaml)

### Dependencies

 * #868 Have a rehearsal of the post-finals sequence
 * #880 Prepare signage for the SR2022 Competition
 * #881 Plan setup schedule and organisation

**Comment by WillB97** [comment]
This task description needs to be fleshed out and a more clear title chosen. Also should #868 be a dependency of this.

**Comment by PeterJCLaw** [comment]
I believe #868 is mentioned here mostly to highlight that it should happen before the competition days themselves while also reflecting the reality that it would be hard to do until the arena area has been installed.

**Comment by WillB97** [comment]
This is probably covered by the setup schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
