### ISSUE TITLE
Tear down everything after the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#884]
Everything will need tearing down at the end of the competition.

### Original

[comp/tear-down/main](https://github.com/srobo/recurring-tasks/blob/master/comp/tear-down/main.yaml)

### Dependencies

 * #883 Create a list of return destinations for everything

**Comment by WillB97** [comment]
This is covered by the setup/teardown schedule https://docs.google.com/spreadsheets/d/1WPH4bMP73kNJ89n6HU0KKuJAs5iNczM-xTuH6jtggnM/edit?usp=sharing
