### ISSUE TITLE
Return stuff from the competition to storage

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#885]
Equipment that came from storage for the competition needs to return there after the competition.

### Original

[comp/venue/transport/return](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/return.yaml)

### Dependencies

 * #729 Hire a van for transporting kit between storage and the venue
 * #730 Transport stuff to the competition
 * #884 Tear down everything after the competition

**Comment by prophile** [comment]
The remaining bits are stored either at my house or in the Clubs and Socs room. We're taking it up to Newbury tomorrow in a van.

**Comment by PeterJCLaw** [comment]
This is underway. Some stuff remains at @prophile's house though most is now in storage.

**Comment by Adimote** [comment]
Container is now filled
