### ISSUE TITLE
Reimburse volunteers

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#887]
We need to reimburse volunteers for all the things. This task exists mostly as a placeholder, the treasurer will of course be handling this ongoing anyway.

### Original

[comp/volunteers/reimbursement](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/reimbursement.yaml)

### Dependencies

 * #802 Plan reimbursement of volunteers

**Comment by WillB97** [comment]
>There is now a process in place to be reimbursed by the trustees, which was sent to all volunteers in an email. Claim form can be found at https://docs.google.com/document/d/1rYpWmxDG-XtN2D9WV_K9KPYDuaqbc3t34vvc8W3KyEA/edit
>
>_Originally posted by @sedders123 in https://github.com/srobo/tasks/issues/802#issuecomment-1078473683_
