### ISSUE TITLE
Gather feedback from teams

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#889]
Send to everyone who was signed up for SR2022.
Usual things:
  - Demographics
  - Prior experience
  - Did they get the support they needed
  - Are Tech Days useful to them?
  - Do they feel that they have the resources in school now?
    If not, why aren't they coming/what can we do to make them more useful?
    Is more real-competition testing the key factor here?

Example from SR2020: https://docs.google.com/forms/d/1HE8b1oRF6dHc3wbBUICJV5CsXHv3qR7egcMtud6pfd4/edit?usp=sharing

### Original

[comp/feedback/gather-team-feedback](https://github.com/srobo/recurring-tasks/blob/master/comp/feedback/gather-team-feedback.yaml)

**Comment by PeterJCLaw** [comment]
Also feedback about the game: https://github.com/srobo/tasks/issues/309

**Comment by PeterJCLaw** [comment]
I'm starting on a form at https://docs.google.com/forms/d/1xfuUsZ5Snb2bAqk993VYFscdOj02H0sMSHVuNAeFYjA/edit.

**Comment by PeterJCLaw** [comment]
For the "What are the gender proportions of your team?" question, should we have a "Prefer not to say" option? (We already have a "non-binary" option)

**Comment by RealOrangeOne** [comment]
We did have this option in the SR2021 survey:

![image](https://user-images.githubusercontent.com/6527489/160287109-c998d8eb-471c-45f2-8429-9d21134b393d.png)

**Comment by PeterJCLaw** [comment]
As a thought on how we can get lots of submissions from competitors -- could we have a box of cookies/chocolates/something at the competition and ask people to complete the form and then show us the completion page on their device in exchange for a cookie/chocolate/whatever? I've seen this work well at conferences (I got a pair of "free" socks this way).
Obviously there's a risk of multiple submissions or other scam behaviours, but I don't think that's a big deal (we can set the form to make duplicate submissions hard anyway) and it's not like the cookies/whatever would cost a lot.

**Comment by PeterJCLaw** [comment]
I've started on feedback forms for competitors & team supervisors, both are a mix of last year's and 2020's. Both in https://drive.google.com/drive/u/1/folders/1uM_fbQCp7q4UarFm4EJ4S7CY0Ye1n1cC.

**Comment by PeterJCLaw** [comment]
Ok, I think the competitor feedback form is now in a state that would be useful to get some review on.

**Comment by PeterJCLaw** [comment]
> we can set the form to make duplicate submissions hard anyway

This turns out to need sign in to Google, so that's probably not an option. I'm still not worried about it though.

**Comment by PeterJCLaw** [comment]
Ok, first pass at the team supervisors form is done also.
Likely both forms need a pass through working out which questions are required and which aren't, but I think they're now both asking about the right questions.

**Comment by JennyLynnFletcher** [comment]
In terms of incentivising students to fill out the feedback forms, an easy way is to offer food, a potentially cheaper (but less effective) way is the same but it's a prize draw for some chocolates or similar. Some other trade-in mechanism apart from food could also work but I'm not sure I can think of any specific mechanisms.

**Comment by PeterJCLaw** [comment]
Are there any gambling rules around it being a prize draw? (That also means we need to keep track of who's entered, which feels more effort than it's worth for this)

**Comment by Scarzy** [comment]
There are definitely gambling rules about this

**Comment by RealOrangeOne** [comment]
I've had a review of the forms we currently have, and sent them over to the trustees for sign-off.

**Comment by RealOrangeOne** [comment]
I've implemented the first round of trustee feedback, still awaiting sign-off.

**Comment by PeterJCLaw** [comment]
Since we've published the forms and invited teams to use them, I'm hoping we had sign off from the trustees?

**Comment by PeterJCLaw** [comment]
This was collected. We reviewed it in the competition team meeting this evening. Was substantially positive.
