### ISSUE TITLE
Gather feedback from volunteers

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#890]
Send to everyone who was signed up for SR2022.
SR2020 Feedback form: https://docs.google.com/forms/d/1nIG36tZNykCxgilKXOT6TJiY2je3iHR2YNMtoXeLeJw/edit?usp=sharing

### Original

[comp/feedback/gather-volunteer-feedback](https://github.com/srobo/recurring-tasks/blob/master/comp/feedback/gather-volunteer-feedback.yaml)

**Comment by PeterJCLaw** [comment]
I've started on a form for this at https://docs.google.com/forms/d/10OBefv4_P3GdxKgzwEAfDx3g6aCoB2vNs55i84--VoY/edit.

Should we be capturing demographic information about volunteers? We don't currently, but perhaps we should? Not immediately sure what we'd use it for though, so we should answer that question first.

**Comment by PeterJCLaw** [comment]
Feedback has been had and looked at.
