### ISSUE TITLE
Create post competiton reports

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#891]
We should give a report on the SR2022 competition cycle and details of the event to the trustees once everything from the event has been sorted out. This will also include a spending report for the year.

### Original

[comp/feedback/post-competition-reports](https://github.com/srobo/recurring-tasks/blob/master/comp/feedback/post-competition-reports.yaml)

### Dependencies

 * #889 Gather feedback from teams
 * #890 Gather feedback from volunteers

**Comment by PeterJCLaw** [comment]
While this is mostly about teams and volunteer feedback, I wonder if each of the area owners should write up a summary of how things went? This could be a useful reflection exercise as well as providing the trustees with understanding.

**Comment by prophile** [comment]
That sounds like a good idea. Would be good to indicate some kind of outline for each of the area owners as to what areas to cover and how much to fill in on each part?

**Comment by PeterJCLaw** [comment]
We ended up covering some of this in the all volunteers meeting which the trustees organised and @Scarzy minuted.
To close this off we should send the trustees the feedback details.

**Comment by Adimote** [comment]
obsolete
