### ISSUE TITLE
[Meta] Tidy up after the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#893]
Root ticket for all cleanup related items

### Original

[comp/cleanup](https://github.com/srobo/recurring-tasks/blob/master/comp/cleanup.yaml)

### Dependencies

 * #884 Tear down everything after the competition
 * #885 Return stuff from the competition to storage
 * #886 Switch the website back to the normal homepage
 * #887 Reimburse volunteers
 * #888 Crop the live stream VOD (Video on Demand)
 * #891 Create post competiton reports
 * #892 Send a wrap-up email to teams

**Comment by WillB97** [comment]
Everything remaining has it's own ticket.
