### ISSUE TITLE
[Meta] Have the SR2022 competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#894]
We need to have the SR2022 competition event.

### Original

[comp/main](https://github.com/srobo/recurring-tasks/blob/master/comp/main.yaml)

### Dependencies

 * #714 Find and book venue for SR2022
 * #715 Announce the competition
 * #717 Publish a news article following the SR2022 Competition
 * #718 Acquire public liability insurance for the competition
 * #720 Sort out sound system for the competition
 * #721 Ensure there is power at the SR2022 competition
 * #722 Have a printer (and paper/ink) at the competition
 * #723 Have a competition network
 * #725 Prepare a layout of the competition
 * #726 Hire radios for the competition
 * #730 Transport stuff to the competition
 * #731 Organise arena lighting
 * #732 Organise cable protectors
 * #739 Organise computer hardware for the competition
 * #743 Work out the day schedules for the competition
 * #750 Organise media consent for SR2022
 * #752 Order wristbands for SR2022
 * #753 Arrange a reception desk at the competition
 * #759 Kit handback arrangement
 * #765 Print all the things for SR2022
 * #773 Ensure the SR2022 competition is safe
 * #775 Organise tinker time
 * #790 Arrange a live stream from the competition
 * #793 Uprate the competitor-services server _before_ the competition starts
 * #796 Update the website for the live SR2022 competition
 * #825 Have an arena
 * #831 Ensure volunteers are equipped at the competition
 * #832 Brief Volunteers on Competition Event
 * #842 Prepare team pits at the competition
 * #850 Have the SR2022 games
 * #856 Have Ops at the SR2022 Competition
 * #869 Organise prizes for the competition
 * #873 Get photos of Teams and Robots at the competition
 * #874 Have kit testing equipment available at the competition
 * #875 Show the live stream within the venue
 * #876 Publicise the competition on our Social Media
 * #877 Invite press to the competition
 * #878 Invite sponsor representatives to the competition
 * #879 Plan the welcome talk for competitors and guests
 * #882 Install things on the set-up day
 * #884 Tear down everything after the competition
 * #893 Tidy up after the competition

**Comment by PeterJCLaw** [comment]
This happened.
