### ISSUE TITLE
Update COVID Guidance

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#895]
https://studentrobotics.org/covid-19/ is looking quite old now, having last been updated at the start of December. We'll definitely need to have _something_ in place prior to the competition and likely should have some idea what this will be for volunteers who are now signing up (as this may impact their decision on whether to come).

**Comment by Scarzy** [comment]
So, there are a couple of aspects to this; the things we can achieve easily and regardless of external factors, and things that are more subject to external factors/guidance.

Examples of things we can achieve easily;
- Cleaning commonly touched surfaces
- Requesting people who are showing symptoms do not show up
- Requesting people wear facemasks

Example of things dependent on external factors;
- Checking COVID passes
- Requesting testing

Important factors to consider here are what is actually available or required in countries our volunteers and teams are in, and what's available in the country the event is hosted in. For example the fact that testing isn't going to be freely available in England at the time of the competition poses a significant concern around requesting testing.

I suggest we start with volunteers adding onto here things they would like to see in place. If anyone isn't comfortable posting it publically then they can email me and I'll add it on anonymously. Once we've got a list of options we can consider what is actually feasible. I suggest we put a deadline on people adding to this by 23:59 20/03/22

**Comment by PeterJCLaw** [comment]
I'm :+1: on requesting masks and strongly discouraging anyone with symptoms from turning up. If we're able to turn away people with symptoms that's preferable.

Having sanitiser available might be nice, though being clear on whether or not it's provided would allow those who want it to choose to bring their own.

I think we should ensure the venue is well ventilated -- we should work out ahead of time which doors/windows we expect to be able to open.

**Comment by Scarzy** [comment]
This is stalled pending getting the venues own risk assessments.

**Comment by Scarzy** [comment]
Pending updates from the venue on their policies

**Comment by WillB97** [comment]
Worth noting:  https://www.gov.uk/guidance/people-with-symptoms-of-a-respiratory-infection-including-covid-19#Children

> It is not recommended that children and young people are tested for COVID-19 unless directed to by a health professional.

**Comment by Scarzy** [comment]
I have a whole list of resources of government/NHS guidance I dug through to get to this. I wasn't going to bother referencing all of it here.

To my mind there are multiple issues just regarding testing, also including that no-one can require anyone to undergo a medical treatment (which is ultimately what a covid test counts as), and without them being free to access then we would isolate anyone from poorer backgrounds.

**Comment by PeterJCLaw** [comment]
> without them being free to access then we would isolate anyone from poorer backgrounds.

I appreciate the sentiment, but they're also not exactly expensive either -- Boots sells 5 packs for substantially less than I expect most people will spend on their travel to the competition: https://www.boots.com/flowflex-antigen-rapid-test-lateral-flow-self-testing-kit-5-tests-10312496 (smaller packs are available for less money though worse value and other pharmacies have them at similar prices)

**Comment by Scarzy** [comment]
Received a response from the venue, filtering through them

**Comment by Scarzy** [comment]
Nothing needed to change based on info from the venue
