### ISSUE TITLE
Add reverse DNS

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#897]
While IP reputation is still important, increasingly inobx providers are relying on DNS reputation rather than IP reputation. The motivations for this include IPv6, where IPs are much easier to change than under IPv4 (since there are so many of them).

We can therefore help our email deliverability by setting up reverse DNS for our domain(s).

**Comment by PeterJCLaw** [comment]
From what I can tell, Digital Ocean don't support explicit [reverse DNS (PTR) records](https://docs.digitalocean.com/products/networking/dns/how-to/manage-records/#ptr-rdns-records). This probably means we need to move our DNS elsewhere to add them.

**Comment by trickeydan** [comment]
@PeterJCLaw  You should be able set the rDNS in Mythic even if the forward dns is in DigitalOcean? Why wouldn't you be able to?

**Comment by PeterJCLaw** [comment]
I'd kinda assumed that it had to be in Digital Ocean, though that doesn't actually make sense given that the IP addresses will resolve into Mythic's system. Yeah, we can probably add this in Mythic.

**Comment by PeterJCLaw** [comment]
Duly configured: 
![image](https://user-images.githubusercontent.com/336212/224832869-8c76e366-d7d7-445c-ab97-5857cd791cd3.png)

Since we don't send email from these machines I'm not sure that this will actually have any impact on our email sending though.

This is also something that we'll need to do ongoing as we rotate new machines in & out.

**Comment by trickeydan** [comment]
I'm pretty sure it's possible to set rDNS up when creating a VPS on mythic, although not actually sure if that's dependent on hosting DNS with Mythic too. Something to look out for and document probably..

**Comment by PeterJCLaw** [comment]
Yeah, I think we can get something by default, though the domain is the plain reverse into mythic domain (whereas adding our own is slightly nicer).
