### ISSUE TITLE
Organise Eduroam accounts for SR2022

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#899]
Various things at the competition will need access to Eduroam:
- teams
- volunteers
- various displays

Since these will all come from the same place, we should get them all together.

**Comment by RealOrangeOne** [comment]
@Adimote you mentioned this should be something as simple as an email to Southampton. Is this something you are already doing?

**Comment by Adimote** [comment]
I've just now sent an email to Joyce in Southampton, will keep you posted!

**Comment by Adimote** [comment]
Joyce has sent me some eduroam accounts, though sadly I didn't realize we were providing accounts for teams (I remember we had a meeting where we just discussed volunteers and screens), so I only asked for 20. I'll ask for more unless anyone has a bright idea on how we can use 20 for the entire competition

**Comment by WillB97** [comment]
We should get at least 1 account per team and another few for volunteers and screens. Say 35-40.

**Comment by Adimote** [comment]
Joyce just forwarded me an email with 40 eduroam guest accounts, consider these received!
