### ISSUE TITLE
Decide on the Awards we will give out

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#9]
We need to announce what the awards will be for the competition, so the teams know what they're working towards.

IIRC we usually have:
- 1st place
- 2nd place
- 3rd place
- Trustees award (Core Team award?)
- Robot and Team Image
- Online presence
- Rookie award
- First Robot Movement (rookies only)

copied from https://github.com/srobo/core-team-minutes/issues/45

**Comment by Adimote** [comment]
> In the [2017 competition](https://studentrobotics.org/docs/resources/2017/rulebook.pdf), there was also a rookie award and a "first robot movement" award.

from @anowlcalledjosh

**Comment by Adimote** [comment]
> Thanks Josh, have added them!
from @Adimote

**Comment by PeterJCLaw** [comment]
I think the decision here probably sits with @prophile as the Head Judge.
The list looks good to me though.

**Comment by RealOrangeOne** [comment]
Discussions were had on Saturday about possibly having a sponsor-decided price, which they decide, and also (ideally) present.

**Comment by PeterJCLaw** [comment]
This happened and were included in the presentation (#10).
