### ISSUE TITLE
Design Team Photo Frames

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#90]

**Comment by Tyler-Ward** [comment]
See https://www.flickr.com/photos/110429792@N04/albums/72157644599478484 for the ones I made for 2014

**Comment by Tyler-Ward** [comment]
here is the git repo for the previous designs https://www.studentrobotics.org/cgit/photoborders.git/tree/

**Comment by Tyler-Ward** [comment]
@TomWheal you had a design for this in another ticket (#89) which might be good here. 
it might need a slight edit so that we can fit both the school,team name and awards on it if we still want to include all of those.

**Comment by Tyler-Ward** [comment]
The repo has now been moved to github at https://github.com/srobo/photo-borders this could be merged into https://github.com/srobo/promotional-material what are peoples opinions on this.

**Comment by RealOrangeOne** [comment]
For now, I think it's fine. `promotional-materials` isn't an ideal name, as it contains things which aren't use solely for promotion. I personally don't see an issue with having repos for each item, but that's a separate conversation.

**Comment by TomWheal** [comment]
I'm happy to refine the design for this, as it's similar to the signage(#83 ) with the python scripts. If I make the designs, can someone (maybe @Tyler-Ward if you have time) okay to look at getting the scripts working for both?

**Comment by TomWheal** [comment]
Also as there is no lead time on this, it is merely nice for releasing photos after the comp, I'm going to leave this till closer to the competition when I have more time.

**Comment by PeterJCLaw** [comment]
I don't think this is going to happen.

**Comment by TomWheal** [comment]
This can still be done if wanted, it completely slipped my mind
