### ISSUE TITLE
Authenticate Livestream machine with YouTube

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#901]
For the livestream, we need the ability to modify things on the YouTube livestream. For this, we need access to YouTube.

I suggest the way we do this is by creating a `livestream@` Google account, purely for this purpose, and add it to the YouTube account. This way, it doesn't require an individual logging in with their account.

This will require both the account being created, and it then being added to the YouTube channel.

### Dependencies

- #788 Organise hardware to run livestream

**Comment by sedders123** [comment]
In the past I believe we've only needed a Stream key, why do we need a full account now?

**Comment by RealOrangeOne** [comment]
It would be nice to be able to access the chat, live stream, and stop/start the stream as needed.

**Comment by sedders123** [comment]
We can admin the chat with moderator accounts, interested in why we'd need to stop/start the stream. It looks like YouTube can auto start and stop streams based on the RTMP feed and personally I think a holding screen might be better for pauses.

Auto stopping could be dangerous but there will be people present at the competition that can press the button

**Comment by PeterJCLaw** [comment]
@RealOrangeOne is this on the right milestone? If this really is prep, is there anything blocking it?

**Comment by RealOrangeOne** [comment]
I have created a `livestream@studentrobotics.org` Google account. Sadly, I can't give it access to YouTube, as I don't have the right permissions. Will need someone with more Google Admin than I (oh hey @dianedowling )

Once that's done, we can get it added to the YouTube channel, and use it from there.

**Comment by Tyler-Ward** [comment]
I have been sent the stream keys by @antoinepetty @RealOrangeOne I will forward them to you to insert into the livestream machine, I think these are all we need but let me know if we will need anything else

**Comment by antoinepetty** [comment]
There's something very weird going on with the actual YouTube account login creds so short-term looks like we can't assign new users. For now, we have a few volunteers who have access with their own accounts.

**Comment by antoinepetty** [comment]
Scarzy has access to that account and has given livestream@ manager-level control

**Comment by RealOrangeOne** [comment]
Excellent, but sadly the `livesteam@` account has its access to YouTube disabled, and I don't have permission to override it in the admin.

I'll authenticate the livestream box with the account during setup.

**Comment by antoinepetty** [comment]
@sedders123 did we manage to sort this out for your account?

**Comment by sedders123** [comment]
Yeah my account is all sorted

**Comment by antoinepetty** [comment]
@Scarzy Are you able to do the same for `livestream@` please?

**Comment by Scarzy** [comment]
Yes. Nudge me on Slack this evening.

**Comment by Scarzy** [comment]
It should now have access to YouTube (they say allow up to 24 hours for the setting to filter through)

**Comment by antoinepetty** [comment]
Thanks Scarzy!

**Comment by prophile** [comment]
This is presumably resolved now?

**Comment by Tyler-Ward** [comment]
It is yes
