### ISSUE TITLE
Purchase items for the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#902]
A range of items need to purchase for the competition. The canonical list is in the [freight list].(https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit#gid=1181706331&fvid=1017945430)

- [x] #807 
  - [x] Blue gaff
  - [x] ~Black gaff~
  - [x] White gaff
  - [x] 1 inch black tape
- [x] #755 
  - Arena markers (2x comp, 1x dev)
- [x] 6ft x 4ft Hardboard
- [x] Radio mic batteries
- [x] A4 paper (#797)
- [x] #745 
- [x] Banner
- [x] #798
- [ ] #827 
- [x] Edible Prizes
- [x] Trophies
- [x] Cans
- [x] #752 
- [x] #816
- [x] #817 
- [x] screwdriver bits

Once they are purchased change them to "On Order" or the person they have been delivered to.

**Comment by PeterJCLaw** [comment]
Closing as this is basically all done. The only outstanding task is https://github.com/srobo/tasks/issues/827, which remains open for its own tracking (though it sounds like the majority of that purchasing has already happened too).
