### ISSUE TITLE
Organise borrowed items

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#903]
There are some items that we use at competitions that we don't have the budget to buy ourselves and volunteers have kindly agreed to loan some of these in the past.

The outstanding items we are looking for are at https://docs.google.com/spreadsheets/d/1VBaqfzK6x-DpunfKygHIvwA1mvfaT8V1tUcV60vxKxY/edit#gid=1181706331&fvid=512752156

- [x] Overhead pi scoring camera
  - [x] Webcam
- [x] Drill/Electric Screwdriver
- [x] Saw
- [x] Desk lamp
- [x] Camera for team photos
- [x] Camera tripod for photo studio
- [x] 2x DVI-HDMI cable
  - [x] 2x HDMI cables from Tyler
  - [x] 2x DVI-HDMI adapters from James
- [x] HDMI-VGA adapter
- [x] VGA cable
- [x] 4x HDMI cable
  - [x] 2x from Jake
  - [x] 2x from Tyler

**Comment by Tyler-Ward** [comment]
I will be brining my camera and tripod as i am covering the group photo, someone is welcome to use it for team photos as well.

**Comment by Tyler-Ward** [comment]
I can also bring some tools (drill+impact driver), it would be good however if SR have some screwdriver bits as previous events have shown that these often get returned broken.

**Comment by Tyler-Ward** [comment]
For the overhead scoring camera I can provide the pi and poe hat, and SR have some picams/webcams we can use

**Comment by WillB97** [comment]
Thanks @Tyler-Ward, can you bring your camera, tripod, scoring camera bits & drill.

**Comment by Tyler-Ward** [comment]
Do SR have screwdriver bits already or do we need to get some?

**Comment by WillB97** [comment]
No, I've added this to the purchase list.

**Comment by WillB97** [comment]
@sedders123 Can you bring the HDMI-VGA adapter from the compbox
@Tyler-Ward/ @RealOrangeOne Can you bring a VGA cable

**Comment by RealOrangeOne** [comment]
I have at least 3 VGA cables, and 2 HDMI cables I will bring

**Comment by WillB97** [comment]
Note that the 2 DVI-HDMI cables does not include whatever you're using to hookup the livestream monitor.

**Comment by RealOrangeOne** [comment]
I have my own DVI-HDMI cable I will use for the livestream monitor, which is separate to the other cables. I also have a DVI-HDMI dongle, which with an HDMI cable can become another DVI-HDMI cable.

**Comment by WillB97** [comment]
Refer to the freight list for borrowed items
