### ISSUE TITLE
Make a plan for volunteer lunches

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#905]
If we aren't providing them we need to tell volunteers they need to bring them.

**Comment by Scarzy** [comment]
As there is no budget for lunches, I suppose specifying "bring your own" is the only available option. Unless anyone has an alternative suggestion?

If not, can we close this?

**Comment by WillB97** [comment]
That probably needs mentioning in #804

**Comment by Tyler-Ward** [comment]
Given the marathon blocks access to food on Sunday we should make sure to send info on how they should get food/that they should bring food (even if we are not providing it) before closing this otherwise volunteers wont have time to go and get food.

**Comment by Scarzy** [comment]
> Given the marathon blocks access to food on Sunday we should make sure to send info on how they should get food/that they should bring food (even if we are not providing it) before closing this otherwise volunteers wont have time to go and get food.

Yes, this will be mentioned in #804, and is still a dependency of #804 to ensure it is mentioned.

But that is not relevant to this task, we now have a plan.
