### ISSUE TITLE
Get carrots to foodbank

### ISSUE THREAD

**Issue by Scarzy** [srobo/tasks#906]
We will have leftover tins of carrots. These shouldn't go to waste.

We need to keep hold of the labels so they can be stuck back on.

**Comment by PeterJCLaw** [comment]
@prophile as the cans are at your place, are you able to take this?

**Comment by prophile** [comment]
Wilco, could someone send me the last email from the food bank?

**Comment by RealOrangeOne** [comment]
@Scarzy was the one who made the initial contact

**Comment by Scarzy** [comment]
Message ID: ***@***.***>I believe I
forwarded the e-mail chain to you on Monday

**Comment by sedders123** [comment]
The carrots have been given to Tommy
