### ISSUE TITLE
Determine coloured tape roll sizes

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#907]
In https://github.com/srobo/tasks/issues/807#issuecomment-1093400322 I realised I didn't know what size rolls of coloured tape we've got. I suspect they're 50m rolls (since "55 yard" and "150 feet" rolls seem to be the norm online), but don't know. When working out how much we need to get this is fairly important.

If we can determine this from our own records that's great, we should record it somewhere. If not we should see if they've got it written on them when we next have them in our hands (i.e: at the competition).

**Comment by RealOrangeOne** [comment]
Looking at https://github.com/srobo/tasks/issues/98#issuecomment-475907988, We've ordered https://www.gaffatape.com/fluorescent-gaffer-cloth-tape/, which appears to be 22.8m per roll

**Comment by WillB97** [comment]
Rolls from https://www.10outof10.co.uk/acatalog/gaffer_tape.html will be 50 meters
