### ISSUE TITLE
Prepare a list of expected visitors

### ISSUE THREAD

**Issue by Scarzy** [srobo/tasks#908]
We should know of any expected visitors (e.g. sponsors, media), when they are expected, and who to fetch to deal with them. This list should be available at reception.

#877 
#878
#861

**Comment by Scarzy** [comment]
Started here: https://docs.google.com/document/d/18dI3x8HmjroagfnvnBp1lr2LNqLEpO-3MT3iKoCZJ0M/edit

**Comment by sedders123** [comment]
List has been populated to the best of our ability
