### ISSUE TITLE
Prepare info for livestream coordinator

### ISSUE THREAD

**Issue by antoinepetty** [srobo/tasks#909]
We had feedback from SR2019 that we should compile information for the livestream commentators to use for filler chat.

We could print information such as:

- Team names & TLAs
- Robot pictures against names (not sure how we'd do this)
- Some information on team progress and strategy leading up to the competition

**Comment by RealOrangeOne** [comment]
This information is also quite useful for commentators

**Comment by antoinepetty** [comment]
Made a start here https://docs.google.com/spreadsheets/d/1mhbIHWwd4hW_3o6Nd1xncWnU8Gcezf1C9XwgsTz9ZFo/edit#gid=0

**Comment by PeterJCLaw** [comment]
This was prepared.
