### ISSUE TITLE
Design Wristbands

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#91]
Assuming we are using wristbands.

Wristbands typically are a single solid colour with 'STUDENT ROBOTICS [logo], [GAME NAME]' around the wrist. They typically are made of embroidered cloth, and have metal crimps attached.

**Comment by Tyler-Ward** [comment]
Do we have the designs from previous years anywhere?

**Comment by PeterJCLaw** [comment]
I'm not sure. The [`marketing`](https://www.studentrobotics.org/cgit/marketing.git) repo is probably where I'd look. Alternatively @richardbarlow might know where they are?

**Comment by Tyler-Ward** [comment]
Leadtime 2 weeks+delivery

**Comment by sedders123** [comment]
[Template for wristband design](https://idc.ftpstream.com/409692/98cc0531323877c6ecf310baaa1eaf83/festivals/marketing/Specs/Fabric_Metal_Ring_Woven_16mm.pdf)

**Comment by Tyler-Ward** [comment]
For reference here are a few previous designs, expect we can probably do better though. looking at the design criteria we can use up to 8 colors and the cost doesn't seem to change if we use less. 
![image](https://user-images.githubusercontent.com/3390465/53688791-3140a700-3d41-11e9-8182-1fbcc99356df.png)

**Comment by PeterJCLaw** [comment]
I quite like the relative simplicity of the designs we've had and would be in favour of following that pattern. (Doing so also has the benefit that we don't need to spend time worrying about this).

Given the theme of this year's competition, maybe let's go with a red strap? (that also keeps it clearly distinct from previous years)

**Comment by Tyler-Ward** [comment]
@mltnhm do you know when you are likley to have this done, if you are busy we can take a look at the southampton meeting this evening

**Comment by Tyler-Ward** [comment]
It would be good to have a bit more of a background pattern or similar on the wristbands to make them look batter, if going for red could do a lava style texture. these are one of the main souvenirs that competitors keep so it is worth putting some effort into making them look good.

**Comment by mltnhm** [comment]
[SVG](https://doggo.cloud/s/fCx9zytbcHM3zbM)

Didn't really know what to add. Could do a two-tone design but it might be difficult to make that look nice with the lock in the way.

**Comment by RealOrangeOne** [comment]
This looks great. We might want to shift the wording to the left more to ensure that when crimped, it still visible.

Depending on what's supported by the manufacturer, it would be nice to get some flame / red decal on it too, but that's definitely not a requirement.

**Comment by Tyler-Ward** [comment]
Done a quick test and could do something like the following for a lava background if people like the style. Also do we want to follow the brand for the SR name or are we happy with plain text

![band2](https://user-images.githubusercontent.com/3390465/53870713-aa1a5a00-3ff2-11e9-93f4-885a3e2b8a86.png)

**Comment by PeterJCLaw** [comment]
@mltnhm nice!

Since we've used a dark blue before, I'd suggest we should pick a different colour. While it sounds rare, we've seen a number of people still wearing older wristbands at our events.

@Tyler-Ward interesting lava! I wonder if we can do something like that which is a little bit less busy? It might just be making the chunks larger or the colours a bit closer together? (My concern is that the text would be hard to read against that background, even though it's really cool)

@mltnhm what font is used in the wristband? It looks a lot like it's Eurostile, which Unfortunately is our old house style. Per https://studentrobotics.org/style/, I think we should be using Quicksand for the name (or, better, an SVG path which has already been rendered from the font, if the printing company support that) and either Oswald or Open Sans Condensed for everything else.

@Tyler-Ward do you have a photo of the other end of your wristbands? I'm trying to recall if we usually have some more text there?

**Comment by mltnhm** [comment]
How does this look?
![srobo_wristband](https://user-images.githubusercontent.com/6197148/53871950-15fdc200-3ff5-11e9-9959-25792c7f633c.png)

**Comment by RealOrangeOne** [comment]
This looks really cool! It's hard to tell if the contrast between the font and background is high enough from the image vs print. I suspect it's fine. 

We should also push the source SVG to GitHub, in the https://github.com/srobo/promotional-material/, in a subdirectory, like `wristbands/2019/image.svg`

**Comment by Tyler-Ward** [comment]
we can darken down the bright yellow to increase contrast with the text, if people like the lava design style I will finish the wrest of the band (currently only done a small section and tiled it). 

![image](https://user-images.githubusercontent.com/3390465/53872811-e94aaa00-3ff6-11e9-9a4b-29b982d7c39f.png)

**Comment by RealOrangeOne** [comment]
I agree with @Tyler-Ward, let's try de-saturating the background or something to make the text stand out more. I suspect after that, @mltnhm, we'll be basically done :tada:

**Comment by trickeydan** [comment]
Due to the lead time on this, these need to be ordered **today** to ensure that we have them at the competition.

**Comment by trickeydan** [comment]
Also, can we add our logo to the design, rather than just the name Student Robotics?

**Comment by mltnhm** [comment]
[Please review this](https://github.com/srobo/promotional-material/pull/5)

**Comment by Tyler-Ward** [comment]
I have reduced the color difference between the colors (we are now also only using colors that appear in their designer). if people are happy with this I can commit the lava SVG and @mltnhm can integrate into his.

![band2](https://user-images.githubusercontent.com/3390465/53879980-b2c95b00-4007-11e9-9c63-c4a6a8cd73d0.png)

**Comment by RealOrangeOne** [comment]
This has lightened it by quite a lot. I don't know if white text will have a high enough contrast against this.

**Comment by mltnhm** [comment]
@Tyler-Ward Could I get the SVG for that?

**Comment by Tyler-Ward** [comment]
@RealOrangeOne could use black text if we are worried about contrast

**Comment by Tyler-Ward** [comment]
For information the pull request is now at https://github.com/srobo/promotional-material/pull/6.

**Comment by RealOrangeOne** [comment]
This has now been merged.
