### ISSUE TITLE
Arrange hand sanitiser for the competition

### ISSUE THREAD

**Issue by Scarzy** [srobo/tasks#910]
However I look at it I cannot reasonably justify not making hand sanitiser available. Several websites state having to have robust hygiene protocols in place and supporting this by having sanitiser available.

I suggest as a minimum we put some:

- At reception
- At the entrance to the arena/cube
- At the entrance to the test arena
- At the power tools area
- At helpdesk

We might need some by the doors on L3 as a common contact point, but I'd rather we prop these doors open if we can (I'm hoping they aren't fire doors)

**Comment by RealOrangeOne** [comment]
If someone can cap this at a reasonable budget, I can go to the shops during the week and purchase as much as possible for the budget.

Do you imagine this only including hand sanitizer, or should it also cover surface cleaner?

**Comment by Scarzy** [comment]
I believe we are still in discussions with the venue over a cleaner coming onsite.

But otherwise yes, we will need other cleaning materials to wipe down common contact points; handles and stair rails etc. That would need to include gloves and cloths as well as the surface cleaner

**Comment by Scarzy** [comment]
It's probably cheaper to get a number of pump bottles (I suggest at least 2
per location to account for breakages) and one or more 5L refills. I'm
honestly not sure what quantity we will need

**Comment by Scarzy** [comment]
Also, something that might help us out here is if SUSU already have
dispensers available and about the place. If possible I suggest this is
checked in person, as they are not being massively responsive to e-mails.

**Comment by RealOrangeOne** [comment]
I'm going to purchase £30 worth of sanitizer, spray and wipes. In the most efficient way possible.

I will also purchase £5 of masks

**Comment by RealOrangeOne** [comment]
We now have:

- 12 500ml bottles of sanitizer (70% abv)
- Large cleaning wipes
- 3 bottles of multi-surface cleaner (antibacterial)
- 1 small bottle of washing up liquid (antibacterial)
- 1 bottle antiseptic disinfectant cleaner from concentrate (to top up the multi-surface cleaner if / when it runs out)
- 100 face masks
