### ISSUE TITLE
Find a table guard for the tech desk

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#911]
we need a table guard for the back of the tech desk that stops things being pushed off the desk

**Comment by WillB97** [comment]
Since our risk assessment says we will have one this is either a must have or the risk assessment needs changing.

**Comment by PeterJCLaw** [comment]
Something's missing here? What's the adverse impact of things falling off the back of the desk onto the floor? Is the concern that things are going to fall off _onto the floor in the Cube_? If so, that sounds like it's a lot more than just a desk guard and instead is a guard for the balcony.

**Comment by Scarzy** [comment]
The balcony has a wall so stuff on the floor can't be pushed and fall off. There are other mitigation's to stop people dropping things or themselves from it. So the remaining risk is stuff slowly being pushed back from the tech desk without being noticed and suddenly falling off which this seeks to prevent.

**Comment by PeterJCLaw** [comment]
The arena walls are MDF planks with wide feet attached. We have spares of them since we're not making full sized arenas. Would one (or more) of them work for this?

**Comment by sedders123** [comment]
We do not have tables backing onto the balcony so should not need a table guard
