### ISSUE TITLE
Design Maps

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#92]
We should design some maps for competitors and possibly also some nice ones for volunteers rather than just our competition planning maps.

Blocked on #64 and probably #65.

**Comment by RealOrangeOne** [comment]
It might also be useful to ensure these are available on our website too, so that teams can view them on devices etc rather than paper, it also means we don't need to print quite as many, or ensure they're distributed to all teams

**Comment by PeterJCLaw** [comment]
In the past we've done this by using SVG layers in the SVGs which render the maps. That reduces the chances that one or other map will get out of date.

https://github.com/srobo/comp-floorplans contains the previous maps as well as the build tools for generating pretty versions. I'd encourage using a similar approach this time around too.

See also #123.

**Comment by PeterJCLaw** [comment]
See also https://github.com/srobo/tasks/issues/124

**Comment by Tyler-Ward** [comment]
Note this ticket is for the graphicial maps for signage and use by teams not our internal planning maps see other layout tasks for these.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward indeed, in the past the two have been built from the same source by using layers within the SVG files to enable hiding/showing different things.
That reduces the overall effort needed as we only need to maintain a single overall layout (building, main fixtures) as well as ensuring low maintenance as the single-source nature means that updates can be made across "all" the maps in one go -- for example if we moved a set of pits, we'd naturally move it on all variants of the map at the same time that we also moved the cabling and other aspects.

**Comment by PeterJCLaw** [comment]
For reference, there are some old plans in https://www.studentrobotics.org/cgit/arena.git/tree/comp13/floorplans which _might_ be useful as references.

**Comment by PeterJCLaw** [comment]
> It might also be useful to ensure these are available on our website too, so that teams can view them on devices etc rather than paper, it also means we don't need to print quite as many, or ensure they're distributed to all teams

Turns out there's already a slot for this in the competition-website config: https://github.com/srobo/competition-website/blob/master/_config.yml#L20. Might need checking that that value is still used (though I suspect it is), but this looks pretty easy to include once we have the PDFs.
Note that this is for the competition-mode website, not the ordinary one, so we'd probably want to add it to the main website first (ideally ahead of time) and then have this link point at that copy of the file.

**Comment by WillB97** [comment]
Blocked on #123

**Comment by PeterJCLaw** [comment]
Why is this blocked? The maps themselves shouldn't care which teams is actually where.

**Comment by Tyler-Ward** [comment]
These maps are for teams to find their pits and other locations in the venue so we need to know who is where.

**Comment by PeterJCLaw** [comment]
I'm aware of that, however rather like road names, the _design_ of the maps is independent of the text which happens to fill the slots.
For clarity: my expectation here is that the original files will include placeholders such as `TLA1`, `TLA2` etc. and then be templated with the actual team identities once we have a more concrete idea of which teams are actually coming and have sorted out the league schedule (#103).
This is what we've done in the past in order to ensure that teams can be inspected in order of first matches while ensuring the robot inspectors have a shortest-path to walk along.
I've found that a [Hilbert curve](https://en.wikipedia.org/wiki/Hilbert_curve) is a useful pattern to use for the layout in order to achieve this effect.

**Comment by Tyler-Ward** [comment]
A rough preview of a potential map style, need to find some better map symbols but this is the rough idea,

![rougth](https://user-images.githubusercontent.com/3390465/54092716-46dc4f00-4387-11e9-980d-2af45959bc74.png)

**Comment by Tyler-Ward** [comment]
List of things to mark on the competitor maps, anything else to add?

- [ ] Reception
- [ ] Helpdesk
- [ ] Arena
- [ ] Stairs
- [ ] Lift
- [ ] Team pits
- [ ] Water taps
- [ ] photo area
- [ ] entrance
- [ ] staging

**Comment by PeterJCLaw** [comment]
Interesting approach.
I suggest we stick to flat top-down maps and minimal colours (i,e: don't fill the general floor space) for clarity.

**Comment by RealOrangeOne** [comment]
The above map example shows lifts and stair cases we don't really want competitors using generally. We should probably remove these from the maps?

**Comment by Tyler-Ward** [comment]
That staircase goes directly to the team pits on L3. it would make sense for it to be used for them to get to their pits from L4 but not for going to the cube from the pits.

**Comment by Tyler-Ward** [comment]
Here is the current map. It is A5 sized for the booklet but can be scaled up for signage

[maps.pdf](https://github.com/srobo/tasks/files/2957959/maps.pdf)

**Comment by RealOrangeOne** [comment]
This looks really nice! Although personally the perspective is a little steep, and makes it really hard to visually grep. What would it look like if we reduce the angle, or remove it entirely?

**Comment by Scarzy** [comment]
Is this map accurate in terms of where everything is?

If so, I have some concerns, like the pits clearly blocking doorways/corridors...

Also, we should probably consider the use of the word "Staging" when there is also actual staging right next to it. It promises to get confusing with what staging people are/aren't allowed in at different times.

**Comment by Tyler-Ward** [comment]
The map is based off the maps in #65 check the maps in https://github.com/srobo/comp-floorplans for the full details of gaps between the zones and other areas.

Staging is what is defined in the rules as the location to present robots at before a match.

**Comment by Scarzy** [comment]
> Staging is what is defined in the rules as the location to present robots at before a match.

I know, and it's also the name we've used historically. It's just unfortunate that this year it's right next to an actual stage. Perhaps marking the stage as "raised viewing area" or something similar will help remove any ambiguity?

**Comment by Tyler-Ward** [comment]
I have deliberately left the stage off the map to avoid adding locations that competitors and visitors wont need to know the location of specifically. I can add it if people think it is necessary but should be fairly clear what is going on when people come into the cube to watch or deliver robots.

**Comment by PeterJCLaw** [comment]
Perhaps call it "Match Staging" for added clarity?

Did the SUSU change the toilets on L2? The last time I was there, the gents were closer to the Cube, with the ladies being the other side.

The text here is quite small. Even looking at it on my monitor (so it's roughly A4 at that point), the text is not especially easy to read. The slim kerning probably doesn't help with this. Can we make the text three or four sizes larger so that it's more easily legible?
Making the grey background lighter (I'd suggest by about 70%) might also help with this.

Another aspect of this layout of map is that, even as someone who _knows_ the layout of SUSU, it's not at all obvious to me how the various levels fit together. I appreciate the effort which has been put in to try to resolve this (colour coding the stairways is a nice touch), however I think we need to do more to provide a reference frame which is consistent between the levels.

I suspect this may even be an intrinsic issue with stylised perspective maps. Is there a particular issue with using a square layout which makes it prohibitive to have the map be square? My expectation is that a square layout (perhaps with a faint outline of the main walls of the building, to act as a reference) would be considerably easier to parse.

**Comment by Tyler-Ward** [comment]
> Perhaps call it "Match Staging" for added clarity?

Sounds good, now done
 
> Did the SUSU change the toilets on L2? The last time I was there, the gents were closer to the Cube, with the ladies being the other side.

Oops good spot now fixed

> The text here is quite small. Even looking at it on my monitor (so it's roughly A4 at that point), the text is not especially easy to read. The slim kerning probably doesn't help with this. Can we make the text three or four sizes larger so that it's more easily legible?
> Making the grey background lighter (I'd suggest by about 70%) might also help with this.

I have converted the text to opensans condensed rather than oswald and made it larger, it is also now in orange as it overlaps other black markings.

> Another aspect of this layout of map is that, even as someone who _knows_ the layout of SUSU, it's not at all obvious to me how the various levels fit together. I appreciate the effort which has been put in to try to resolve this (colour coding the stairways is a nice touch), however I think we need to do more to provide a reference frame which is consistent between the levels.
>
> I suspect this may even be an intrinsic issue with stylised perspective maps. Is there a particular issue with using a square layout which makes it prohibitive to have the map be square? My expectation is that a square layout (perhaps with a faint outline of the main walls of the building, to act as a reference) would be considerably easier to parse.

This is a problem with the building in general as different floors have different shapes (due to it being half in a hill) and compounded by the fact that we are using more of a diagonal slice through the building and don't really want to include the large sections of the building we are not using. I tried top down maps when doing my initial tests but these were even more confusing when arranged on a page as L2 has quite an unhelpful shape with regards to page layout.

I have shifted L2 to the right to keep the stairs more in line which might help a bit. The other idea i had was to draw lines between the stairs but this would cut across areas which we want to have information in.

I have attached a modified version with the changes suggested above.

[maps.pdf](https://github.com/srobo/tasks/files/2975436/maps.pdf)

**Comment by PeterJCLaw** [comment]
I've had a very quick look at the updated maps.

The colour in the text helps a bit, though reading the words over the top of the borders isn't great. Is there something we can do about that? Maybe lighter grey, or possibly move some of the text out and use lines to indicate what the text relates to?

I'd still be tempted to try a _much_ lighter grey for the "floor", perhaps in the HTML #eee range, and maybe lighter borders a little too? I'm not too worried about the greys not being the specific brand colours here - I think it's more important to have a clear diagram.

I see the issue with the odd shapes of the building, will have a think.

Is the source of the maps available somewhere so I can have a play? (that's likely faster for me to understand the limitations than lots of round trips of suggestions)

I've also realised that there isn't a reference here of what our maps have looked like in the past. Here's the 2016 map: https://github.com/PeterJCLaw/srweb/blob/master/resources/2016/competition-layout.pdf (the previous ones at Newbury were almost identical; I'm not sure we have any from before Newbury).

**Comment by Tyler-Ward** [comment]
I haven't added it to git yet as we don't seem to have an appropriate repo for this yet, have attached the map source here for you.
[maps.zip](https://github.com/srobo/tasks/files/2975864/maps.zip)

**Comment by Tyler-Ward** [comment]
Here are the designs will the team details and map changes added
[maps.zip](https://github.com/srobo/tasks/files/2999643/maps.zip)
[maps.pdf](https://github.com/srobo/tasks/files/2999644/maps.pdf)

**Comment by Scarzy** [comment]
The First Aid point should probably be shown on there, as mentioned in #142

**Comment by Tyler-Ward** [comment]
Team BMC have been removed and I have uploaded the maps to git at https://github.com/srobo/event-maps-2019

**Comment by Tyler-Ward** [comment]
@TomWheal I have created a variant with the labels slanted as per our discussion at the weekend. It helps with some of the labels but others are harder to read, let me know if you want me to try any other edits.
[maps.pdf](https://github.com/srobo/tasks/files/3010839/maps.pdf)
[maps.zip](https://github.com/srobo/tasks/files/3010841/maps.zip)

**Comment by Scarzy** [comment]
A few thoughts;

Could TLC move into the corner? Also, could SWI move to the other side? These just help open up some walkways.
Can we show where the first aid is going to be stationed? Will help to avoid unnecessary delays if an incident occurs (though I have just noticed this is probably pending some information from me on #142 ).
The power tools area as shown implies it takes up the full width, however comp-floorplans shows it only using half the width, and I'm aware there are fire exits there which we really shouldn't be completely blocking.

**Comment by Tyler-Ward** [comment]
> Could TLC move into the corner? Also, could SWI move to the other side? These just help open up some walkways.
I will move SWI now, @sedders123 can you update the other listings to accommodate
There are two fire exits on the other side which we don't want to block.

> Can we show where the first aid is going to be stationed? Will help to avoid unnecessary delays if an incident occurs (though I have just noticed this is probably pending some information from me on #142 ).
I can add an icon if we know where it wants to be. (if we don't know now we can print the ones in the competitor booklets without it and add it to the ones printed around the venue.

> The power tools area as shown implies it takes up the full width, however comp-floorplans shows it only using half the width, and I'm aware there are fire exits there which we really shouldn't be completely blocking.
It is only on one side of this area. the full size on this map is mostly a limitation of needing large labels for things. we will make sure this area is well marked in reality.

**Comment by Scarzy** [comment]
> > Could TLC move into the corner? Also, could SWI move to the other side? These just help open up some walkways.
> 
> I will move SWI now, @sedders123 can you update the other listings to accommodate

I assume you mean TLC? SWI going to the other side is the one that would block the fire exit, not TLC going to the corner.

> There are two fire exits on the other side which we don't want to block.

Fair point.
 
> > Can we show where the first aid is going to be stationed?
> 
> I can add an icon if we know where it wants to be. (if we don't know now we can print the ones in the competitor booklets without it and add it to the ones printed around the venue.

Ideally I'd want it in both. People will look at the first map to hand, they won't want to be hunting through different variants of map. Also, the more they see it when not looking for it, the more likely they are to know where to look when they do need it.
I've responded on #142, hopefully that'll be enough info to allow it to be placed.

> > The power tools area as shown implies it takes up the full width, however comp-floorplans shows it only using half the width, and I'm aware there are fire exits there which we really shouldn't be completely blocking.
> 
> It is only on one side of this area. the full size on this map is mostly a limitation of needing large labels for things. we will make sure this area is well marked in reality.

I guessed that was probably the case, thought it best to check though

**Comment by Tyler-Ward** [comment]
> > > Could TLC move into the corner? Also, could SWI move to the other side? These just help open up some walkways.
> > 
> > 
> > I will move SWI now, @sedders123 can you update the other listings to accommodate
> 
> I assume you mean TLC? SWI going to the other side is the one that would block the fire exit, not TLC going to the corner.

Yes that is what I meant.

I will add a first aid point on bar 3 to the map.

**Comment by sedders123** [comment]
> I will move SWI now, @sedders123 can you update the other listings to accommodate

I can update the floor plan (and the compstate if necessary) to move TLC into the corner later this evening. SWI will stay where they are if I've understood correctly

**Comment by Tyler-Ward** [comment]
That is correct

**Comment by TomWheal** [comment]
Is there an ETA on this?

**Comment by Tyler-Ward** [comment]
The maps are on github and ready to go. let me know if you need it in any particular file format.

For info the repo is  https://github.com/srobo/event-maps-2019

**Comment by RealOrangeOne** [comment]
Map looks great!

I still personally think the large orange text is difficult to read, but that could be me, and i'm more than happy to be outvoted on that!

**Comment by sedders123** [comment]
Have created https://github.com/srobo/comp-floorplans/pull/9 with proposed changes

**Comment by PeterJCLaw** [comment]
I agree on the orange over the plans and still think the grey is too dark. I'll emit a PR against that repo with some suggestions.

(Meta: this would ideally end up in the floorplans repo, rather than its own repo, but let's sort that out later).

**Comment by PeterJCLaw** [comment]
I've emitted some suggestions on https://github.com/srobo/event-maps-2019/pull/1

**Comment by sedders123** [comment]
Now that https://github.com/srobo/event-maps-2019 exists and a map has been designed should we close this ticket?

**Comment by Tyler-Ward** [comment]
Agreed, given the the booklets are about to be sent off for printing and contain this i think this can be closed.
