### ISSUE TITLE
Send wrap-up email to volunteers

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#920]
This is a companion to https://github.com/srobo/tasks/issues/892, but with a different audience. See also discussion at https://studentrobotics.slack.com/archives/CBP7UL6RG/p1650907577298239

This would cover things like:
- Thanking them for helping run the event and competition cycle
- Asking for feedback (see #890)
- Summarising the success of the year
- Reminding them that it's not quite over yet, ideally with dates for when we'll be sorting out the stuff that's now in the container (team kits and otherwise), asking for support at those events (or at least advertising that these will happen if details aren't ready yet)
- Inviting them to the retro (maybe, depends on how we want to run that and the timing of the email; see #918)

There miiight be some overlap with https://github.com/srobo/tasks/issues/891 here, though only at a high level. We probably don't need to share anything like same the level of detail with volunteers (as it's not that interesting to most).

**Comment by Adimote** [comment]
this was done a while ago, forgot to close
