### ISSUE TITLE
Review display driver setup

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#922]
SR has a number of old Raspberry Pi 1s which are used as display drivers, along with power supplies for them. However these Pis are old enough that they are no longer being fully supported by the latest versions of Raspberry Pis OS (notably Firefox & Chromium don't work on them, see https://github.com/PeterJCLaw/srcomp-kiosk/issues/15) and we may need to move to a different OS.

The power supplies that we currently have work fine for the Pi 1s, however do not provide quite enough power to keep Raspberry Pi OS on Pi 3s happy. Pi 3s do work and appear to do so without issue, however the OS shows a very visible warning that the power supply isn't providing enough power. Silencing the warning may be a way to go, if we can do so consistently.
In any case we don't have enough Pi 3s to use for this purpose, so would need to either get more or keep some Pi 1s alongside them.

The Pi 1s are also lacking good cases. We have some cardboard cases I put together a few years back (and which have survived remarkably well!) but don't allow easy access to the Pis for e.g: power cycling them. This was by design at the time -- these cases were aimed at hiding away the Pis so that they didn't get damaged and so that people (i.e: attendees) didn't poke them, however we should probably look at getting some more robust cases if we are going to continue using them.

With the planned move that the Kit Team have from the ODROID Brains to Pi 4 Brains in the kits SR will have a number of ODROIDs available which might be suitable alternatives (they also have their own cases). This would likely mean spinning our own OS and mean development was limited to individuals with access to the right hardware, which has substantial complications, though given the use-case we have and the number of ODROIDs we have this may be worth the drawbacks.

**Comment by raccube** [comment]
We certainly could roll with ODROIDs. If we can't put together, there are some community-maintained images available, as well as [Arch Linux ARM](https://archlinuxarm.org/platforms/armv7/samsung/odroid-u3)

**Comment by WillB97** [comment]
Using the spare Pi 4's has been shown to be a functional solution. The kiosk OS has been replaced with https://github.com/WillB97/sb-kiosk
