### ISSUE TITLE
Design Robot Flags

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#93]

**Comment by antoinepetty** [comment]
Assigned myself to this as a backup but would rather it were associated with whoever is designing the posters and other graphics in order to stay consistent.

**Comment by RealOrangeOne** [comment]
There's a formal specification in the rules for what these flags should look like. I don't believe there's much scope for any design work?

**Comment by RealOrangeOne** [comment]
The rules contain a spec, which is good enough to be used. 

![image](https://user-images.githubusercontent.com/6527489/53681623-168c1500-3ce4-11e9-94cb-9a3d996afc52.png)

**Comment by PeterJCLaw** [comment]
@RealOrangeOne what's the spec of tubing we're going to get? Have we sourced it? How will the flag be joined to it? What will the flag be made of?

Related to these: can we get these made far enough in advance that we can have at least the pole part available at the March 9th Tech Day for teams to test with?

**Comment by RealOrangeOne** [comment]
We already have the parts to assemble these in the cupboard. I don't know the spec of the pipe, but it's the same one used for flag assembly in the past. 

We can have the pole part ready for the tech day, yes. A full assembly might occur, but depends on https://github.com/srobo/tasks/issues/105 and https://github.com/srobo/tasks/issues/107

**Comment by trickeydan** [comment]
The pipe is 15mm white PVC.
