### ISSUE TITLE
Email team leaders the SR2023 Kickstart details

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#933]
We need to remind team leaders that the kickstart is happening, communicate the final details and encourage them to prepare for it on their end.
We should tell them: * What venue to come to * What time to arrive * That they should pre-create competitor user accounts * To bring their signed disclaimer forms (optional; if we sent them out)

### Original

[kickstart/remind-teams](https://github.com/srobo/recurring-tasks/blob/master/kickstart/remind-teams.yaml)

### Dependencies

 * #931 Book venues for the SR2023 Kickstart
 * #932 Confirm which teams are taking part in SR2023

**Comment by RealOrangeOne** [comment]
Fixed in https://github.com/srobo/team-emails/pull/113 and https://github.com/srobo/team-emails/pull/114
