### ISSUE TITLE
Ship SR2023 kits to Kickstarts

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#937]
Teams will want kits at Kickstart so we need to ship the relevant kits to each of the Kickstart venues.

### Original

[kickstart/kit/ship-kickstarts](https://github.com/srobo/recurring-tasks/blob/master/kickstart/kit/ship-kickstarts.yaml)

### Dependencies

 * #936 Allocate SR2023 kits to teams

**Comment by WillB97** [comment]
@Tyler-Ward Could you see if TIm is happy to store the kits until next week

**Comment by Tyler-Ward** [comment]
Kits have been moved to mine so will be stored with me until kickstart. Will need some people with cars in the morning to move them to the uni.

**Comment by WillB97** [comment]
The remaining kits are covered under #938 and #939
