### ISSUE TITLE
Ship SR2023 kits to overseas Teams

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#939]
Teams overseas need their kits shipped to them. This has mostly been the German teams in the past few years, which have been shipped together to the German Kickstart. This is intentionally separate from the shipping to Kickstarts as it involves an international delivery.

### Original

[kickstart/kit/ship-overseas](https://github.com/srobo/recurring-tasks/blob/master/kickstart/kit/ship-overseas.yaml)

### Dependencies

 * #936 Allocate SR2023 kits to teams

**Comment by raccube** [comment]
MAI has been delivered a kit.

**Comment by PeterJCLaw** [comment]
This has happened. All teams now have kits.
