### ISSUE TITLE
Populate Events Page with schedule

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#94]
Fill in the events page for the competition.

Blocking on #73 and probably any other info needed for volunteers.

**Comment by antoinepetty** [comment]
I think this is a duplicate of #160

**Comment by RealOrangeOne** [comment]
I think the intention behind the separation was to distinguish between details of the event itself, and then the schedule inside it (#73 ). I think it's probably still worth tracking separately, meaning we can get the base information out first, and _then_ get the competition schedule out, which takes longer to finalise.

**Comment by PeterJCLaw** [comment]
I think this is done? https://github.com/srobo/website/pull/138 added a schedule; is there anything more here?

**Comment by RealOrangeOne** [comment]
Correct, this is a duplicate of #161
