### ISSUE TITLE
Prepare Discord for SR2023

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#943]
In order to allow the competitors to chat to each other and request help from mentors, we setup forums each year. These are typically an instance of [phpBB](https://www.phpbb.com/) hosted on a VM of ours.
The forums allow login using the competitors' user accounts and when they post in the forums, updates are cross-posted into Slack.
We usually have forums as follows:
 - *General Discussion* (General chitchat.)
 - *Programming* (Python, libraries and concepts.)
 - *Electronics* (Electrons, holes and joules.)
 - *Mechanics* (Pulleys, sprockets, hinges and gudgeon pins.)
 - *Teams on the web* (A place to show off your team blogs, videos, and bat-based memes.)
 - *<name of the game>* (Discussion about the game.)

### Original

[kickstart/services/forums](https://github.com/srobo/recurring-tasks/blob/master/kickstart/services/forums.yaml)

### Dependencies

 * #941 Decide on the SR2023 game

**Comment by WillB97** [comment]
This is now Discord, it needs to be configured.

**Comment by sedders123** [comment]
Have chatted with @raccube and I'm taking a look at this

**Comment by raccube** [comment]
A Discord ~guild~ server has been set up with the exception of the bot.

**Comment by WillB97** [comment]
I believe the bot is covered under #947

**Comment by PeterJCLaw** [comment]
> I believe the bot is covered under #947

Not really, that's a meta ticket which pulls together various hosted services.
