### ISSUE TITLE
Hire Scaff

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#95]

**Comment by Tyler-Ward** [comment]
Parts list from SP2018

* 17 2.5m (preferred) or 3m verticals
* 15 3m horizontals
* 22 2.5m horizontals
* 12 1.3m horizontals
* 5 2m scaffolding tubes
* 10 swivel couplers
* 17 combined jack and base plates

**Comment by RealOrangeOne** [comment]
Lead time is likely around a week.

**Comment by Tyler-Ward** [comment]
We need a quote for this and can then get this booked. can someone take this on.

**Comment by Adimote** [comment]
Assigning to Alistair to verify, then we need to find someone to do it. (I'm happy to do it)

**Comment by Adimote** [comment]
@BitBait Has offered to do this!

**Comment by Tyler-Ward** [comment]
@BitBait any update on the status of this?

**Comment by prophile** [comment]
Approved

**Comment by Tyler-Ward** [comment]
A price of £300 was mentioned on slack has there been any update on this or is a quote ready to be approved?

**Comment by Adimote** [comment]
Update on this: the original form asked for a 4 week minimum, however after enquiry we found it's only for newly registered companies, so we're grandfathered into the old scheme! new price is ~£150 but we are yet to get an actual invoice so numbers may change.

Also, there's a delay in that the company has asked us to fill out a form to update our details, which requires trustee signatures, so hopefully they're responsive.

**Comment by Tyler-Ward** [comment]
That sounds great, £150 sounds good to me. Let me know when you get an invoice, we can send this one to the trustees for direct payment.

**Comment by Tyler-Ward** [comment]
As this is for direct payment send me the invoice when you get it and i will send it on for payment.

**Comment by Tyler-Ward** [comment]
I have been informed that scaff has been ordered and we area waiting the invoice to pay. added to #200

**Comment by BitBait** [comment]
Scaffolding has been ordered and will be arriving on the Thursday (4th) and will be collected on the Monday (8th), the invoice will be sent after they have collected the scaffolding (it will be more than £150 as earlier quoted and will most likely be a similar cost to the last sourcebots competition).

**Comment by Tyler-Ward** [comment]
As a separate issue has been raised for paying for the scaff this can no be closed.
