### ISSUE TITLE
Send kit disclaimer forms to team leaders

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#960]
As the kits contain valuable and potentially dangerous components, many of which are not CE marked, we normally ask the team leaders to sign a form accepting responsibility for it and promising to return it at the end of the year.
We should send (digital) copies of the form to team leaders so that they can sign & return the forms ahead of time, simplifying things at kickstart.

### Original

[kickstart/send-disclaimer-forms](https://github.com/srobo/recurring-tasks/blob/master/kickstart/send-disclaimer-forms.yaml)

### Dependencies

 * #930 Allocate TLAs for SR2023
 * #958 Update kit disclaimer forms for SR2023

**Comment by Scarzy** [comment]
Side note; in the UK the CE marking is no longer relevant (it's an EU
standard), the current UK standard is the UKCA marking.Message ID:
***@***.***>

>
