### ISSUE TITLE
Inform volunteers of the SR2023 Kickstart details

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#963]
We need to remind volunteers that the kickstart is happening and communicate the final details: who is doing what, at what venue, what time to arrive, etc.

### Original

[kickstart/remind-volunteers](https://github.com/srobo/recurring-tasks/blob/master/kickstart/remind-volunteers.yaml)

### Dependencies

 * #931 Book venues for the SR2023 Kickstart
 * #962 Volunteer signups for the SR2023 Kickstart

**Comment by sedders123** [comment]
This was done in https://github.com/srobo/volunteer-emails/pull/58
