### ISSUE TITLE
Decide who will present the kickstart presentation

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#964]
The presentation needs to be given at each venue, so will be presented by multiple people. It's recommended the person who creates the presentation be one of the people to present.

### Original

[kickstart/decide-presenters](https://github.com/srobo/recurring-tasks/blob/master/kickstart/decide-presenters.yaml)

### Dependencies

 * #931 Book venues for the SR2023 Kickstart

**Comment by sedders123** [comment]
Jake will present (thanks @RealOrangeOne!)
