### ISSUE TITLE
Prepare Robot Competition USBs

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#97]
Include spares

**Comment by RealOrangeOne** [comment]
I suspect we already have these from SR2017. This ticket is likely to be more like _"Find Robot Competition USBs"_

**Comment by PeterJCLaw** [comment]
I'm fairly sure these are in the container storage.

**Comment by trickeydan** [comment]
These are definitely in the Broom Cupboard.

We can dig them out tomorrow night.

**Comment by Tyler-Ward** [comment]
We have searched the cupboard they are not there, there are a couple of spares which are empty but not enough for the competition.

**Comment by PeterJCLaw** [comment]
Ah, I thought someone said on Saturday that they had already previously been located in the cupboard? Oh well.

@trickeydan you're still owning this; does that mean you're planning to obtain and prepare these?

I suggest if we're making new ones that we:
- try to get them to be a consistent look & feel
- use keyrings to indicate the arena corner colour (this is what's been done in the past, which works fairly well)
- (obviously) document how to create them if there aren't existing docs/tooling

**Comment by trickeydan** [comment]
Code that reads the keys: https://www.studentrobotics.org/cgit/brain/herdsman.git/tree/herdsman/compkey.py

There were apparently 8 USBs with keyrings, but the one I checked was blank. Is 8 sufficient? @PeterJCLaw

**Comment by PeterJCLaw** [comment]
Most odd that they're blank. I'd expect 8 is fine - it's two full sets. While both sets will be in use, we won't be letting the teams run off with them, so the chances of them going missing are fairly low.

**Comment by PeterJCLaw** [comment]
Actually, there ought to have been 16 SR ones - two full sets for each of two arenas.
I wonder where the other 8 are?
Anyway, 8 is enough for this year.

**Comment by Tyler-Ward** [comment]
We found a bag of key rings which contained 4 blank USB sticks not eight there were also two key rings labeled with helpdesk in the same box as the bag.

**Comment by trickeydan** [comment]
> We found a bag of key rings which contained 4 blank USB sticks not eight there were also two key rings labeled with helpdesk in the same box as the bag.

I am certain you said 8... Was this miscounted at the time?

**Comment by Tyler-Ward** [comment]
I probably said something like, I expect to find at least 8 (that was before i realized each arena needs two sets)

**Comment by trickeydan** [comment]
Actions we can do to solve this:

- Purchase 4 more USBs of the same variety if available + 4 tags
- Purchase 8 new USBs of the same variety + 4 tags
- Find the 16 previous ones in the container

**Comment by PeterJCLaw** [comment]
I'm fairly sure they're not in the container - we had a fairly good look while we were there last weekend (#183).

If we've only found 4, does that mean they're in fact SourceBots' ones?

Buying some more seems a good solution to me. This should probably come out of the arena props budget line I suspect.

@richardbarlow do you happen to know where the competition mode USB sticks might have ended up?

**Comment by richardbarlow** [comment]
Rob has the competition USB sticks (as they belong to him), however he is happy for you to have them. @PeterJCLaw do you want to email Rob to arrange for getting hold of them?

**Comment by trickeydan** [comment]
> If we've only found 4, does that mean they're in fact SourceBots' ones?

No, we used Lego ones at SB2018 and SP2018. The ones that we found were 4 Kingston DTSE9 8GB. I note that the exact model is no longer sold in 8GB capacity. Purchasing more would cost approximately per USB drive.

**Comment by Tyler-Ward** [comment]
if we cant get the previous ones new ones arent too expensive https://www.amazon.co.uk/Kingston-Technology-DTSE9H-32GB-Traveler/dp/B00D9OQ1QQ/ref=sr_1_4?ie=UTF8&qid=1552499694&sr=8-4&keywords=kingston%2Busb&th=. These also match the 4 we already have

**Comment by PeterJCLaw** [comment]
Hrm, if the competition-mode sticks are indeed Rob's, does that mean that the four we found are also in fact Rob's too?

If he's happy for us to use them/donate them to SR (I'm not sure which @richardbarlow means), then that's likely to be the simplest. I'll email him to find out.

**Comment by PeterJCLaw** [comment]
I have emailed Rob.

**Comment by trickeydan** [comment]
Marked as blocked on obtaining USBs.

**Comment by rgilton** [comment]
I do indeed have a box of USB keys + keyrings intended for this purpose.  They'll be in the post to @PeterJCLaw later today.  I am happy to relinquish ownership of them to SR.

**Comment by PeterJCLaw** [comment]
I now have said USB keys & keyrings. Many thanks @rgilton.

**Comment by PeterJCLaw** [comment]
I'll aim to bring these with me this weekend and we can validate them on a kit.

**Comment by Tyler-Ward** [comment]
This has been completed and they are now in the inventory under. sr9V1G
