### ISSUE TITLE
Work out where we can run the Virtual Competition matches

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#972]
We need to find suitable hardware and/or hosting to run the virtual competition match simulations.

The performance is less this year than we've seen in the past, so we may need to consider solutions which allow for taking longer to run.

This needs to be a single place/machine/whatever where we can run all the simulations, so that the conditions are the same for all matches.

This also needs to be available for the run-through the week before (and needs to be the same for that event as for the real thing).

**Comment by antoinepetty** [comment]
I assume this is about rendering the simulated matches rather than a physical location for the livestream?

**Comment by PeterJCLaw** [comment]
These are going to be run on Will's machine.
