### ISSUE TITLE
Find and book venue for SR2023

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#974]
We need a venue for SR2023.

### Original

[comp/venue/book](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/book.yaml)

**Comment by WillB97** [comment]
We have booked SUSU for this year, the hire details are in the drive at: https://drive.google.com/drive/folders/158JqjcpboOPAWu_41m-Zr-xNWhh8euDJ?usp=share_link
