### ISSUE TITLE
Order Tape

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#98]
Order more tape if necessary.

**Comment by PeterJCLaw** [comment]
Should have been part of #183. There is however, _lots_ of tape in the container. We're not sure how much of each type though.

**Comment by Tyler-Ward** [comment]
If we cant verify what we have we should order what we need and keep the stuff in the container as spares/stuff for future years. Can someone build a purchasing list for what we need so i can approve.

**Comment by PeterJCLaw** [comment]
Do we have an idea of the lead-time for getting tape? If it's under a week I suggest this can wait until after next weekend, which allows time for a visit to the container.

**Comment by Tyler-Ward** [comment]
Lead time is around a week by the looks of it so ordering at the weekend should be fine as that still gives us two weeks for delivery.

**Comment by PeterJCLaw** [comment]
#225

**Comment by PeterJCLaw** [comment]
Given the level of effort here vs the cost of just getting more, I'm no longer convinced that this is worth doing -- instead I think we should just buy what more we think we'll need.

How are we for budget for getting tape?

**Comment by sedders123** [comment]
We have got budget allocated for tape. Pricings below:

[Fluorescent Tape](https://www.gaffatape.com/Fluorescent-Gaffer-Cloth-Tape-1/default.aspx) - £10.19 a roll
[Duct Tape](https://www.gaffatape.com/general-use-gaffer-duct-tape/default.aspx) - £1.78 a roll (though a box of 24 for £41.52 has been suggested)
[Electrical Tape](https://www.gaffatape.com/Electrical-PVC-Tape-2/Default.aspx) - £0.78 a roll
[Hazard Tape](https://www.gaffatape.com/barrier-tape-safety/default.aspx) - £7.08 a roll

**Comment by PeterJCLaw** [comment]
What would we expect to use Electrical tape for?

**Comment by PeterJCLaw** [comment]
(I'm pretty sure we have a good quantity of electrical tape, so I'm more trying to judge whether we really need more)

**Comment by PeterJCLaw** [comment]
@sedders123 do we have estimates for the quantities we'll need?

**Comment by sedders123** [comment]
Electrical tape will be used for helping secure/group cables in any necessary runs. Red Electrical tape will be used for marking broken kit. A large amount of electrical tape will be required during pack down to keep cables together. (I'll defer to @Tyler-Ward for any future electrical tape questions as I'm just relaying)

Our (very) rough estimates were:
 - 4 x Fluroscent Tape (one of each colour)
 - 24 x Duct Tape (1 Box)
 - 1 x Hazard tape
 - Unknown Electrical Tape - @Tyler-Ward suggested looking for a different supplier of higher quality

**Comment by Tyler-Ward** [comment]
We will need white gaff for the arena walls. we can use either white or black for the team pit floor markings. We will need about 300m of tape for the pits and probably about the same again for the arena. tape will also be needed elsewhere for other things but not a huge amount. What mix of black+white do we think we will want?
The link above for hazard tape is wrong we should get the following at £2.29
https://www.gaffatape.com/Hazard-warning-pvc-tape/Default.aspx
We will also need some cable protection tape at £23.47
https://www.gaffatape.com/slipway-cable-cover-tape/default.aspx

With the above from gaffa tape.com.
This will come to around £140 with delivery once we have confirmed the required mix of black and white has been confirmed this is approved. @sedders123 are you happy to order this?

Also needed from another supplier is some carpet tape and some electrical tape.
We should aim to have a minimum of 10 large rolls of electrical tape for taping cables and other things during setup and take-down.

**Comment by RealOrangeOne** [comment]
> What mix of black+white do we think we will want

Assuming we can buy in lots of 24, I suspect a 3/4 split will work out best for us. 6 rolls of white, 18 rolls of black. That ensures we're almost certainly not going to run out of either at the competition. 

Besides that, all the numbers above sound pretty good to me. We definitely need both red and black electrical tape for securing cables and marking broken kit.

**Comment by PeterJCLaw** [comment]
In case it's any cheaper, I think we've used electrical tape for the pits before. I'm fairly sure it came back up fine, but I can't remember how good or bad it looked.

**Comment by Tyler-Ward** [comment]
I anyone able to order this?

**Comment by sedders123** [comment]
I can take this on if we can confirm quantities and it can be shipped to SUSU.

Tape | Quantity | Price per roll | Total
-----| ----------| ---------------| -----|
Fluroscent| 4 (one of each colour) | £10.19 | £40.76
Black Gaff | 18 | £1.78 | £28.48
White Gaff | 6 | £1.78 | £10.68
Hazard | 1 | £2.29 | £2.29
Cable Protection | 1 | £23.47 | £23.47
| | | *Total* | £105.58

**Comment by RealOrangeOne** [comment]
That list looks good. We also need [carpet tape](https://www.amazon.co.uk/Double-Sided-Carpet-Rug-Tape/dp/B01L2LN33Q/)

**Comment by Adimote** [comment]
It can be shipped to SUSU, address will be:
```
Southampton Robotics Outreach Society
Building 42
University Road
Southampton
Hampshire
SO17 1BJ
```

**Comment by Tyler-Ward** [comment]
This looks fine to me. I assume the plan would be to do the arena walls in white and everything else in black? 
it looks like they do the flooring tap as well https://www.gaffatape.com/NEC-approved-double-sided-tape/Default.aspx get the 50mm by 50m I think we will need two rolls of this.

It also looks like they have good electrical tape as well. I think a multi-pack and 3 extra rolls of black should cover us.
https://www.gaffatape.com/Electrical-PVC-Multi-Pack/Default.aspx
https://www.gaffatape.com/Electrical-PVC-Tape/Default.aspx

I also found some better hazard tape on their site which might avoid the stretching issues we have had With the stuff we have had in the past https://www.gaffatape.com/utility-gaffer-tape-colours/Default.aspx

Also do we want the high viz cable tape or the black stuff?

Assuming people agree with the above I think that will cover all our tape needs.

Budget is approved for all of the above assuming that covers what we need.

**Comment by sedders123** [comment]
Tape has been ordered to SUSU

**Comment by Tyler-Ward** [comment]
added to #200
