### ISSUE TITLE
Have a printer (and paper/ink) at the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#983]
In case we need to print out MCFs/game lists/whatever at high speed. SR owns an HP DeskJet 2130 which takes HP 302 and HP 302XL cartridges

### Original

[comp/venue/printer](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/printer.yaml)

**Comment by WillB97** [comment]
Last year we used a full cartridge and still ran out.

**Comment by RealOrangeOne** [comment]
Most of our printing is for scoresheets. Could we print those ahead of time (perhaps using uni printers)?

**Comment by PeterJCLaw** [comment]
The on-site printer is _not_ for scoresheets. We do print them separately, ahead of time. The usage noted here is for other ad-hoc things.

**Comment by PeterJCLaw** [comment]
See https://github.com/srobo/tasks/issues/1018 and https://github.com/srobo/tasks/issues/1026 for score entry form printing and other printing in general.

**Comment by sedders123** [comment]
Printer is on the freight list and we have new ink
