### ISSUE TITLE
Have a competition network

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#984]
This also requires that we have a pretty significant internet connection given the number of people that are coming and our video streaming requirement.
If possible this should be mostly configured in a corner of the venue as early as possible during setup and then, once working, deployed to the proper locations.

### Original

[comp/venue/network](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/network.yaml)

**Comment by trickeydan** [comment]
If we need the big Cisco (3750G-48TS) switch again, I am happy to lend it again.

It's still configured the same as last year, just one big layer 2 network. 48 gigabit ports with PoE

**Comment by sedders123** [comment]
Thanks Dan, though our current plan is to use 2 smaller switches. We're also going to keep the balcony pretty clear this year and give Livestream as much space as possible so want to keep the physical footprint of the network as small as possible :)

**Comment by WillB97** [comment]
We'll just have 3/4 8 port switches (booth, balcony, stage, arena) to cover the network. THe venue can provide these.
