### ISSUE TITLE
Prepare equipment for transport to the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#989]
The things that we are taking to the competition needs to be prepared for transportation. Most of the things we need are in storage, however some may be elsewhere.

### Original

[comp/venue/transport/prepare](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/prepare.yaml)

### Dependencies

 * #988 Work out what we need from storage at the competition

**Comment by WillB97** [comment]
Most of what needs transporting is either coming from the container or being provided by volunteers so this doesn't feel relevent.
