### ISSUE TITLE
Work Out Computers and screens needed For Venue

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#99]
This will be computers at locations such as score entry and reception and any other places that will need permanent or temporary computers

**Comment by kierdavis** [comment]
Is this referring to internal equipment (e.g. compbox), computers for competitors to use, or something else entirely?

**Comment by RealOrangeOne** [comment]
@kierdavis We'll need machines to handle score entry, a couple on reception, and probably some others lying around. I suspect we can use volunteer machines for these tasks, although it would be good to know if we're going to have enough we can use.

**Comment by prophile** [comment]
Minima:

* 5 Pis running displays (4 × arena corner, 1 × outside)
* 1 machine (possibly a Pi) as competition server and admin/score entry
* 1 router (possibly a machine) with 2+ Ethernet ports for network termination

Preferred:

* 8 Pis running displays (4 × arena corner, 1 × shepherding, 2 × outside, 1 × corner mirror for balcony)
* 1 machine (possibly a Pi) as competition server
* 2 machines for admin/score entry
* 1 machine for mixtape/SFX
* 1 router (possibly a machine) with 2+ Ethernet ports for network termination

Any advance on the above?

**Comment by PeterJCLaw** [comment]
For info: SR owns a good number of Pis (12 x Pi 1As I think) which are usable for displays, plus some Pi 3B one of which has been the compbox in the past.
Score entry has typically happened on a different machine to the compbox.

**Comment by prophile** [comment]
Score entry has happened on the compbox in the past at Smallpeice. Separate machines is definitely preferable, but it is workable.

**Comment by trickeydan** [comment]
If we deploy a VOIP network, which is dependent on whether I can acquire enough handsets for it to be useful, we will need a box to run that also.

**Comment by Tyler-Ward** [comment]
Here are some extra machines we will need.

* Reception *2
* Screen pis - i think we will need around 12
  * 5*Arena (corners+staging)
  * 3* team areas score displays
  * 1*volunteer area
  * 1* tech preview
  * 1/2* shepherding
* livestream overlay renderer
* nonsync sound machine
* 2* status display outputs either two pis or a machine with dual graphics outputs

There are probably some more i have missed as well

**Comment by RealOrangeOne** [comment]
The machine running the event music (#148) will be provided by me ready to go with the required setup. The only prerequisit is power, 3.5mm audio output, and an internet connection.

**Comment by Tyler-Ward** [comment]
I have added monitors here as well as laptops will have inbuilt ones and some don't need them.

* Reception 2* computers, 2* monitors
* COMP screens
    * Arena screens 5* pis, 5* montors
    * Team score displays 3*pis, 3*SUSU TVs
    * Cube score display 1*pi 1*SUSU TVs
    * volunteer area 1*pi, 1*screen (could also use projector in the room)
    * tech desk preview 1*pi, 1* screen
    * sheparding 2*pi 2*montors
    * comp server 1*pi
* Router 1*PC(dual NIC)
* Score entry 1*pc 1*screen
* livestream renderer 1*pc
* nonsync sound 1*pc 1*screen
* Tech desk admin 1/2*pc 1/2*screen
* SR mixtape machine 1*PC 
* Status dashboard 1*PC 2*screen (could use 2 pcs if we cant get a dual output machine)

Rough total
Pis: 14
Pcs/laptops: 8
Screens (no stand):5
Screens with stand/laptops: 9

**Comment by PeterJCLaw** [comment]
>    * Arena screens 5* pis, 5* montors

What's the fifth screen here? (The arena only has four corners as far as I'm aware)

Are you including a Staging screen here (shows which teams should be in the staging area, for use by the shepherds)?

>   * volunteer area 1_pi, 1_screen (could also use projector in the room)

What's this showing?

>   * tech desk preview 1_pi, 1_ screen

What's this showing?

>   * sheparding 2_pi 2_montors

What are these two screens showing? In recent history the Shepherds have only used a single screen and when offered more they've not wanted them. It would be good to have a concrete understanding of what these will show before putting in the effort to get them. (see also #114)

>   * livestream renderer 1*pc

Presumably whoever are doing the live stream (#77) will provide this? (Not sure if you're including it here for completeness, or actually suggesting that we need to provide this)

**Comment by trickeydan** [comment]
> What's the fifth screen here? (The arena only has four corners as far as I'm aware)

The staging screen.

> Are you including a Staging screen here (shows which teams should be in the staging area, for use by the shepherds)?

Exactly correct.

> > * volunteer area 1_pi, 1_screen (could also use projector in the room)

> What's this showing?

Current information about the competition, it's easy to setup and will be useful at the volunteer area is deliberately not near the competition area.

> > * tech desk preview 1_pi, 1_ screen

> What's this showing?

I believe that this is for the overhead view of the arena for commentating, but @Tyler-Ward will have to confirm.
> > * livestream renderer 1*pc

> Presumably whoever are doing the live stream (#77) will provide this? (Not sure if you're including it here for completeness, or actually suggesting that we need to provide this)

This is for the overlay, so is provided by us.

**Comment by PeterJCLaw** [comment]
> > > * volunteer area 1_pi, 1_screen (could also use projector in the room)
> 
> > What's this showing?
> 
> Current information about the competition, it's easy to setup and will be useful at the volunteer area is deliberately not near the competition area.

Could you be more precise about this? Is this for showing the suggested "status dashboard" (#169)? If so, that seemed to already be listed separately.

I disagree that this will be easy to setup -- while it might not seem like much, it'll mean another box to configure, content to create, network cabling to run and power to be run.

**Comment by Tyler-Ward** [comment]
final list based on merged in floorplans

* Reception 2* computers, 2* monitors
* COMP screens
    * Arena screens 5* pis, 5* montors
    * Team score displays 5*pis, 2*SUSU TVs 1*monitor 2*fixed displays
    * Cube score display 1*pi 1*SUSU TVs
    * volunteer area 1*pi, 1*screen (could also use projector in the room)
    * tech desk preview 1*pi, 1* screen
    * sheparding 2*pi 2*montors
    * comp server 1*pi
* Router 1*PC(dual NIC)
* Score entry 1*pc 1*screen
* livestream renderer 1*pc
* nonsync sound 1*pc 1*screen (probably jakes laptop)
* Tech desk admin 1/2*pc 1/2*screen
* SR mixtape machine 1*PC 
* Status dashboard 1*PC 2*screen (could use 2 pcs if we cant get a dual output machine)

Rough total
Pis: 15
Pcs/laptops: 8
Screens (no stand):5
Screens with stand/laptops: 9

**Comment by PeterJCLaw** [comment]
@Tyler-Ward thanks for driving this forwards, I appreciate the push to keep this moving. I am concerned however that we appear to be planning a considerable number of computers & displays for which the use is not clear and when the people who might use those screens to not appear to have been consulted (or in some cases even appointed yet). I've found in the past that this leads to considerable wasted (or at least misplaced) effort and we would do well to ensure we know what we're creating before we start creating it.

In particular we seem to be accounting for a screen in the staging area three times, yet only one is useful.

I think it would also be useful to clarify which of these are must-haves from those which are less critical.
