### ISSUE TITLE
Transport stuff to the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#991]
Many things will need to be moved from various locations to the venue.

### Original

[comp/venue/transport/main](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/transport/main.yaml)

### Dependencies

 * #988 Work out what we need from storage at the competition
 * #989 Prepare equipment for transport to the competition
 * #990 Hire a van for transporting kit between storage and the venue

**Comment by WillB97** [comment]
This is covered in the setup schedule #1140
