### ISSUE TITLE
Organise drivers for the arena screens

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#996]
We have screens around the arena to display live information, these need something to drive them.

In the past this has been Raspberry Pis displaying a web-page. If this is used again then the following things need doing:
* Ensure we have enough Pis that work
* Ensure we have enough Pi power supplies that work
* Pre-load the Pis SD cards with the proper OS (and https://github.com/PeterJCLaw/srcomp-kiosk/)
* Label each Pi with where it will be deployed (e.g: Arena B, Corner 1)
* Ensure the Pis will have a suitable name/address on the network

### Original

[comp/arena/screens-drivers](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/screens-drivers.yaml)

### Dependencies

 * #995 Pre competition storage trip

**Comment by PeterJCLaw** [comment]
My understanding is that the various screens around the venue now all have their own drivers which we can easily point at a webpage, so in theory we only need drivers for additional screens. It would be good to have spares prepared though.

**Comment by PeterJCLaw** [comment]
I've checked that the kiosk puppet setup applies cleanly using my own Pi 3 and Raspberry Pi OS 2023-02-21 Bullseye Desktop 32-bit.

**Comment by PeterJCLaw** [comment]
Hrm, looks like SSH needs enabling on the Desktop image.

**Comment by WillB97** [comment]
Under Bullseye neither firefox nor chromium support armv6l (https://github.com/RPi-Distro/chromium-browser/issues/21) so will fail to load on Pi 2 and Pi 1. On Buster firefox-esr still has this issue and chromium is extremely slow to load and fairly unresponsive so we may need to look at alternate browsers if we are going to continue using Pi 1's

**Comment by PeterJCLaw** [comment]
That's weird, my Pi 2 definitely worked on Bullseye.
