### ISSUE TITLE
Acquire screens

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#998]
We do not have enough screens to cover everything, so we may need to hire more.
4 screens per arena, plus 2 for staging / shepherding.
Plus however many neeeded for non arena screens ("outside").

### Original

[comp/arena/acquire-screens](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/acquire-screens.yaml)

**Comment by WillB97** [comment]
The outside screens are provided by the venue (#974)
