### ISSUE TITLE
Organise the non-arena ("outside") display screens

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#999]
Throughout the venue we typically have a number of general information screens which show the schedule of matches, state of the league, etc. We need to organise screens & drivers for these to run on. They also need power and internet connections.
This may also include stands to mount the screens on. These screens are typically larger-format than the screens used within the arena.

### Original

[comp/arena/non-arena-display-screens](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/non-arena-display-screens.yaml)

### Dependencies

 * #984 Have a competition network
 * #995 Pre competition storage trip
 * #998 Acquire screens

**Comment by WillB97** [comment]
The screens in the venue support being given a web address to display so they can be pointed at the external compbox without additional hardware.

**Comment by WillB97** [comment]
This is covered in the setup schedule #1140. They will be shown on all the screens not showing livestream (#1134).
